### ISSUE TITLE
DataSchema "Only applicable to..."

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1007]
In multiple places in the DataSchema there is the following phrase or similar:

> Only applicable for associated number or integer types.

This one is for `maximum` in the Integer Schema. Does this mean that if one uses it in a String Schema, an error should be shown? A JSON Schema parser would not throw an error for this, i.e. the following is a valid JSON Schema:
```json
{
    "type": "array",
	"maximum": 23
}
```

Given that these terms are already in the table of their corresponding types, we don't need to assert anything. If we are not asserting something, then it might be better to reformulate it to give guidance.

**Comment by sebastiankb** [comment]
Interesting question. I would simple follow the JSON Schema behavoir and ingnore this kind of information. In case of validation I can image that there will be a hint or warning that `maximum` is not relevant here.

**Comment by egekorkan** [comment]
> In case of validation I can image that there will be a hint or warning that maximum is not relevant here.

Do you mean TD validation (I guess so)? Detecting these kind of things is really annoying since it requires recursive parsing of schemas in a TD via code and it is not possible to create just a warning by using a pure JSON Schema implementation.

For the specification, I would propose to soften this statement since it could also result in TD Consumer implementations to not accept such schemas in a TD. My proposal would be (incorporating #1010):

> Specifies an inclusive lower limit for the values. Associated to number or integer types.

**Comment by sebastiankb** [comment]
From today's TD call:

- to show more flexibility, even it would not make sense that the sentence "Only applicable for associated number or integer types." is more soften
- we should simple remove "only"
- this is also true for multipleOf
- @egekorkan will provide a PR

**Comment by sebastiankb** [comment]
From today's TD call, we decided not to change this and keep as it is
