### ISSUE TITLE
[DataSchema] maximum and minimum are not clear about inclusiveness

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1010]
In the TD spec, the `minimum` and `maximum` for the Integer and NumberSchema are not clear whether they mean and inclusive or exclusive maximum/minimum. Currently it says:

> Specifies a minimum numeric value. Only applicable for associated number or integer types.

Which actually tries to say an inclusive minimum according to the JSON Schema (see https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.6.2.4).

JSON Schema has also `exclusiveMaximum` and `exclusiveMinimum` keywords to indicate the exclusive maximum/minimum.

Thus, I propose to change to the following (also incorporating #1007 ):

> Specifies an inclusive lower limit for the values. Associated to number or integer types.

**Comment by danielpeintner** [comment]
Q: Does it make sense to *add* `exclusiveMaximum` and `exclusiveMinimum` in the TD also?

**Comment by egekorkan** [comment]
It makes sense but there has been no voiced interest in it.

**Comment by sebastiankb** [comment]
From today's TD call:
- we agree that the definition should be more clear about inclusive in min/max
- there is also an agreement that we should also introduce `exclusiveMaximum` and `exclusiveMinimum` in the TD to support more feature from JSON Schema
- @danielpeintner will provide a PR

**Comment by danielpeintner** [comment]
>     * @danielpeintner will provide a PR

PR created, see https://github.com/w3c/wot-thing-description/pull/1021
