### ISSUE TITLE
Required restriction for the hierarchical defined properties

### ISSUE THREAD

**Issue by mryuichi** [w3c/wot-thing-description#1019]
Required restriction for the hierarchical defined properties

Thing Description has a great possibility that many things could be described.  However, it could be sometimes difficult to interpret any TDs if there is not any restriction on the way to describe TD.  Some restrictions on how to describe TD should be required because we must have embedded the TD interpreter to the proxy in advance.

This proposal is based on the experience of the past two plugfests.  Fujitsu provided [the proxy service](https://github.com/mryuichi/documents/blob/master/Plugfest_Outcome_Proxyservice_Fujitsu20201026.pdf) that can read TDs members provided first and generate shadow devices associated with them automatically. The applications handle shadows on the proxy instead of the physical devices since the proxy relays messages between physical and shadow devices.

In the plugfest in June, the proxy could interpret all TDs of accessible devices and enable the application to access them via the proxy. However, some TDs could NOT be done in September.  The reason why it doesn't work is the proxy cannot interpret correctly the hierarchically defined properties in your TDs.  Until the previous plugfest, all TDs were described with one layer properties, so the proxy succeeded to read them and generate shadows from TDs.  However, TUM TDs' properties on this plugfest are defined in three layers like "lightinformation", "state" and "on" for [the Hue color lamp](https://github.com/w3c/wot-testing/blob/master/events/2020.09.Online/TDs/TUM/HueColorLight1.td.jsonld), for example.

I don't mean this TD is wrong. I believe these layered property descriptions are necessary, as some standards use such as Broadband forum TR-069, eclass, and so on.

**Comment by sebastiankb** [comment]
Thank you for sharing this information.

The good news is that this topic is definitely addressed by the WoT profile and an initial guide to the data hierarchy is provided [here](https://w3c.github.io/wot-profile/#constraints-against-the-td-specification). I think this is also a question of resources available of constrained IoT devices which will not support an high hierarchy level.

As you also mentioned, and as is true in #1020, there are already IoT interfaces existing that favor a more hierarchical data model approach and may not fit the planned WoT profile. I think there may be WoT implementations that differ in their support of specific features like parsing a certain level of data hierarchy. This may comparable to the situation where only some security schemes are supported by some implementations.

I think, this is also a good topic to discuss this in one of the next TD calls.

**Comment by egekorkan** [comment]
I think that this out of the scope of the TD spec and handled by the profile. TD does not (and should not) aim to put constraints on existing devices
