### ISSUE TITLE
Multiple bases or forms?

### ISSUE THREAD

**Issue by Citrullin** [w3c/wot-thing-description#1026]
Similar topic to #977
We thought about how we should handle changing IPs and not available scopes. 
One solution would be to have multiple bases. I guess that would also solve #977. So, you are able to put all IPs in it. Global, ULA and link-local.
But for the moment we thought about just adding multiple forms with all of these different IPs. This probably makes it more complicated to interpret. So, I wanted to know the working groups opinion on this. 
Should we just generate multiple forms with different IPs?

**Comment by Citrullin** [comment]
Another use-case where this is relevant: Having multiple interfaces on which the WoT TD is accessible. 
The IPv6 privacy extension is also a use-case where you can have multiple IPv6 addresses for a certain amount of time.

**Comment by danielpeintner** [comment]
FYI: w.r.t. multiple base there has been dome discussion in the past, see https://github.com/w3c/wot-thing-description/issues/803

**Comment by sebastiankb** [comment]
if ok, I like to close this issue since this topic is already addressed here #803
