### ISSUE TITLE
HTML Thing Description Ontology - fragment identifier not fully correct

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#1028]
I don't think it is a big issue but I noticed the following.

The TD context uses references like the following
[`https://www.w3.org/2019/wot/td#hasPropertyAffordance`](https://www.w3.org/2019/wot/td#hasPropertyAffordance)

Clicking on it in a browser opens the right HTML rendered page but does not point to the right fragment identifier which uses non capitalized form

[`https://www.w3.org/2019/wot/td#haspropertyaffordance`](https://www.w3.org/2019/wot/td#haspropertyaffordance)

Do you think this should be fixed?
...meaning the fragment identifier should use the correct capitalized fragment identifier...
@vcharpenay

**Comment by vcharpenay** [comment]
Indeed, it would be convenient, thanks for the suggestion.

Fragments are meant to refer to the content of the Turtle file, not the HTML doc. I'll see if ReSpec can be configured when generating section IDs but I don't guarantee it's possible.

**Comment by vcharpenay** [comment]
From [respec.org](https://respec.org/docs/#sections):

> If you wish a section to have a specific ID, then simply use an id attribute on it.

I'll try to modify the STTL template accordingly. Let's see.

**Comment by vcharpenay** [comment]
seems to work. Please review and merge PR if appropriate.
