### ISSUE TITLE
Wrong context in JSON Schema for TD v1.1

### ISSUE THREAD

**Issue by farshidtz** [w3c/wot-thing-description#1036]
Hi,

In [TD 1.1](https://www.w3.org/TR/wot-thing-description11/) examples, the main context has changed to: `http://www.w3.org/ns/td`

However, the JSON Schema still enforces `https://www.w3.org/2019/wot/td/v1` as the first context:

https://github.com/w3c/wot-thing-description/blob/48e6fa20c6d769f5594eef7675852ac85024d139/index.html#L5140-L5166

This causes JSON Schema based validations to fail.

**Comment by danielpeintner** [comment]
I raised a similar issue for the thingweb-playground (see https://github.com/thingweb/thingweb-playground/issues/168).
Having said that, I don't really have a good solution?
* allowing both uris?
* having a final JSON schema in TD published spec and any yet another with the temporary uri in the draft document
* ...

**Comment by farshidtz** [comment]
I think the JSON Schema should be backward compatible the same way as TD. Otherwise the applications need to maintain multiple JSON Schemas and check against both. So I'll vote for having both URIs.

**Comment by farshidtz** [comment]
BTW, shouldn't the examples use `https://www.w3.org/ns/td` (https scheme) instead?

**Comment by egekorkan** [comment]
> BTW, shouldn't the examples use https://www.w3.org/ns/td (https scheme) instead?

I think that it should. What do you think @sebastiankb ?
