### ISSUE TITLE
Simplified TD: @type

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#104]
Moderated focused discussion on the [Simplified TD proposal](https://w3c.github.io/wot-thing-description/proposals/simplified-td/) and `@type`. Please stay on topic and use https://github.com/w3c/wot/issues/393 for any general remarks.

In https://github.com/w3c/wot/issues/393 @benfrancis wrote:

> * I agree on using this for optional semantic type annotations
> * Does it need to be an array? What if a thing has a single @type and a capability (property, action and event) has a single @type?
> * Could the three levels of @type (thing type, capability type and data type) be reduced down to two? (thing type and capability type). E.g. Do we really need SwitchStatus and SwitchData or could we just have an OnOffProperty capability type whose data type is defined to be boolean in the capability's JSON-LD schema?

```
  "@context": "https://iot.schema.org",
  "@type": "DimmableLight",
  ...
  "properties": {
    "on": {
      "name": "On/Off",
      "description": "Whether the lamp is turned on",
      "@type": "OnOffProperty",
      "schema": {
        "type": "boolean",
      } 
    }
  }
```

**Comment by mkovatsc** [comment]
The data annotations are mainly for complex types. The syntactic information of object key names does not give you the information what data item must go where. It is again the argument of separating instance (cf., `href`) from meaning (cf., `rel`):

From `{ "temp": 23, "hum": 71 }`, only a human can guess the meaning of the fields, because the author was so nice to choose something sensible. To be formal, one needs to attach the semantic type to the keys as well.

Note that capability !== Properties, Actions, Events

Properties, Actions, Events == Interactions

Capabilites == set of Interactions

**Comment by zolkis** [comment]
In wonder if the reason for having array for `@type` is because it is actually means "implements this type", i.e. a Thing property could "implement" constraints coming from multiple definitions? 

In that case (uneducated idea)  wouldn't it be better to use a different word, like `@implements`? If I apply that on the couple of TD examples we have, I believe it makes them more readable / easier to grasp.

**Comment by mkovatsc** [comment]
When there is `SwitchStatus` and it only has `SwitchData` it is truely redundant. The two levels are, however, for the case where there is something along a `DeviceStatus` Property that is of `"type": "object"`, which in turn has one field with `"@type": "SwitchData"` and others along `"@type": "BatteryLevelData"`, `"@type": "SignalStrengthData"`, etc.

In other words, the `*Data` level is for annotating complex (JSON) data schemas.

**Comment by mkovatsc** [comment]
> In wonder if the reason for having array for @type is because it is actually means "implements this type"

`@type` is a standardized JSON-LD keyword for [`rdf:type`](https://www.w3.org/TR/rdf-schema/#ch_type) meaning that the Linked Data node described implements an RDF class (see https://json-ld.org/spec/latest/json-ld/#dfn-node-type, which explains it much better than the JSON-LD 1.0 spec...)

Since it is for Link Data, it should follow Semantic Web standard. Creating the alias term `implements` might just further confuse programmers who then start looking for some class definition, but not in RDF...

**Comment by benfrancis** [comment]
> The two levels are, however, for the case where there is something along a DeviceStatus Property that is of "type": "object", which in turn has one field with "@type": "SwitchData" and others along "@type": "BatteryLevelData", "@type": "SignalStrengthData", etc.

In this example you could simply model the data as three separate properties, of types `@SwitchProperty`, `@BatteryLevelProperty` and `@SignalStrengthProperty`. You could then mix and match those capabilities (assuming here that property types are a kind of capability) between thing types. For example both a power outlet and a coloured dimmable light could have a `@SwitchProperty`, but the light could also have a `@ColorProperty` and `@LevelProperty`.

 Are there other use cases where this approach doesn't work?

> In other words, the *Data level is for annotating complex (JSON) data schemas.

So is the limitation here that a JSON-LD `@type` annotation can only apply one level deep in the JSON structure, but some properties can be multiple layers deep through the use of objects and arrays? I think I had imagined a schema for a `@type` (in the iotschema.org sense of the word "schema") being like a JSON Schema, which can be multiple levels deep.

If you have to provide a `@type` annotation for every level in the JSON structure of a property definition, then presumably the data level `@type`s are not just one level, but many?

```
{
  "@type": "FooThing",
  "name": "Foo Thing", 
  "properties": {
    "foo": {
      "@type": "FooProperty",
      "type": "object",
      "properties": {
        "bar": {
          "@type": "BarData",
          "type": "boolean"
        }
        "baz": {
          "@type": "BazData"
          "type": "object",
          "properties": {
            "qux": {
              "@type": "QuxData",
              "type": "number"
            }
          }
        }
      }
    } 
  },
  "actions": {
    "foo": {
      "@type": "FooAction",
      "input": {
        "foo": {
          "@type": "FooData",
          "type": boolean
        }
       }
    }
  }
}
```

I suppose you could equally just think of those as multiple levels of property types.

```
{
  "@type": "FooThing",
  "name": "Foo Thing", 
  "properties": {
    "foo": {
      "@type": "FooProperty",
      "type": "object",
      "properties": {
        "bar": {
          "@type": "BarProperty",
          "type": "boolean"
        }
        "baz": {
          "@type": "BazProperty"
          "type": "object",
          "properties": {
            "qux": {
              "@type": "QuxProperty",
              "type": "number"
            }
          }
        }
      }
    } 
  },
  "actions": {
    "foo": {
      "@type": "FooAction",
      "input": {
        "foo": {
          "@type": "FooProperty",
          "type": boolean
        }
       }
    }
  }
}
```

**Comment by mkovatsc** [comment]
With the Simplified TD based on JSON-LD 1.1, we now have a [`DataSchema`](https://w3c.github.io/wot-thing-description/#dataschema) class that works as you described in the previous post, @benfrancis . A defined class such as `FooProperty` can be used to annotate a simple Property, a sub-property of a complex Property, or input or output data of Actions -- given all the data items have the same semantic meaning.

This is now possible, because `properties` became recursive from the top-level (whereas the elements under the top-level also implement the [`Property`](https://w3c.github.io/wot-thing-description/#property) class in addition to the [`DataSchema`](https://w3c.github.io/wot-thing-description/#dataschema) class) and because `DataSchema` is a superclass of DataValue (an actual instance of the data, i.e., the Property instance) and DataSpecification (a description of what data can be instantiated, i.e., when invoking an Action (with input) or when a result/output is returned). The latter distinction is also done on schema.org (https://schema.org/PropertyValue vs https://schema.org/PropertyValueSpecification and is needed to make sense in formal semantics).

An open point might be how to use the `@type` at Thing level, whether to put strict types or capabilities. Yet this is more up to the users of the TD spec, as both is allowed.

@benfrancis Are you fine with this? Can we close?

**Comment by benfrancis** [comment]
I *think* I followed that, and it all sounds OK.

FWIW the [experimental Mozilla schemas](https://iot.mozilla.org/schemas/) we've defined currently use only two levels:
1. the thing level (device capabilities)
2. the interaction level (properties, actions and events) 

and that's all our implementation currently supports (although we are looking at how to supported nested properties as well). Our schemas for device capabilities define which properties, actions and events a device supporting that capability might provide and the schemas for interactions define data constraints for property values, action inputs and event payloads. This is a bit different to the current iot.schema.org schemas which have at least one additional level to define data types.

As I understand it these annotations are basically just semantic hints, so authors can add as many annotations as they like and its up to clients to decide whether and how to make use of them.

Does that sound right?

**Comment by mkovatsc** [comment]
That sounds about right. Note that one must still be careful not to annotate with conflicting classes (contradicting statements between annotations or statements contradicting the Property/Action/Event model), as this can/will break reasoning on the formal model. This should be solved by providing proper catalogs such as iot.schema.org or https://iot.mozilla.org/schemas/

@mjkoster @danicic Please just note this outcome for iot.schema.org.

Luckily some consensus. Closing.
