### ISSUE TITLE
Missing "href" in Link under TD 1.1

### ISSUE THREAD

**Issue by farshidtz** [w3c/wot-thing-description#1041]
Hi,

Looks like the "href" attribute has been removed in TD 1.1: https://www.w3.org/TR/wot-thing-description11/#link

It used to be there: https://www.w3.org/TR/wot-thing-description/#link

Was this intentional? [This examples](https://www.w3.org/TR/wot-thing-description11/#link-serialization-json) still uses "href".

Thanks

**Comment by danielpeintner** [comment]
I am not aware of any rational for doing so. Hence it this seems like a bug to me...

**Comment by vcharpenay** [comment]
Indeed, a label was missing in `td-validation.ttl`. See  0f5ad82.
