### ISSUE TITLE
The term required in Thing Model is confusing

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1046]
I find the use of term `required` in Thing Model to imply that this interaction affordance has to be in the generated TD is confusing. First, this `required` is an array whereas all interaction affordances are objects. This makes it difficult for validation, iterating interactions etc. Secondly, I have to realize that this is not an affordance. Thirdly, what if my TM has an affordance called `required`. 

Possible solutions:
- Have a `instanceRequired` term inside of an affordance in a TM that can have a boolean value. The exact term can be something else but it should not be an existing term in JSON Schema to not confuse anyone.
- As SDF does, have a term in the Thing level which is an array that has string values of JSON Pointers that point to arbitrary locations in the TD. This would also allow more granularity, i.e. saying that a single key of an object of a property affordance is required.

**Comment by danielpeintner** [comment]
Yet another alternative could be to have something like the following (the term `requiredInteractions` would allow for indicating the required properties/actions/events).

```
{
	"@context": "https://www.w3.org/2019/wot/td/v1",
	"title": "MyLampThing",
	"requiredInteractions": {
		"properties": ["status"],
		"actions": ["toggle"]
	}
        ...
}

```

**Comment by sebastiankb** [comment]
This topic will be addressed in our next vF2F.

**Comment by sebastiankb** [comment]
I think PR #1092 makes this issue obsolete. If you agree, please close this topic.
