### ISSUE TITLE
Two step generation of the TD from a TM should be clear

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1047]
Currently, two things happen when a TD is generated from a TM (in no particular order, for now):

- Placeholders are replaced with a map. This is properly specified in the current version
- Required terms for a TD such as security definitions or forms are generated somehow. This is only shown in the examples in the current version but specified in the text. It should be made clear that this is left to implementation

Also as mentioned, the TM with no placeholder is a partial TD according to Scripting API. It would be good to combine the efforts here. In any case, these two generation steps should be made clear

Note: Thanks @relu91 for putting my concern into a proper format ::)

**Comment by sebastiankb** [comment]
Actually, there a couple more actions which have to be covered. The PR is updated by:

![image](https://user-images.githubusercontent.com/13832739/108203310-9eae9380-7122-11eb-819a-8f43008b9d13.png)

**Comment by egekorkan** [comment]
Some comments regarding TD (not TM) validation:
- Can a TD have an `@type` with a value of ThingModel? -> I guess not so a change in TD Validation Schema would be needed
- Can a TD have links with `rel:extend` ? -> I guess not so a change in TD Validation Schema would be needed

These have implications to the TD and I would say that such restrictions should be at least hinted in the core part of the document. If I am only interested in the TD and not in TM, how would I know these restrictions? So somewhere in Chapter 5 should say something like "A TD document cannot contain some name-value pairs that are reserved for the Thing Models. Please refer to the Thing Model chapter to find out the restrictions"

**Comment by sebastiankb** [comment]
> Can a TD have an @type with a value of ThingModel? -> I guess not so a change in TD Validation Schema would be needed

based on point two above this should be replaced. But checking this in schema would be great.

> Can a TD have links with rel:extend

So far, it is only motivated for TM and should be removed in the TD (see last point)

**Comment by relu91** [comment]
> Actually, there a couple more actions which have to be covered. The PR is updated by:
> 
> ![image](https://user-images.githubusercontent.com/13832739/108203310-9eae9380-7122-11eb-819a-8f43008b9d13.png)

I think that the algorithm looks good from the TD specification point of view. However, it would be really great to reflector it somehow so that we could reuse some steps in [this task](https://github.com/w3c/wot-scripting-api/issues/304).

Concretely, it would be sufficient to talk about PartialTD and move the "missing communication etc." to a separate algorithm since we have our own algorithm to concretely create a TD using runtime capabilities.

**Comment by relu91** [comment]
Something like this:

To derive a `Thing Description` instance from a `Thing Model` first transform it to a `PartialTD`:
- Copy all definitions in the applied Thing Model to the resulting PartialTD instance. If used, the extension and imports feature according to Section § 10.3.2 Extension and Import must be resolved and represented in the PartialTD instance as well.
- If used, remove from `PartialTD` links entry with "rel":"extend".
- The value ThingModel value of the top-level @type have to be replaced by the value Thing in the PartialTD instance.
If the required feature is used based on Section § 10.3.4 Required, the required interactions must definitely be taken over in the  PartialTD instance.
- If used, all placholder (see Section § 10.3.3 Placeholder) in a Thing Model must be replaced with a valid corresponding value in the PartialTD.

Finally, take the resulting `PartialTD` and transform it into a `Thing Description` with the following step:
- Fill in missing communication and/or security metadata details based on Section § 6.3.4 securityDefinitions and security and/or § 6.3.9 forms.

Just to have an idea, but if we follow this structure we would be less redundant and more consistent between the ScriptingAPI and TD documents.

**Comment by egekorkan** [comment]
I really like this kind of algorithmic approach. It would make it easier to verify for different implementations since we can see the result in different steps as well :) Also would give more guidance on how to implement this

**Comment by sebastiankb** [comment]
Yes why not. One thing which I do not like is that we have to introduce what a "partial TD" is. May confuse reader?

**Comment by relu91** [comment]
>  One thing which I do not like is that we have to introduce what a "partial TD" is. May confuse reader?

yeah, that could be a risk, However, it is formally introduced in the architecture document so a link should sufficient 🤔

**Comment by danielpeintner** [comment]
> Yes why not. One thing which I do not like is that we have to introduce what a "partial TD" is. May confuse reader?

Yet another advantage is that other documents (like scripting, discovery, ..) might make use of it also....

**Comment by sebastiankb** [comment]
From today's TD call:
- we agreed to use the following approach as @relu91 provided by this [comment](https://github.com/w3c/wot-thing-description/issues/1047#issuecomment-781226227)
- we have to introduce the definition of "Partial TD" in the terminology section (or check if we can rely on the Architecture 1.1 version?) -->  there is a definition [available ](https://w3c.github.io/wot-architecture/#dfn-partial-td)
- @sebastiankb provide a PR

**Comment by sebastiankb** [comment]
text is updated by the PR
