### ISSUE TITLE
Array definitions in Hypermedia Controls Vocabulary Definitions

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#1048]
[Links](https://w3c.github.io/wot-thing-description/#link) of the current draft defines a string AND an array  for `type` and `rel`. Same situation can be found in Form and ExpectedResponse. I think, there is a mistake in the validation or ontology file.

**Comment by vcharpenay** [comment]
Regarding `type` (and `contentType` in Form and ExpectedResponse), an array implies that the resource can be served in different formats. A client can then start content negotiation.

Regarding `rel`, it's true an array wouldn't make sense.

**Comment by sebastiankb** [comment]
PR fixed this issue
