### ISSUE TITLE
Simplified TD: @id/id

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#105]
Moderated focused discussion on the [Simplified TD proposal](https://w3c.github.io/wot-thing-description/proposals/simplified-td/) and `@id`/`id`. Please stay on topic and use https://github.com/w3c/wot/issues/393 for any general remarks.

In https://github.com/w3c/wot/issues/393 @benfrancis wrote:

> Why is this necessary? Why is the URL of the Thing Description not a suitable URI to identify a Thing? Why is an additional urn needed?

**Comment by mkovatsc** [comment]
For identity and related device management. It is necessary for all commercial/industrial use cases.

**Comment by mkovatsc** [comment]
> In https://github.com/w3c/wot/issues/393 @benfrancis wrote:

That doesn't answer my question. Why can't the Thing URL be used as as that identifier? Why is an additional URN needed?

**Comment by mkovatsc** [comment]
* "Thing URL" is the URI from where the client fetched the TD: This URI might just be a proxy, might be pointing to a directory, might be a local copy, etc. A TD is just a serialization of metadata and might be available at multiple resources. But we need to identify the unique physical assets that are represented as Things. Hence, these identifiers.
* "Thing URL" is the `base` URI of a Thing (which is the same as above when you use relative URIs and no `base` as proposed by you): Here we have issues of mobility and lifecycle changes in general: the physical asset might roam from one gateway to another, which would change the Thing's network address and potentially more parts of that URI; a Thing directly hosting its Servient (e.g., a CoAP server on a device) underlies IP address changes; Things connected over mobile networks are usually behind a cascade of NATs and a port change leads to a URI change as well (search OMA LWM2M for more details on this). Then just imagine a Thing is available over HTTP, CoAP, and some to-come WebSocket protocol. Does it have multiple identities then? No. Do we want to manage and carry around lists of identities for a single asset? Usually no. Hence, you find these identity URNs in most enterprise systems.

**Comment by benfrancis** [comment]
I would argue that:
* A thing isn't a web thing unless it has a URI on the web
* If two thing descriptions exist at two different URIs, then they are two separate web things as far as a WoT client is concerned
* Multiple representations of the same thing can share the same URI (using content negotiation)
* Sub-resources of a Thing (e.g. a property or a WebSocket endpoint) can have a different URI
* Assuming that two separate URIs from two separate origins are the same resource breaks the same-origin security policy of the web
* If you want to associate a real world unique identifier such as a serial number with a web thing, then that should be an optional semantic annotation
* "[Cool URIs don't change](https://www.w3.org/Provider/Style/URI)"

Again I'm wondering, are we building a web **of** things, or a web **about** things?

**Comment by mkovatsc** [comment]
My understanding is, you are proposing the "web **about** things" where stable URIs, lifecycle changes, and mobility are not an issue.

We want to use concepts from the Web to better deal with the complexity of IoT, and hence want to build a "Web **of** Things", where resources are not as stable because of the nature of actual things.

Also the same-origin policy is not a good fit for WoT, as we are aiming for interoperability across vendors and operators. When you control all hosts in a Web of Things, it becomes trivial and we don't need innovation.

**Comment by draggett** [comment]
The URL for a thing description is an identifier for metadata for that thing. Tim Berners-Lee's Cool URI's don't change is fine for URLs used as stable identifiers.  Some metadata may be very stable, some may not. I don't understand the rest of what @mkovatsc said.

**Comment by draggett** [comment]
We should follow and encourage best practices for Linked Data rather than encouraging the use of URNs, see:

* [Best Practices for Publishing Linked Data](https://www.w3.org/TR/ld-bp/)  W3C Working Group Note 09 January 2014

And for the use of HTTP URIs (URLs) in particular:

* https://www.w3.org/TR/ld-bp/#HTTP-URIS

I agree that sometimes, a thing description may be available from multiple sources, and in such cases, it is valuable to have the canonical Linked Data identifier for the thing to be declared within the the thing description.

**Comment by mkovatsc** [comment]
Having a mandatory ID for Things in their TD is independent from the discussion whether Interactions of Things are reachable at a URI (which they of course are).

Most examples of Thing or device IDs we saw during the Prague F2F (e.g., the external presentation by ETSI ISG CIM) used URNs as unique device/Thing IDs. Also see for instance https://tools.ietf.org/html/draft-arkko-core-dev-urn-05.

Current conclusion is to have a mandatory `id` field in the TD, which takes any URI (which includes URNs) and is compatible with Linked Data (JSON-LD `@id` is also a URI). This can be the same URI where the TD is fetchable and the base URI of the Interactions, but due to real-world issues, it does not have to be.

**Comment by sebastiankb** [comment]
The new TD version includes a mandatory ID field at the top level as current working assumption.
