### ISSUE TITLE
Updating NEW_FEATURES.md

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1051]
There is a document in this repository called NEW_FEATURES.md (https://github.com/w3c/wot-thing-description/blob/master/NEW_FEATURES.md). It says:

> This document will log all new features that are implemented in the new Thing Description Maintenance version

However, it is not updated for 9 months where some new features did get implemented such as combo security scheme etc.

We can just keep this issue open until the publication (or feature freeze) as a reminder to document the changes.

**Comment by sebastiankb** [comment]
see PR #1282

**Comment by egekorkan** [comment]
Instead, this will be probably deleted. See #1367
