### ISSUE TITLE
[validation] Changing `oneOf` to `anyOf` for the validation of security scheme

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1055]
## Background

When I was working on the PR #1049 , I was removing the `enum` for all string types so that one can have a TM that has:

```js
"op":"{{MY_PLACEHOLDER}}"
```

but of course also:

```js
"scheme":"{{MY_PLACEHOLDER}}"
```

## Problem

All good for now. However, this means that a security scheme becomes unidentifiable since the value of `scheme` is how they are identified. Current validation schema has:
```js
"securityScheme": {
      "oneOf": [{},...,{}]
}
```

So now when I go and validate TD, it can satisfy multiple security scheme Schemas and not only one as implied by `oneOf`. 

## Possible Solutions

1. Replace `oneOf` with `anyOf` in the TD validation schema. Thus TM Schema is also with `anyOf`
2. Change `oneOf` to `anyOf` only in the TM schema during TM Schema generation process.

This is mostly a small thing but wanted to ask anyway :)

**Comment by mmccool** [comment]
So #1205 has been merged so I think this issue is now resolved and can be closed.  I have added the "Propose closing" label therefore (and removed the PR available since it was already merged).
