### ISSUE TITLE
Representation of examples (hidden information)

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#1059]
I the current TD document we have examples that use different approaches to show _additional_ information:

* checkbox, see https://w3c.github.io/wot-thing-description/#example-3
* tab, see https://w3c.github.io/wot-thing-description/#example-48

Both makes sense when taking a look at the spec in a browser but user experience suffers when printed out.
Are there *better* alternative we can use? Does it seem acceptable?

Note1: I do know that JSON-LD uses tabs also
Note2: In the scripting API we use the tab approach also for examples and we are having the same concern/question.

**Comment by egekorkan** [comment]
I could think of a "printable version" on the W3C specs where such sections can be expanded. So we can have index.html but also another document that is generated with the render script.

**Comment by danielpeintner** [comment]
Yet another alternative would be to have them next to each other (in a kind of column on bigger screens or underneath on mobiles devices a la bootrap columns) but *always* fully visible.

**Comment by danielpeintner** [comment]
see https://github.com/w3c/wot-thing-description/pull/1279 for a proposal how to solve this.
