### ISSUE TITLE
Simplified TD: base

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#106]
Moderated focused discussion on the [Simplified TD proposal](https://w3c.github.io/wot-thing-description/proposals/simplified-td/) and `base`. Please stay on topic and use https://github.com/w3c/wot/issues/393 for any general remarks.

In https://github.com/w3c/wot/issues/393 @benfrancis wrote:

> Similarly, why is a base URL needed? Can the Thing Description's URL be used as the base URL?
> **Note**: I strongly recommend against automatically generating URL structures based on property/action/event names. Links to property/action/event resources should be explicit with the use of a URL.

**Comment by mkovatsc** [comment]
In https://github.com/w3c/wot/issues/393 @benfrancis wrote:

OK. Perhaps base can be optional and the Thing URL could be used as a fallback, like in HTML and CSS.

**Comment by mkovatsc** [comment]
While it is technical possible, it just makes TDs more error-prone. When sharing TDs, you will always have to process them first and fill in the absolute URIs. Given that directories are a common use case in IoT, it is much easier to make them self-contained by specification. Just think about all the links that you cannot share because the server used cookies or session IDs in the URI and the recipient of the link cannot see what you see. That has always been very annoying. You would start something similar for WoT or would force everyone to always have some exporting tool at hand that rewrites the URIs...

See also the issues explained in https://github.com/w3c/wot-thing-description/issues/105

**Comment by draggett** [comment]
You should share the URL for the thing description as this ensures you also share it URL. We also know that this is a thing description from the media type e.g. application/json+td

**Comment by sebastiankb** [comment]
_base_ is used for optimization and is defined optional. If desired, interactions can always use absolute URIs.
