### ISSUE TITLE
Suggestion for change in upcoming release - Update link for JSON LD 1.1

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [w3c/wot-thing-description#1066]
Dear all,

in [Informative Reference](https://www.w3.org/TR/wot-thing-description/#informative-references) section the reference to the JSON LD standard is as follows:

> https://www.w3.org/TR/2020/CR-json-ld11-20200316/

Since it is available as a recommendation now the reference could be updated to:

> https://www.w3.org/TR/json-ld11/

Best

Georg

**Comment by sebastiankb** [comment]
Respec now generates the right reference. Also see https://w3c.github.io/wot-thing-description/#informative-references

Propose to close this issue.
