### ISSUE TITLE
uriVariables needs to be more limited

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#1068]
`uriVariables` should only typed with simple data types such as string and number. Complex types like arrays and object should not allowed. We need an assertion about this.

**Comment by relu91** [comment]
Another thing that is confusing about `uriVariables` is the ability to use them also in action affordances. There, we have already the `input` field which specifies the required arguments of an action. I think we should rather rely on the input field and specify that the URI template can refer to first-level properties in the input data schema. For example, consider this odd Web Thing that has an action that takes in input id as URI variable and a payload:
```js
"configure":{
            "title": "configure",
            "description": "",
            "input": {
                "title": "payload",
                "type": "object",
                "properties": {
                    /**/
                }
            },
            "uriVariables": {
                "id":{
                    "type": "string"
                }
            },
            "output": {},
            "forms": [{
                "href": "http://example.com/subdevice{?id}"
            }]
        }
```

Essentially we could simplify the affordance like this: 
```js
"configure":{
            "title": "configure",
            "description": "",
            "input": {
                "title": "payload",
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    }
                    /**/
                }
            },
            "uriVariables": {
                "id":{
                    "type": "string"
                }
            },
            "output": {},
            "forms": [{
                "href": "http://example.com/subdevice{?id}"
            }]
        }
```

A runtime just needs to know which property of the input should be inserted in the URI. Conflicts between the payload and the URI template can be easily resolved by using a different name. 

Regarding other interaction affordances (i.e., properties and events), having `uriVariables` it's a strong hint for a bad design choice as they are probably actions. I've not found anything on the document describing this possible issue. I think we should consider also this problem when talking about https://github.com/w3c/wot-thing-description/issues/1020.

**Comment by egekorkan** [comment]
> Regarding other interaction affordances (i.e., properties and events), having uriVariables it's a strong hint for a bad design choice as they are probably actions.

The main use case I find for `uriVariables` in properties or events is to filter a key of an object, give an input for getting something or to simply describe already existing Web APIs. I think that the first two points are not really RESTful designs but they are what literally every weather API does... Examples of weather APIs below:
- https://openweathermap.org/current
- https://www.weatherbit.io/api/weather-current
- https://developer.accuweather.com/accuweather-forecast-api/apis : This one is actually not `uriVariables` but `uriTemplates` that we cannot describe yet in TDs, I think?

**Comment by relu91** [comment]
Yes! exactly. What I would like to see on the document is an explainer saying that: "retrofitting an existing API might need the usage of `uriVariables` as in (examples of APIs that needs  `uriVariables`) .... however they SHOULD not be used when designing _a new WoT system_.

**Comment by egekorkan** [comment]
@relu91 I think your second example above has some copy-paste artifact left in there. I guess uriVariables in the second example should not be there?

Regarding modeling it as an action, I think that it does not make sense from an interaction modeling point of view. Here, a data is simply being retrieved and retrieving it does not cause any changes in the system. I think the 3rd option used by Accuweather is the most logical one and uses REST principles better.

**Comment by egekorkan** [comment]
In the call of 12.05, we have decided to close this issue but open a new one at: https://github.com/w3c/wot-thing-description/issues/1138
