### ISSUE TITLE
Missing Thing securityDefinitions in TD 1.1

### ISSUE THREAD

**Issue by farshidtz** [w3c/wot-thing-description#1069]
Hi,

Similar to #1041, the securityDefinitions has gone missing from Thing table:

https://www.w3.org/TR/wot-thing-description11/#thing
![image](https://user-images.githubusercontent.com/11150423/111456037-cccdc600-8716-11eb-98c0-602aac864fd8.png)

https://www.w3.org/TR/wot-thing-description/#thing
![image](https://user-images.githubusercontent.com/11150423/111456089-dbb47880-8716-11eb-8431-c9276e6fd701.png)

**Comment by sebastiankb** [comment]
strange. I will check this.

**Comment by mmccool** [comment]
Yes, I noted this in the other issue related to security/securityDefinitions.  I wanted to borrow the structure of securityDefinitions for schemaDefinitions only to find securityDefinitions had gone AWOL...

**Comment by mmccool** [comment]
see also PR https://github.com/w3c/wot-thing-description/pull/937 and PR https://github.com/w3c/wot-thing-description/pull/915 - neither of which necessarily fixes this problem.

**Comment by farshidtz** [comment]
Thing.base is also missing in TD 1.1.

**Comment by sebastiankb** [comment]
securityDefinitions is back again
