### ISSUE TITLE
An explainer table for the operation values is missing

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1074]
As mentioned in the call of 24.03.2021, there is a lack of an explanation of what each operation such as `readproperty`, `observeallproperties` does is missing. I think a table would suit this quite well.

There is actually such a table in the binding templates document (https://w3c.github.io/wot-binding-templates/#form-operation-type-vocabulary) so I can migrate that here and add the remaining values.

**Comment by sebastiankb** [comment]
@egekorkan can you provide a PR for it?

**Comment by egekorkan** [comment]
A PR should be created soon, once the discussion in https://github.com/w3c/wot-architecture/issues/606 is resolved
