### ISSUE TITLE
"Previous version" link not available anymore

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1087]
In the earlier published versions, like https://www.w3.org/TR/2020/PR-wot-thing-description-20200130/, there was a link to the previous published versions. Now the 1.1 version does not link back to the previous ones https://www.w3.org/TR/wot-thing-description11/

I am not sure if this is a bug but it would be nice to be able to navigate back to the previous versions somehow. I had to manually find the URL.

**Comment by egekorkan** [comment]
By the way, this applies to architecture as well

**Comment by danielpeintner** [comment]
It *seems* 1.1 is being considered to be a *new* version rather than an update ... also w.r.t. to the URL
https://www.w3.org/TR/wot-thing-description/ vs
https://www.w3.org/TR/wot-thing-description11/

**Comment by egekorkan** [comment]
In the call of 21.07, we have agreed on:
- We will close this issue since one can use the search function at https://www.w3.org/TR/ to search for old versions. This is also mentioned in the "Status of This Document" section.
- @egekorkan will create an issue in marketing webpage
