### ISSUE TITLE
Missing top-level "base" field in TD 1.1.

### ISSUE THREAD

**Issue by farshidtz** [w3c/wot-thing-description#1091]
Thing.base was available in [TD 1.0](https://www.w3.org/TR/wot-thing-description/#thing) but has gone missing in [TD 1.1](https://www.w3.org/TR/wot-thing-description11/#thing).

Was this intentional?

_Originally posted by @farshidtz in https://github.com/w3c/wot-thing-description/issues/1069#issuecomment-816581540_

**Comment by sebastiankb** [comment]
base is back again
