### ISSUE TITLE
How to extend Data Schema terms while being JSON Schema compliant

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1094]
The TD Spec says:

> The data schema vocabulary definition is reflecting a very common subset of the terms defined by JSON Schema [JSON-SCHEMA]. It is noted that data schema definitions within Thing Description instances are not limited to this defined subset and may use additional terms found in JSON Schema using a TD Context Extension for the additional terms as described in § 7. TD Context Extensions, 

This is a bit too open for Data Schema terms that are meant to be JSON Schema terms. For example, assuming that JSON Schema has an OWL vocabulary at `"https://jsonschema.org/vocab"` and I want to use the term `pattern` of JSON Schema that allows the definition of regular expressions and that is not the TD vocabulary. If I write a TD like the following:
```js
{
    "@context": [
        "http://www.w3.org/ns/td",
        {
            "schema": "https://jsonschema.org/vocab",
        }
    ],
    ...
    "properties": {
        "phoneNumber": {
            "description": "Phone number to send SMS notifications to",
            "type": "string",
            "schema:pattern": "^(\\([0-9]{3}\\))?[0-9]{3}-[0-9]{4}$",
            "forms": [...]
        }
    }
}
```

A semantic processor would understand this but a JSON Schema processor would fail to understand the pattern keyword. I would have thus failed on using JSON Schema. The correct TD should be thus something like the following:

```js
{
    "@context": [
        "http://www.w3.org/ns/td",
        "https://jsonschema.org/vocab"
    ],
    ...
    "properties": {
        "phoneNumber": {
            "description": "Phone number to send SMS notifications to",
            "type": "string",
            "pattern": "^(\\([0-9]{3}\\))?[0-9]{3}-[0-9]{4}$",
            "forms": [...]
        }
    }
}
```

Thus, I would propose to change the note above (or add a new one) to restrict the usage of JSON Schema vocabularies to not be used in a Map but appended to the `@context` array.

P.S. This issue brought to you by https://github.com/w3c/wot-thing-description/issues/1093#issuecomment-818865847

**Comment by sebastiankb** [comment]
Proposal: When using terms that are not deffined in DataSchema and do not have a prefix, it must be assumed that the origin is in the JSON schema. If this is not intended the terms must have a prefix with specific context.

**Comment by fennibay** [comment]
So I understand the proposal here is to use the jsonschema:pattern (currently missing, see #1101) instead of [schema:pattern](https://schema.org/pattern), correct?

**Comment by sebastiankb** [comment]
This is a generic discussion of JSON Schema features that are not yet covered in DataSchema. The TDs spec allows these features to be used as well, but it should be clearer whether these features need to be introduced with a context or are indirectly assumed to come from the JSON Schema context.

Regarding `pattern` itself I would +1 to introduce this simple in DataSchema.

**Comment by egekorkan** [comment]
After seeing issue #1101 , I just want to point out that the example above is just something I thought on the spot.

**Comment by sebastiankb** [comment]
continue discussion here #1119
