### ISSUE TITLE
Simplified TD: Media Type

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#110]
Moderated focused discussion on the [Simplified TD proposal](https://w3c.github.io/wot-thing-description/proposals/simplified-td/) and Media Type. Please stay on topic and use https://github.com/w3c/wot/issues/393 for any general remarks.

In https://github.com/w3c/wot/issues/393 @benfrancis wrote:

> I'd suggest `application/td+json` as that is the format used by most [registered MIME types](https://www.iana.org/assignments/media-types/media-types.xhtml) for JSON-based formats.

**Comment by mkovatsc** [comment]
Good, agreement, beause I forgot the `+json` extension, but meant to have it as discussed in #86 and #88.

I updated the [Simplified TD proposal](https://w3c.github.io/wot-thing-description/proposals/simplified-td/#media-type) accordingly.

**Comment by sebastiankb** [comment]
Media type is introduced in the new TD version (see section 6.2)
