### ISSUE TITLE
Canonical form: dateTime ambiguities

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#1105]
A few details need to be nailed down in dateTime for canonical form:
- <s>Z must be capitalized (technically lower case is allowed)</s>
- <s>T must be present and capitalized (technically it may be lower case or replaced with a space)</s>
- TD processors must preserve the serialization of fractional seconds, if present, using the same rules as for real numbers in JCS (not entirely sure about this one; fracsecs are optional, and rarely used, maybe we should just not allow them in Canonical form)
- <s>4 digit years must be used (spec is confusing, this may be mandatory already in rfc3339, if so we can omit)</s>

**Comment by danielpeintner** [comment]
Question: I assume the different representations for numbers are handled by https://datatracker.ietf.org/doc/html/rfc8785#section-3.2.2.3 or respectively https://262.ecma-international.org/10.0/#sec-tostring-applied-to-the-number-type, correct?

**Comment by mmccool** [comment]
Yes, numbers are handled by JCS, which also defines the sorting of objects.  However, JCS does say anything about timestamps or URLs, so we have to nail down any variants for those types.  So I was reading through the dateTime spec and noticed it allows a few variations.  These are technically permitted (like use of z instead of Z) although unusual... but for canonical form we should explicitly disallow them.  The only really tricky one is fractional seconds, which is optional.  Probably should add a rule to disallow trailing zeros and suppress the decimal in case of a zero fractional part, but I need to check if they are already disallowed by the dateTime spec.

Actually, I need to clean up one more thing: the difference between a canonicalizer and a processor. A processor basically should not modify an already canonicalized TD, or if it does (eg in the case of chained signing, another PR I am working on and hope to submit today) it should not modify existing elements, like URLs.  A canonicalizer needs to PUT things into canonical form in the first place.

**Comment by mmccool** [comment]
Anyway, for fracsecs, I could just say "The representation of seconds, including any fractional part, should follow the canonicalization rules defined by JCS for numbers, except that no exponent is allowed".

**Comment by mmccool** [comment]
So here is the ECMA definition of "NumberToString" that JCS references:
https://262.ecma-international.org/10.0/#sec-tostring-applied-to-the-number-type
It's fairly complicated, and for fracsecs we don't want big chunks of it (Infinity, negative numbers, exponents...).
Also, https://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/#dateTime SEEMS to allow fractional seconds with arbitrary numbers of trailing zeros like "25.1000000" which is numerically equivalent to "25.1".  That actually makes sense to allow if you want to be able to sort timestamps lexically, assuming all fractional seconds use the same resolution, but is an issue here.
I propose adding the following assertion:
"Seconds will be serialized as other numbers under the JSON Canonicalization Scheme, except that negative numbers and exponents are not permitted."  I will follow this with a note: "Note that trailing zeros and zero fractional seconds are not permitted under this serialization."

**Comment by mmccool** [comment]
The dateTime spec is also specific about Z or T being capitals (and T being present) so I have not added an assertion about that and have struck it out in the above description.

**Comment by mmccool** [comment]
Please review the above PR, which I think resolves this issue fully.

**Comment by danielpeintner** [comment]
Maybe just something to look at...

Not sure but based on the "3.2.7.2 Canonical representation" section of [dateTime](https://www.w3.org/TR/xmlschema-2/#dateTime) it seems that
* hour can be '24' ... Canonical XML forbids that besides
* fractional second string, if present, must not end in '0'
