### ISSUE TITLE
Identify Canonical TD

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#1107]
It would be helpful to have a simple way to determine when a TD is in canonical form.  I propose adding a value "Canonical" to be used in the @type at the top level.  This would be included in the base TD vocabulary so would not need a prefix.

**Comment by sebastiankb** [comment]
What would be the advantage or use cases? My understanding is that a signing process will always do a normalisation process as one of the first steps, right?

**Comment by mmccool** [comment]
A canonical TD is not necessarily signed, but would be useful for other purposes, such as diffs or checking for updates.  It'd be useful to know in such cases if a TD is already in Canonical form.

**Comment by mmccool** [comment]
Anyway, the other reason to have it is that a processor may have to apply special processing to keep a TD in canonical form, such as sorting objects when it spits out a new TD, steps it can omit if canonicalization is not necessary (eg if the input was not canonical).

**Comment by egekorkan** [comment]
While not being very sure, wouldn't it be better to specify this somehow when the TD is delivered, i.e. in the content type? What are other specifications that need canonical form do?

**Comment by relu91** [comment]
I did a brief research and I found out that json-ld uses the content-type to request a particular _profile_: 
> This specification defines six values for the profile parameter.
>
>   http://www.w3.org/ns/json-ld#expanded
>   To request or specify expanded JSON-LD document form.
>
>   http://www.w3.org/ns/json-ld#compacted
>   To request or specify compacted JSON-LD document form.
>
>   http://www.w3.org/ns/json-ld#context
>   To request or specify a JSON-LD context document.
>
>   http://www.w3.org/ns/json-ld#flattened
>   To request or specify flattened JSON-LD document form.
>
>   http://www.w3.org/ns/json-ld#frame
>   To request or specify a JSON-LD frame document.
>
>   http://www.w3.org/ns/json-ld#framed
>   To request or specify framed JSON-LD document form.
>
>   All other URIs starting with http://www.w3.org/ns/json-ld are 
>   reserved for future use by JSON-LD specifications.

See the [full content-type IANA registration](https://www.iana.org/assignments/media-types/application/ld+json). I would start from this approach, even if it might still be a problem for non-HTTP clients that want to use a TD.

**Comment by egekorkan** [comment]
Ah that is what I was thinking of :+1: How do the concrete string for a media type look like with optional parameters? So where should I indicate expanded profile in  `application/ld+json` ?

**Comment by danielpeintner** [comment]
> It would be helpful to have a simple way to determine when a TD is in canonical form. I propose adding a value "Canonical" to be used in the @type at the top level.

I am also not sure whether it helps that a TD labels itself as "canonical".

Cases
1.  The TD is canonical
    * one can directly create the hash (the same could be also done without the label).
    * IF label is wrong (the hash does not match) go to step 2 
2. The TD is *not* canonical
   * one needs to go through the canonicalization steps to check hash 

Note: I would encourage implementations to provide TDs in a canonical form.  Hence, we should state that as best practice in the spec.

**Comment by mmccool** [comment]
True, a non-canonical TD labelled as Canonical might be a problem in practice, so it would always be best practice to recanonicalize anyway.

**Comment by mmccool** [comment]
so:
- Have labelled this as related to canonicalization so we can find it later
- Propose we close this (as with all other canonicalization issues) - we can reopen it later if necessary

In passing though I want to mention the use of the fragment identifier in the context URL to identify a "profile" is a little troubling since the IETF specs specifically state that fragment identifiers should be used to identify *parts* of a document.  We had a similar discussion around using fragment identifiers on IDs to distinguish different "views" of a master TD and resolve the TD/Thing id issue.

**Comment by egekorkan** [comment]
Closing this as part of canonicalization issues. They will be reconsidered in 2.0 by searching for the label
