### ISSUE TITLE
Simplified TD: Objects vs Arrays

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#111]
Moderated focused discussion on the [Simplified TD proposal](https://w3c.github.io/wot-thing-description/proposals/simplified-td/) and Media Type. Please stay on topic and use https://github.com/w3c/wot/issues/393 for any general remarks.

In https://github.com/w3c/wot/issues/393 @benfrancis wrote:

> As I've mentioned before, we'd prefer the object representation. You can easily iterate through keys of an object in JavaScript. Having an ID in an array element is doable, but `thing.properties[0]` is a lot more clunky than `thing.properties.on`.

**Comment by zolkis** [comment]
I agree for using object instead of array: it is more generic, more compact and it's easier to manipulate members.

**Comment by mkovatsc** [comment]
Yes, for a more intuitive Scripting API, I now also tend toward objects. The `@id` part being assigned to the Interaction node is also a nice side-effect. We do not use `name` anymore to identify the Linked Data node, but correctly use `@id`.

**Comment by mkovatsc** [comment]
Based on the Prague 2018 resolution to change to the Simplified TD with a JSON-LD 1.1 style object notation, I close this issue.

Example of Simplified TD syntax:
```javascript
{
    "id": "urn:dev:wot:com:example:servient:lamp",
    "name": "MyLampThing",
    "properties": {
        "status" : {
            "type": "string",
            "form": [{"href": "coaps://mylamp.example.com:5683/status"}]
        }
    },
    "actions": {
        "toggle" : {
            "form": [{"href": "coaps://mylamp.example.com:5683/toggle"}]
        }
    },
    "events":{
        "overheating":{
            "type": "string",
            "form": [{"href": "coaps://mylamp.example.com:5683/oh"}]
        }
    }
}
```
