### ISSUE TITLE
Canonical dates and times

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#1117]
I think there are still some issues w.r.t. to canonical dates/times:

* ISO 8601 allows hour to be `24`. Hence I believe that `"2021-01-01T24:00:00Z"` and `"2021-01-02T00:00:00Z"` should be considered to be the same date-time. Note: Canonical XML schema forbids hour 24, see https://www.w3.org/TR/xmlschema-2/#dateTime to get rid of this issue.
* besides `"date-time"` JSON schema also supports the format for "`time"` and `"date"`. Should they be integrated/mentioned also?
   * I know that the TD just has the type `dateTime` but what if I use the JSON schema format  term (e.g., `{"type": "string",  "format": "time" }`) ?

**Comment by mmccool** [comment]
Thanks for pointing the 24 hour thing out.  There's also leap seconds... 

I think in general we should reference the XML spec over ISO. Time and date could be used in payloads, but (so far) are not used in any normative values that I know of.  If we do put them somewhere in the future, they would have to follow the same rules.

**Comment by mmccool** [comment]
PR https://github.com/w3c/wot-thing-description/pull/1124 should resolve the 24:00 issue.  I think application to date and time is not relevant since we use dateTime everywhere (date or time used in a schema defining a payload are not relevant to TD canonicalization)
