### ISSUE TITLE
Should non-web protocols be accommodated by the WoT Thing Description?

### ISSUE THREAD

**Issue by benfrancis** [w3c/wot-thing-description#113]
In the TD serialization call today hosted by EVRYTHNG I heard a lot of agreement around Siemens' proposed [simplified Thing Description](https://w3c.github.io/wot-thing-description/proposals/simplified-td) format as the next stage of the Thing Description after Prague, particularly the [experimental example](https://w3c.github.io/wot-thing-description/proposals/simplified-td/#wip-experimental-td) which applies JSON-LD 1.1 to allow for further simplifications and neatly aligns with JSON Schema syntax.

One topic we briefly touched on was what should be **out of scope** for the Thing Description, which I thought could do with a broader discussion.

I put forward the argument that the Thing Description should be restricted to only describing things using web protocols (which can be linked to using URLs) and should not try to describe non-web protocols.

EVRYTHNG explained one use case of the Web Thing Model where the REST API is used as a layer of abstraction to expose devices using MQTT to the web using a cloud integration pattern, such that MQTT itself doesn't need to be described in the Thing Description.

@mkovatsc mentioned a use case where the Thing Description is used for internal asset tracking and may want to describe things using non-web protocols like Bluetooth to make use of the semantic annotations used. He also mentioned a use case where you might want to describe the HomeKit protocol (using Bluetooth) directly in the Thing Description.

I argued that Bluetooth is not a web protocol and therefore should not be described in a WoT Thing Description, but instead used in a layer of abstraction below the Web of Things. (An exception to this might be if Bluetooth 4.2/5.0 is used with an IP layer + a web protocol like HTTP or CoAP on top and can directly expose URLs).

Matthias made the point that many web technologies are often used outside of web browsers like HTML inside native packaged apps. This is true, but I'd argue that using HTML inside a packaged app (e.g. Cordova) isn't the web (although a native app which calls a REST API over HTTP is using the web). I can understand if people want to re-use the Thing Description format for non-web use cases (like re-using HTML inside native packaged apps or JavaScript on servers), but we shouldn't complicate the Thing Description format in order to accommodate those use cases, or provide them as examples in the specification.

The Verge have a useful and concise [definition](https://www.theverge.com/2017/5/24/15681958/what-is-web-definition) of the web:

>  To count as being part of the web, your app or page must:
>  1. Be linkable, and
>  2. Allow any client to access it.

Both of these points are also necessary in order to make ad-hoc interoperability on the Web of Things possible.

- HTTP is the web because it is both linkable and uses a royalty free standard which can be accessed by any client.
- CoAP is the web because it is both linkable and uses a royalty free standard which can be accessed by any client.
- WebSockets are the web (I would argue) because things can be linkable (you can have a URL per thing) and any web client can access them. This one is a bit more contentious because of the low level nature of a WebSocket and the need for a sub-protocol. I hope that a future version of HTTP might come up with a better solution to pub/sub use cases which is a more natural extension of REST, like CoAP has.

- Bluetooth is not the web because it is not linkable.
- HomeKit is not the web because it is not linkable (at least in the Bluetooth version) and can only be accessed by clients which Apple approves.
- ZigBee is not the web because it isn't linkable.
- MQTT is not the web because it isn't linkable. There is a [proposal](https://github.com/mqtt/mqtt.github.io/wiki/URI-Scheme) (not part of the standard as far as I know) for an mqtt:// URL scheme for opening a connection to an MQTT server, but this is only to open a connection to the server. Individual resources are not linkable. You could argue that MQTT used as a WebSocket sub-protocol is the web because individual things can still be linkable.

The reason this is important is because if all things are linkable using URLs, the Thing Description only need provide links to web thing resources using a `href` and an optional `mediaType` and `rel`. It doesn't have to try to declaratively explain to the client how protocols work and how to read and write properties, request actions and subscribe to events using those protocols. Those things can be described in separate concrete protocol binding specifications if necessary (e.g. a webthing WebSocket sub-protocol or a concrete HTTP or CoAP binding).

This approach allows for future web protocols to be invented which are better suited to constrained devices and IoT use cases (like CoAP), but only if they are linkable using URLs.

Note that this doesn't necessarily rule out using the proposed "form" syntax in the Thing Description (that's a [separate discussion](https://github.com/w3c/wot-thing-description/issues/88)), but it does drastically simplify the requirements for protocol bindings.

Should we declare non-web protocols as out of scope for the Thing Description format?

**Comment by mkovatsc** [comment]
Protocol bindings require an existing URI scheme for the protocol, as the mechanism is to plug URIs into the `href` field. This has always been the case. When we talk, for instance, about MQTT, we have also been considering registering an `mqtt` scheme for topics. Other protocols are considered as extensibility checks; protocols that are "fit for WoT" can be included by defining a URI scheme with a specification of the URI structure in the future.

Based on this restriction, the TD works just as any other Web system that uses URIs.

**Comment by mkovatsc** [comment]
Consensus is that only protocols with an URI scheme can be used in TD. Further restrictions are the use of media types to identify payload formats and a fixed set of methods. Other considerations about declarative protocol bindings are discussed here:

https://github.com/w3c/wot-thing-description/issues/237
