### ISSUE TITLE
Consumer should/must ignore unknown event types 

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#1134]
See https://github.com/w3c/wot-discovery/pull/170 - we wanted to say something about this for directories, but realized it was a more general issue.  Note this would be a "behavioural" assertion, and addresses the "server strict, client forgiving" principle.

**Comment by egekorkan** [comment]
If this happens then there is something wrongly described in a TD. If I did not subscribe to an event, why do I get it? 

However, if we add an operation like `subscribeallevents`, this becomes maybe an issue but even then a _maybe_.

**Comment by egekorkan** [comment]
This can be closed since the problem mentioned is unrealistic. Please reopen otherwise.
