### ISSUE TITLE
Need context URL for directories

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#1135]
See https://github.com/w3c/wot-discovery/issues/148
- What should it be?  Under td, e.g. https://www.w3.org/ns/td/discovery
- Under its own namespace, e.g. https://www.w3.org/ns/wot-discovery

Discuss.  We need to close on this so we can start the request process...

**Comment by sebastiankb** [comment]
I'm not sure if this issue is still relevant. Based on the TPAC meeting we will have most likely a new namespace for TD 1.1 such as https://www.w3.org/2022/wot/td/v1

**Comment by sebastiankb** [comment]
also see #1276

**Comment by egekorkan** [comment]
Directory context URL is `https://w3c.github.io/wot-discovery/context/discovery-context.jsonld` as defined by the Discovery Spec. Closing.
