### ISSUE TITLE
Comments - Call for Review of WoT Thing Description 1.1 specification  and resolution to publish update

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#1137]
### General 
* There are still broken links/references reported by ReSpec

### 5.3.1.1 Thing
https://w3c.github.io/wot-thing-description/#thing

1. In the REC document we used to have `MultiLanguage` for `titles` and `description`. Now it is `Map of string`

2. Contains twice "https://www.w3.org/2019/wot/td/v1" in the text after the table. 
Should this be changed to "http://www.w3.org/ns/td" for the draft version?

### 5.3.1.2 InteractionAffordance
https://w3c.github.io/wot-thing-description/#interactionaffordance

In the REC document we used to have `MultiLanguage` for `titles` and `description`. Now it is `Map of string`

### 5.3.2.1 DataSchema
https://w3c.github.io/wot-thing-description/#dataschema

In the REC document we used to have `MultiLanguage` for `titles` and `description`. Now it is `Map of string`

### 5.3.3.1 SecurityScheme 
https://w3c.github.io/wot-thing-description/#securityscheme

In the REC document we used to have `MultiLanguage` for `description`. Now it is `Map of string`

### Security Schema Assignment Issues
* https://www.w3.org/TR/wot-thing-description/#basicsecurityscheme , `name` and `in` are optional now. `in` used to be "with default"
* https://w3c.github.io/wot-thing-description/#digestsecurityscheme, all assignments optional. `qop` and `in` used to be "with default"
* ... there are more issues in other security schemes ...

### D.1 Changes from Recommendation 9 April 2020
https://w3c.github.io/wot-thing-description/#example-26

There is a reference to "Example 26" which does *not* exist
There is a reference to "Example 23" which does *not* exist

General comment. Does it make sense to order the changes according to the sections. Currently it is an unordered list I believe ?

### 6.3.9 forms
https://w3c.github.io/wot-thing-description/#form-serialization-json

Example 29 <https://w3c.github.io/wot-thing-description/#example-29> has
* "eg": "http://www.example.org/iot#"  .... not needed anywhere, shall we remove it?
* break "lat" and "long" values for better readability ? 

### 6.6 Canonicalization

https://w3c.github.io/wot-thing-description/#canonicalization-serialization-json

Step 4
In the Canonical TD, all required elements MUST be given explicitly, even if they have defaults and are assigned their default value. For example, the default value of observable is false. If an input TD omits observable where it is allowed, it must still explictly appear in the canonical form with the value of false. 

I don't think observable is the right example here given it is optional (and *not* required).
OR on the contrary, it is not clear (at least to me) what "all required elements" means?

### 10.1 Basic Concept
https://w3c.github.io/wot-thing-description/#thing-model

there is a a list that starts like
The Thing Model enables: 
* onboard and manage of 
* ..

I think the list items should all start with the same verb form:
* onboarding and managing ...
* simulating ...
* developing ...
* combining  ...
* implementing ...

### Examples

I proposed https://github.com/w3c/wot-thing-description/pull/1136 to fix some minor bugs/glitches in the examples

**Comment by sebastiankb** [comment]
>In the REC document we used to have MultiLanguage for titles and description. Now it is Map of string

I will provide a PR to fix this

**Comment by danielpeintner** [comment]
Note: There are more issues that should be fixed like the ones w.r.t. security
see "Security Schema Assignment Issues" above 
@mmccool I don't think those changes were done on purpose...

**Comment by sebastiankb** [comment]
no yet, I will work on this

**Comment by sebastiankb** [comment]
PR is available regarding the topics above. Please review.
