### ISSUE TITLE
Making the uriVariables recommendation paragraph an editor's note

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1138]
The paragraph below example 29 would be better as an editor's note (like the format keyword has). Currently, it is not very visible. 

![image](https://user-images.githubusercontent.com/20195407/117994402-cf2c5500-b340-11eb-81c3-b77b226fae8c.png)

**Comment by egekorkan** [comment]
There is also a typo at `possbile`.

**Comment by egekorkan** [comment]
This is in a normative section, thus making it an editor's note at this stage needs consideration. Since this is a recommendation for new systems and not for existing implementations, it does not imply changes to the existing implementations. Thus, it can be made informative by putting it into an editor's note.

**Comment by danielpeintner** [comment]
> There is also a typo at `possbile`.

typo fixed by https://github.com/w3c/wot-thing-description/pull/1133

**Comment by egekorkan** [comment]
Given that editor's notes are meant to be removed in the recommendation stage, we should not put this information as an editor's note.
