### ISSUE TITLE
Relax constraints on @context and @type in JSON-LD serialization

### ISSUE THREAD

**Issue by vcharpenay** [w3c/wot-thing-description#114]
According to [Sect. 6](https://w3c.github.io/wot-thing-description/#json-ld-serialization), `@context` and `@type` must _always_ be arrays. When using JSON-LD libraries, users are usually not given control over how context and type fields are being serialized. If a context consists of a single string, it will be serialized simply as a string and not as an array with a single element. I have this issue in the Thing Directory, in particular.

Would it be possible to relax this constraint and simply follow the JSON-LD specification with that respect?

**Comment by sebastiankb** [comment]
There is already a similar discussion here #103

**Comment by sebastiankb** [comment]
The new TD version follows JSON-LD 1.1 and its @contex handling.
