### ISSUE TITLE
New context url nonfunctional in json-ld operations

### ISSUE THREAD

**Issue by RoboPhred** [w3c/wot-thing-description#1159]
Rejoining this project after a long break, I see the documentation references `http://www.w3.org/ns/td` as the new context.

However, this context is nonfunctional when passed to a json-ld transformation engine, such as the playground:

New context: Observe no compaction takes place:
[Compaction with new context](https://json-ld.org/playground/#startTab=tab-compacted&json-ld=%7B%22%40context%22%3A%22http%3A%2F%2Fwww.w3.org%2Fns%2Ftd%22%2C%22id%22%3A%22zwave%3A%3A44-0%22%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Fdescription%22%3A%22Multi-Color%20Bulb%22%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Ftitle%22%3A%22LZW42%22%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Ftd%23hasActionAffordance%22%3A%7B%22%40index%22%3A%22zwave%3A%3Ainterview-node%22%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Ftitle%22%3A%22Interview%20Node%22%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Ftd%23hasInputSchema%22%3A%7B%7D%7D%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Ftd%23hasPropertyAffordance%22%3A%5B%7B%22%40index%22%3A%22model%3A%3Aname%22%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Fdescription%22%3A%22The%20name%20of%20this%20thing.%22%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Ftitle%22%3A%22Name%22%2C%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%22%3A%7B%22id%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23StringSchema%22%7D%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23maxLength%22%3A255%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23minLength%22%3A0%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23readOnly%22%3Afalse%7D%2C%7B%22%40index%22%3A%22model%3A%3Alocation%22%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Fdescription%22%3A%22The%20location%20of%20this%20thing.%22%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Ftitle%22%3A%22Location%22%2C%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%22%3A%7B%22id%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23StringSchema%22%7D%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23maxLength%22%3A255%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23minLength%22%3A0%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23readOnly%22%3Afalse%7D%2C%7B%22%40index%22%3A%22zwave%3A%3Amultilevel-switch%22%2C%22%40type%22%3A%22LevelProperty%22%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Ftitle%22%3A%22Level%22%2C%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%22%3A%7B%22id%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23NumberSchema%22%7D%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23maximum%22%3A99%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23minimum%22%3A0%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23readOnly%22%3Afalse%7D%2C%7B%22%40index%22%3A%22zwave%3A%3Anode-status%22%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Ftitle%22%3A%22Node%20Status%22%2C%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%22%3A%7B%22id%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23StringSchema%22%7D%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23readOnly%22%3Atrue%7D%2C%7B%22%40index%22%3A%22zwave%3A%3Ainterview-status%22%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Ftitle%22%3A%22Interview%20Status%22%2C%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%22%3A%7B%22id%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23StringSchema%22%7D%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23readOnly%22%3Atrue%7D%5D%2C%22base%22%3A%22http%3A%2F%2Flocalhost%3A8080%2Fthings%2Fzwave%3A%3A44-0%22%7D&context=%7B%22%40context%22%3A%22http%3A%2F%2Fwww.w3.org%2Fns%2Ftd%22%7D)

Old context (https://www.w3.org/2019/wot/td/v1#).  Observe properly compacted values
[Compaction with old context](https://json-ld.org/playground/#startTab=tab-compacted&json-ld=%7B%22%40context%22%3A%22http%3A%2F%2Fwww.w3.org%2Fns%2Ftd%22%2C%22id%22%3A%22zwave%3A%3A44-0%22%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Fdescription%22%3A%22Multi-Color%20Bulb%22%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Ftitle%22%3A%22LZW42%22%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Ftd%23hasActionAffordance%22%3A%7B%22%40index%22%3A%22zwave%3A%3Ainterview-node%22%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Ftitle%22%3A%22Interview%20Node%22%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Ftd%23hasInputSchema%22%3A%7B%7D%7D%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Ftd%23hasPropertyAffordance%22%3A%5B%7B%22%40index%22%3A%22model%3A%3Aname%22%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Fdescription%22%3A%22The%20name%20of%20this%20thing.%22%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Ftitle%22%3A%22Name%22%2C%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%22%3A%7B%22id%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23StringSchema%22%7D%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23maxLength%22%3A255%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23minLength%22%3A0%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23readOnly%22%3Afalse%7D%2C%7B%22%40index%22%3A%22model%3A%3Alocation%22%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Fdescription%22%3A%22The%20location%20of%20this%20thing.%22%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Ftitle%22%3A%22Location%22%2C%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%22%3A%7B%22id%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23StringSchema%22%7D%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23maxLength%22%3A255%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23minLength%22%3A0%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23readOnly%22%3Afalse%7D%2C%7B%22%40index%22%3A%22zwave%3A%3Amultilevel-switch%22%2C%22%40type%22%3A%22LevelProperty%22%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Ftitle%22%3A%22Level%22%2C%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%22%3A%7B%22id%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23NumberSchema%22%7D%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23maximum%22%3A99%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23minimum%22%3A0%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23readOnly%22%3Afalse%7D%2C%7B%22%40index%22%3A%22zwave%3A%3Anode-status%22%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Ftitle%22%3A%22Node%20Status%22%2C%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%22%3A%7B%22id%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23StringSchema%22%7D%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23readOnly%22%3Atrue%7D%2C%7B%22%40index%22%3A%22zwave%3A%3Ainterview-status%22%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Ftitle%22%3A%22Interview%20Status%22%2C%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%22%3A%7B%22id%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23StringSchema%22%7D%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23readOnly%22%3Atrue%7D%5D%2C%22base%22%3A%22http%3A%2F%2Flocalhost%3A8080%2Fthings%2Fzwave%3A%3A44-0%22%7D&context=%7B%22%40context%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Ftd%2Fv1%23%22%7D)

**Comment by egekorkan** [comment]
This URL is only temporary since once the spec is published, there will be a proper one like before. The old context is still usable and unless you are doing a cutting edge implementation, the editor's draft or working drafts should not be used

**Comment by egekorkan** [comment]
Given that we now have a new context at `https://www.w3.org/2022/wot/td/v1.1`, we can close this issue. @RoboPhred let us know in case you disagree.
