### ISSUE TITLE
[Schema] accept other OAuth2 flows

### ISSUE THREAD

**Issue by relu91** [w3c/wot-thing-description#1162]
The current JSON schema allows only for `code` to be used as an OAuth2 flow. However, in the spec, we refer also to `client` and `device`. I'd just add the two flows but looking at the spec it does not seem that we fixed the set of values allowed. Therefore it might make sense to just leave the field open-ended. Doing so will allow the usage of weird flows that we are not aware of. What do people think? @mmccool @Citrullin @egekorkan

**Comment by relu91** [comment]
> Doing so will allow the usage of weird flows that we are not aware of

Plus the ones that we were not confident to add in the spec cause considered obsolete.

**Comment by danielpeintner** [comment]
I wonder whether it is useful to be that strict. Does it make sense to open it to future extensions ?
(e.g., providing a list but essentially allowing any string)

```
  "flow": {
    "oneOf": [
      {
        "type": "string"
      },
      {
        "type": "string",
        "enum": [
          "code"
        ]
      }
    ]
  }
```

**Comment by relu91** [comment]
In the spec we explicitly allow other flows using an extension vocabulary:
> If an OAuth 2.0 flow other than code, client or device needs to be specified an extension vocabulary MUST be used. This includes the password and implicit flows, which are no longer considered best practice [WOT-SECURITY-GUIDELINES]. 

If we are so strict we can't pass validation with other terms, right? Even if I define a schema specifically for `password` or `implicit` flow

**Comment by egekorkan** [comment]
I think I misunderstood. The flow keyword can be anything from what I understand, like `subprotocol`. Thus we can make it completely free by removing enum?

**Comment by danielpeintner** [comment]
> Thus we can make it completely free by removing enum?

The only reason to keep `string` and `enum` for me is to have a sample list people can look at which increases interoperability and may also help tools to provide proper suggestions. With regards to validation it does not help...

**Comment by relu91** [comment]
Reopening it seems that the lastest wot-types does not have the correct JSON schema (and types)

**Comment by relu91** [comment]
Sorry, this is not an issue for the wot-td repo but for node-wot. Reclosing.
