### ISSUE TITLE
Minor spelling and grammar errors

### ISSUE THREAD

**Issue by ajs124** [w3c/wot-thing-description#1165]
I was reading chapter 10 and noticed a typo in §10.4: "placholder" should be "placeholder".

Also in §10.1, 
```
The Thing Model enables:
- onboard and manage […]
- simulate of […]
- develop common […]
- combining multiple […]
- implementation support […]
```
I'm not a linguist and English isn't my first language, so I lack the vocabulary to describe what exactly is wrong with this, but it would be news to me if this is correct. I really don't think something can "enable onboard and manage" or "enable develop".

Please tell me if this is the wrong way to report this kind of thing, if you don't care, etc.

**Comment by sebastiankb** [comment]
Thanks for pointing that out and yes, that is the right place. I will take care in the next update.
