### ISSUE TITLE
Unclear assertion on security

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1172]
The following assertion is not understandable, at least I couldn't understand :) 

> When an element of a data schema indicated by a JSON pointer indicated in a body locator does not already exist in the indicated schema, it MUST be possible to insert the indicated element at the location indicated by the pointer.

**Comment by sebastiankb** [comment]
from today's TD call: @egekorkan will provide a PR with alternative sentence

**Comment by egekorkan** [comment]
- A pointer to an object where the key does not exist in the object -> the key and its value would inserted by the runtime at the specified location
- A pointer to an array where the index does not exist in the array -> the item inserted by the runtime at the end of the array

**Comment by egekorkan** [comment]
Fixed via #1176
