### ISSUE TITLE
Unclear assertion on TMs

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1173]
I do not understand the following assertion:

>  If it is intended to override an existing JSON name-value pair definition from tm:ref, the same JSON name MUST be used at the same level of the tm:ref declearation that provides a new value. 

The example provided overwrites a property it references, which is allowed. Am I not allowed to reference a property and overwrite a sub element of its dataschema? Or is it about referencing a property inside an action? In any case, this limitation is not very clear.

**Comment by sebastiankb** [comment]
Thanks for the hint. In the next update I will be more clear. In addition I will also have an illustration to make the overwriting more clear.

**Comment by sebastiankb** [comment]
PR was merged today
