### ISSUE TITLE
Missing assertion in ComboSecurityScheme

### ISSUE THREAD

**Issue by FadySalama** [w3c/wot-thing-description#1179]
`npm run assertions`  does not extract an assertion that corresponds to the rule `Exactly one of either oneOf or allOf MUST be included.` under the ComboSecurityScheme ([link](https://w3c.github.io/wot-thing-description/#combosecurityscheme)). In the `index.html`, this rule is encapsulated in a `<scan/>` element with no respective `id`

**Comment by egekorkan** [comment]
The problem is that scan is used instead of span at https://github.com/w3c/wot-thing-description/blob/4789e1da3b8a1880b262ee8b9c11c38f9d2c3155/ontology/wotsec.ttl#L115 in addition to not having an id.

**Comment by Fady222** [comment]
The actual definition that gets rendered is at
    https://github.com/w3c/wot-thing-description/blob/8dda72f9cf3c61ed25688eb3c2006b5ca23b4fec/validation/td-validation.ttl#L1196

**Comment by egekorkan** [comment]
This is fixed via #1184
