### ISSUE TITLE
Field name `schema`  in the `Event` pattern

### ISSUE THREAD

**Issue by danicic** [w3c/wot-thing-description#118]
Field name `schema`, used in the `Event` pattern, suggests that `Event` might have both input and output data (at least this applies for the 'Property' pattern). Since one expects 'Event' only to have output data, why should not we use 'outputSchema' instead of 'schema' as this reduces ambiguity.

**Comment by mkovatsc** [comment]
I expect Events to emit payloads that are not resource representations (i.e., not representations of exposed and accessible state, but self-contained event instances). Hence, I see them also as `outputSchema` (which defines the schema of action results in resource/REST speak).

I would recommend to continue working on the proper terms.

We also need to look into use cases where Event subscription requires input, and hence `inputSchema` (or however we will call it).

**Comment by sebastiankb** [comment]
@danicic please can you provide an example where an input and output is needed? This would help to understand the motivation.

**Comment by danicic** [comment]
@sebastiankb actually I expect `Event` to have only output. Therefore I would expect to find in the `Event` specification just `outputSchema` instead of `schema`, as schema suggests `Event` has both input and output (which is not the case). 
As @mkovatsc mantioned, Event subscription may have an input, but this is not the input of Event.

**Comment by sebastiankb** [comment]
The new TD version do not use terms such as _schema_. Instead, JSON Schema is directly embedded in the Property and Event Interaction.
