### ISSUE TITLE
Default value for observable

### ISSUE THREAD

**Issue by fatadel** [w3c/wot-thing-description#1180]
TD canonicalization [instructions](https://w3c.github.io/wot-thing-description/#canonicalization-serialization-json) mention that there is a default value of `false` for the `observable` property.
However, in the default value definitions [section](https://w3c.github.io/wot-thing-description/#sec-default-values), there is nothing about `observable`.
So, does it have a default value or not?

**Comment by egekorkan** [comment]
Good catch, we should probably add a default value of false in the default values section

**Comment by egekorkan** [comment]
Call of 21.07: @egekorkan will create a PR to add this to the defaults table
