### ISSUE TITLE
Problems translating TDs to RDF and their validation

### ISSUE THREAD

**Issue by AndreaCimminoArriaga** [w3c/wot-thing-description#1185]
During the implementation of the WoT directory I found the following problem. Taking the first TD sample from the spec:

````

{
    "@context": "https://www.w3.org/2019/wot/td/v1",
    "id": "urn:dev:ops:32473-WoTLamp-1234",
    "title": "MyLampThing",
    "securityDefinitions": {
        "basic_sc": {"scheme": "basic", "in":"header"}
    },
    "security": ["basic_sc"],
    "properties": {
        "status" : {
            "type": "string",
            "forms": [{"href": "https://mylamp.example.com/status"}]
        }
    },
    "actions": {
        "toggle" : {
            "forms": [{"href": "https://mylamp.example.com/toggle"}]
        }
    },
    "events":{
        "overheating":{
            "data": {"type": "string"},
            "forms": [{
                "href": "https://mylamp.example.com/oh",
                "subprotocol": "longpoll"
            }]
        }
    }
}
````

It can be translated into RDF using the `https://json-ld.org/playground/`, which outputs the following triples:

````
<urn:dev:ops:32473-WoTLamp-1234> <http://purl.org/dc/terms/title> "MyLampThing" .
<urn:dev:ops:32473-WoTLamp-1234> <https://www.w3.org/2019/wot/td#hasActionAffordance> _:b0 .
<urn:dev:ops:32473-WoTLamp-1234> <https://www.w3.org/2019/wot/td#hasEventAffordance> _:b2 .
<urn:dev:ops:32473-WoTLamp-1234> <https://www.w3.org/2019/wot/td#hasPropertyAffordance> _:b5 .
<urn:dev:ops:32473-WoTLamp-1234> <https://www.w3.org/2019/wot/td#hasSecurityConfiguration> <https://json-ld.org/playground/basic_sc> .
<urn:dev:ops:32473-WoTLamp-1234> <https://www.w3.org/2019/wot/td#securityDefinitions> _:b7 .
_:b0 <https://www.w3.org/2019/wot/td#hasForm> _:b1 .
_:b0 <https://www.w3.org/2019/wot/td#name> "toggle" .
_:b1 <https://www.w3.org/2019/wot/hypermedia#hasTarget> <https://mylamp.example.com/toggle> .
_:b2 <https://www.w3.org/2019/wot/td#hasForm> _:b3 .
_:b2 <https://www.w3.org/2019/wot/td#hasNotificationSchema> _:b4 .
_:b2 <https://www.w3.org/2019/wot/td#name> "overheating" .
_:b3 <https://www.w3.org/2019/wot/hypermedia#forSubProtocol> "longpoll" .
_:b3 <https://www.w3.org/2019/wot/hypermedia#hasTarget> <https://mylamp.example.com/oh> .
_:b4 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://www.w3.org/2019/wot/json-schema#StringSchema> .
_:b5 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://www.w3.org/2019/wot/json-schema#StringSchema> .
_:b5 <https://www.w3.org/2019/wot/td#hasForm> _:b6 .
_:b5 <https://www.w3.org/2019/wot/td#name> "status" .
_:b6 <https://www.w3.org/2019/wot/hypermedia#hasTarget> <https://mylamp.example.com/status> .
_:b7 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://www.w3.org/2019/wot/security#BasicSecurityScheme> .
_:b7 <https://www.w3.org/2019/wot/security#in> "header" .
````

If we take this triples and we apply the [SHACL shape defined in the group](https://github.com/w3c/wot-thing-description/blob/main/validation/td-validation.ttl) this is the validation result we obtained:

````
[ a            sh:ValidationReport ;
  sh:conforms  true
] .
````

It may seems that this is correct, but actually it isn't. If we submit a different TD that is not correct this shape will always return true since the shape is tied to the rdf:type td:Thing. In other words, if the subject of the thing lacks of the implicit triple `<subject> rdf:type td:Thing` it will always validate as true since the restrictions of the shape are triggered based on this triple. This can be a dangerous issue especially for the round tripping, since the type td:Thing is never included in the triples (maybe this could be addressed in the @context so it is always automatically injected).

After adding the implicit triple, when the sample TD is validated error is reported:

````
[ a            sh:ValidationReport ;
  sh:conforms  false ;
  sh:result    [ a                             sh:ValidationResult ;
                 sh:focusNode                  <urn:dev:ops:32473-WoTLamp-1234> ;
                 sh:resultMessage              "DatatypeConstraint[xsd:string] : Not a literal" ;
                 sh:resultPath                 td:hasSecurityConfiguration ;
                 sh:resultSeverity             sh:Violation ;
                 sh:sourceConstraintComponent  sh:DatatypeConstraintComponent ;
                 sh:sourceShape                []  ;
                 sh:value                      <urn:dev:ops:32473-WoTLamp-1234/basic_sc>
               ]
] .
````
In the shape the range of the property td:hasSecurityConfiguration is expected to be a string (literal) but instead in the context is translated as an URI. The solution is either changing the shape, or modifying the context to translate the value of the json as a string.

**Comment by AndreaCimminoArriaga** [comment]
I have identified also a new problem. When I validate a TD like this one:

````
{
    "@context": "https://www.w3.org/2019/wot/td/v1",
    "id": "urn:dev:ops:32473-WoTLamp-1234",
    "title": "MyLampThing",
    "securityDefinitions": {
        "basic_sc": {"scheme": "basic", "in":"header"}
    },
    "security": ["basic_sc"]
}
````

If I use the JSON schema it is correct, but if I use the SHACL shape I get a validation error because the Thing has to have at least one Property, Action, or Event. Which one is the correct? the shape of the schema? Many thanks beforehand

**Comment by danielpeintner** [comment]
According to [Figure 1](https://w3c.github.io/wot-thing-description/#overview) in the TD spec there is no need to have any interaction.

all interactions are marked as `0 .. *`

**Comment by sebastiankb** [comment]
From my view it should be ok to simple extend the SHACL to validate RDF instances correctly when  no `<subject> rdf:type td:Thing` is present.

@AndreaCimminoArriaga can you provide the definition for this?

>If I use the JSON schema it is correct, but if I use the SHACL shape I get a validation error because the Thing has to have at least one Property, Action, or Event. Which one is the correct? the shape of the schema? Many thanks beforehand

Oh, this have to be changed since properties, actions, and events are optional and the [TD example](https://github.com/w3c/wot-thing-description/issues/1185#issuecomment-874694248) is correct.

**Comment by AndreaCimminoArriaga** [comment]
@sebastiankb sorry I'm not sure what I should provide, could you give me more details about it?

**Comment by mahdanoura** [comment]
> After adding the implicit triple, when the sample TD is validated error is reported:
> 
> ```
> [ a            sh:ValidationReport ;
>   sh:conforms  false ;
>   sh:result    [ a                             sh:ValidationResult ;
>                  sh:focusNode                  <urn:dev:ops:32473-WoTLamp-1234> ;
>                  sh:resultMessage              "DatatypeConstraint[xsd:string] : Not a literal" ;
>                  sh:resultPath                 td:hasSecurityConfiguration ;
>                  sh:resultSeverity             sh:Violation ;
>                  sh:sourceConstraintComponent  sh:DatatypeConstraintComponent ;
>                  sh:sourceShape                []  ;
>                  sh:value                      <urn:dev:ops:32473-WoTLamp-1234/basic_sc>
>                ]
> ] .
> ```
> 
> In the shape the range of the property td:hasSecurityConfiguration is expected to be a string (literal) but instead in the context is translated as an URI. The solution is either changing the shape, or modifying the context to translate the value of the json as a string.

@AndreaCimminoArriaga This has already been fixed with the previous updates on the @context file and SHACL shapes. 

@AndreaCimminoArriaga Regarding the issue with injecting the rdf:type thing, we will discuss it in [issue1345](https://github.com/w3c/wot-thing-description/issues/1345).

**Comment by mahdanoura** [comment]
> I have identified also a new problem. When I validate a TD like this one:
> 
> ```
> {
>     "@context": "https://www.w3.org/2019/wot/td/v1",
>     "id": "urn:dev:ops:32473-WoTLamp-1234",
>     "title": "MyLampThing",
>     "securityDefinitions": {
>         "basic_sc": {"scheme": "basic", "in":"header"}
>     },
>     "security": ["basic_sc"]
> }
> ```
> 
> If I use the JSON schema it is correct, but if I use the SHACL shape I get a validation error because the Thing has to have at least one Property, Action, or Event. Which one is the correct? the shape of the schema? Many thanks beforehand

@AndreaCimminoArriaga This issue is also not existent anymore, and is currently validated correctly with the current SHACL shapes.
