### ISSUE TITLE
Issues with Thing Model schema

### ISSUE THREAD

**Issue by JKRhb** [w3c/wot-thing-description#1186]
At the moment there are no `"required"` fields in the JSON Schema for Thing Models. However, the current draft states that

> Thing Model definitions MUST use the keyword @type at top level and a value of type string or array that equals or respectively contains tm:ThingModel

which is not reflected by this approach (a TM without a top-level `@type` field is valid at the moment).

I am also wondering if it could make sense to also declare `@context` and maybe `title` mandatory.

**Comment by egekorkan** [comment]
`@type` not being mandatory is a bug that I will fix. Regarding making the other fields mandatory, I remember discussing that everything required should be removed. However, the text reads as if `@context` should be mandatory.

**Comment by JKRhb** [comment]
I just noticed another TM related bug in the schema: Specifying a `@type` for an affordance somehow does not work at the moment except when the value is `tm:ThingModel". I created a minimal example illustrating the issue here: https://www.jsonschemavalidator.net/s/HUCDN9HO

**Comment by JKRhb** [comment]
I discovered another issue with the TM schema: At the moment it is not possible to use `rel` in a link object. See the following minimal example: https://www.jsonschemavalidator.net/s/yFlOOPVN

**Comment by JKRhb** [comment]
`multipleOf` seems not to be working as well. The following definition is not valid at the moment:

```json
{
    "@context": ["http://www.w3.org/ns/td"],
    "@type": "tm:ThingModel",
    "properties": {
        "foo": {
            "title": "Invalid",
            "multipleOf": 2
        },
        "bar": {
            "title": "Invalid",
            "multipleOf": 2.0
        },
        "baz": {
            "title": "Valid, because not an integer",
            "multipleOf": 2.2
        }
    }
}
```

Also see: https://www.jsonschemavalidator.net/s/lX5pEnaQ
