### ISSUE TITLE
datetime format in TD canonicalization

### ISSUE THREAD

**Issue by fatadel** [w3c/wot-thing-description#1187]
In the [TD canonicalization section](https://w3c.github.io/wot-thing-description/#canonicalization-serialization-json), it's mentioned that

> 1. In the Canonical TD, values that are of type `dateTime` MUST use the literal "Z" representing the UTC time zone instead of an offset.

However, this looks like a more validation step rather than canonicalization. Especially, taking into account that this format is already described as the only correct format for `datetime` in the [Mapping to JSON Types section](https://w3c.github.io/wot-thing-description/#td-basic-types-mapping).

The same holds for other constraints prescribed for `datetime` format in the TD canonicalization section.

**Comment by danielpeintner** [comment]
Not sure If I can agree. The [Mapping to JSON Types section](https://w3c.github.io/wot-thing-description/#td-basic-types-mapping) allows the following `dateTime`s as given in the example:
* `2019-05-24T13:12:45Z`
* `2015-07-11T09:32:26+08:00`

According to TD canonicalization the latter is not allowed given that it does *not* use `Z`. It must be transformed to use UTC time zone instead.
Do I misunderstand the issue?

**Comment by sebastiankb** [comment]
I think, the situation is that `dateTime` is not really existing in JSON Schema and is usually handled as string. Be aware that the format term in JSON schema is not supported anymore.

**Comment by danielpeintner** [comment]
Note: the current draft still mentions `dateTime`s, see https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.7.3.1.
Having said that, there were [discussions](https://github.com/w3c/wot-thing-description/issues/956#issuecomment-676536658) that `format`  most likely will be replaced with extension vocabularies.

This to me relates to the issue but in general I would say "TD canonicalization" (as it is done at the moment) is needed...

**Comment by mmccool** [comment]
this issue is still relevant (and IMO the text is correct as is... we don't care how the format is enforced, just that it is so the serialization is unique) but canonicalization in general is being deferred so I would propose closing this issue after labelling it so we can find it again later if necessary.

**Comment by egekorkan** [comment]
Closing this as part of canonicalization issues. They will be reconsidered in 2.0 by searching for the label
