### ISSUE TITLE
Why is contentType optional on AdditionalResponse?

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1189]
At https://w3c.github.io/wot-thing-description/#additionalexpectedresponse contentType is defined to be optional. Why is it optional here? It should be especially required since the additional response content type usually differs from the normal one. 

I think this is a bug that needs to be fixed.

**Comment by danielpeintner** [comment]
What strucks me in your message is the statement

> _usually_ differs

This would mean that optional is fine, isn't it?
Having said that, I am not finding good use-cases for it ..

**Comment by egekorkan** [comment]
Well if it usually differs, then we **cannot** write something like:

> when contentType is not present it can be assumed to be the same as the request's contentType

Thus, we have to encourage (by making it mandatory) that it is always provided.

**Comment by sebastiankb** [comment]
In [expectedResponses](https://w3c.github.io/wot-thing-description/#expectedresponse) contentType is mandatory. AdditionalResponse may be used to provide different response message (e.g., error message) which still can have the same contenType as presented in the forms level. So optional would make sense here.

I think, an explanation is needed that the same contentType is assumed of the forms definition if contentType is not present in AdditionalResponse.

**Comment by egekorkan** [comment]
In this case, it should be added to the default values section

**Comment by egekorkan** [comment]
Call of 21.07: @egekorkan will add a default value for contentType inside an AdditionalExpectedResponse class

**Comment by egekorkan** [comment]
The PR #1198 is merged, closing
