### ISSUE TITLE
Small incoherence in `forms` Thing Description core vocabulary

### ISSUE THREAD

**Issue by relu91** [w3c/wot-thing-description#1199]
After #1191 landed we can now express "aggregate" operations also for events. However, in `forms` field description we say:
>  In this version of TD, all operations that can be described at the Thing level are concerning how to interact with the **Thing's Properties** collectively at once.

I think is sufficient to remove that sentence.

See [here](https://www.w3.org/TR/wot-thing-description/#thing).

**Comment by egekorkan** [comment]
I think changing it to something like this would be better:

Forms in the Thing level are used for describing endpoints for a group of interaction affordances.

**Comment by sebastiankb** [comment]
from today's TD call: group agrees to replace the sentence with Ege's proposal

**Comment by sebastiankb** [comment]
issue solved
