### ISSUE TITLE
Handling interactions that have binary payloads

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#120]
I have a "webcam" service that I want to describe with a [TD](https://github.com/w3c/wot/blob/master/plugfest/2018-prague/TDs/IntelTDs/SimpleWebCamera.json).
One of the API interactions is a Property called "frame" that returns an JPEG image, described with mediaType: "image/jpeg".   The question is: what should the "schema" be for this interaction?   No schema?  Should we add a type: "binary"?

**Comment by mmccool** [comment]
After some discussion with Victor and Michael K. about this and we agreed that binary data such as this (not to be processed via the WoT scripting API) should be handled as a "link".  However, we need a concrete proposal/example for how to do this in a TD...

**Comment by mmccool** [comment]
I have updated the IntelTD for the camera to reflect the above discussion.

**Comment by mmccool** [comment]
Additional issues:
- There are actions that don't return any data.   [The "webspeak" Thing](https://github.com/w3c/wot/blob/master/plugfest/2018-prague/TDs/IntelTDs/WebSpeak.json) I just created does this for the "say" action.   In this case... what should be the output schema be?  If I omit it, then it's ambiguous whether the output is empty (no return data at all) or just data that the scripting API/node-wot should not parse (eg an image).   So... probably we should add additional schema types, like "empty" and "binary", to make this explicit.

**Comment by sebastiankb** [comment]
This is a very good question and it makes sense to omit the _schema_ term. However, I do not understand the motivation of the current proposal/work around by the usage of the _link_ vocabulary? So far, the _link_ is only allowed on the top level and not within the interaction level. From my view _form_ can be also used since it serves the same content as _link_.

**Comment by sebastiankb** [comment]
The new TD version allows to obmit the schema type.
