### ISSUE TITLE
Top-level `data` field for Thing Models?

### ISSUE THREAD

**Issue by JKRhb** [w3c/wot-thing-description#1206]
I am currently dealing with the conversion between SDF and TDs/TMs. In SDF you can define an `sdfData` object field is supposed to store reusable data that can be referenced from affordances. I wanted to suggest adding a similar field to TMs as well that could look like the following:

```json
{
    "@context": "http://www.w3.org/ns/td",
    "@type": "tm:ThingModel",
    "data": {
        "reusableData": {
            "type": "string"     
    },
    "actions": {
        "bestActionEver": {
            "input": {
                "tm:ref": "#/data/reusableData"
            },
            "output": {
                "tm:ref": "#/data/reusableData"
            }
        }
    }
}
```

Adding such a field to Thing Models would not only align SDF and WoT TMs more closely but could also be useful in general to avoid redundancy. As there is no reference mechanism in TDs (yet) I guess all `tm:ref`s should be resolved and the `data` field removed before instantiating a TD from a TM.

**Comment by egekorkan** [comment]
This is almost solved via schemaDefinitions. Stay tuned! :)

**Comment by JKRhb** [comment]
> This is almost solved via schemaDefinitions. Stay tuned! :)

Oh, great! :) Then I'll mark this issue as closed :)
