### ISSUE TITLE
[TM] Use of instance in version should be banned in TMs

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1209]
Currently, the TD spec says:

> Due to the definition of Thing Model the term instance can be omitted within the version container. 

I would say that `instance` MUST be omitted from a TM version container

**Comment by sebastiankb** [comment]
Actually, I was okay with it, but I'm not 100% anymore. You can also express in the TM which instance version should show-up in the TD instance or you define it together with a placeholder:

```js
"version" : {"instance" : {{INSTANCE_VERSION}}, "model" : "1.0.0" }
```

**Comment by egekorkan** [comment]
Good point! I will close the PR
