### ISSUE TITLE
Queston about https://www.w3.org/2019/wot/td#securityDefinitions

### ISSUE THREAD

**Issue by cecemel** [w3c/wot-thing-description#1218]
Hello,

Exciting work!

New to the spec, my apologies if this isn't the right platform for the following question.

I am not entirely sure how I should interpret the definition of  `https://www.w3.org/2019/wot/td#securityDefinitions`. The best I could find is this
[section](https://www.w3.org/TR/wot-thing-description/#security-serialization-json).

It seems that there is a need to define upfront which SecurityScheme is supported and how it is configured. Depending on what is needed from the Thing, different Schemes could be satisfied, described in `https://www.w3.org/2019/wot/td#securityDefinitions`

The way it would serialize -to my understanding-  makes it hard to work within RDF and store it in some stores which don't support blank nodes. (The blank nodes is less of a concern, note)

Take the stripped-down version of [example 1](https://www.w3.org/TR/wot-thing-description/#simple-thing-description-sample),
[converted here](https://json-ld.org/playground/#startTab=tab-table&json-ld=%7B%22%40context%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Ftd%2Fv1%22%2C%22id%22%3A%22urn%3Adev%3Aops%3A32473-WoTLamp-1234%22%2C%22title%22%3A%22MyLampThing%22%2C%22securityDefinitions%22%3A%7B%22basic_sc%22%3A%7B%22scheme%22%3A%22basic%22%2C%22in%22%3A%22header%22%7D%7D%2C%22security%22%3A%5B%22basic_sc%22%5D%7D)

```
{
    "@context": "https://www.w3.org/2019/wot/td/v1",
    "id": "urn:dev:ops:32473-WoTLamp-1234",
    "title": "MyLampThing",
    "securityDefinitions": {
        "basic_sc": {"scheme": "basic", "in":"header"}
    },
    "security": ["basic_sc"]
}
```
The RDF equivalent, I get,
```
<urn:dev:ops:32473-WoTLamp-1234> <http://purl.org/dc/terms/title> "MyLampThing" .
<urn:dev:ops:32473-WoTLamp-1234> <https://www.w3.org/2019/wot/td#hasSecurityConfiguration> <https://json-ld.org/playground/basic_sc> .
<urn:dev:ops:32473-WoTLamp-1234> <https://www.w3.org/2019/wot/td#securityDefinitions> _:b0 .
_:b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://www.w3.org/2019/wot/security#BasicSecurityScheme> .
_:b0 <https://www.w3.org/2019/wot/security#in> "header" .

```
To know what security definitions must be satisfied, I have to step out the RDF equivalent to deduce what `basic_sc` belongs to.

What would be more natural, working in the RDF equivalent, is a different SecurityScheme, making storing and querying easier. RDF-wise, this could be:

```
<https://json-ld.org/playground/basic_sc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://www.w3.org/2019/wot/security#BasicSecurityScheme> .
<https://json-ld.org/playground/basic_sc> <https://www.w3.org/2019/wot/security#in> "header" .
<urn:dev:ops:32473-WoTLamp-1234> <http://purl.org/dc/terms/title> "MyLampThing" .
 <urn:dev:ops:32473-WoTLamp-1234> <https://www.w3.org/2019/wot/td#hasSecurityConfiguration> <https://json-ld.org/playground/basic_sc> .
<urn:dev:ops:32473-WoTLamp-1234> <https://www.w3.org/2019/wot/td#securityDefinitions> <https://json-ld.org/playground/basic_sc> .
```
The JSON-LD would then be

```
{
    "@context": "https://www.w3.org/2019/wot/td/v1",
    "id": "urn:dev:ops:32473-WoTLamp-1234",
    "title": "MyLampThing",
    "securityDefinitions": [
        { "@id": "basic_sc",
          "scheme": "basic",
          "in":"header"
        }
    ],
    "security": ["basic_sc"]
}
```

So, my question(s):
- Is my understanding of `https://www.w3.org/2019/wot/td#hasSecurityConfiguration` correct?
- Why does ``https://www.w3.org/2019/wot/td#hasSecurityConfiguration` expect a map as value?
Thanks

**Comment by egekorkan** [comment]
I cannot answer all the questions here but:

> Why does ``https://www.w3.org/2019/wot/td#hasSecurityConfiguration` expect a map as value?

It is done this way so that the keys of the map can be used as ids (like your `@id`).

**Comment by mmccool** [comment]
My understanding was that we could set up the ontology files so that the keys of the map used for securityDefinitions *would* get turned into values for @id, so it would be equivalent to what was suggested by @cecemel , but with a nicer syntax.  This should be true for similar "named objects", e.g. for named DataSchema definitions.

@vcharpenay can you confirm if this is the case, and if so, can you mark this issue with "Propose Closing"?

**Comment by egekorkan** [comment]
I think that this issue has received the answers. @cecemel let us know if your question is not settled.
