### ISSUE TITLE
Error in JSON Schema example (ontology doc)

### ISSUE THREAD

**Issue by vcharpenay** [w3c/wot-thing-description#1219]
Spotted by @danielpeintner. Example [l. 204-205](https://github.com/w3c/wot-thing-description/blob/09a0fec43ff431ab2117da893d726751c11cfee5/ontology/jsonschema.html#L204-L205) would be more accurate if datatype were `xsd:integer` instead of `xsd:decimal`.

**Comment by danielpeintner** [comment]
Note: I added the fix to the _similar_ PR https://github.com/w3c/wot-thing-description/pull/1212 that exist already

see https://github.com/ioggstream/wot-thing-description/commit/05408cf20036a21e04681c7623469f9d94e8aa3a
