### ISSUE TITLE
JSON Schema issue / request

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#1235]
## Issue
[OAuth2SecurityScheme](https://w3c.github.io/wot-thing-description/#oauth2securityscheme) states `flow` can be string (e.g., code, client, or device)

The JSON schema seems to require `"code"` only
see https://github.com/w3c/wot-thing-description/blob/0600e4384c129bf1dc1fa4fa1a34074d6b684afa/validation/td-json-schema-validation.json#L1143-L1148

## Request
As you might know we use the JSON schema to auto-generate TypeScript definitions so that they can be used in the Scripting API and in other places, see https://github.com/w3c/wot-scripting-api/tree/main/typescript/thing-description

At the moment the outcome for all security schemes is a big  list of possible anonymous types since they are anonymous types in [JSON schema](https://github.com/w3c/wot-thing-description/blob/main/validation/td-json-schema-validation.json#L807-L1156) also.
see https://github.com/w3c/wot-scripting-api/blob/main/typescript/thing-description/thing-description.d.ts#L32-L124

to facilitate re-use it might be beneficial to have proper names like
* NoSecurityScheme
* BasicSecurityScheme
* OAuth2SecurityScheme
* ...

so that anyone can re-use these definitions and/or point to it.

Do you think it is possible to create global types in the JSON schema so that we are getting those named types?

**Comment by relu91** [comment]
I can volunteer looking into this 👍🏻
