### ISSUE TITLE
New term 'support' at the top level

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#125]
Based on the outcome of the Prague f2f it was decided to have a support term at the top level to have a contact point for the metadata maintainer:
`"support": "http://..."`

**Comment by benfrancis** [comment]
What are the intended use cases? Would this be surfaced in a user interface somehow?

Note that in the case of a gateway which provides Thing Descriptions for non-web devices this can probably not be inferred automatically from most devices.

**Comment by sebastiankb** [comment]
support can be found in the new TD version.
