### ISSUE TITLE
What is the exact structure of TM placeholder identifiers?

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1252]
Regarding the identifiers of placeholders, currently the specification says :

> The string-based pattern of the placeholder MUST follow {{PLACEHOLDER_IDENTIFIER}}, which should contain a placeholder identifier name. The identifier name can be used to identify the placeholder for the substitution process. Placeholder can be only applied within the value of the JSON name-value pair and the value have to be typed as JSON string. 

I think it is not clear in the following aspects:
- The requirement of starting with {{ and ending with }} is not clearly mentioned. It should be worded in the text with something like: Start and end with a double curly bracket
- The fact that the a string can contain a placeholder and does not have to only a placeholder, i.e. `"Thermostate No. {{THERMOSTATE_NUMBER}}"` is allowed. This is only understood via an example
- It does not have to be capital letters? Actually, even I am not sure about this. 
- Allowed special characters. E.g. are the following allowed: `/`, `{`, `}`, `_`, `-`, `%` etc.
- Can it be only a special character, i.e. is the following allowed? `{{?}}`

**Comment by sebastiankb** [comment]
many thanks @egekorkan for the reg expression https://regex101.com/r/dIHC4y/1/

**Comment by sebastiankb** [comment]
PR was merged today
