### ISSUE TITLE
Numbering tables

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1256]
Currently, all the tables in the spec have no numbers so it is not possible to refer to them from anywhere. One table in the architecture spec has a number and can be used for simple linking: https://www.w3.org/TR/wot-architecture/#table-operation-types

I think we should have this in the TD spec so that we can refer to the tables like we do the examples

**Comment by egekorkan** [comment]
I could not solve this with a respec option and opened an issue at respec https://github.com/w3c/respec/issues/4004

**Comment by egekorkan** [comment]
So one "solution" would be to wrap tables in figures, like below:
![image](https://user-images.githubusercontent.com/20195407/152772275-84adc6d0-b5f3-4313-9cf9-9175b98e37ac.png)

 This solves the functional problem but I find it a bit confusing for the reader that a table is a figure. We can also add more post-processing to the render script but that would make it difficult to link while writing the document

**Comment by egekorkan** [comment]
There is a PR available at respec, see https://github.com/w3c/respec/pull/4200 . Once that is merged, we should check manually if it fixes it here, thus not linking that PR

**Comment by egekorkan** [comment]
The PR above is merged! https://github.com/w3c/respec/pull/4200#event-7028415932

So we can try it now :)

**Comment by ProgramMax** [comment]
I haven't added documentation yet for how to use it. I'll be doing that soon.
But in the mean time: Add class="numbered" to your table and make sure the first child node of the table is `<caption>your table caption here</caption>`.

Additionally, you can use `<a href="#my_table_id"></a>` to have it populate the link text with the auto-generated table number, such as `Table 3`.

**Comment by ProgramMax** [comment]
If I understand correctly, you want the table to be able to contain a link to itself. This is useful for someone who scrolls down the page, finds a table, and wants to grab the link to that table.

Right now, figures and tables look up the translated wording ("Figure" and "Table", for example), then append the number, then the caption. To make this a link, we could change the code that generates that text. The code which does this is here: https://github.com/w3c/respec/blob/main/src/core/tables.js#L69
and here:
https://github.com/w3c/respec/blob/main/src/core/figures.js#L100

We might want to put this behind a flag somehow, though. Maybe not everyone wants the tables and figures to be links.
I imagine it would be a page-wide flag (not a per-table / per-figure flag). So maybe it could go in the ReSpec config?

**Comment by egekorkan** [comment]
> If I understand correctly, you want the table to be able to contain a link to itself. This is useful for someone who scrolls down the page, finds a table, and wants to grab the link to that table.

This is exactly what I had in mind as a use case.

> We might want to put this behind a flag somehow, though. Maybe not everyone wants the tables and figures to be links.
I imagine it would be a page-wide flag (not a per-table / per-figure flag). So maybe it could go in the ReSpec config?

I would definitely see this as part of ReSpec config

**Comment by ProgramMax** [comment]
I could probably code that up.
Would you mind opening a bug in ReSpec, including me, and asking:
1.) If this is a feature that should be added,
2.) If a global setting is ideal, and
3.) What that setting should look like?

BTW the code that generates links to figures and tables is here:
https://github.com/w3c/respec/blob/main/src/core/anchor-expander.js#L76
and here:
https://github.com/w3c/respec/blob/main/src/core/anchor-expander.js#L100

We'll likely share code with that.
