### ISSUE TITLE
Good Practice for observe property flow

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#1258]
The TD specification misses a clear specification what should happen once a property observation is started. I see at least 2 different behaviors
* return a value right away
* inform about a value change for the first time the value changes (in the future)

I think it is difficult to enforce a given behavior but we could at least state a _good practice_.

Note: the [PropertyAffordance](https://w3c.github.io/wot-thing-description/#propertyaffordance) has already a similar note about the good practice that each observeproperty has a corresponding unobserveproperty.
Having said that, I would say a good practice is also that each `observeproperty`  directly responds with the *latest* known value.

**Comment by benfrancis** [comment]
We kind of implement `observeallproperties` in WebThings over WebSockets in that when a WebSocket is first opened on a device we push the current value of all properties to the client, then then push new values of individual properties when they change. This avoids the Consumer needing to carry out a separate `readallproperties` operation to get the initial value of properties before observing them.

**Comment by sebastiankb** [comment]
from today's TD call:
- the behavoir depends on the used protocol (it may respond with the latest value or not)
- to be sure to get the latest value there should be a read on the property and do an observation after that
- we should provide a note that provides information about this kind situation

**Comment by sebastiankb** [comment]
PR merged
