### ISSUE TITLE
rel:type to multiple TMs

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1265]
The new composition mechanism makes it possible to model TMs (and thus TDs) as multiple TMs #1207 . However, there is an assertion in the spec that says:

> Please not that a TD can only be an instance of only one TM at a time. That means for Thing Descriptions: The links array can use the entry with "rel" : "type" maximum one. 

This should be reworked. I think we can and should still say rel:type can be used maximum once but if someone wants to use the composition mechanism, they should do it with the appropriate keywords.

Note: Also, there is a typo. It should be `Please note that...`

**Comment by sebastiankb** [comment]
From technical point of view, a single type entry is enough. The pointed type / TM tells which other sub-types are used. 

From my point of view, no action is required here.

**Comment by danielpeintner** [comment]
> Note: Also, there is a typo. It should be `Please note that...`

FYI: the typo has been fixed by now.

**Comment by egekorkan** [comment]
What I wanted to say is that: I think we should add another sentence afterward, making the whole paragraph something like:

> Please not that a TD can only be an instance of only one TM at a time. That means for Thing Descriptions: The links array can use the entry with "rel" : "type" maximum one. If such mechanisms are needed, they can be modeled via the composition mechanism in TMs (link to corresponding section).

**Comment by sebastiankb** [comment]
merged
