### ISSUE TITLE
Room information

### ISSUE THREAD

**Issue by tkzkno** [w3c/wot-thing-description#1268]
I want to describe "room information" of sensors  in TD.
( Not Geographic information but Room name, building name etc.. )
But there is no fields in TD. ( only  properties, actions, link...etc)
Please give me any ideas.

**Comment by egekorkan** [comment]
Do you mean you want to put the location of a Thing in the TD?  We have some examples at https://w3c.github.io/wot-thing-description/#semantic-annotations-example-geoloc

As a design choice, we avoid adding domain-specific keywords to the core of the standard but allow anyone to add semantic annotations

**Comment by Citrullin** [comment]
This sounds like labeling to me. You can use `@type` for that. You can follow a standard for it, such as saref, or just label it as you like.

**Comment by sebastiankb** [comment]
Such domain specific metadata should be relied on a domain specific ontology. For building you can take a look at [BOT](https://w3c-lbd-cg.github.io/bot/). An example usage with TD can be found [here](https://w3c.github.io/wot-usecases/#TemperatureSensor).
