### ISSUE TITLE
Add Security Metadata

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#127]
A draft of the proposal for security metadata for the TD is [here](https://github.com/w3c/wot-security/blob/working/wot-security-metadata.md).   There is a [PR here](https://github.com/w3c/wot-security/pull/88) as well which may or may not have been merged by the time you read this comment.

The goal is to merge this with the TD specification as normative content, ideally in time for the next Plugfest, so that we can explore implementations that include security.  

There are some tasks we have to get through to make this happen:
1. **Vocabulary.**   The proposal defines a number of new fields whose definitions need to be added to the context.   The proposal is not done... there are a few more terms that should be added... but it's at the 90% point so a first draft of the vocabulary can be done at this point.
2. **Syntax.** There are some new elements inside "forms": "security" and "scope".   These take either single values (ids referring to security configurations or scopes defined in the top-level security block) or arrays of such values.   A single value should be treated as an array with a single element.
3. **Framing.**  There are some assumptions about default values, single value/arrays allowed for some fields, etc. that have to be checked and implemented as part of the framing.
4. **Examples.**   The examples need to be made consistent with the updated JSON-LD 1.1-based TD syntax.
5. **Definitions.**  There is one example that uses "definitions" to organize security configurations.   This usage should be checked for correctness.  In particular the values in the forms for "security" and "scope" may use identifiers declared under the "definitions" block at the top level.

**Comment by sebastiankb** [comment]
Thanks for the overview.

**Comment by sebastiankb** [comment]
Security metadata form the Sercurity TF was merged in the new TD version.
