### ISSUE TITLE
UML diagrams contain lines with multiple properties

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#1280]
Several of the URL diagrams contain more than one property in a single line.
The formatting looks a bit weird, perhaps it is possible to fix during the automatic generation.

**Comment by sebastiankb** [comment]
Yes, the diagrams are auto generated. After the feature freeze in Dec I would suggest to create manual diagrams again like [here](https://www.w3.org/TR/wot-thing-description/#overview)

**Comment by egekorkan** [comment]
Call of 30.11: The current diagrams do not have this issue anymore.
