### ISSUE TITLE
Canonicalization Bug in sample

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#1286]
I believe the canonicalized form for the [Example 39](https://w3c.github.io/wot-thing-description/#canonical-thing-description-nows) in the  [Canonicalization](https://w3c.github.io/wot-thing-description/#canonicalization-serialization-json) section is wrong.

the sort order is

`..."securityDefinitions":{"basic_sc":{"in":"header","scheme":"basic"}},"security":["basic_sc"],"title":"MyLampThing"}`

while it should be

`..."security":["basic_sc"],"securityDefinitions":{"basic_sc":{"in":"header","scheme":"basic"}},"title":"MyLampThing"}`

Note: "security" should come before "securityDefinitions"

I encountered it since I started a first draft of implementing it in node-wot, see https://github.com/eclipse/thingweb.node-wot/pull/630

**Comment by sebastiankb** [comment]
also see #1304

**Comment by mmccool** [comment]
well... this is in fact a bug but the example is no longer in the document.  Let's close this issue, but if we bring canonicalization back we'll have to fix this.  Even closed we'll see this issue since it is labelled with "canonicalization"

**Comment by egekorkan** [comment]
Closing this as part of canonicalization issues. They will be reconsidered in 2.0 by searching for the label
