### ISSUE TITLE
Default Value Definitions should sort security schemes

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#1295]
see https://w3c.github.io/wot-thing-description/#sec-default-values

`DigestSecurityScheme` and `BearerSecurityScheme` are split.

![grafik](https://user-images.githubusercontent.com/11281461/142985317-60bfa784-c857-43c9-b25e-814d66039f0c.png)

**Comment by egekorkan** [comment]
I think that intention was to group by the terms that get the default value. This is also the case for `contentType` of the first line

**Comment by danielpeintner** [comment]
> I think that intention was to group by the terms that get the default value. This is also the case for contentType of the first line

I think this is counter intuitive. In most of the cases I would like to support one security schema and know what are the default values. To me it seems unlikely that I would like to know where the term `in` is used.

**Comment by egekorkan** [comment]
I agree with this, I was just explaining the possible reason behind

**Comment by sebastiankb** [comment]
close issue since PR with commit https://github.com/w3c/wot-thing-description/commit/8960b61bcef12908c0fde0fcdc9e0184db071b1d solve it
