### ISSUE TITLE
Add Action attributes

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#130]
Actions are very broad and can have many effects. As a learning from REST, we should allow to annotate Actions with the following attributes:

* safe: no internal state (cf. resource state) is changed when invoking this action (e.g., CoAP FETCH)
* idempotent: the Action can be called repeatedly with the same outcome (i.e., is idempotent)
* (functional): (better term needed) the Action does not even use internal state to return result (it is more than safe), cf. ICN Named Function Networking (NFN).

**Comment by lgleim** [comment]
with functional, do you mean a [pure function](https://en.wikipedia.org/wiki/Pure_function)?

**Comment by takuki** [comment]
Though it may be obvious to us, for clarity, the definition of idempotent had better mention that it is idempotent with regards to the same input values.

**Comment by sebastiankb** [comment]
I extended the definition of `idempotent ` based on takis comment. Please review.
