### ISSUE TITLE
title/titles and description/descriptions definition with global `@language` in the context

### ISSUE THREAD

**Issue by Murloc6** [w3c/wot-thing-description#1302]
We tried to round trip data using a sparql endpoint as discovery database.
During the round trip process, the `title` attribute has been transformed into `titles` language map when the original TD contains a `@language` in the context.

You can see the example [in this playground](https://tinyurl.com/y4c3zswp)

This issue has been reported to the JSON-LD framing repository, [see issue](https://github.com/w3c/json-ld-framing/issues/126).

This issue could be solved by changing the JSON-LD framing algorithm.
An alternative solution could be to use two different URI for `title` and `titles` (idem for  `description`/`descriptions`). For example, using an equivalent of `skos:prefLabel` for `title` and an equivalent of `skos:altLabel` for `titles`. This solution is not satisfactory, but it can be implemented quickly.

**Comment by vcharpenay** [comment]
It does make sense to me.

Since the two properties would have a particular meaning (presence of language tags or not), I'd rather create new properties under the TD namespace and add a `... rdfs:subPropertyOf dc:title` statement.
