### ISSUE TITLE
Make it clear that operation names are case sensitive

### ISSUE THREAD

**Issue by benfrancis** [w3c/wot-thing-description#1303]
From the Architecture call today, relating to https://github.com/w3c/wot-architecture/issues/637

The TD specification needs to make it clear that operation names are case sensitive.

**Comment by egekorkan** [comment]
I mean, why would they not be? So is every single keyword that is defined in the TD and JSON is case sensitive. We can add some text but I don't think it is necessary

**Comment by benfrancis** [comment]
For context, there is currently an assertion in section [6.5.2](https://www.w3.org/TR/wot-architecture/#sec-hypermedia-forms) of the WoT Architecture specification which directly contradicts the Thing Description with regards to whether the list of operation names is extensible (i.e. implementations can define their own extensions).

> The set of predefined operation types MAY be augmented by Extension operation types chosen by applications. Extension operation types MUST be URIs [RFC3986] that uniquely identify the type. Extension operation types MUST be compared as strings using a case-insensitive comparison. Nevertheless, all-lowercase URIs SHOULD be used for extension operation types.

The conclusion by others on the call was that this assertion would be removed from the WoT Architecture specification, but in return the Thing Description should clarify that op names are case sensitive, because this is currently a contradiction between the two 1.0 specifications.

Don't shoot the messenger ;)

**Comment by egekorkan** [comment]
> Don't shoot the messenger ;)

Sorry about that, I didn't direct my message at you but more on the decision that was made. About the decision:

I don't think it makes sense to write something like this normatively, especially if it is only for the `op` values. The spec says:

>  Future versions of the standard may extend this list but operations types SHOULD NOT be arbitrarily set by servients and be restricted to the values in the table below.

If we are going to put something about case sensitiveness, there is already some at https://w3c.github.io/wot-thing-description/#td-basic-types-mapping which already implies this.

But we can add a non-assertion text at the end of this section saying: 

> This means that all terms are case sensitive.

**Comment by benfrancis** [comment]
I agree it would be strange to make this assertion only about operation names since there are lots of other string literals defined in the specification.

@egekorkan wrote:
> If we are going to put something about case sensitiveness, there is already some at https://w3c.github.io/wot-thing-description/#td-basic-types-mapping which already implies this.

I don't think this is particularly explicit, but in reading this I also wouldn't assume that e.g. `READPROPERTY` would work. I personally don't have a strong opinion about whether this needs making more explicit.

**Comment by egekorkan** [comment]
I am not sure why I am assigned to this since the decision on what to exactly do is not clear.

**Comment by mlagally** [comment]
I think this is potentially a source of confusion and (accidential) interoperability issues.
If the TD remains silent, the Profile should make it explicit for all TD literals.

**Comment by danielpeintner** [comment]
> I think this is potentially a source of confusion and (accidential) interoperability issues.
> If the TD remains silent, the Profile should make it explicit for all TD literals.

IF something is unclear it should be fixed (improved) in the TD document.

Having said that, I am still unsure whether this is really necessary...  every vocabulary term we are using (i.e., `href`, `contentType`, `security`, ...) and other values like `"scheme": "basic"` are case-sensitive. 
This would need clarification also. Hence,  I don't think this is necessary!

**Comment by sebastiankb** [comment]
also see https://github.com/w3c/wot-thing-description/issues/1325

**Comment by egekorkan** [comment]
Superseeded by https://github.com/w3c/wot-thing-description/issues/1325, closing
