### ISSUE TITLE
Simplified TD Example Questions and Requests for Extension

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#131]
The Simplified TD is currently documented here https://w3c.github.io/wot-thing-description/proposals/simplified-td and mainly documented by example.

Since the example does not yet cover all features nor all corner cases, please leave a comment here, when you need feedback how a specific feature or corner case should look like.

**Comment by sebastiankb** [comment]
I think, we can close this issue since the simplified TD is compiled in the official TD spec. All open issues should be placed in an own thread.
