### ISSUE TITLE
hctl:hasTarget as a DatatypeProperty ?

### ISSUE THREAD

**Issue by ethieblin** [w3c/wot-thing-description#1310]
We are dealing with TDs in which href may look like this.
```
"href": "/api/something/{parameter}
```
Currently the href (i.e., hctl:hasTarget) object is considered as a URI because hctl:hasTarget is an ObjectProperty (see [hctl:hasTarget definition](https://github.com/w3c/wot-thing-description/blob/7343d5ab9d2db1b8016c63a58753337a6481114b/ontology/hctl.ttl#L83)).

The generated URI, in this example something like `<https://json-ld.org/api/something/{parameter}>` is not valid according to the URL specification (https://www.ietf.org/rfc/rfc3986.txt). (and causes SPARQL endpoints to raise an error when uploading such URIs).

We propose that hctl:hasTarget is changed to a DatatypeProperty so that the object is kept to is original form, which can be a URL pattern and not a URI stricto sensu.

[Playground link](https://json-ld.org/playground/#startTab=tab-nquads&json-ld=%7B%22%40context%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Ftd%2Fv1%22%2C%22%40type%22%3A%22Thing%22%2C%22id%22%3A%22urn%3A123%22%2C%22base%22%3A%22http%3A%2F%2Fmything.fr%22%2C%22properties%22%3A%7B%22myprop%22%3A%7B%22forms%22%3A%5B%7B%22href%22%3A%22%2Fapi%2Fsomething%2F%7Bparameter%7D%22%2C%22contentType%22%3A%22application%2Fjson%22%2C%22op%22%3A%5B%22readproperty%22%5D%2C%22htv%3AmethodName%22%3A%22GET%22%7D%5D%7D%7D%7D)

**Comment by wiresio** [comment]
@sebastiankb @vcharpenay - any option on that?

**Comment by vcharpenay** [comment]
right, thanks. Even in [example 21](https://www.w3.org/TR/wot-thing-description/#form-serialization-json) of the TR, there would be a bug.

Somehow, somewhere, the change you suggest had already been made because the examples in the TD ontology documentation display hrefs as strings (see e.g. [example 1](https://www.w3.org/2019/wot/td#thing-description-json-ld-1-1-instance-to-rdf-dataset)). Examples in the Hypermedia Controls ontology documentation are consistent with the TR, though...

So, let's change that.

**Comment by vcharpenay** [comment]
while I made the change, I noticed that the `hctl` [example with reified links](https://www.w3.org/2019/wot/hypermedia#reified-links) would make little sense after the change.

Any suggestion on how to proceed? Should I just remove the example? Is there a way to retain it (e.g. by creating a second property for linking to OWL individuals)?

**Comment by ethieblin** [comment]
We think that we can keep the reification on hasLink for example, to specify the type of link between a TD and the given string URL (or URL pattern).
For example
```json
"links":[{ "href": "http://example.org/toto.pdf", "rel": "documentation"}]
```

Concerning the reification, we are not sure what the point of this example is :
Is this JSON-LD example (based on TD context):
```json
"links": [
        {
            "anchor": "https://en.wikipedia.org/wiki/Web_of_Things",
            "rel": "about",
            "href": "http://www.wikidata.org/entity/Q2814098"
        }
    ]
```
supposed to represent the following triple and add it to the description of the TD somehow ?
``` 
<https://en.wikipedia.org/wiki/Web_of_Things> <http://schema.org/about> <http://www.wikidata.org/entity/Q2814098> .
```

**Comment by ethieblin** [comment]
@vcharpenay We agree with your proposal of  a new ObjectProperty to link a TD to a OWL:Individual.

However, we are perplex on the use of "anchor" in the links section, cf my previous comment on this [example](https://www.w3.org/2019/wot/hypermedia#reified-links)

**Comment by wiresio** [comment]
@vcharpenay - any suggestions?
