### ISSUE TITLE
clarify whether vocabulary terms in the information model are case sensitive

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#1325]
@egekorkan 
> I don't think it makes sense to write something like this normatively, especially if it is only for the `op` values. The spec says:

>  Future versions of the standard may extend this list but operations types SHOULD NOT be arbitrarily set by servients and be restricted to the values in the table below.

I agree with you, that it should not be only for the op values, a clarification is required for all TD literals. 

> If we are going to put something about case sensitiveness, there is already some at https://w3c.github.io/wot-thing-description/#td-basic-types-mapping which already implies this.

> But we can add a non-assertion text at the end of this section saying: 
> This means that all terms are case sensitive.

This section is talking about the JSON binding, but IMHO a common normative clarification should be done in chapter 5.

**Comment by sebastiankb** [comment]
from today's TD call:
- group decided to mention in the TD spec that all key-value pairs and the sample values provided in the information model is case sensitive
- best place would be in Section 5.3 the explains this and is valid for the full TD model

**Comment by sebastiankb** [comment]
merged
