### ISSUE TITLE
Review use cases document / align terminology / identify gaps

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#1350]

**Comment by egekorkan** [comment]
As mentioned in the editors call, I propose to do this only for identifying work items for the next charter and not trying to squeeze new stuff into TD 1.1 since we are past the time to include new features.

**Comment by mlagally** [comment]
This is not about new features for the current TD.
The objective is to identify which use cases are covered by the current TD.

**Comment by sebastiankb** [comment]
I will provide my comments to use cases that have TD impact:

- 2.1 Smart Agriculture
- 2.1.1 Greenhouse Horticulture --> I do not see any conflict to define TDs for all mentioned sensors and actuators
- 2.1.2 Open-field Agriculture -->   I do not see any conflict to define TDs for all mentioned sensors and actuators. Potential discussions about "time series" can be provided in the TD spec. 
- 2.1.3 Irrigation in Outdoor Environment --> TDs can simple describe the specific soil sensors. Additional ontologies can be integrated in TD definitions to describe the specific depth, the root zone volume or the min temperature per day.

tbc

**Comment by mlagally** [comment]
@sebastiankb 
Please update the coverage table at: https://github.com/w3c/wot-usecases/edit/main/USE-CASES/coverage.csv with your asessment of the gaps of other use cases.

**Comment by egekorkan** [comment]
Call of 21.12: https://github.com/w3c/wot-usecases/pull/197 is merged, closing
