### ISSUE TITLE
TD generated from TM should allow custom `@type`

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1351]
Coming from https://github.com/w3c/wot-discovery/pull/253#issuecomment-1010131653

The TD spec says:

> The tm:ThingModel value of the top-level `@type` MUST to be replaced by the value Thing in the Partial TD instance.

This means that all TDs generated from a TM MUST have `@type:Thing`. @farshidtz and I think that this assertion should be simply changed to remove `tm:ThingModel` so that custom `@type`s can be used.

**Comment by sebastiankb** [comment]
from today's TD call:
- ok to update the spec
- a new text will be provided that explains that the @type can be selected in a custom style
