### ISSUE TITLE
JsonSchema findings: missing definitions or types

### ISSUE THREAD

**Issue by thjaeckle** [w3c/wot-thing-description#1355]
During implementing the [WoT Integration in Eclipse Ditto](https://github.com/eclipse/ditto/pull/1270) I found some missing definitions in the TD JsonSchema:
* "dataSchema" -> "const" and "property_element" -> "const" do not contain a type, but should be `"type": "any"`
   * https://github.com/w3c/wot-thing-description/blob/9db5e96f5d8654e54a2d6884b90485251b9768da/validation/td-json-schema-validation.json#L185
   * https://github.com/w3c/wot-thing-description/blob/9db5e96f5d8654e54a2d6884b90485251b9768da/validation/td-json-schema-validation.json#L568
* "dataSchema" -> "default" is missing from JsonSchema
   * defined for DataSchema: https://w3c.github.io/wot-thing-description/#dataschema
* "exclusiveMinimum" and "exclusiveMaximum" are missing from "dataSchema" (defined in NumberSchema and IntegerSchema)
   * defined for NumberSchema: https://w3c.github.io/wot-thing-description/#numberschema
   * defined for IntegerSchema: https://w3c.github.io/wot-thing-description/#integerschema
* the JsonSchema would probably need a separate "numberSchema" and "integerSchema" extending "dataSchema" similar to how it is done here: #1319 to also get the "type" correct on "dataSchema" -> "minimum" / "maximum" / "exclusiveMinimum" / "exclusiveMaximum"

**Comment by thjaeckle** [comment]
In addition I just found that the top-level [Thing](https://w3c.github.io/wot-thing-description/#thing) `"profile"` is missing from the TD and TM JsonSchema.

**Comment by egekorkan** [comment]
- Regarding `enum`, `const` and now `default`, the way to say any type is to leave the schema empty with no type specified. There is no `type:any` in JSON Schema. Also please see: https://stackoverflow.com/questions/16826128/why-is-this-json-schema-invalid-using-any-type
- Adding default, exclusiveMinimum and exclusiveMaximum
- I will create a separate issue on refactoring the json schema to reuse existing definitions in a better way, it is long overdue!
