### ISSUE TITLE
UriVariables can't be used for RootForms

### ISSUE THREAD

**Issue by thjaeckle** [w3c/wot-thing-description#1357]
Hi.

I just found out that [uriVariables](https://w3c.github.io/wot-thing-description/#form-uriVariables) can currently only be defined in [InteractionAffordances](https://w3c.github.io/wot-thing-description/#interactionaffordance).
That rules out using them for "RootForms" - which also is defined in the JsonSchema: 
* `property_element`: https://github.com/w3c/wot-thing-description/blob/9db5e96f5d8654e54a2d6884b90485251b9768da/validation/td-json-schema-validation.json#L536-L541
* `action_element`: https://github.com/w3c/wot-thing-description/blob/9db5e96f5d8654e54a2d6884b90485251b9768da/validation/td-json-schema-validation.json#L652-L657
* `event_element`: https://github.com/w3c/wot-thing-description/blob/9db5e96f5d8654e54a2d6884b90485251b9768da/validation/td-json-schema-validation.json#L701-L706

I wonder if this is an explicit decision or if this just was not yet thought about.
Using `uriVariables` in root forms might become really useful, e.g. in order to define which `fields` to select for the `readmultipleproperties` OP, e.g.:
```json
{
    "@context": [ "https://www.w3.org/2022/wot/td/v1.1" ],
    "security": "basic_sc",
    "id": "urn:de.jaeckles.test:the-thing-1",
    "base": "http://localhost:8080/api/2/things/de.jaeckles.test:the-thing-1",
    "securityDefinitions": {
        "basic_sc": {
            "in": "header",
            "scheme": "basic"
        }
    },
    "uriVariables": {
        "fields": {
            "type": "string",
            "title": "Comma separated list of properties to select."
        }
    },
    "forms": [
        {
            "op": "readallproperties",
            "href": "/attributes",
            "htv:methodName": "GET"
        },
        {
            "op": "writeallproperties",
            "href": "/attributes",
            "htv:methodName": "PUT"
        },
        {
            "op": "readmultipleproperties",
            "href": "/attributes{?fields}",
            "htv:methodName": "GET"
        },
        {
            "op": "writemultipleproperties",
            "href": "/attributes",
            "htv:methodName": "PATCH",
            "contentType": "application/merge-patch+json"
        },
        {
            "op": [
                "observeallproperties",
                "unobserveallproperties"
            ],
            "href": "/attributes",
            "htv:methodName": "GET",
            "subprotocol": "sse",
            "contentType": "text/event-stream"
        }
    ],
...
```

Which could be usable as:
```
GET http://localhost:8080/api/2/things/de.jaeckles.test:the-thing-1/attributes?fields=location,manufacturer
```

**Comment by benfrancis** [comment]
Nice catch, I've never noticed this.

This also makes me curious why `uriVariables` is a member of `InteractionAffordance` rather than a member of `Form`. Is it so that `uriVariables` can theoretically be shared by multiple forms?

**Comment by thjaeckle** [comment]
I think the `uriVariables` should be defined on TD top level next to and similar to `schemaDefinitions`.

The securityDefinitions are referenced only from `additionalResponses` in Form elements. Being on top level they can however also be used in root forms as well.

**Comment by relu91** [comment]
> This also makes me curious why uriVariables is a member of InteractionAffordance rather than a member of Form. Is it so that uriVariables can theoretically be shared by multiple forms?

This is a good point, I think they were originally assigned the InteractionAffordance class because they were thought to be additional input parameters in the WoT Interaction Model. I remember people reporting use cases for having the ability to use UriVariables for reading properties (which in the abstract interaction model does not have any input). However, for their protocol-related nature, they should be really inside a Form and maybe as @thjaeckle in a root object for easy reuse. 

I would be happy also to see mechanisms to map Action inputs to specific UriVariables so that we have a clear separation between logical inputs of an Affordance and protocol level payloads.

**Comment by sebastiankb** [comment]
from today's TD call:
- it would be consistent to have uriVariables at the top level for forms similar we have at interaction level 
- it seems realistic to cover this feature also for TD 1.1
- lets decide next week

**Comment by sebastiankb** [comment]
from today's TD call:
- group decided to introduce uriVariables at the top level
- this has also the benefit that global-based uriVariables definitions can be made that are valid for local interactions forms
