### ISSUE TITLE
Split "9. Security and Privacy Considerations" into two sections?

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#1363]
from @danielpeintner (also see https://github.com/w3c/wot-thing-description/pull/1359):

Note: we do have 2 remaining issues 

![grafik](https://user-images.githubusercontent.com/11281461/150343671-eea9d836-d15b-4951-a1f5-24ab6345e801.png)

Properly fixing it would require to split  [9. Security and Privacy Considerations](https://w3c.github.io/wot-thing-description/#sec-security-consideration) into **two** sections 
* Privacy Considerations
* Security Considerations

I don't think we should do that in the current state. We could also simply ignore this check.
Any thoughts?

**Comment by egekorkan** [comment]
I think we can simply put 9.5 and 9.6 into security and the others in a privacy section. So I think it is doable in the current state?

**Comment by mmccool** [comment]
https://github.com/w3c/wot-thing-description/pull/1360 now resolves this as part of our general update of these sections.  As it happens the considerations were already identified as being either security or privacy.  However the PR will also add some new considerations in both categories (see the PR for a link to the other issue for new considerations)

**Comment by mmccool** [comment]
TO DO: I realized I have to update the references anyway since now everywhere elsewhere in the doc where we cite "Security and Privacy Considerations" we now have to separately cite each one: "Security Considerations and Privacy Considerations".

**Comment by j1y3p4rk** [comment]
Actually seperating the chpater to 9. Security Considerations and 10. Privacy Considerations looks more clear to me to understand.

**Comment by sebastiankb** [comment]
PR #1387 solved this issue
