### ISSUE TITLE
Should the ThingModel `"tm:extends"` mechanism support transitive extension?

### ISSUE THREAD

**Issue by thjaeckle** [w3c/wot-thing-description#1374]
I think it is currently not clearly defined whether the ThingModel [extension mechanism](https://w3c.github.io/wot-thing-description/#thing-model-extension-import) should also support transitive extension (a hierarchy of extensions).

For example, assuming I have 3 TMs `ColorableLamp` which defines a `tm:extends ` of the TM `DimmableLamp` which itself defines a  `tm:extends ` of the TM `SwitchableLamp`:
```
ColorableLamp extends DimmableLamp extends SwitchableLamp
```

Should this work and should TDs generated from the `ColorableLamp` TM also extend all definitions of both `DimmableLamp` and `SwitchableLamp`?

Coming from the object oriented world and knowing about inheritance I would assume so, but I think that should be made clear.

A similar clarification is missing for the `tm:import` which might also point to a definition using another level of `tm:import`.

**Comment by sebastiankb** [comment]
This is a good point that is clearly missing so far. An additional text should make this clear.

**Comment by danielpeintner** [comment]
I think this is fine and what people would expect. 
Having said that, shall we add some statements/warnings about recursive extensions also?

**Comment by thjaeckle** [comment]
> Having said that, shall we add some statements/warnings about recursive extensions also?

Good catch, yes!

And there must also be rules what happens when extending from multiple TMs containing conflicting definitions ("Multiple inheritance" problem).
For example:
```
ColorableLamp extends SwitchableLamp, Switchable
```

`SwitchableLamp` containing:
```json
"properties": {
  "on": {
    "type": "boolean"
  }
}
```

`Switchable` containing:
```json
"properties": {
  "on": {
    "type": "string"
  }
}
```

Programming languages supporting "Multiple inheritance" (e.g. Scala with its Traits concept) e.g. solve this by clear "order rules": https://teepika-r-m.medium.com/multiple-inheritance-in-scala-d206493e83

Or, if "multiple inheritance" brings too much problems, there is also the option to forbid it in the specification.
Currently it is explicitly mentioned that this is possible:
> "A [Thing Model](https://w3c.github.io/wot-thing-description/#dfn-thing-model) MUST use **at least one** links entry with "rel":"tm:extends""

**Comment by sebastiankb** [comment]
PR was merged
