### ISSUE TITLE
i18n review checklist for TD 1.1 REC

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#1375]
Short i18n review checklist is [here](https://w3c.github.io/i18n-drafts/techniques/shortchecklist)

1. [x] If the spec (or its implementation) contains any natural language text that will be read by a human (this includes error messages or other UI text, JSON strings, etc, etc),

In principle TD does not have such information. TD spec defines fields [`support`, `description` and `title`](https://w3c.github.io/wot-thing-description/#thing) with which the authors of TD can add natural language texts that can be read by a human. The fields `descriptions` and `titles` can be used for multi-language human-readable text. TD itself uses W3C JSON-LD 1.1 serialization and reuse the multi-language mechanism as specified in JSON-LD 1.1 (e.g.,  @language ). Also see section about [human-readable metadata](https://w3c.github.io/wot-thing-description/#titles-descriptions-serialization-json) in TD.
    
2. [x] If the spec (or its implementation) allows content authors to produce typographically appealing text, either in its own right, or in association with graphics.

    **N/A (Not Applicable)**
    TD authors are not expected to produce typographically appealing text.
    TD does not provide a means to do so, either.
 

3. [x] If the spec (or its implementation) allows the user to point into text, creates text fragments, concatenates text, allows the user to select or step through text (using a cursor or other methods), etc.

     **N/A (Not Applicable)**
    TD users are not expected to do such operations.
    TD does not provide a means to do so, either.

4. [x] If the spec (or its implementation) allows searching or matching of text, including syntax and identifiers

TDs can be stored in databases such as by RDF stores. Their search APIs let you search for text contained in fields such as `support`, `description`, and `title`. 

5. [x] If the spec (or its implementation) sorts text

    **N/A (Not Applicable)**
    TD spec or its implementation do not involve sorting text.

6. [x] If the spec (or its implementation) captures user input

    **N/A (Not Applicable)**
    TD spec or its implementation do not involve capturing user input.

7. [x] If the spec (or its implementation) deals with time in any way that will be read by humans and/or crosses time zone boundaries
 
TD has data fields that contain time information: [`created` and `modified`](https://w3c.github.io/wot-thing-description/#thing)

8. [x] If the spec (or its implementation) allows any character encoding other than UTF-8.

    **N/A (Not Applicable)**
    UTF-8 is the only valid encoding for TD format.

9. [x] If the spec (or its implementation) defines markup.

    **N/A (Not Applicable)**
    TD spec does not define markup.

10. [x] If the spec (or its implementation) deals with names, addresses, time & date formats, etc

See checklist number 1. and 7.
 
11. [x] If the spec (or its implementation) describes a format or data that is likely to need localization.

    TD describes data that is likely to need localization such as description and title, which may be used for user interfaces related to the Thing.   However, in each case such strings can also be given using MultiLanguage objects (given as "descriptions" and "titles") which allow the storage and labelling of localized alternatives.  The TD spec also supports single-language default values for each such string which can however be set via language negotiation from the corresponding MultiLanguage data.
 

12. [x] If the spec (or its implementation) makes any reference to or relies on any cultural norms

    **N/A (Not Applicable)**
    TD spec neither depends or refers to any cultural norms.

**Comment by sebastiankb** [comment]
also see https://github.com/w3c/i18n-request/issues/171

**Comment by sebastiankb** [comment]
please see the checklist for TD 1.0. I think all answers are still valid for TD 1.1. I will double check.

**Comment by aphillips** [comment]
Thanks for this checklist! Will you be filing a review request with I18N soon?

**Comment by sebastiankb** [comment]
@aphillips Thanks for your feedback. I setup this issue last week https://github.com/w3c/i18n-request/issues/171 . Do I need to submit another request for review?

**Comment by egekorkan** [comment]
There are separate issues for the checklist, closing
