### ISSUE TITLE
Empty tm documents

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1385]
There are two files that are empty:
- [tm.svg](https://github.com/w3c/wot-thing-description/blob/main/visualization/tm.svg)
- [tm.html](https://github.com/w3c/wot-thing-description/blob/main/ontology/tm.html)

We have the TTL file so it is related to the tooling not picking it up.

**Comment by egekorkan** [comment]
@sebastiankb can you explain what is happening here?

**Comment by mahdanoura** [comment]
I checked this and it's because the template file is missing

**Comment by mahdanoura** [comment]
I checked this, the problem was that it didn't have a template.html file and was not referenced in the templates.sparql file. I have added this. But there are more issues which needs deeper look into the ontology file.
