### ISSUE TITLE
Complete TAG/Security Wide Review Request

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#1396]
Draft TAG review request here; this is also for Security Review.
* https://github.com/w3ctag/design-reviews/issues/715

Needs various things to complete it; see checklist below.  Currently marked as WIP.

- [ ] Update explainer, "minimally containing user needs and example code".  Here is the old explainer; suggest we do a PR to create a new, Explainer11.md file and avoid clobbering the old one (then the new Explainer can link to the old one...): https://github.com/w3c/wot-thing-description/blob/main/explainer/Explainer.md.  See PR #1397.
- [ ] Add one paragraph summary of idea, ideally copy-pasted from explainer intro.
- [ ] Update text (e.g. descriptions of implementations) in [implementation report](https://github.com/w3c/wot-thing-description/blob/main/testing/report11.html).
- [ ] Describe testing process (right now have a generic link to the wot-testing repo, but this is not sufficient.  We need to describe the testing process... *including* security testing!).  It might be a good idea for this explanation to go into the implementation report rather than into a separate document.
- [ ] Publish snapshot and use it for the review (use WD, and/or define a branch/tag, and/or copy a draft to a subdirectory.  We *could* also use the editor's version, but only if it will not change a lot.  Better to have a stable version so that comments can be correlated easily).
- [x] Complete security and privacy questionnaire (see PR #1382)
- [x] Complete primary contacts (editors, but need to fill in full names and affiliations in addition to github handles.  @mmccool will copy from header of TD1.1 document, so please make sure that is correct)
- [ ] Review the [Web Platform Design Principles](https://www.w3.org/TR/design-principles/) and check off the box in the request. (all editors)
- [x] Fill in time constraints or deadline (@mmccool to do: will copy from/link to revised schedule)
- [ ] Link to outstanding unresolved issues in the tracker (if any that relate to 1.1; can also include a link to a label for issues deferred to 2.0)
- [ ] TD editors to review entire issue before marking it as "ready" (removing WIP)

**Comment by sebastiankb** [comment]
from today's TD call:
-  it seems that the explainer should follow the recommended guideline as shown [here](https://tag.w3.org/explainers/) 
- marketing TF can discuss if we reuse the planed content of the explainer for the Webpage then
- we would support also to have separate explainer documents of each TF (we need to check with @mmccool if this ok)
- we need to decide how relevant the  [Web Platform Design Principles](https://www.w3.org/TR/design-principles/) is for Thing Description. It seems is more applying for API-based specs

**Comment by mmccool** [comment]
So I think we need to resolve this issue now too: https://github.com/w3c/wot-thing-description/issues/1405
