### ISSUE TITLE
JsonSchema findings - wrong types: toplevel `security`; AdditionalExpectedResponse `schema`

### ISSUE THREAD

**Issue by thjaeckle** [w3c/wot-thing-description#1398]
During validation of [Eclipse Ditto](https://github.com/eclipse/ditto/pull/1270) generated TDs I noticed that the JsonSchema for TD validation has 2 inconsistencies with the spec:

## 1. toplevel `security`

The JsonSchema for td-validation defines that top-level `security` is of type "array":
https://github.com/w3c/wot-thing-description/blob/4e19c7928db7690e78a43035f553f2c0c92473c7/validation/ext-td-json-schema-validation.json#L1280-L1286

The specification however [declares](https://w3c.github.io/wot-thing-description/#thing):
> [string](http://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/#string) or [Array](https://w3c.github.io/wot-thing-description/#dfn-array) of [string](http://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/#string)

## 2. AdditionalExpectedResponse `schema`

The JsonSchema defines this to be of type "object":
https://github.com/w3c/wot-thing-description/blob/4e19c7928db7690e78a43035f553f2c0c92473c7/validation/ext-td-json-schema-validation.json#L331-L336

https://github.com/w3c/wot-thing-description/blob/4e19c7928db7690e78a43035f553f2c0c92473c7/validation/ext-td-json-schema-validation.json#L413-L418

https://github.com/w3c/wot-thing-description/blob/4e19c7928db7690e78a43035f553f2c0c92473c7/validation/ext-td-json-schema-validation.json#L493-L498

https://github.com/w3c/wot-thing-description/blob/4e19c7928db7690e78a43035f553f2c0c92473c7/validation/ext-td-json-schema-validation.json#L587-L592

The specification however [declares](https://w3c.github.io/wot-thing-description/#additionalexpectedresponse) type "string" - referencing to the named schema in the toplevel `schemaDefinitions` map.

Which one shall it be?

**Comment by egekorkan** [comment]
I do not know where that ext-td-json-schema-validation.json comes from. It is not up to date. Please look at https://github.com/w3c/wot-thing-description/blob/4e19c7928db7690e78a43035f553f2c0c92473c7/validation/td-json-schema-validation.json

**Comment by thjaeckle** [comment]
Oh, right .. I searched via GitHub for "schema" and that was kind of the first hit I got - thanks 👍

**Comment by danielpeintner** [comment]
Note: it has been removed by now to avoid any further confusion, see https://github.com/w3c/wot-thing-description/pull/1391
