### ISSUE TITLE
TD Data Types

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#14]
This is the main issue thread to reflect the current status of the data type definition for the Thing Description.

Next AIs generated from the Düsseldorf f2f meeting:

1) @draggett provides some concrete use cases why some type constructs such as Vector is needed
2) Model JSON Schema vocabularies in Linked Data 
   -  use ShEx and/or SHACL for validation
   - OWL and RDFS

Next status report: 6. October 2017

Team: @vcharpenay, @draggett, @danicic

Side issues regarding this issue:
#13, #19

**Comment by draggett** [comment]
Today, I added JSON Schema examples to illustrate the subset of JSON Schema I believe that the IoT use cases I've looked at justify in respect to the initial Linked Data Vocabulary. I've created a separate issue #19  to discuss good practices for standardising Linked Data vocabularies

**Comment by handrews** [comment]
@draggett Where are these examples?  I apologize, I've drifted off for the past few months but am trying to get back to JSON Schema work and saw the phrase in your comment here just now :-)

**Comment by draggett** [comment]
@handrews see issue #13 which provides JSON Schema examples for IoT use cases and cites some specific use cases from the OCF and oneM2M standards suites.  Please let me know if I've made any mistakes.

**Comment by sebastiankb** [comment]
@vcharpenay, @draggett, @danicic
Just a reminder: In tomorrow's TD web meeting I would like to ask you for a status report. Any news about ShEx and/or SHACL? This is an open issue in  [(https://w3c.github.io/wot-thing-description/Overview.html#conformance)]

**Comment by sebastiankb** [comment]
non active issue anymore. TD contains JSON Schema definitions as subset (~covers IoT use cases) and the JSON Schema terms are mapped to a Linked Data representation.
