### ISSUE TITLE
ThingModels should not define "required" affordances in derived TDs, but "optional" ones 

### ISSUE THREAD

**Issue by thjaeckle** [w3c/wot-thing-description#1400]
During discussion in #1384 several opinions agreed upon that defining optional affordances in ThingModels would be a more intuitive way than defining required ones (as currently [defined with `tm:required`](https://w3c.github.io/wot-thing-description/#thing-model-td-required)).

To summarize the discussion in #1384:
* proposal: by default every affordance defined in a TM should be required to be present in a TD following that model
* the current default (if `tm:required` is omitted/forgotten) is, that everything is optional
    * everything being optional means that a TD can "implement" a TM without providing any affordance of the TM - making the TM kind of "useless"
    * analogy to "interfaces" in programming languages: implementing an interface / abstract class without providing any abstract method in it
* by default, modelers of TMs will likely do not consider adding required affordances to `tm:required`

So a simple proposal would be to have an element `tm:optional` with the same syntax than the current `tm:required`.

**Comment by sebastiankb** [comment]
`tm:required` is more less inspired from JSON Schema which also not have an optional definition. I would be open to adopting a new default assumption, if `tm:required` is missing, everything should be mandatory. Lets talk about this in one of the next TD meetings.

**Comment by egekorkan** [comment]
Call of 23.02:
- The group says that by default everything should be required
- The default behavior should be explained more clearly
- The word stays `tm:required` but the default value (in case it is not present) has all the affordances
- We should contact the JSON Schema community to see what is the history behind using required instead of optional

**Comment by egekorkan** [comment]
I got replies from the JSON Schema slack with some issues that talk about this. Some discussions are even less than 1 year old:
- https://github.com/json-schema-org/json-schema-spec/issues/1112
- https://github.com/json-schema-org/json-schema-spec/pull/1144
- https://github.com/json-schema-org/json-schema-spec/issues/846
- https://github.com/json-schema-org/json-schema-spec/issues/1096

**Comment by thjaeckle** [comment]
Something else came into my mind:
It must also be specified how "extended" `tm:required` relations must be handled.

I assume that a model B which `tm:extends` model A **must** also provide all `tm:required` affordances from model A, as an instance of B can only be also an instance of A, if all required affordances from A were provided.

For `tm:ref` this can not be defined as there is no "is a" relationship here.

**Comment by egekorkan** [comment]
Discussions about its default value can be discussed at #1581 . Closing
