### ISSUE TITLE
No reference to Thing Model Schema for Validation

### ISSUE THREAD

**Issue by FadySalama** [w3c/wot-thing-description#1409]
The TD spec currently shows a schema for validating a TD, but does not contain or even reference a schema for validating Thing Models. I believe there is already a schema for Thing Models under [here](https://github.com/w3c/wot-thing-description/blob/main/validation/tm-json-schema-validation.json). Adding a link to the schema in the spec would solve this.

**Comment by egekorkan** [comment]
Call of 02.03:
- We will add a link to the introduction section of the TM, just above 11.2 and after the text:

>Note that a [Thing Model](https://w3c.github.io/wot-thing-description/#dfn-thing-model) cannot be validated in the same way as [Thing Description](https://w3c.github.io/wot-thing-description/#dfn-thing-description) instances due to some missing mandatory terms.

That text already hints at the need for this.

**Comment by danielpeintner** [comment]
I opened a dedicated *new* issue, see https://github.com/w3c/wot-thing-description/issues/1453
