### ISSUE TITLE
security became securityDefinitions

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#141]
I cannot understand why we would use a new term that it also very long. `security` was expressive enough and is also somewhat established.

I understand that there is now another field under `forms`, yet which is the optional one. So why not make that one bulky? Something like `useSecurity` might even be more intuitive.

**Comment by mkovatsc** [comment]
@mmccool Can you comment if you have a preference here?

**Comment by mmccool** [comment]
These are two separate things and you can have both.   It was not actually modelled correctly in the last version of the TD...  My intention was with the securityDefinitions was to provide a way to avoid having to repeat security configurations when using the same one in many (but not all) forms.  However, it can be considered an optional feature; the "security" object is the important one.

I have included both "security" and "securityDefinitions" in my TD PR for security metadata (https://github.com/w3c/wot-thing-description/pull/144) but will also create an issue to discuss "securityDefinitions" further.

**Comment by mmccool** [comment]
See https://github.com/w3c/wot-thing-description/issues/145

**Comment by zolkis** [comment]
I'd also prefer `security`, at least in Scripting API we could use that term.
We don't need definitions in Scripting since we can let a variable hold those definitions and then use them in code.

**Comment by sebastiankb** [comment]
In the new TD version, _security_ was compiled.

**Comment by mmccool** [comment]
Again, security and securityDefinitions were meant to be separate things.   You can have both.   The securityDefinitions is a set of named configurations, the security is the configurations that apply at a given scope within the TD. 

Anyhow, to avoid complicating things, I took securityDefinitions out of the PR.
