### ISSUE TITLE
Interaction of RFC3986 and JSON Pointer

### ISSUE THREAD

**Issue by aphillips** [w3c/wot-thing-description#1410]
11.3.2 Extension and Import
https://w3c.github.io/wot-thing-description/#thing-model-extension-import

> The tm:ref value MUST follow the pattern
>
> *   file location as URI [[RFC3986](https://w3c.github.io/wot-thing-description/#bib-rfc3986)](Section 4.1)), followed by
> *    \# character, and followed by
> *    JSON Pointer [[RFC6901](https://w3c.github.io/wot-thing-description/#bib-rfc6901)] definition.

JSON Pointer allows basically any Unicode character (excepting the path separator). The `tm:ref` definition allows the pointer to appear effectively as a fragment identifier glued onto the file location's URI. URIs on the wire are not code point sequences, though. Should there be a mention of the need to encode as UTF-8 for the wire? I think the intention of the URI reference is more like what is specified by the [URL Spec](https://url.spec.whatwg.org/) rather than octets 

(All of the examples are ASCII, so it's non-obvious, and JSON doesn't need to percent-encode the values)

**Comment by egekorkan** [comment]
Call of 02.03:
- We should discuss whether it is OK to have spaces instead of URL encoding (ege guesses that they should be URL encoded)

**Comment by sebastiankb** [comment]
I'm not sure we have to do any action here. [TD must be encoded in UTF-8](https://w3c.github.io/wot-thing-description/#td-json-open_utf-8) and this should be also valid for the content of the `tm:ref`. Do I see that correctly?

**Comment by sebastiankb** [comment]
from todays TD call, we would like also discuss this issue again with @aphillips.

**Comment by sebastiankb** [comment]
from today's TD call:
- it seems to introduce a note that describes the URI situation and how it can encoded on the wire
- it should make clear that a double encoding should be avoided
- @sebastiankb will provide a PR; @aphillips will review

**Comment by sebastiankb** [comment]
PR merged
