### ISSUE TITLE
Emphasize locale neutrality in example

### ISSUE THREAD

**Issue by aphillips** [w3c/wot-thing-description#1411]
Example 39: Sample of a DataSchema serialization
https://w3c.github.io/wot-thing-description/#dataschema-serialization-sample

```
"properties": {
    "status": {
        "title": "Status",
        "type": "string",
        "enum": ["On", "Off", "Error"]
    },
```

There is nothing wrong with the above example, although it may not be obvious that the string values are not meant to be shown to the end-user as display strings. When writing enums like this, it is commonly an I18N best practice to emphasize that the string values are not meant to be displayed by rendering them "code-like", e.g. `ON` and `OFF` or (less usable) `OnValue` or `off_value`. Consider modifying examples such as the above appropriately.

**Comment by egekorkan** [comment]
I have three solutions/answers on how to proceed with this:

The lazy answer: We are just using respec and JSON rendering is like this. We can add text to reflect this problem
Medium lazy answer: We can add some rendering adjustments to respec but I am not sure what is the best way
Dangerously not-lazy answer: Actually, these enums can be rendered in user interfaces when the user would write a property by choosing `On`, `Off` in a drop-down menu. Doing this in an "international" way would imply a rather drastic changes to the Data Schema, definitely not possible in TD1.1 and TD2.0 solution would be breaking compatibility with JSON Schema (very bad). However, I will ask the JSON Schema community how this is handled

**Comment by aphillips** [comment]
@egekorkan I'm not sure I agree but I may not be understanding. Are you saying that the values `On`, `Off`, and `Error` are built-in to TD1.1 / TD2.0? I was under the impression that these were just arbitrary values that the field `status` could have (and some other device might have other values, like `starting`, `stopping`, `running`, `idle`, etc.).

The I18N best practice is that program internal values are always wrapped with display strings. This prevents an explosion of values from being needed by the clients (e.g. what would the German enum look like? `Ein`, `Aus`, `Fehler`?) and helps discourage (but does not prevent) lazy developers from using the program internal values as display strings.

**Comment by egekorkan** [comment]
Call of 02.03: This is simply about having more obviously code-related names for "On", like "ON"

**Comment by sebastiankb** [comment]
issue is solved (see PR https://github.com/w3c/wot-thing-description/pull/1448)
