### ISSUE TITLE
Languages of service-doc?

### ISSUE THREAD

**Issue by aphillips** [w3c/wot-thing-description#1412]
Example 27
https://w3c.github.io/wot-thing-description/#example-link-to-developer-documentation

> To point to a developer documentation of a [Thing](https://w3c.github.io/wot-thing-description/#dfn-thing) the value service-doc can be used:

```
"links": [{
    "rel": "service-doc",
    "href": "https://example.com/howTo",
    "type": "application/pdf"
}]
```

The example shows how to link to service documentation. Perhaps this should include an affordance for indicating the language(s) of the documentation and/or ways to indicate different language versions of the documentation?

**Comment by egekorkan** [comment]
That is a valid concern, generally devices come with:
1. A single pdf (or other document formats) with multiple languages: This would be a single link with an array of languages
2. Different pdf for different languages: This would be an array of links with a language tag for each
3. Multiple pds: Combination of the two above

**Comment by egekorkan** [comment]
Call of 02.03.2022:
- We would need an annotation that can be a single string or an array. There is an HTML attribute that can provide this

**Comment by sebastiankb** [comment]
From today's TD call:
we should evaluate the following aspects:
- we should check if the web linking (rfc8288) already provides such a hint in links definition
- how html is handle this if links points to a pdf documents as example (it seems that there is tag about this)
- how is the relation of the underlying protocol like HTTP (language negation)

**Comment by aphillips** [comment]
@sebastiankb 

The HTML attribute is `hreflang` and can be used on `link` and `a` elements in HTML. You might include an optional field or fields `hreflang` into the link structure. The `hreflang` can indicate the language of any target: they don't have to be HTML pages, any old mimetype will do.

RFC8288 supports `hreflang`. Here's one quote:

>    The "hreflang" attribute, when present, is a hint indicating what the language of the result of dereferencing the link should be.  Note that this is only a hint; for example, it does not override the Content-Language header field of a HTTP response obtained by actually following the link.  Multiple hreflang attributes on a single link-value indicate that multiple languages are available from the indicated resource.

The attribute doesn't participate in or affect HTTP; there is no guarantee that the tag is at all accurate. Language negotiation could still take place in addition to/in spite of the attribute.

**Comment by egekorkan** [comment]
Closing after #1449
