### ISSUE TITLE
Missing "available languages/locales" feature?

### ISSUE THREAD

**Issue by aphillips** [w3c/wot-thing-description#1413]
Human Readable Metadata
https://w3c.github.io/wot-thing-description/#titles-descriptions-serialization-json

> Another possibility to set the default language is through a language negotiation mechanism, such as the Accept-Language header field of HTTP. In cases where the default language has been negotiated, an @language member MUST be present to indicate the result of the negotiation and the corresponding default language of the returned content. When the default language has been negotiated successfully, TD documents SHOULD include the appropriate matching values for the members title and description in preference to MultiLanguage objects in titles and descriptions members. Note however that Things MAY choose to not support such dynamically-generated TDs nor to support language negotiation (e.g., because of resource constraints). 

This section discusses the "default language". The above quote is only an example of some of the discussion. 

There is no feature that allows a Thing to indicate what languages are available for language-negotiation or what locales are available. Having a list of available languages or available locales (and these are not necessarily the same thing) would allow the user-agent calling the Thing's interfaces to provide an appropriate `Accept-Language` header or otherwise tailor the request so that the end-user's experience most closely matches their language and locale preferences.

While a multilanguage map is somewhat indicative of available languages, it is often the case that the localization depends on language fallback to avoid bloating the data. In other words, instead of providing separate translations for various (for example French) locales like `fr-FR`, `fr-BE`, `fr-CA`, `fr-CH`, etc., the map might only provide a language value for `fr` (French). However, specifying a more fully qualified locale gives a better overall experience, since regional locale variations affect the formatting of numbers, dates, etc.

**Comment by egekorkan** [comment]
I sort of see two issues:
1. Should we declare the available languages with another map? Like you mentioned, the multilanguage map already does this and a TD should have homogenous language in all multiplelanguage maps, so looking at one gives this information.
2. Current way would explode if we want to include all locales of one language even if for a pure text string (`description` can be same for `fr-FR` and `fr-BE`) and there should be a better way forward?

**Comment by egekorkan** [comment]
Call of 02.03:
- This is more like a feature request but a TD can describe the supported locales as individual keys or language ranges (there is an RFC for that). 
- Another option would be to additionally list locales for a given language (with a new keyword?)

**Comment by egekorkan** [comment]
@aphillips by the way the RFC you have provided in today's call was unrelated (some TCP based DOS mitigation). Could you share the RFC with the language tag ranges?

**Comment by sebastiankb** [comment]
Alternative usage can be that we use the links container to signalize there are alternative TDs available:
```json
        "links": [
        {
            "rel": "alternate",
            "href": "https://example.com/td1",
            "type": "application/td+json",
            "hreflang" : "en"
        },
        {
            "rel": "alternate",
            "href": "https://example.com/td2",
            "type": "application/td+json",
            "hreflang" : "jp"
         },
"..." :".."
]
```

**Comment by sebastiankb** [comment]
from today's TD call:
- it is not clear what should be done in the TD spec
- @aphillips would it possible for you to join in one of the next TD call (Wed, 4-6pm CEST) to discuss this issue?

**Comment by aphillips** [comment]
> @aphillips by the way the RFC you have provided in today's call was unrelated (some TCP based DOS mitigation). Could you share the RFC with the language tag ranges?

Language tag ranges are defined by RFC 4647, which is part of BCP47 (the core of BCP47 is RFC5646). See https://www.rfc-editor.org/rfc/rfc4647

**Comment by mmccool** [comment]
Quick thought: if this is the language used in a TD when the TD is *fetched*, is this perhaps an issue that should be resolved in WoT Discovery, which handles both directories and self-description?  Note that a directory is a Thing and has a TD, but we have no way to specify language negotiation, Accept headers, etc.

**Comment by sebastiankb** [comment]
from today's TD call:
- it seems it is more a topic which is related to the discovery TF
- TD only defines the content and do not describe a systems that manages TD (like database)
- @mmccool will setup an issue in the discovery repo

**Comment by mmccool** [comment]
Proposal to think about: a new optional-with-default member of "forms", perhaps "localefilter"; a boolean, true by default, that says that language filtering (e.g. the Accept-Language header in HTTP) for filtering by language.  There might also be a "locales" array that lists what locales are supported by the interaction, but the default can be the same ones that are used in the TD.  Also, the default language ("localedefault", a single locale) can also default to be the same one as the default language of the TD.

**Comment by danielpeintner** [comment]
FYI: some way to distribute *localized* TDs exists already. See last para in [6.3.2](https://w3c.github.io/wot-thing-description/#titles-descriptions-serialization-json)

![grafik](https://user-images.githubusercontent.com/11281461/166873043-8b1d4749-d8a1-4946-ba66-28622b8cb492.png)

In the node-wot implementation we do that too. Let's assume we have a TD in several languages (EN, DE, IT), see

https://github.com/eclipse/thingweb.node-wot/blob/a446f4824b607982f5523d621127850044bcccc9/examples/scripts/counter.js#L26-L37

we look into the HTTP Accept-Language header field of HTTP and report the TD in this language only.
http://plugfest.thingweb.io:8083/counter

![grafik](https://user-images.githubusercontent.com/11281461/166873433-e5ba86fb-c93f-4aa6-a58b-5fd2e41b99ad.png)

**Comment by egekorkan** [comment]
Call of 30.11: We will close this issue since it is resolved. It can be reopened if needed. The label `i18n-needs-resolution` can be removed

**Comment by aphillips** [comment]
Please do not remove horizontal review labels!! Just closing the issue is sufficient.
