### ISSUE TITLE
Definition of 'well-formed'

### ISSUE THREAD

**Issue by aphillips** [w3c/wot-thing-description#1415]
(globally, but link is to specific instance)
https://w3c.github.io/wot-thing-description/#thing

> One [Map](https://w3c.github.io/wot-thing-description/#dfn-map) contained in an @context [Array](https://w3c.github.io/wot-thing-description/#dfn-array) SHOULD contain a name-value pair that defines the default language for the Thing Description, where the name is the [Term](https://w3c.github.io/wot-thing-description/#dfn-term) @language and the value is a well-formed language tag as defined by [[BCP47](https://w3c.github.io/wot-thing-description/#bib-bcp47)] (e.g., en, de-AT, gsw-CH, zh-Hans, zh-Hant-HK, sl-nedis).

In the above quoted text (and elsewhere in the document) there is a reference to "well-formed language tags" referencing BCP47. This is the right thing to define and the right level of conformance to BCP47 for this specification. However, "well-formed" is probably mysterious to readers of the specification unless they are familiar with BCP47's use of the term (and the difference from "valid language tag").

I suggest linking to our term "well-formed language tag" in the I18N Glossary (https://w3c.github.io/i18n-glossary/#def_well_formed), at least on the first occurrence. You might also consider using "valid language tag" as the recommendation for the contents of the tag (i.e. as guidance to authors), even if the specification only requires that the tags be well-formed (i.e. as something an implementation would check).

**Comment by egekorkan** [comment]
I think I have understood the difference but just to make sure that I did, I have reformulated:
- well formed: it would validate a regex that checks the grammar. This would notice that a tag like `123` is not a language tag but will not cross check with IANA Language Registry at (https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry). `pmy` is there but `pmv` is not but they are both well formed
- valid language tag: it would check whether the tag exists in IANA language registry

I think that we should go with valid language tag and change the document to reflect this but let's hear other opinions

**Comment by aphillips** [comment]
@egekorkan That's the correct interpretation of "well-formed" vs. "valid". I think a more nuanced approach should be used here (it's what I18N generally recommends), which is: require authors to use valid tags, but don't require devices to check the tags contents against the registry. The text I quoted above probably should say "valid", but other text might say "well-formed" when referring to validation.

**Comment by egekorkan** [comment]
Call of 02.03:
- We can map this to our basic and full validation, where basic is well-formed and full is valid tags.
- TDs SHOULD provide valid tags but consumers are not required to check against IANA registry (well formed is ok)

**Comment by egekorkan** [comment]
Closing after #1465
