### ISSUE TITLE
Pubrule checker for TD v1.1 3rd WD

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#1418]
@ashimura created https://github.com/w3c/wot-thing-description/blob/main/publication/ver11/3-wd/Overview.html for publication.

I tried to check remaining issue?

## Pubrules
https://www.w3.org/pubrules/

No errors, just warnings/advises that seem okay to me as is.

![grafik](https://user-images.githubusercontent.com/11281461/156366053-de34b7b9-4b12-4e2a-810e-1e6dca4987bc.png)

## Html Validator
https://validator.w3.org/

--> Document checking completed. No errors or warnings to show.

##  LinkChecker
https://validator.w3.org/checklink

Broken Links that will come in the future (OR will be updated)
  - https://www.w3.org/TR/2022/WD-wot-thing-description11-20220228/
  - https://www.w3.org/2022/wot/td/v1.1

Broken fragments
* https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.1.md#securitySchemeObject
  - reported as broken link but exists?
* https://w3c.github.io/wot-binding-templates/#creating-a-new-protocol-binding
  - reported as broken link but exists?
* Internal Server Error: http://www.ontology-of-units-of-measure.org/resource/om-2/
  - works for me, but changes to http://www.ontology-of-units-of-measure.org/page/om-2   (without trailing/)

**Comment by sebastiankb** [comment]
WD is published
