### ISSUE TITLE
Restricting the context url in JSON Schema

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1420]
Rather easy but urgent decision needs to be made before the testfest/plugfest of next week:

Should we allow only the new context URL? Currently at https://github.com/w3c/wot-thing-description/blob/main/validation/td-json-schema-validation.json#L67 three are allowed, I think only the latest should be allowed?

**Comment by egekorkan** [comment]
Actually the old one might be still permitted but the temporary one should be removed for sure

**Comment by sebastiankb** [comment]
from today's TD call:
- based on the TD 1.1 spec we have to follow " When there are possibly TD 1.0 consumers the anyURI https://www.w3.org/2019/wot/td/v1 MUST be the first entry and the https://www.w3.org/2022/wot/td/v1.1 MUST be the second entry."
- it seems possible to setup a OR statement to check this requirement. 
- @egekorkan will implement this in the JSON Schema for the TestFest

**Comment by egekorkan** [comment]
I need https://github.com/w3c/wot-thing-description/pull/1433 merged to quickly implement this
