### ISSUE TITLE
OAuth2 Assertion: other-flow assertion is removed from spec but visible in implementation report

### ISSUE THREAD

**Issue by FadySalama** [w3c/wot-thing-description#1439]
The OAuth2-related assertion `td-security-oauth2-other-flows`: `If an OAuth 2.0 flow other than code, client or device needs to be specified an extension vocabulary MUST be used.` has been removed from the spec, but the assertion is still visible in the implementation report

**Comment by egekorkan** [comment]
@FadySalama This seems to be fixed now, we will close it on the TD call of 15.06 but feel free to reopen it. CTRL+F on https://w3c.github.io/wot-thing-description/testing/report11.html to search `td-security-oauth2-other-flows` gives me nothing
