### ISSUE TITLE
TD Schema does not allow for SecurityScheme property "in" to have the value "uri"

### ISSUE THREAD

**Issue by FadySalama** [w3c/wot-thing-description#1440]
Currently, the TD Schema does not include the value `"uri"` as a possible value for the `"in"` property of SecuritySchemes
See: [1](https://github.com/w3c/wot-thing-description/blob/bafa33e47c84bb879e1f5a102649cc3bea1ec3ca/validation/td-json-schema-validation.json#L873), [2](https://github.com/w3c/wot-thing-description/blob/bafa33e47c84bb879e1f5a102649cc3bea1ec3ca/validation/td-json-schema-validation.json#L918), [3](https://github.com/w3c/wot-thing-description/blob/bafa33e47c84bb879e1f5a102649cc3bea1ec3ca/validation/td-json-schema-validation.json#L956), [4](https://github.com/w3c/wot-thing-description/blob/bafa33e47c84bb879e1f5a102649cc3bea1ec3ca/validation/td-json-schema-validation.json#L1003). These will cause any TD that uses this feature to not validate properly.

**Comment by JKRhb** [comment]
I noticed this, too, (see https://github.com/w3c/wot-thing-description/issues/1394#issuecomment-1061937519), it seems as if the addition of this field to SecuritySchemes other than the `apiKeySecurityScheme` was not actually intended.

**Comment by FadySalama** [comment]
Then the spec would need to change because that field was also added to [BasicSecurityScheme](https://w3c.github.io/wot-thing-description/#basicsecurityscheme), [DigestSecurityScheme](https://w3c.github.io/wot-thing-description/#digestsecurityscheme) and [BearerSecurityScheme](https://w3c.github.io/wot-thing-description/#bearersecurityscheme)
