### ISSUE TITLE
Clarification about NullSchema

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1441]
I have just realized that we do not explain what `null` really means. What we currently say is:

> Metadata describing data of type null. This [Subclass](https://w3c.github.io/wot-thing-description/#dfn-subclass) is indicated by the value null assigned to type in DataSchema instances. This Subclass describes only one acceptable value, namely null. It can be used as part of a oneOf declaration, where it is used to indicate, that the data can also be null.

It means something specific in [JSON Schema](https://json-schema.org/understanding-json-schema/reference/null.html). I think this needs rewording since even our text can mean that type:null means lack of payload.

**Comment by relu91** [comment]
> I think this needs rewording since even our text can mean that type:null means lack of payload.

is it? we have an open issue asking to have this ability: https://github.com/w3c/wot-thing-description/issues/1234. 
From the text you cited above I don't understand that specifying `null` actually indicates the absence of value and it seems quite aligned to what is specified in the JSON Schema spec you cited. What do I miss?

**Comment by egekorkan** [comment]
Well the problem is that we keep saying `null` but do not explain what null means. My idea is to add something like "It’s important to remember that in JSON, null isn’t equivalent to something being absent." like JSON Schema does. Maybe putting links to the programming language concepts would be also nice

**Comment by sebastiankb** [comment]
good point. @egekorkan would you provide a PR proposal?
