### ISSUE TITLE
Can TMs have the V1.0 context URL?

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1443]
All our TM examples use the context URL `"https://www.w3.org/2022/wot/td/v1.1"`. Additionally, none of the TM terms are in the old context file. So should we restrain the usage of the old URL in TMs?

**Comment by danielpeintner** [comment]
I think the *old* context URL should be usable also.

I know TMs might be a 1.1 feature but why should we constraint it to create only *newer* TDs ... I think it should be applicable to all valid URLs.

**Comment by egekorkan** [comment]
My concern is that JSON-LD processors might show errors or warnings since the terms are not in the old published context

**Comment by sebastiankb** [comment]
Good catch. The main difference is the `tm:ThingModel` value introduced in v1.1. I don`t see any problems using this feature for deriving TDs that contain also the 1.0 context definition. Doing so, the TM model should use both namespaces v1.1 and v1.0 as defined [here](https://www.w3.org/TR/wot-thing-description11/#ref-for-dfn-consumer-2). An example would be helpful.

**Comment by egekorkan** [comment]
I think this is somewhat weird but ok. I think the following need to be made clear since not every reader of our spec understands what `@context` does:
- Say that TM-related keywords are only available in the 1.1 context
- Generating a TD 1.0 from a TM is possible. In that case, the correct context order should be used (what @sebastiankb said above)
- `@context` should not be modified during the generation process

**Comment by sebastiankb** [comment]
from today's TD call:
- theoretical, generating TD 1.0 instances are possible with the TM approach
- however, its maybe confusing for the reader, when we introduce a new concept in TD 1.1 that is also applicable to TD 1.0. The expectation would be more that is only relevant for 1.1
- we would keep as it is and not add addition text for now. Maybe we can be more clear in the next charter about in a specific TM specification
