### ISSUE TITLE
Alignment of assertion ids

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1446]
Currently there are some assertion ids that start with `td`, `tm` and a bunch of others that have some other prefixes. We should align them in order to have:
- better ordering in the implementation report
- possiblity of grouping them for consuming

I'll do a passover in order to generate a possible list of prefixes and comment below

**Comment by egekorkan** [comment]
I prefer to do this once we have merged some PRs and the spec is more stable. Doing this will generate a lot of changes that are purely editorial and maintenance related

**Comment by egekorkan** [comment]
I am putting both label 2.0 and 1.1 labels since we may still do it quickly at once? @mmccool what do you think?

**Comment by mmccool** [comment]
Updating assertion ids stands a good chance of messing up our testing data.  It's not enough to update the ids in the spec itself at this point, we also have to update the ids in all testing data and in configuration data like depend.csv, categories.csv, etc in the testing/inputs directory.

So sure, let's do it, but I propose writing a script that takes as input a table of new/old ids and that script should be designed to work with any input text file.  Then we can apply it to everything else where we have to update the ids.

Note also that the implementation report sorts ids and it is good to have names that cluster together, so starting ids with a category name (consistent with categories in categories.csv) would be good.

However, I would prefer to do this after we go to CR to avoid any last-minute breaking changes prior to the CR transition.  I think fixing it up for the PR transition is good enough.
