### ISSUE TITLE
Do we include securityDefinitions?

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#145]
The "securityDefinitions" can be considered an optional feature of the current security metadata proposal; see https://github.com/w3c/wot-thing-description/pull/144.

It is meant to provide a definition/subsitution mechanism to avoid having to redundantly repeat security configurations if the same configurations are used in many (but not all) forms.   However, it probably needs to be implemented in the preprocessor and is only important for very complex security configurations.  As there are other ways to do exceptions (for example, a global security definition overridden by a local one in a form) to avoid verbosity this feature can be omitted without causing too much pain.

Do we leave it in or take it out?

Note: this can also be considered a special case of the more general "definitions" feature discussed in the Prague F2F.

**Comment by mmccool** [comment]
Based on the discussion in the meeting earlier this week it seems that there may be technical difficulties to include securityDefinitions.   In the interests of expediting the process of updating the TD spec with security metadata, I have therefore removed the securityDefinitions from PR141.   I did however tag the version with the securityDefinitions classes and did not change the remaining class names so it should be possible to merge them back in later if we decide they would be useful.

**Comment by mmccool** [comment]
In Bundang we discussed this issue and there was support for adding back the securityDefinitions.   I have prepared a [presentation](https://github.com/w3c/wot-security/blob/master/presentations/W3C%20WoT%20Security%20Definitions%20Proposal.pdf) about this; please review and comment.

**Comment by sebastiankb** [comment]
ok. If there is some time we can discuss this in tomorrow's TD web meeting.

**Comment by mmccool** [comment]
Based on the feedback and discussions with Victor C. regarding feasibility (conclusion: my proposal is implementable) it seems I should proceed with creating a PR.  I kind of want to wait until the one currently on the table (for making security mandatory) is in the master, though.

**Comment by sebastiankb** [comment]
Just a short question: Does the PR https://github.com/w3c/wot-thing-description/pull/207 relates to this issue?

**Comment by sebastiankb** [comment]
I close this issue since `securityDefinitions` is now part of the TD
