### ISSUE TITLE
Consistent way of linking / integrating JSON Schemas into the document

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#1453]
- however we should think about to add the JSON Schema of the TM within the spec document in the next update

_Originally posted by @sebastiankb in https://github.com/w3c/wot-thing-description/issues/1430#issuecomment-1083279896_

**Comment by danielpeintner** [comment]
Note: As mentioned in the TD call I think we should either
* link both JSON Schema files in the document
  OR
* include both files

Mixing does not make sense to me.

**Comment by egekorkan** [comment]
I would prefer to link both of them in this case. My arguments are:
1. Smaller specification document
2. Sections after the schemas need less scrolling
3. People who read it are sent to the GitHub version which is:
  - more or equally up to date 
  - easier to copy-paste
  - its link is more obvious. We had some people asking where the schemas are
4. If we have another schema in the future, it might start getting more annoying to put more and more schemas.
