### ISSUE TITLE
Metadata for protocol bindings  

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#15]
This is the main issue thread to reflect the current status of the metadata definitions for the Thing Description.

Next AIs generated from the Düsseldorf f2f meeting:
1)  enhance core TD vocabulary set with an operation vocabulary for protocols, e.g.,

`"link": [{
 "href" : "coap://mytemp.example.com:5683/temp",

  **"method" :"POST",**

  "mediaType": "application/json"
 }]
}
`
2) enable URI templates, e.g., /blabla/{timestamp}

**Next status report**: 15. September 2017

Side issues regarding this issue:

Team: @mmccool, @mkovatsc, @mjkoster, @sebastiankb, Uday

**Comment by mkovatsc** [comment]
I propose to leave this open until the Binding Templates documents is available.

**Comment by sebastiankb** [comment]
Is there a timeline when this document is available? Any chance to have a first draft for next PlugFest at TPAC?

**Comment by sebastiankb** [comment]
no longer an active issue. Communication metadata like "http:method" are possible within the field "forms" (formerly field "link").
