### ISSUE TITLE
Specify how to treat `id`s in ThingModel

### ISSUE THREAD

**Issue by relu91** [w3c/wot-thing-description#1503]
Given the [Deriviation process of ThingModels](https://w3c.github.io/wot-thing-description/#thing-model-td-generation), is it not clear how the field `id` should be treated. In particular, the process states in step 1 that all the definitions from a ThingModel should be copied over to the target partial TD. Of course, this also includes the `id` field. However, in the [example 63](https://w3c.github.io/wot-thing-description/#example-63) the `id` field changes from `urn:smart:device:wot:pump` to `urn:smart:device:wot:pump:instance:1` as if the generator applied some additional logic to the process. Being a tricky corner case I think we should explicitly say something about it in the definition of the steps. 

#### Discussion points
- Should the `id` field be changed during the derivation process?
- is `id` field in a ThingModel A the `id` of A OR an hint to generate an `id` field for TDs derivated from A ?
- if the `id` field is not the id of the ThingModel should we define a `modelId` field ?

**Comment by mmccool** [comment]
Also the example does not use "opaque" IDs (such as UUIDs) which is/should be an S&P best practice.

**Comment by sebastiankb** [comment]
good catch. In principle, the id field is the identifier of the Thing and not of the TD. 
I would suggest adding a note that this type of information may be modified during derivation process according to the application context. I would not force any specific process. Authors could also use the placeholder concept in the ID value string.

> if the id field is not the id of the ThingModel should we define a modelId field ?

Typically, TM also have a resource identifier which is used for the tm:extend / tm:ref feature as example. So, I'm not sure if we really need this. 

@mmccool 
> Also the example does not use "opaque" IDs (such as UUIDs) which is/should be an S&P best practice.

ok, we should update this

**Comment by mmccool** [comment]
Security Meeting discussion:
- IDs should not define relationships.  They should be identifiers, used to distinguish entities from each other, full stop.
- If you want to define a relationship, use a link.
- Putting a relationship in an id generally falls into the category of "embedding metadata in an id" and will cause various security and privacy issues.  Specifically, if I can infer the type of a Thing from its id (e.g. "an insulin pump") and the id makes its way into a publically shared URL (which is a common pattern, used in WebThings and WoT Discovery directories), then I can infer PII from publically shared information, which we want to avoid.

Conclusion: Don't embed the Thing Model identifiers in the Thing id.  In fact, we would strongly recommend UUIDv4 be used for all ids (this is what we have in profiles at the moment, BTW).

**Comment by egekorkan** [comment]
> Conclusion: Don't embed the Thing Model identifiers in the Thing id. In fact, we would strongly recommend UUIDv4 be used for all ids (this is what we have in profiles at the moment, BTW).

Why should we limit this to only TMs and not for TDs? In the spec, all the examples even put this metadata such as model number, which can be `urn:dev:MyCompany-InsulinPump9000-214234`

**Comment by mmccool** [comment]
See section 10.4 of the TD spec:

10.4 ID Metadata
The value of the id field of a TD might become available to entities that do not have access to the full TD. If the value of the id contains embedded metadata, such as the type of the device or the owner, this could be used to infer personal information.

Mitigation:
The value of the id of a TD SHOULD NOT contain metadata describing the Thing or from the TD itself. Any temporary ID generated to manage TDs, for example an ID for a database or directory service, SHOULD NOT contain metadata describing the Thing or from the TD itself. Using random UUIDs as recommended in [10.5 Globally Unique Identifiers](https://w3c.github.io/wot-thing-description/#sec-privacy-consideration-global-id-risk) also mitigates this risk.

**Comment by relu91** [comment]
> Conclusion: Don't embed the Thing Model identifiers in the Thing id. In fact, we would strongly recommend UUIDv4 be used for all ids (this is what we have in profiles at the moment, BTW).

I generally like this mainly because it is not open-ended. As I pointed out in https://github.com/w3c/wot-thing-description/pull/1506#discussion_r875931599 the current proposal is a little bit vague. It could create a proliferation of implementations that treat the id field differently: keeping the id from the TM, completely ignoring it, doing custom stuff, and mixing the two extremes. 

However, I might see some use cases when people want to personalize the URI scheme. Recommending UUID4 means that every TD generated from a TM should have an urn-like: `urn:uuid:6e8bc430-9c3a-11d9-9669-0800200c9a66`. Does it make sense to allow for template variables inside TMs? For example: `urn:mynamespace:{{ID}}`
