### ISSUE TITLE
TD JSON Schema not backwards-compatible with v1

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#1510]
A recent change to JSON Schema causes issues with validation of *old* v1 TD instances. It is no longer possible to use purely
"https://www.w3.org/2019/wot/td/v1"
for validation.

see [JSON Schema](https://github.com/w3c/wot-thing-description/blob/main/validation/td-json-schema-validation.json)

A simple sample that used to work and fails now.

```
{
	"id": "urn:simpleWithDefaults",
	"@context": "https://www.w3.org/2019/wot/td/v1",
	"title": "MyLampThing",
	"description": "Valid TD copied from the spec's first example",
	"securityDefinitions": {
		"basic_sc": {
			"scheme": "basic",
			"in": "header"
		}
	},
	"security": [
		"basic_sc"
	]
}
```

Changing it to 
`"@context": ["https://www.w3.org/2019/wot/td/v1", "https://www.w3.org/2022/wot/td/v1.1"]`
works.

I am not sure if this is intended. To me this seems to be a *breaking* change in the sense that older TD cannot be validated anymore.

relates to https://github.com/eclipse/thingweb.node-wot/issues/763

**Comment by egekorkan** [comment]
I have seen the discussion in node-wot and talked with @danielpeintner . According to my point of view, there is a problem. If an implementation wants to use TD1.0 only features, that implementation should simply use that schema to do validation or generation of ts types. 

We cannot allow people to use the old context value while using the new features.

**Comment by relu91** [comment]
> I have seen the discussion in node-wot and talked with @danielpeintner . According to my point of view, there is a problem in versioning of scripting api with respect to TD. If an implementation wants to use TD1.0 only features, that implementation should simply use that schema to do validation or generation of ts types.
> 
> We cannot allow people to use the old context value while using the new features.

That was my understanding too, but a little bit complex to achieve in practice.

**Comment by egekorkan** [comment]
> I think this is a different point. The new schema should also validate old TDs. This is no longer the case and I think this is what backwards compatible means.

I think the consensus at https://github.com/w3c/wot-thing-description/issues/1243 was to let this happen. However, I see a problem now. The spec says:

> When there are possibly TD 1.0 consumers the anyURI https://www.w3.org/2019/wot/td/v1 MUST be the first entry and the https://www.w3.org/2022/wot/td/v1.1 MUST be the second entry.

This allows a 1.0 consumer to consume new TDs. However, the 1.1 consumers who try to parse an old TD will fail. This means that consumers need separate logic for consuming 1.0 TDs and 1.1 TDs. This **may** not backwards compatible. How to solve this problem, without consumers having separate consume or validation steps, is not straightforward though. Other than the initial validation step, there should be no changes needed and validation is not mandatory for consumption (it was not even implemented in node-wot before).

**Comment by benfrancis** [comment]
I recall pointing out this problem in #1243.


>> 1.1 Consumer interacting with a 1.0 Thing

> This might work if we make the assertion that a 1.0 Thing Description can be parsed as a 1.1 Thing Description, but it requires testing of all the changes in types, defaults and mandatory/disallowed members to make sure that actually works. If not then consumers will need separate code paths for 1.0 and 1.1 parsing. There's also always the option that a given Thing Description can include both the 1.0 and 1.1 contexts, if it is valid against both specifications.

...

> The only feasible solution I can think of is that a Thing Description can use the 1.0 context (if a valid 1.0 TD), 1.1 context (if a valid 1.1 TD) or both (if it's both a valid 1.0 TD and 1.1 TD). A 1.0 consumer can only be expected to parse a Thing Description which includes the 1.0 context, but can not be expected to parse a Thing Description which only has a 1.1 context. A Thing Description which only contains the 1.1 context should be a valid 1.1 Thing Description.

**Comment by egekorkan** [comment]
So one solution would be to allow only the 1.0 context in the schema but put an assertion in the spec saying that a TD should not use the new features if it has only 1.0 context. That would mean that a 1.0 Consumer would not have problems. The problem would be that we cannot avoid that some people do not change the context value but still use the new features.
