### ISSUE TITLE
ReSpec Warnings - Normative reference defined in informative document

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#1518]
e.g., Normative reference to "base direction" found but term is defined "informatively" in "i18n-glossary".

![grafik](https://user-images.githubusercontent.com/11281461/171179870-b33ba4b7-cdb8-4456-b9c8-c08925539f4f.png)

What shall we do?

**Comment by danielpeintner** [comment]
@ashimura  mentioned the following in the main call today
> ... we can use W3C drafts if they are REC-track or Note, and stable enough.

**Comment by egekorkan** [comment]
- We should talk with @plehegar to change respec to allow this. 
- For now, we are going to ignore these warnings

**Comment by egekorkan** [comment]
The discussion continues at https://github.com/w3c/wot-thing-description/issues/1518, closing here.
