### ISSUE TITLE
ReSpec Error - Form definition 

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#1519]
see https://w3c.github.io/wot-thing-description/#protocol-bindings

![grafik](https://user-images.githubusercontent.com/11281461/171180480-278df0a4-5cc9-4709-8048-f92a6e64d280.png)

@egekorkan were should the definition to "Form" point to ?

**Comment by egekorkan** [comment]
Call of 15.06:
- We should simply internally link to https://w3c.github.io/wot-thing-description/#form
