### ISSUE TITLE
ReSpec Error - Reference "[ACE-OAuth]" not found.

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#1520]
we use the spec reference [[ACE-OAuth](https://w3c.github.io/wot-thing-description/#bib-ace-oauth)] which is not available in [specref](https://www.specref.org/?q=ACE-OAuth)
see for example https://w3c.github.io/wot-thing-description/#adding-security-schemes

![grafik](https://user-images.githubusercontent.com/11281461/171180783-53167ee1-7f9f-427a-88d1-b0f49c6cb563.png)

@mmccool what is the correct reference?

**Comment by danielpeintner** [comment]
The problem is that if we publish CR and we have the following reference https://w3c.github.io/wot-thing-description/#bib-ace-oauth looking like this, it is not good.

![grafik](https://user-images.githubusercontent.com/11281461/171368174-d684d05d-ffbe-431e-9f2b-323eb633321a.png)

**Comment by sebastiankb** [comment]
in my point of view, the should be only a replacement from [ACE-OAuth] to [RFC9200], right?

**Comment by danielpeintner** [comment]
The problem right now is that RFC9200 is not known yet, see [specref](https://www.specref.org/?q=RFC9200).

**Comment by egekorkan** [comment]
Call of 15.06:
- We have an editor's note about this:
![image](https://user-images.githubusercontent.com/20195407/173866286-ef6b63f1-c0a9-4159-a490-ef483dffdfd0.png)

- Specref is sometimes slow to adopt such new specs, we will add it to localBiblio for now.

**Comment by mmccool** [comment]
Note the above PR also updates a second reference I found (where we give an example of how to use an extension).

**Comment by mmccool** [comment]
RFC9200 is still in "Auth48" state as of today: https://www.rfc-editor.org/auth48/rfc9200

Once it is published and is added to ReSpec we will want to update this references.

**Comment by sebastiankb** [comment]
[ACE-OAuth] is replaced by [RFC9200] in the spec: 

![image](https://user-images.githubusercontent.com/13832739/183378884-ed6487c5-059d-45fc-9a58-a8eb17d52166.png)

I will close this issue
