### ISSUE TITLE
Missing RFC-2119 Keywords in Assertions

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#1523]
The following assertions are missing RFC-2119 keywords:
* tm-compose-name-collision
* tm-rel-type-maximum

**Comment by egekorkan** [comment]
tm-compose-name-collision should be updated to use SHOULD
tm-rel-type-maximum should be updated to use MUST

**Comment by sebastiankb** [comment]
PR was merged. Issue will be closed
