### ISSUE TITLE
Explaining contentType usage

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1531]
I have realized that we are not explaining what messages are described by `contentType`. It can be understood if details are read all over the place, but it would be better to list the following possibilities somewhere:

- Request Response are the same: `contentType`  in the form applies to both
- Request Response different: `contentType`  in the form applies to request, for the Response one needs `response` term
- Request not present: `contentType`  in the form applies only to response (i.e. there is only `output` in an action)
- Response not present: `contentType`  in the form applies only request (i.e. there is only `input` in an action)

Note: Request is what Consumer sends to Thing, Response is what Thing sends to Consumer

**Comment by sebastiankb** [comment]
Can you setup a PR. Maybe we have a change to cover this in CR. Otherwise we can postpone this to the next version.
