### ISSUE TITLE
At risk section in TD

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1539]
Before CR, we need to update/uncomment the following section: https://github.com/w3c/wot-thing-description/blob/main/index.html#L417

**Comment by sebastiankb** [comment]
it seems the line number has changed. Please can you update your comment with the latest link.

**Comment by egekorkan** [comment]
What I meant is the part just after that (https://github.com/w3c/wot-thing-description/blob/main/index.html#L430) that has the AT RISK text but it is commented out

**Comment by sebastiankb** [comment]
latest ED version has the at risk paragraph in Section "Status of This Document"

**Comment by egekorkan** [comment]
Call of 21.12: Available in the ED, closing
