### ISSUE TITLE
Explicitly allow/mention relative `tm:ref` imports?

### ISSUE THREAD

**Issue by JKRhb** [w3c/wot-thing-description#1546]
The TD specification currently only gives examples for `tm:ref` that import definitions from other documents. However, as the empty string for the URI part indicates a same-document reference (if I am not mistaken), I think it would be nice if the specification explicitly mentioned that relative imports are also legal values and gave an example for such an import. Otherwise, you could get the impression from the current examples that you can use `tm:ref` for imports from external documents only.

An example for a relative `tm:ref` import could look something like this:

```json
{
  "@context": ["https://www.w3.org/2022/wot/td/v1.1"], 
  "@type" : "tm:ThingModel",
  "title": "Multi Sensor Model",
  "properties": {
    "genericTemperature": {
      "type": "number",
      "unit": "C"
    },
    "innerTemperature": {
      "tm:ref": "#/properties/genericTemperature",
      "title": "The inner temperature",
      "minimum": 10
    },
    "outerTemperature": {
      "tm:ref": "#/properties/genericTemperature",
      "title": "The outer temperature",
      "description": "The outer temperature is measured in Kelvin",
      "unit": "K"
    }
  },
  "tm:required": [
    "#/properties/innerTemperature",
    "#/properties/outerTemperature"
  ]
}
```

**Comment by sebastiankb** [comment]
Good point. I would be open to allow self-contained references. What do the others think about it?
@thjaeckle

**Comment by thjaeckle** [comment]
I think that supporting relative references is only consequent, so 👍

**Comment by JKRhb** [comment]
Thank you for the feedback, @thjaeckle and @sebastiankb :) I will try to come up with a PR resolving this issue. As mentioned above, I think the additions to the specification could simply be informative, as relative references should already be covered by the assertions present.

**Comment by mmccool** [comment]
TD call June 22: no objections, please proceed with a PR.
