### ISSUE TITLE
Flexible character for instanceName in Thing Model definition 

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#1556]
The [tm-compose-name-collision assertation](https://w3c.github.io/wot-thing-description/#tm-compose-name-collision) predefines the character `'_'` to identify affordances from different TM definitions and to avoid name collisions. I think, TD should be more flexible and should allow other character then `'_'`.

A simple solution is that there is no assertion anymore that forces to use  `'_'`. Instead we can point out in the TD spec that the usage of `instanceName` would also be enough and can also introduce the `'_'` as last character or an alternative character such as `'.'` . Example:

```
{
...
    "links": [
      {
        "rel": "tm:submodel",
        "href": "./Ventilation.tm.jsonld",
        "type": "application/tm+json",
        "instanceName": "ventilation_"
      },
      {
        "rel": "tm:submodel",
        "href": "./LED.tm.jsonld",
        "type": "application/tm+json",
        "instanceName": "led_"
      }
    ],
...
  }
```

Or

```
{
...
    "links": [
      {
        "rel": "tm:submodel",
        "href": "./Ventilation.tm.jsonld",
        "type": "application/tm+json",
        "instanceName": "ventilation."
      },
      {
        "rel": "tm:submodel",
        "href": "./LED.tm.jsonld",
        "type": "application/tm+json",
        "instanceName": "led."
      }
    ],
...
  }
```

This is a small change and would help to be more flexible. What do you think?

**Comment by sebastiankb** [comment]
from today's TD call:
- no decision yet
- we like to collect more views on this topic and get more people that have this implementation experiences

**Comment by sebastiankb** [comment]
> Does it need to be specified at all?

Good point. I would be ok to redefine the assertion to

"Thereby the generation process SHOULD avoid possible name collisions. " 

Followed with a recommendation statement:

"To achieve this, the following strategy is recommended: All sub/child interaction names begin with the instanceName value followed with a predefined character(s) (e.g., '_', '.', '-', etc.)  and ends with the interaction name of the sub/child [Thing Model](https://w3c.github.io/wot-thing-description/#dfn-thing-model)."

What do you think? If ok, I can prepare a PR for Wednesday.

**Comment by thjaeckle** [comment]
@sebastiankb yes, I think that is a good suggestion 👍
