### ISSUE TITLE
Missing keywords for "in" property in "APIKeySecurityScheme"

### ISSUE THREAD

**Issue by FadySalama** [w3c/wot-thing-description#1557]
https://github.com/w3c/wot-thing-description/blob/f1c251501cb4babec4313a24051ff05b021d1e74/validation/td-json-schema-validation.json#L1080-L1087
The `APIKeySecurityScheme` is missing the keywords `uri` and `auto` for the `in` property. (See: [here](https://w3c.github.io/wot-thing-description/#apikeysecurityscheme))

**Comment by sebastiankb** [comment]
from today's TD call:
- Security TF will evaluate if all keywords make sense in this context (it will be evaluate if auto does make sense here or not) 
- @egekorkan please update the JSON  Schema and provide an PR, the Security TF will review the PR

**Comment by mmccool** [comment]
Security TF reviewed the PR and it is ok, please proceed with the fix.
