### ISSUE TITLE
additionalSecurityScheme in JSON Schema needs to have `"additionalProperties": true`

### ISSUE THREAD

**Issue by thjaeckle** [w3c/wot-thing-description#1589]
I currently look into how to provide the [additionalSecurityScheme](https://w3c.github.io/wot-thing-description/#adding-security-schemes) in the Eclipse Ditto WoT Java SDK.

I noticed that the JSON Schema for both TD and TM do not defined that this object can have "additionalProperties", see the TD schema:
https://github.com/w3c/wot-thing-description/blob/f97f6f36065f8ea42f09c7a5b072234b412c520c/validation/td-json-schema-validation.json#L816-L850

Without
```json
"additionalProperties": true
```
it would not be possible to e.g. add the in the example mentioned properties:
```json
"ace:as": "coaps://as.example.com/token",
"ace:audience": "coaps://rs.example.com",
"ace:scopes": ["limited", "special"],
"ace:cnonce": true
```

**Comment by egekorkan** [comment]
But if additionalProperties does not exist, it means that it would have value true. In other words, if you don't see it set to false, it is allowed to have additional properties.

**Comment by thjaeckle** [comment]
Oh, you're right .. I did not yet realize this. 😕
In our current implementation I explicitly only made json objects able to take additional properties which were defined so in the JSON schema (currently done at 10 places).

**Comment by egekorkan** [comment]
@thjaeckle I did this for the security schemas atm. Can be done everywhere as well I guess

**Comment by thjaeckle** [comment]
FMPOV this issue can be closed then..
