### ISSUE TITLE
Use TD context from WG repo instead of IG repo

### ISSUE THREAD

**Issue by vcharpenay** [w3c/wot-thing-description#159]
It would be easier to use the following URI for the TD context:

https://w3c.github.io/wot-thing-description/context/td-context.jsonld

instead of the one hosted on the IG repository:

https://w3c.github.io/wot/w3c-wot-td-context.jsonld

Currently, the two files are duplicated and may be out of sync. The former is the reference context, used to render the W3C recommendation draft.

**Comment by mkovatsc** [comment]
Funnily the TD spec examples all point to the IG repo version... :)

Must be fixed in the TD spec and we should update the TD playground to inform implementers (@egekorkan).

**Comment by sebastiankb** [comment]
done, in TD spec as well as within TD playground.

Please note that all TDs that uses the "old" context reference will be not correct anymore when using the TD playground.
