### ISSUE TITLE
Why can `oneOf` and `allOf` in `ComboSecurityScheme` be a string?

### ISSUE THREAD

**Issue by benfrancis** [w3c/wot-thing-description#1595]
While discussing https://github.com/w3c/wot-profile/issues/234 I noticed that  `oneOf` and `allOf` in [`ComboSecurityScheme`](https://w3c.github.io/wot-thing-description/#combosecurityscheme) can have a type of string, but the descriptions say they have to be an "Array of two or more strings". Should the type just be Array of string?

**Comment by egekorkan** [comment]
This is a bug in the rendering process. I had an initial try but could not find the issue. This issue is a duplicate of https://github.com/w3c/wot-thing-description/issues/1438

**Comment by benfrancis** [comment]
Closing as a duplicate of #1438.
