### ISSUE TITLE
[OracleReview] RFC2119 assertions

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1599]
There are multiple requriements in normative sections which contain an optional clause (should, may, recommended) in lower case. Several of them are important assertions and should be marked up with RFC2119 markup.

Examples include the language around TD processors and TD producers in 5.3.1.1 Thing, content of some tables in chapter 5.3, e.g. 5.3.3.9 OAuth2SecurityScheme and several clauses in 8. Behavioral Assertions.

**Comment by mlagally** [comment]
This should be addressed in 1.1. to make the spec stronger.
