### ISSUE TITLE
[OracleReview] Hints

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1600]
In several sections, the text talks about hints, e.g. 5.3.4.1 Link:

type: "Target attribute providing a hint indicating what the media type [RFC2046] of the result of dereferencing the link should be."

To achieve interoperability this is not sufficient. it should be an assertion that only media type values defined by IANA MUST be used.

**Comment by egekorkan** [comment]
My comment on this:

We define our own values as well so we cannot limit to IANA only. However, it would be a valid point to discuss whether we should limit it to what IANA defines + what we define. In any case, restricting these values should be done in TD2.0 since TD1.0 TDs might be using some custom values or annotated ones.

**Comment by mlagally** [comment]
@egekorkan 
I still think the language should be a bit stronger. What about "SHOULD use IANA defined media types [RFC2046] where applicable"?

**Comment by mlagally** [comment]
The comment was more generic than this discussion. Suggest to search for "hint" across the entire document.

**Comment by sebastiankb** [comment]
I have always some difficulties to change something what was already available in the TD 1.0 such as the mentioned assertion above. 

Please not that everything what is defined within the information model table are specified as assertion, and is also listed in the implementation report such as: 

![image](https://user-images.githubusercontent.com/13832739/183411474-1d5cec38-de4a-4aec-8fc6-6748379f2fd2.png)

(Please ignore "MAY be included. Type boolean." its only visible in the implementation report and not in the spec)

My recommendation is to leave everything as it is.

**Comment by sebastiankb** [comment]
from today's TD call, decided to close.

@mlagally if you disagree please reopen this issue.
