### ISSUE TITLE
[OracleReview] 5.3.1.5 EventAffordance

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1606]
- [ ] data: is currently optional, should be mandatory since an event subscription without a data flow does not make sense.
- [ ] combinations of operations do not make sense and should not be permitted.

**Comment by egekorkan** [comment]
My comments were:
- data: Not necessarily. If an event is called buttonPressed, it does not even need a payload.
- combination: see other issues relating to this comment

**Comment by sebastiankb** [comment]
from today's TD call, decided to close

@mlagally please reopen the issue if you disagree
