### ISSUE TITLE
 [OracleReview] 5.3.2 Data Schema Vocabulary Definitions

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1608]
- [ ] The following should be an RFC2119 assertion: "it is noted that data schema definitions within Thing Description instances are not limited to this defined subset and MAY use additional terms found in JSON Schema".
- [ ] What does it mean "the table is at risk"? all entries?

**Comment by sebastiankb** [comment]
would be ok for me, to have also this as assertion.

>What does it mean "the table is at risk"? all entries?

yes, this makes no sense and should be removed
