### ISSUE TITLE
[OracleReview] 5.3.2.1 DataSchema

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1609]
- [ ] enum: is defined as an array of any type without details. type lists possible values for any type (including null). Is null valid for enum?
- [ ] default: missing RFC2119 markup. Consider MUST.

**Comment by egekorkan** [comment]
My comment was:
- enum: Yes.

**Comment by sebastiankb** [comment]
> enum: is defined as an array of any type without details. type lists possible values for any type (including null). Is null valid for enum?

I think what we can do is to provide a text what "any type" means (=JSON-based data types compatible with JSON Schema (one of boolean, integer, number, string, object, array, or null)).

> default: missing RFC2119 markup. Consider MUST.

also see: https://github.com/w3c/wot-thing-description/issues/1600#issuecomment-1208030601

**Comment by sebastiankb** [comment]
from today's TD call, decided to close

@mlagally please reopen when disagree
