### ISSUE TITLE
[OracleReview] 5.3.2.6 ObjectSchema

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1611]
required: what does "members are mandatory" imply?

**Comment by egekorkan** [comment]
My comment was:
- This definitely needs an improvement. It means what members are mandatory in the payload that is to be sent (e.g. invokeaction input, writeproperty) and what members will be definitely delivered in the payload that is being received (e.g. invokeaction output, readproperty)

**Comment by egekorkan** [comment]
![image](https://user-images.githubusercontent.com/20195407/180653335-41853157-44a4-4098-86ab-803813539748.png)

**Comment by mlagally** [comment]
@egekorkan 
Please link PR.

**Comment by egekorkan** [comment]
> @egekorkan 
> Please link PR.

Sorry about that, it's #1568

**Comment by egekorkan** [comment]
This has been fixed some time ago. We now say:

> Defines which members of the object type are mandatory, i.e. which members are mandatory in the payload that is to be sent (e.g. input of invokeaction, writeproperty) and what members will be definitely delivered in the payload that is being received (e.g. output of invokeaction, readproperty)

Adding propose closing.
