### ISSUE TITLE
[OracleReview] 5.3.2.7 StringSchema

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1612]
- [ ] contentEncoding: please add link to RFC
- [ ] contentMediaType: please add link to RFC
- [ ] RFC2119 assertion: "Since this value is not a fragment identifier, and is not relative to the root of the TD but to whichever data schemas the security scheme is bound to, this value SHOULD not start with #;"

**Comment by sebastiankb** [comment]
from today's TD all, group like to close this issue
@mlagally please can you check of this is ok and your issue was addressed

**Comment by egekorkan** [comment]
Call of 05.04: The issue is addressed in #1650. Closing
