### ISSUE TITLE
[OracleReview] 5.3.1.6 VersionInfo

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1615]
- [ ] semantic versioning should be RECOMMENDED
- [ ] typo: (unnecessary ".") "underlying TM. instance"

**Comment by egekorkan** [comment]
The second point is addressed at PR #1558

**Comment by mlagally** [comment]
The following text should be an assertion:

> It is recommended that the values within instances and model of the VersionInfo [Class](https://w3c.github.io/wot-thing-description/#dfn-class) follow the semantic versioning pattern, where a sequence of three numbers separated by a dot indicates the major version, minor version, and patch version, respectively.

**Comment by egekorkan** [comment]
I don't know if you have seen my previous comments on this but if we make it more assertive than it already is, we have to explain what these versions mean. This is a discussion we do not have time for at the moment.

Also, please do not add the needs-triage label, it is added automatically for new issues.

**Comment by sebastiankb** [comment]
This is a discussion which we already had in TD 1.0 and decided NOT to recommend a specific version pattern. Companies have already specific version strategies and would also keep them for TD/TM definitions.

**Comment by sebastiankb** [comment]
from today's TD call:
- we should turned this into an assertion with "RECOMMENDATION" statement
- @sebastiankb will provide a PR

**Comment by egekorkan** [comment]
Closing since the discussion happens in #1607
