### ISSUE TITLE
[OracleReview] 11. Thing Model

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1618]
The note states that the section is work in progress. Will this note be removed? What is currently missing from the draft?

If this chapter is not stable or complete, it should be made informative.

- normative assertion? : "This kind of template should be valid and followed for all instantiated Thing Descriptions that are relied on this Thing Model."

**Comment by egekorkan** [comment]
![image](https://user-images.githubusercontent.com/20195407/180653124-c3afe908-3aa6-4c67-b40a-cd675f112b76.png)

**Comment by mlagally** [comment]
@egekorkan Please provide a link to the pull request.

**Comment by sebastiankb** [comment]
It's this PR #1558

**Comment by sebastiankb** [comment]
from today's TD call, decided to close this issue since its addresed by the mentioned PR
