### ISSUE TITLE
Type of additionalResponses

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1624]
I am not sure if this is a spec generation bug but the `additionalResponses` seems to be `AdditionalExpectedResponse or Array of AdditionalExpectedResponse` . However, the JSON Schema only accepts arrays and the name also implies that. There is also the following  text in 5.3.4.2.2 (that is added my me):
> In this case the response name-value pair is still used for the primary response but additionalResponses may also be provided, whose value is an array of AdditionalExpectedResponse objects.

And another text that is an assertion:
> If the content type of an additional expected response differs from the content type of the form, the Form instance MUST include an entry in the array associated with the name additionalResponses that includes a value for the name contentType.

**Comment by sebastiankb** [comment]
good catch. The two type options was always motivated to avoid complicated JSON definitions if only one simple value or entry is needed (similar with `@context` that can be a string or an array). 
I would be ok to just keep the array option, since there seems to be no impact of any assertions.

**Comment by egekorkan** [comment]
I would also prefer the array only option. I am guessing that this is a similar bug to what happens for #1438

**Comment by relu91** [comment]
I can work on a PR for this
