### ISSUE TITLE
Proposal for a way to model TD in RDF

### ISSUE THREAD

**Issue by mjkoster** [w3c/wot-thing-description#163]
https://github.com/mjkoster/wot-thing-description/blob/rdf-model-proposal-mjk/proposals/rdf-model/td-model-rdf.pdf

I created a diagram for how I think TD can be modeled in RDF in a way that makes sense for validation, application interface, and TD tools I can think of.

**Comment by mjkoster** [comment]
My use case is that I read in a TD and use SHACL and RDF framing to transform it into a valid RDF model that I can then use in applications, including tools that can construct and assemble TDs in the RDF domain, which can then be serialized out as a JSON TD.

**Comment by mjkoster** [comment]
Another use case for the RDF model is that it is compatible with iot.schema.org categories of annotation (capability, event, action, property, data item).

**Comment by mkovatsc** [comment]
If you serialize the proposed model using the JSON-LD rules, you would arrive at something like this:
```javascript
{
  "@type": "Thing",
  "id": <...>,
  "name": <...>,
  "properties": {
    <...>: {
      "describedBy": { "type": <...>, ... },
      "forms": [{
        "rel": "dataItem",
        "href": <...>
      }]
    }
  },
  "actions": {
    <...>: {
      "input": {
        "@type": ["DataInstance", "ActionData"],
        "describedBy": { "type": <...>, ... }
      },
      "output": {
        "@type": ["DataInstance", "ActionData"],
        "describedBy": { "type": <...>, ... }
      },
      "forms": [{
        "href": <...>
      }]
    }
  }
}
```
This is quite different from our current model. To me, in particular the "describedBy" relations=`rdf:Property` are confusing.

**Comment by mjkoster** [comment]
I see, you would have the property, input, or output element directly implement DataSchema, which is why you propose a subClassOf relation and the ontology pattern we reviewed yesterday.

I had assumed we would not need such a literal RDF model for the JSON serialization, and could use framing to map the JSON to a more natural and descriptive RDF model.

The model I propose is meant to say that the Property, Input, or Output element has Data Items in it which are described by the embedded schema. But I see that it doesn't directly identify where the embedded schema is in the JSON serialization. Framing would be needed to extract the schema from the TD...

**Comment by mjkoster** [comment]
I will look into whether JSON-LD Framing could be used to map the JSON TD to a more descriptive RDF model.

**Comment by mjkoster** [comment]
rdf:Property is the name for a relation type in RDF, which can be an object Property or a data Property.

Object Properties in RDF are like link relations ("rel") and Data Properties are like Target Attributes in Web Linking.

Not sure if that's what you are asking, pardon me if I'm being redundant.

**Comment by mjkoster** [comment]
To take an example from the proposal, iot.schema.org defines Object Properties providesInteractionPatern, accepteInputData, etc. to describe the relationship between thing/capability class, interaction class, and data item classes. These property names aren't serialized in instances. 

Likewise, I don't propose that the Object Properties "provides", "describedBy", etc. are serialized in the TD but they are used to describe the relationships between classes in the model. This is what I mean by having a more descriptive model in RDF.

But again, I see the idea to use RDF to describe the TD serialization as a different thing, and maybe JSON-LD Framing is the missing piece.

**Comment by mkovatsc** [comment]
I was rather asking how your visualization is meant, because assuming it shows an RDF graph, it uses (and hence defines) different predicate terms than used in the WoT Working Group (e.g., "provides" instead of "properties", "actions", "events" or at least "interactions").

Ignoring the different shape and terms of the ontology for now, why
* call it "DataInstance" when input/output are exactly not instances
* does "DataInstance" have an RDF Property "DataValue" within the TD model? DataValue is only created when an Action is invoked

**Comment by mjkoster** [comment]
It looks like DataInstance roughly corresponds with "DataSpecification" in the model we reviewed last week in Korea (which also is not explicitly part of the JSON TD vocabulary...)

"providesInteractionPattern": "Property" is an RDF mapping for the JSON TD "property" element at the JSON path: /properties/property-name

"acceptsInput": "DataInstance" is likewise an RDF mapping for the "input" predicate with its associated input payload (also "DataSpecification")

**Comment by draggett** [comment]
Could someone please describe what the model (i.e. the diagram) of TD in RDF would be used for as this will help when it comes to assessing different proposals. As an example, @mjkoster suggests that properties, actions and events are subclasses of interaction. What is this fact used for?

In Korea, we have a brief discussion around the role of time.  A property value, for instance,  may be updated from time to time, and holds a value for a time interval.  A named event can be triggered from time to time. Likewise, a named  action can be invoked at different times, and the corresponding response will never occur before the action was invoked. We could go on to model this in RDF in some detail, but I have to ask what the benefit would be from the ensuing complexity.

Perhaps we really just need to associate the datatypes and related metadata.  Thus a thing can have zero or more properties, actions and events. We can use an RDF shape constraint at design-time to test for valid data types, and at run-time, to test values passed in property updates, events, action invocations and action responses. A recent extension allows designers to declare the data type for data passed when subscribing to an event stream. This too could be validated at design- and run- time.

My advice would be to keep the model to the simplest needed and only enrich it as the benefit for doing so clearly outweighs the cost of increased complexity.

**Comment by takuki** [comment]
In the latest [diagram](https://user-images.githubusercontent.com/2302085/42424377-4f08333e-82c0-11e8-85b0-1c724c18f0b8.png), Property is a subclass of both DataItem and DataInstance at the same time. Was it so intended? I think Property can just be a subclass of DataItem.

**Comment by mjkoster** [comment]
After more discussion on this topic, I think a simplified diagram that represents a flattened TD document is a good approach, which allows making Interaction Property a subclass of DataSchema.

I can externalize the concept of payload instances by making a statement that DataSchema describes a DataInstance and DataItems, and a DataInstance can be a DataItem. This doesn't need to be part of the TD model.

![td-model-3](https://user-images.githubusercontent.com/2302085/43042699-601e6152-8d38-11e8-81c4-36580049b1ec.png)

**Comment by mjkoster** [comment]
Here is an example flat JSON-LD that uses this model
```
[
  {
    "@id": "_:b0",
    "@type": ["Thing", "iot:ThermostatCapability"],
    "providesInteraction": ["temperature", "setTemperature"]
  },
  {
    "@id": "temperature",
    "@type": ["Property", "iot:Temperature", "DataSchema", "iot:TemperatureData"],
    "type": "number",
    "minimumPropertyValue": 0,
    "maximumPropertyValue": 150,
    "hasForm": "_:b2"
  },
  {
    "@id": "settemperature",
    "@type": ["Action", "iot:SetTemperature"],
    "acceptsInput": "_:b1",
    "hasForm": "_:b3"
  },
  {
    "@id": "_:b1",
    "@type": ["DataSchema"],
    "type": "number",
    "minimumPropertyValue": 0,
    "maximumPropertyValue": 150
  },
  {
    "@id": "_:b2",
    "@type": ["Form"],
    "href": "http://example.com/thermostat/temperature"
  },
  {
    "@id": "_:b3",
    "@type": ["Form"],
    "href": "http://example.com/thermostat/temperaturesetpoint"
  }
]
```

**Comment by mjkoster** [comment]
And the resulting framed TD:
```
{
  "@context": [
    "..."
  ],
  "id": "urn:uuid:e821a969-551b-4967-83b6-27eea0aa6a6e",
  "properties": {
    "temperature": {
      "@type": ["iot:Temperature", "iot:TemperatureData"],
      "type": "number",
      "minimum": 0,
      "maximum": 150,
      "forms": [{"href": "http://example.com/thermostat/temperature"}]
    }
  },
  "actions": {
    "settemperature": {
      "@type": ["iot:SetTemperatureAction"],
      "input": {
        "@type": ["iot:TemperatureData", "iot:TemperatureSetPointData"],
        "type": "number",
        "minimum": 0,
        "maximum": 150,
      },
      "forms": [{"href": "http://example.com/thermostat/temperaturesetpoint"}]
    }
  }
}
```

**Comment by mjkoster** [comment]
The flat JSON-LD example looks like a good candidate for modular hypermedia serializations, where the TD is broken up into modular content-format instances (link collections, forms, schemas) pointed to by links, which are exposed as hypermedia controls.

**Comment by sebastiankb** [comment]
non active issue anymore. Based on the latest TD model properties, actions, and events are sub-classes of the InteractionPattern class (also see https://w3c.github.io/wot-thing-description/#overview)
