### ISSUE TITLE
Should "security" be mandatory?

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#165]
We should decide whether "security" should be mandatory.   This can be combined with a "none" scheme.  The intent is that Things with no security will still have to explicitly declare they don't have any.

My main concern with this is whether we can combine it with multi-level overriding.   In particular I'd like it so that if a "security" tag is given at the Thing level, that satisfies the "mandatory" requirement and it then does not need to be given at the "forms" level.

This would make it clear that a Thing has no security (if that is the case) without adding an extra security definition to every form.

For slightly more information, see the last slide in [this presentation](https://github.com/w3c/wot-security/blob/master/presentations/W3C%20WoT%20Security%20Definitions%20Proposal.pdf).

**Comment by mkovatsc** [comment]
As commented during the Bundang F2F, I prefer making `security` mandatory and require "no sec" to be declared explicitly, e.g., with scheme `none` or `nosec`.

**Comment by benfrancis** [comment]
Is the idea that a client should refuse to parse an otherwise valid Thing Description if it doesn't define a security member?

What's the rationale for not just assuming "none" as a default?

**Comment by takuki** [comment]
Another option is we state Security is a should-have, and warn that it should be specified for interoperability reasons. We do not need to specify what it means by default when there is no security specified.

**Comment by mmccool** [comment]
I think there is also a difference in the requirements for H2M and M2M use.   For M2M use, we want to know for sure in advance all the interface requirements, including security.   If something unexpected happens at runtime, and in particular if an unanticipated request for credentials occurs without a human in the loop, it would likely break the system. For H2M, asking for credentials "unexpectedly" just means a small diversion in the browser to prompt for credentials.

So one thing we could do here is "RECOMMEND" (RFC2119 style) the of a "security" declaration for any system meant to be used in an M2M fashion, and should consider the TD a "binding contract" so if we declare "none", it really should mean "none".  Leaving "security" off should only be used for Things that are not used as part of an M2M system.

I *personally* think making "security" mandatory, and "binding", would be safer and would support better interoperability.  This is because even if a Thing is designed for H2M use, *someone* is going to want to use it in a M2M use case, if only for automation.

**Comment by mmccool** [comment]
@takuki , your comment is not entirely off-topic since if we make security mandatory, then one form of “incomplete” TD would be one without a security definition.   At any rate, the going name for incomplete TDs seems to be “TD template”.

**Comment by danielpeintner** [comment]
FYI: in the scripting task force we used to use the term `ThingTemplate` and some people tend to switch to `ThingFragment` for partial TDs.

I think we should try to align those terms in both task forces.

**Comment by mmccool** [comment]
We discussed this in the Security TF and the consensus was to make "security" mandatory.   Also, we felt that the security spec in the TD should be "binding", eg. it should be considered an error if the Thing goes off and does security a different way.   

I will make a PR that updates the TD spec with these points.

**Comment by mmccool** [comment]
RESOLUTION: Yes, make it mandatory.   Also Binding.
