### ISSUE TITLE
Versioning container 

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#166]
Based on the discussion about the different lifecycle phases of a Thing in Bundang (see [slides](https://www.w3.org/WoT/IG/wiki/images/c/c8/TD_Lifecycle_Versioning.pdf)), there shall be an optional version container that allows to provide information about the current version state. Example:

```JSON
...
"version": {"td": "1.2.0"}
...
```

 The container can be also used to add additional metadata information when required. Example:

```JSON
...
"version": {"td": "1.2.0", "iot:firmware": "10.0.1", "iot:hw": "..."}
...
```

As best practice the [semantic versioning](https://semver.org/) as version value pattern shall be mention in the TD spec, however, not be declared as mandatory.

**Comment by mmccool** [comment]
I like the proposal, but suggest changing "td" to "instance" to make it clear the version indicated refers to the current instance of the JSON file, not to the TD spec itself.

**Comment by sebastiankb** [comment]
ok, maybe we should spend two characters more for a "tdInstance". What do you think?

**Comment by takuki** [comment]
In my opinion, "td" appears to be more like instances. What is missing is a terminology that clearly separates instances from the definition language itself.  We can explicitly call the language itself as "Thing Description Definition". In this case, "td" denotes instances, and "tdd" would denote the definition language.

**Comment by mlagally** [comment]
I think that we need to revisit the discussion about separating thing instance descriptions from a thing interface description like we have in object oriented programming languages. 
There is already a thread for this in https://github.com/w3c/wot-thing-description/issues/91

**Comment by takuki** [comment]
The TD TF discussed and agreed to have a "instance" instead of "td" for instance versioning which is mandatory within "version" container (version itself is optional), and optional "wot-standard" (or similar, to be decided later) for WoT versioning with fixed value "1.0.0". TD spec needs to describe this.

**Comment by sebastiankb** [comment]
Just reopoen the issue and mark it "for next itteration". So, we do not forget this.

**Comment by sebastiankb** [comment]
included in the latest TD version for Lyon: https://htmlpreview.github.io/?https://github.com/w3c/wot-thing-description/blob/td4lyon/index.html
