### ISSUE TITLE
Prepare modular vocabulary

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#167]
We decided to have modular vocabulary to more easily extend and evolve in the future. This requires new deliverables.

We should fork [this document](https://www.w3.org/TR/HTTP-in-RDF10/) and create copies in the TD repo for WG Notes for:

* Data Schema ("JSON Schema in Linked Data")
* Security
* CoAP (binding vocabular)
* MQTT (binding vocabular)

The binding vocabular for HTTP already exists, is it is the document to be forked :)

**Comment by sebastiankb** [comment]
Here we should organize a meeting with the W3C staff.  

@ashimura  Are there some news about this?

**Comment by sebastiankb** [comment]
This issue is not effecting the TD specification. Used samples with additional terms for protocols are relied on the existing http ontology. The TD spec mention the opportunists to use other protocol context if it exists.

**Comment by vcharpenay** [comment]
see `/ontology/*.html`: skeletons for a WG Note on all vocabularies defined by the TD model.
