### ISSUE TITLE
Add informative text defining use of `proxy-to` link relation type

### ISSUE THREAD

**Issue by benfrancis** [w3c/wot-thing-description#1670]
First raised in #1324.

The `proxy-to` link relation type recommended in the table in section [5.3.4.1 Link](https://w3c.github.io/wot-thing-description/#link) is not defined anywhere.

The table references the W3C WoT Security and WoT Binding Templates documents, but I can't find a definition in either of them.

Unless a definition can be found (or added to the WoT Thing Description specification), I suggest removing this line from the table.

**Comment by sebastiankb** [comment]
@mmccool would be this ok or should we keep it, since we have it also in TD 1.0?

**Comment by sebastiankb** [comment]
based on yesterday's discussion: label it as at-risk and if there is no veto during CR phase we will remove it

**Comment by mmccool** [comment]
OK with that, but we probably do need to add some informative text if we keep it, to avoid ambiguity with "proxy" field in securityDefinitions.  Probably this link type should be used in "virtual Things" acting as a proxy/shadow for another thing.

**Comment by mmccool** [comment]
The Security TF is looking at this, but we did not get to it this week, and next week the mtg will be cancelled due to the plugfest.  However, I will explicitly put it on the agenda for the week after next.

**Comment by mmccool** [comment]
Discussion (Security TF 2022.10.10)
- Members still need to look at it in more depth
- First approximation: both make sense and can be used together.  The "proxy-to" link indicates WHAT is being proxied, the "proxy" field in the security scheme is used to provide security metadata for the proxy itself, e.g. what kind of authentication is needed.  So if you do have a proxy, you could reasonably use both.
- We do lack an implementation, however, let alone one.   However, Intel implemented a proxy service and could provide at least one that also uses proxy-to.  We just need a second...

**Comment by sebastiankb** [comment]
@mmccool 
> The last point said, some informative text would be helpful for proxy-to, e.g. in the table, comparing it to "proxy" in the SecurityScheme. 

are you going to provide a PR for it?
