### ISSUE TITLE
Resolve Editor's Notes before publication

### ISSUE THREAD

**Issue by benfrancis** [w3c/wot-thing-description#1671]
I'm sure the editors know this, but there are quite a few "editor's notes" left in the specification (many with no corresponding issues on GitHub) which are not yet resolved. There's also an unresolved issue called "issue 1" written as a note.

My understanding is that Editor's Notes are not meant to be published.

Since TD 1.1 is getting closer to publication now, this is just a reminder to review and remove them (or convert them into Notes or GitHub issues deferred to 2.0) before publication.

**Comment by sebastiankb** [comment]
Thank you for pointing this out. In yesterday's TD call, we removed some of them. However, we need another iteration for the published version.

**Comment by egekorkan** [comment]
I am creating a PR (#1811) for the easy ones. The remaining ones are:
- 5 at https://w3c.github.io/wot-thing-description/#media-type-section
- 1 at https://w3c.github.io/wot-thing-description/#sec-security-consideration-execution

**Comment by egekorkan** [comment]
This is solved quite some time ago, closing
