### ISSUE TITLE
Use CoAP protocol binding template in examples

### ISSUE THREAD

**Issue by benfrancis** [w3c/wot-thing-description#1672]
Section 7.2 says:
> The following TD example uses a fictional CoAP [Protocol Binding](https://w3c.github.io/wot-thing-description/#dfn-protocol-binding), as no such [Protocol Binding](https://w3c.github.io/wot-thing-description/#dfn-protocol-binding) is available at the time of writing this specification.

Firstly, I think this should say "no such Protocol Binding Template is available" rather than "no such Protocol Binding is available", since a "protocol binding" is defined in a Form in an instance of a Thing Description.

Secondly, as I understand it there is now a CoAP protocol binding template in https://w3c.github.io/wot-binding-templates/bindings/protocols/coap/index.html. Should the example reference this?

**Comment by JKRhb** [comment]
With the merging of #1728, I think this issue is also resolved, right?

**Comment by egekorkan** [comment]
Indeed this is fixed to some extent, closing.
