### ISSUE TITLE
[Nit] Consistent code/example formatting

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#1681]
I noticed that many examples have inconsistent formatting.
* no space after `:`
* space before `:`
* no space at all around `:`
* ...

Does it make sense to apply proper and consistent formatting?

**Comment by sebastiankb** [comment]
I would suggest "no space after :" since this is also used in [JSON-LD1.1](https://www.w3.org/TR/json-ld11/).

**Comment by danielpeintner** [comment]
I created an initial PR dealing with _some_ examples, see #1698 

I used https://jsonlint.com to format the samples.
* I tried Examples 1 to 4 (valid JSON)
* I tried also Example 5 to 7 (invalid JSON, code snippet)
  Note: https://jsonlint.com formats/works also fine for those code snippets.

Downsides:
* it introduces some more new lines like, e.g, 
        `"basic_sc": {"scheme": "basic", "in": "header"}`
 becomes 
```
     "basic_sc": {
			"scheme": "basic",
			"in": "header"
		}

```
* it is an online service. No built-in tool or so..

Anyhow, I would argue we should find a a consistent formatting. The website  jsonlint is handy doing so...

@sebastiankb others
What do you think? Any other proposals?
Shall I continue formatting the remaining examples in #1698  ?
