### ISSUE TITLE
Refine definition of "semantic tag"

### ISSUE THREAD

**Issue by benfrancis** [w3c/wot-thing-description#1687]
The definition of the term [semantic tag](https://w3c.github.io/wot-thing-description/#dfn-semantic-tag) is a bit hard to understand due to some grammatical and spelling errors:

> A JSON-LD mechanism that links definitions in a Thing Descriptions document to concepts in an (RDF) ontology. This allows to give further context about the object property and express the domain knowledge in a standardized way. In a Thing Descriptions document, this can seen in `@type` or as prefixes to a string with the usage of a column (:).

I suggest:

"A JSON-LD mechansim that links definitions in a Thing Description's document to concepts in an (RDF) ontology. This allows Thing Description authors to provide further context and express domain knowledge in a standardized way. In a Thing Description document, this can be achieved using `@type` members, and through the use of string prefixes using a colon (:)."

It might also be worth adding "semantic annotation" as a synonym, since that term is used in many places throughout the document, including the next definition.

**Comment by sebastiankb** [comment]
This sounds ok for me.
