### ISSUE TITLE
Normative JSON Schema for TD validation in TD spec

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#169]
There was a decision in Bundang that the next TD working draft should come with a JSON Schema definition that can be used to validate TD instances (also see [slides ](https://www.w3.org/WoT/IG/wiki/File:JSON_or_ABNF_for_TD.pdf) from @mlagally ) based on the underlying TD specification.

**Comment by vcharpenay** [comment]
Note: in the RDF domain, the RDF SHACL shapes defined in [`/validation/td-validation.ttl`](https://github.com/w3c/wot-thing-description/blob/master/validation/td-validation.ttl) have the same role. Given a fixed JSON-LD context, there are probably equivalences between SHACL and JSON Schema.

**Comment by sebastiankb** [comment]
Thanks for the comment. Does SHACL also validate the structure of a TD instance?

**Comment by vcharpenay** [comment]
Yes. It is its only purpose, in fact. I expect that validation through JSON Schema yields the same results as validation through SHACL of JSON-LD data turned into triples.

**Comment by sebastiankb** [comment]
OK! 

Due to the acceptance I would suggest to add JSON Schema in the new working draft. In the future version we can add SHACL as alternative validation variant.

**Comment by sebastiankb** [comment]
https://w3c.github.io/wot-thing-description/#json-schema-4-validation
