### ISSUE TITLE
Action - double check node-wot's error codes, are there error response payloads?

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#1691]
There's a discussion in an issue of the Profile https://github.com/w3c/wot-profile/issues/80  (https://github.com/w3c/wot-profile/issues/80#issuecomment-845983422)
that leads to requirements for the action response payload for the TD:

@danielpeintner, @sebastiankb  Please let's use this issue to continue the discussion - it is relevant for well-defined action responses.

**Comment by mmccool** [comment]
The TD does have mechanisms to document error responses.  If that is the question, yes, a mechanism exists.  The TD spec does not (and probably should not) prescribe WHICH error responses are used. But that kind of thing can be in a profile...

**Comment by mmccool** [comment]
Close - resolved in meeting 21 Sept, can use existing TD mechanisms.
