### ISSUE TITLE
TD Events

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#17]
This is the main issue thread to reflect the current status of the interaction pattern Event for the Thing Description.

Next AIs generated from the Düsseldorf f2f meeting:
1) make a clear definition about Events in TD
2) How to subscribe and unsubscribe events?  --> should be synchronized with the binding team
3) How does it work in practice? --> have a look of existing protocols: CoAP & MQTT (@mjkoster) and automotive wg (@ashimura)

**Next status reports**: 22. September 2017

Team: @naka, @mmccool, @nakakatsu, @mjkoster, @sebastiankb

Side issues regarding this issue:

**Comment by draggett** [comment]
One open question is whether we support groupings of events so that you can subscribe to the group to get notifications for all of the events in the group. The ability to define such groups impacts the Linked Data vocabulary for thing interaction models. This is also related to the idea of topics for message routing in protocols such as MQTT.

**Comment by zhangyongjing** [comment]
Two aspects should be clearly defined:

**Comment by zolkis** [comment]
I guess we can use this old issue as an umbrella for tracking Event-related issues.
https://github.com/w3c/wot-thing-description/issues/231 
https://github.com/w3c/wot-thing-description/issues/156
https://github.com/w3c/wot-thing-description/issues/216
https://github.com/w3c/wot-thing-description/issues/61
Closing these issues will be visible in this space.

**Comment by draggett** [comment]
Can we get a consensus on events and close this issue?   

I think we agreed to extending TD to allow for data to be passed when subscribing to an event. This data is application specific and can be used by applications to determine the conditions for sending an event. It can be updated by resubscribing, and cancelled by unsubscribing.

Mozilla's Things Gateway allows clients to request the event log. I consider this as something that should be dealt with as an application specific capability, e.g. via an action.  My advice is to keep TD as simple as possible for events and actions and leave complex requirements to the application layer.

**Comment by sebastiankb** [comment]
Outdated issue. Latest discussion on Events can be found here #398
