### ISSUE TITLE
Syntax highlighting of examples

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#1701]
I looked into the reason _why_ some examples are not properly rendered with Syntax highlighting, e.g., 
* https://www.w3.org/TR/wot-thing-description11/#example-5
* https://www.w3.org/TR/wot-thing-description11/#thing-serialization-sample

ReSpec uses [highlight.js](https://github.com/highlightjs/highlight.js) for syntax highlighting (see https://respec.org/docs/#pre-and-code-elements).

Unfortunately highlight.js it does not seem to support code snippets with "..."

To solve this we **_could_** simply use comments like `//` or `/* */` to make it work.... Would that be okay for everybody?

see below Example5 and Example6 and how it may look like

![grafik](https://user-images.githubusercontent.com/11281461/193049284-9337c6e7-4d56-4045-b657-e44c0d2c337b.png)

![grafik](https://user-images.githubusercontent.com/11281461/193049887-59e7e25a-cb3a-4537-a723-e3fa6e722e3c.png)

**Comment by egekorkan** [comment]
I think this is definitely much nicer! Also from markdown, I generally pick `js` as the language and then use the `//` type of comments. Not sure how the behavior changes here though
