### ISSUE TITLE
Section 8.2: Contradicting and unprecise normative behavioral assertions

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#1702]
In the following two assertions only the first sentence is marked as normative in the span markup. From the intention of the text it seems that the second sentence should also be part of the normative assertion. This implies a significant change of normative language.

> A [Thing](https://w3c.github.io/wot-thing-description/#dfn-thing) MAY return additional data from an interaction even when such data is not described in the data schemas given in its WoT Thing Description. This applies to ObjectSchema and ArraySchema (when items is an Array of DataSchema) where there can be additional properties or items in the data returned. This behaves as if "additionalProperties":true or "additionalItems":true as defined in [[JSON-SCHEMA](https://w3c.github.io/wot-thing-description/#bib-json-schema)].

> A [Thing](https://w3c.github.io/wot-thing-description/#dfn-thing) MAY return additional data from an interaction even when such data is not described in the data schemas given in its WoT Thing Description. This applies to ObjectSchema and ArraySchema (when items is an Array of DataSchema) where there can be additional properties or items in the data returned. This behaves as if "additionalProperties":true or "additionalItems":true as defined in [[JSON-SCHEMA](https://w3c.github.io/wot-thing-description/#bib-json-schema)].

The 3rd assertion completely contradicts these statements, since a consumer is also a thing (what else?).

> A [Consumer](https://w3c.github.io/wot-thing-description/#dfn-consumer) when interacting with another [Thing](https://w3c.github.io/wot-thing-description/#dfn-thing) MUST NOT generate data not described in the data schemas given in the [Thing](https://w3c.github.io/wot-thing-description/#dfn-thing) Description of that Thing.

These are normative requirements which MUST be fixed before CR publication.

**Comment by egekorkan** [comment]
So first of all, these assertions are part of the 1.0 and their implementability is already proven.

> Since a consumer is also a thing (what else?).

There is no such assumption? An entity can have the consumer and things behaviors but the two are considered separate. Thus, there is no contradiction with the 3rd assertion.

The second part of the assertions further clarifies what is meant by them, thus no need to enclose them into the same assertion or make them two separate assertions. Given how data schema is specified in TD (and JSON Schema), additional data is only possible in array or object types. Even if we include the second part into the assertion, there is no need to do what is meant by "This implies a significant change of normative language.".

Adding propose closing label.

**Comment by mlagally** [comment]
@egekorkan It is a significant difference if the assertion is just:

> A [Thing](https://w3c.github.io/wot-thing-description/#dfn-thing) MAY return additional data from an interaction even when such data is not described in the data schemas given in its WoT Thing Description.

or if it is:

> A [Thing](https://w3c.github.io/wot-thing-description/#dfn-thing) MAY return additional data from an interaction even when such data is not described in the data schemas given in its WoT Thing Description. This applies to ObjectSchema and ArraySchema (when items is an Array of DataSchema) where there can be additional properties or items in the data returned. This behaves as if "additionalProperties":true or "additionalItems":true as defined in [[JSON-SCHEMA](https://w3c.github.io/wot-thing-description/#bib-json-schema)].

I believe I understand the intention of the author of this paragraph, however, If only the first sentence is true, a return value of a basic type can be followed by an arbitrary sequence of other data. I'm not sure this is the intended meaning of that rule.
The additional constraints in the second sentence make a lot of sense, so they should be included in the assertion.

**Comment by egekorkan** [comment]
As I have said at "Given how data schema is specified in TD (and JSON Schema), additional data is only possible in array or object types.", if there were more data coming back from the Thing, we would have no way of modelling or describing it with a TD. In the case of HTTP, you cannot send a request and get multiple responses over time (unless it is a stream). So, even though I would not oppose including that part in the assertion, I _believe_ that we do not have such a case. Maybe a WS subprotocol or MQTT (a certain way to use it) can do that but some examples would be nice. Otherwise, we have an assertion that is difficult to test.

**Comment by sebastiankb** [comment]
from today's TD call, we decided to close this issue (reason: definitions also exist in TD1.0)
