### ISSUE TITLE
Tagging of assertions 

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#1704]
The following editors note in section 6.5 indicates that some tagging needs to happen before CR transition. Has this tagging been done?

> EDITOR'S NOTE: No Tag Yet
This section refers to tagging of assertions into different categories for the purposes of validation. This has not yet been done but will be done prior to CR transition.

**Comment by egekorkan** [comment]
I think there was more text here that we wanted to put but we removed it? @mmccool do you remember something specific?

**Comment by sebastiankb** [comment]
The editor note is gone in the meantime. Solved this in last week's TD call (also see https://github.com/w3c/wot-thing-description/pull/1729). Propose to close

**Comment by sebastiankb** [comment]
from today's TD call, decided to close

@mlagally please reopen when you disagree
