### ISSUE TITLE
TM Namespace is not used anywhere

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1714]
The second table in the spec shows that there is a TM namespace at `https://www.w3.org/2022/wot/tm`. However, literally, all the TM examples use the TD namespace. Is this intended?

**Comment by sebastiankb** [comment]
TM namespace is defined within the TD context file (https://www.w3.org/2022/wot/td/v1.1):

![image](https://user-images.githubusercontent.com/13832739/195285871-d8589e97-16e4-486d-b5fa-917e59346dfe.png)

TMs consist of definitions from the TD information model + TM specific definitions. So the TD context is reasonable.

**Comment by egekorkan** [comment]
ah I see, ok closing :)
