### ISSUE TITLE
Normative assertion points to informative binding template note which is WIP

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#1722]
The TD CR draft has a set of normative requirements in section 
https://w3c.github.io/wot-thing-description/#protocol-bindings
that are pointing to the informative protocol binding specification.

> Every form in a WoT Thing Description MUST follow the requirements of the [Protocol Binding](https://w3c.github.io/wot-thing-description/#dfn-protocol-binding) Template indicated by the URI scheme [[RFC3986](https://w3c.github.io/wot-thing-description/#bib-rfc3986)] of its href member as indicated by the Binding Templates specification at [Creating a New Protocol Binding](https://w3c.github.io/wot-binding-templates/#creating-a-new-protocol-binding).

The reference points to an WG note on github.io. which is a draft of an informative document.
This draft contains editors notes about sections that still need to be restructured.

Annex F2: "Informative References" https://w3c.github.io/wot-thing-description/#informative-references
contains the following reference to the published WG note.

> [WOT-BINDING-TEMPLATES]
> [Web of Things (WoT) Binding Templates](https://www.w3.org/TR/wot-binding-templates/). Michael Koster; Ege Korkan. W3C. 30 January 2020. W3C Working Group Note. URL: https://www.w3.org/TR/wot-binding-templates/

The following problems need to be addressed before CR transition:

1. As a fundamental rule, normative requirements of the specification cannot reference informative documents. The normative reference to the "yet to be completed" WG note MUST be removed. 
Informative documents MUST NOT create additional requirements on specification adopters.

2. When we go to CR, there should be a **single informative reference** to a **published version** of the binding notes. A second dependency on a still evolving WG note is confusing and not appropriate for a document that is under full control of the WoT WG.

**Comment by sebastiankb** [comment]
In today's TD call, we spent some time checking the independence of the Binding Template document. It seems that the situation is identical as we have in the TD 1.0. A quick check can be done by the search pattern "[WOT-BINDING-TEMPLATES]" which leads to the same results as in TD 1.0 and does not touch any assertion.

However, in the TD call, we decided to check all assertions in detail again and check if there is a dependency that can only be given by the content of the binding template document. 
@relu91 @ashimura @egekorkan and myself will volunteer this work. To speed up this work, volunteers will take care of a specific area of the assertions (based on the assertion table and assertion ids from the [Implementation report](https://w3c.github.io/wot-thing-description/testing/report11.html#test_results)):

- @relu91 from **privacy-distributed-ids** to **td-event-objects**
- @ashimura from **td-event-objects_cancellation** to **td-security-overrides**
- @egekorkan from **td-security-scheme-name** to **td-vocab-op--Form**
- @sebastiankb from **td-vocab-op--Form_cancelaction** to **well-known-operation-types-only** 

If there are one or more assertions that causes some dependency to the Binding Template document, they should be mentioned here in this issue.

**Comment by sebastiankb** [comment]
I just scan the assertions from **td-vocab-op--Form_cancelaction** to **well-known-operation-types-only**.

I have not found any dependency to the Binding Template document. The assertion [bindings-requirements-scheme](https://w3c.github.io/wot-thing-description#bindings-requirements-scheme) was solved by this [PR](https://github.com/w3c/wot-thing-description/pull/1720) last week.

**Comment by relu91** [comment]
I scanned the assigned section and I didn't find any substantial dependency on the Binding Template document. The assertions in my section were mostly about the serialization of different components of the TD model. There were references to forms serialization that, if followed, bring to [bindings-requirements-scheme](https://w3c.github.io/wot-thing-description#bindings-requirements-scheme), but as stated by @sebastiankb it is a non-issue.

**Comment by egekorkan** [comment]
I have done the scan of the above mentioned assertions. Similar to what @relu91 said above, there are assertions about the forms term, such as:
- **td-vocab-forms--InteractionAffordance:** forms: Set of form hypermedia controls that describe how an operation can be performed. Forms are serializations of Protocol Bindings. The array cannot be empty. MUST be included. Type: Array of Form.

However, these assertions follow the definition of Protocol Binding set by the architecture specification at https://w3c.github.io/wot-architecture/#dfn-wot-protocol-binding so it is not a dependency on the Binding Templates document.

These assertions are only (or mostly) about vocabulary terms.

**Comment by ashimura** [comment]
I didn't see any issues on the dependency on the [WoT Binding Templates Note](https://w3c.github.io/wot-binding-templates/), either.

However, I found the following minor issues and would suggest we fix them:
* missing "a" for "as JSON object" in some of the assertions, e.g., td-multi-languages_descriptions
    * should add "a" and make it "as a JSON object"
* missing values between commas (",") at td-processor	Syntax
    * should add actual values between commas
* ambiguous "included" at td-security-combo-exclusive-oneof-or-allof	
    * should clarify Exactly one of either oneOf or allOf MUST be included in what
* ambiguous usage of "token" and "authorization", e.g., at td-security-oauth2-client-flow, td-security-oauth2-client-flow-no-auth, td-security-oauth2-code-flow and td-security-oauth2-device-flow
    * would be better to explicitly state "the token element" and "the authorization element", or clarify those are specific keywords meaning the Thing Description elements (e.g., using specific style like bold italic).
* ambiguous usage of "form level" and "Thing level" at td-security-overrides
    * would e better to explicitly sate "the level of the form element" and "the level of the Thing element", or like the above point, better to use some specific style (e.g., bold italic) for "form" and "Thing" within this assertion

**Comment by sebastiankb** [comment]
Many thanks for your time @relu91 @ashimura @egekorkan !!!

from @mlagally 
> The reference points to an WG note on github.io. which is a draft of an informative document.
This draft contains editors notes about sections that still need to be restructured.

The PR #1720 solved the problem. 

> As a fundamental rule, normative requirements of the specification cannot reference informative documents. The normative reference to the "yet to be completed" WG note MUST be removed.
Informative documents MUST NOT create additional requirements on specification adopters.

That is the reason why we [scanned all assertions](https://github.com/w3c/wot-thing-description/issues/1722#issuecomment-1284364795) again. 

> When we go to CR, there should be a single informative reference to a published version of the binding notes. A second dependency on a still evolving WG note is confusing and not appropriate for a document that is under full control of the WoT WG.

Since the major problem is solved in this issue, I will remove the "blocker" label. 

For Kaz's findings on the minor issue, I will prepare a PR.

**Comment by sebastiankb** [comment]
from today's TD call:
- decided to close this issue since the topic was solved for the CR transition
- Kaz's findings will be addressed in issue https://github.com/w3c/wot-thing-description/issues/1735
