### ISSUE TITLE
Correct nitpick in TD JSON Schema

### ISSUE THREAD

**Issue by Silvanoc** [w3c/wot-thing-description#1740]
[This comment](https://github.com/w3c/wot-thing-description/commit/c900468ae71f8fa66bd72d92bc8bc2f677740aa1#r89274684) marks the place of an erroneous comment in the TD JSON Schema.

**Comment by egekorkan** [comment]
Thank you @Silvanoc for spotting this. I will fix it rightaway

**Comment by egekorkan** [comment]
I pressed the wrong shortcut and committed it directly to master branch at https://github.com/w3c/wot-thing-description/commit/0bbcc5cb0a120ad6491907323aecd0e028c257c2

If others are ok, we can keep it since it is a super simple change.

**Comment by sebastiankb** [comment]
from today's TD call: 
- issue is solved and it was ok by the group that this small change was committed directly to the main
- issue will be closed
-
