### ISSUE TITLE
tm:optional usage

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#1745]
[Section 9.3.4](https://w3c.github.io/wot-thing-description/#thing-model-td-optional) introduce the `tm:optional` feature and focuses on usage to make interaction affordances optional. `tm:optional` does not forbid also to be used on terms like title(s), description(s), etc.. I would suggest to add a (informative) sentence to clarify this.

**Comment by egekorkan** [comment]
Given that #1746 is closed, we can close this issue
