### ISSUE TITLE
Add a warning about the "other" Thing Model specification

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1747]
Coming from WoT CG Office Hours:

There is a document submitted by EVERYTHING in 2015 called Web Thing Model at https://www.w3.org/Submission/wot-model/  . For us it might be clear that this is just a member submission but a google search shows it very prominently, see below:

![image](https://user-images.githubusercontent.com/20195407/202501654-e3a53341-217a-4d1b-b0e7-41fc7f121e9c.png)

For an outsider, it seems like an official W3C document.

I think we cannot remove a member submission but I think we should at least add a note in our spec saying that this is the standardized document.

**Comment by sebastiankb** [comment]
from today's TD  call:
- we can not influence such kind of search results
- maybe we should ask W3C system staff if the ranking can be influenced (e.g. the member submission should be not associated with the TD 1.1 document)

**Comment by lu-zero** [comment]
The easiest/generic way would be to have a central page linking all the latest documents, probably. This way us implementors can link to it and boost its importance and that should carry the linked document.

Also it makes easier for us to tell what we refer to.

**Comment by danielpeintner** [comment]
> The easiest/generic way would be to have a central page linking all the latest documents, probably.

I think https://www.w3.org/WoT/wg/ should that be (see section "Publication Status")

**Comment by egekorkan** [comment]
Call of 21.12: We cannot do anything about this.
