### ISSUE TITLE
Adding link to 1.0 REC

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1770]
With the publication of the CR, we have lost a convenient link to the 1.0 publication, i.e. https://www.w3.org/TR/wot-thing-description/ points to TD 1.1 and this is apparently correct. So I propose to simply adding a "Previous Recommendation" link like JSON-LD 1.1 https://www.w3.org/TR/json-ld11/ . It would be the dated URL.

**Comment by sebastiankb** [comment]
from today's TD call:
- we should update all TD1.0 references to a dated URI
- we should also discuss in the main call how to handle the URI for Arch 1.1 and TD 1.1 for the PR --> policy is needed
