### ISSUE TITLE
Updating @context value in TD document

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#1771]
The current [TD draft](https://w3c.github.io/wot-thing-description/) still uses for _some_ examples the following context

`"@context": "http://www.w3.org/ns/td"`

Since the CR version has been published, I wonder whether it is time to change it to

`"@context": "https://www.w3.org/2022/wot/td/v1.1"`

If so, please let me know and I will provide a PR.

**Comment by egekorkan** [comment]
@danielpeintner yes please! We should indeed change it since people use the examples quite a lot by copy pasting it
