### ISSUE TITLE
Consider adding `observeaction` operations

### ISSUE THREAD

**Issue by benfrancis** [w3c/wot-thing-description#1775]
Currently it's possible to observe properties and subscribe to events, but the status of an action has to be polled with a `queryaction` operation. It would be more efficient in many protocols (e.g. HTTP using Server-Sent Events) to "observe" an action so that status changes are pushed to the Consumer.

Potential new operation types:
- `observeaction`
- `unobserveaction`
- `observeallactions`
- `unobserveallactions`
- `observemultipleactions`
- `unobservemultipleactions`

**Comment by egekorkan** [comment]
In principle, I agree with the different semantics of these different operations. The one issue I have is that we will have way too many operations and it will be difficult for readers to keep track of them.

**Comment by lu-zero** [comment]
https://github.com/w3c/wot-thing-description/issues/1692 is the original discussion about it.

**Comment by benfrancis** [comment]
Thanks, closing as duplicate of #1692.
