### ISSUE TITLE
2019 urls in the context file

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1798]
When one opens the current context file (https://www.w3.org/2022/wot/td/v1.1), the links in there contain 2019 . Is this a temporary problem and will be fixed with the REC publication or is there an actual bug?

**Comment by JKRhb** [comment]
Interestingly, at the same time, https://www.w3.org/2019/wot/td points to the latest version of the TD 1.1 ontology. Is this intentional (since TD 1.1 is backward compatible and should contain all the original terms) or should the original ontology TD 1.0 state be restored here?

**Comment by egekorkan** [comment]
Call of 26.04: This is normal behavior. The ontologies will not change in the 1.1, only the context file will get updated. #1807 identified the actual problem to solve here.
