### ISSUE TITLE
TM namespace not active yet

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#1807]
the TD spec mentions the TM namespace behind https://www.w3.org/2022/wot/tm#
 
it seems not active yet

**Comment by egekorkan** [comment]
The file that should be behind this URL is currently missing. We need to indicate where the redirection needs to happen and explain content negotiation requirements.

**Comment by egekorkan** [comment]
It seems that the TM HTML is empty: https://github.com/w3c/wot-thing-description/blob/main/ontology/tm.html @sebastiankb is there something missing?

**Comment by danielpeintner** [comment]
Note: we need to re-check the tooling. It seems the [TTL](https://github.com/w3c/wot-thing-description/blob/main/ontology/tm.ttl) file is also not correct.

**Comment by egekorkan** [comment]
https://github.com/w3c/wot-resources/pull/20 has been merged to document the settings needed. This issue will be closed once the redirection settings are updated.

**Comment by egekorkan** [comment]
@ashimura has adjusted the redirection settings, closing :)
