### ISSUE TITLE
Usage of "scopes"

### ISSUE THREAD

**Issue by vcharpenay** [w3c/wot-thing-description#181]
The field `scopes` is used in several places in the TD model (`OAuth2SecurityScheme`, `InteractionPattern`, `Form`). It is however not obvious to understand what this field means in these different contexts.

@mmccool, is its usage documented somewhere?

**Comment by mmccool** [comment]
I will expand the description.   It's an OAuth thing.

**Comment by mmccool** [comment]
Expanded descriptions for use of scopes have been added.
