### ISSUE TITLE
TD model figure shows wrong cardinalities when serialization has default values

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#184]
Please find below my findings when reading through the TD draft document. The order of my points is document order and my comments are mostly about minor typos/suggestions/improvements.

## Editorial note in the very beginning
* Editorial note points to the generic https://www.w3.org/TR/wot-thing-description/. I am not exactly sure about the second part of the editorial note but I believe the idea is to point to the stable 
https://www.w3.org/TR/2018/WD-wot-thing-description-20180405/ url.

## 1. Introduction
* "That means if these vocabulary terms not explicit used in a Thing Description instance" 
   -->
  "That means if these vocabulary terms are not explicitly used in a Thing Description instance" 

* "the Thing Description instance can be simple transformed"
  -->
  "the Thing Description instance can be simply transformed"

##  5.1 Overview
*  "Please note that the figures reflects the"
   -->
   "Please note that the figures reflect the"

* General question comment about core model / Figure 1
  writable/observable in Property and mediaType in Form for exampla have cardinality 0..1
  I understand why it is optional but I also know that in the end (due to default assumptions) it must be 1. Not sure how this can be shown though...

* Figure 1 uses "anyURI" while Figure 3 uses "Url"

* Figure 2 about schema model uses explicit type ranges
  e.g., unsigendInt, why not unsignedLong or unlimited nonNegativeInteger

## 5.4 Security Vocabulary Definition
* Header "OAuthSecurityScheme" should be rather "OAuth2SecurityScheme" given that it only talks about OAuth2

## 6.1.3 actions
has 2 statements "The forms field MUST NOT be serialized as a JSON object." and "The type of the field forms MUST  be serialized as a JSON array."
I think the latter is sufficient.

##  6.1.5 forms
* "each forms MUST be contain the vocabulary mediaType" 
   -->
  "each forms (array) entry MUST be contain the vocabulary mediaType"

## 6.1.7 security
* Example 15 has an unexpected intendation for "security" 

## C. Acknowledgements
* "This document contains a significant contribution from Web of Things members: ..."
  I think there we need to fill in content or remove the statement

##  General comment
* I can find "e.g.," and also "e.g." without the comma in the document

**Comment by sebastiankb** [comment]
- [x]  I am not exactly sure about the second part of the editorial note but I believe the idea is to point to the stable
https://www.w3.org/TR/2018/WD-wot-thing-description-20180405/ url.

- [x] "That means if these vocabulary terms are not explicitly used in a Thing Description instance" --> done by @mmccool 

- [x] "the Thing Description instance can be simple transformed" --> done by @mmccool 

- [x] "Please note that the figures reflect the"

- [x] Figure 1 uses "anyURI" while Figure 3 uses "Url" --> done by @mmccool 

- [x] Header "OAuthSecurityScheme" should be rather "OAuth2SecurityScheme" given that it only talks about OAuth2 --> done by @mmccool 

- [x] has 2 statements "The forms field MUST NOT be serialized as a JSON object." and "The type of the field forms MUST be serialized as a JSON array."
I think the latter is sufficient.

- [x] "each forms (array) entry MUST be contain the vocabulary mediaType"

- [x1] Example 15 has an unexpected intendation for "security" --> done by @mmccool 

- [x] I can find "e.g.," and also "e.g." without the comma in the document

**Comment by sebastiankb** [comment]
@danielpeintner 
> writable/observable in Property and mediaType in Form for exampla have cardinality 0..1
I understand why it is optional but I also know that in the end (due to default assumptions) it must be 1. Not sure how this can be shown though...

Good question. The non-usage of the "default" terms is a kind of compactness optimization. Maybe we should check other specs that contain a similar usage of such an approach and how is this defined there. Any ideas?

**Comment by mkovatsc** [comment]
Since the figures depict the model, it should be 1.
In the serialization has the default values, so also making it 1 even when not given there.

**Comment by mkovatsc** [comment]
Similar issue with security, as Forms always must have at least one security scheme -- they trickle down from InteractionPattern or Thing.

For now we leave this more complicated case and only fix straight-forward cases.

**Comment by sebastiankb** [comment]
ok, I will discuss this in the next TD web meeting

**Comment by takuki** [comment]
Information Model section as I understand is about relationship between information, not about serialization. In that case, I think that "writable" field should be marked as mandatory. It is that it is optional in serialization, which is discussed in another section (i.e. Thing Description Serialization).

**Comment by sebastiankb** [comment]
@takuki , @danielpeintner 
compiled in TD spec. Please review and close the issue.

**Comment by takuki** [comment]
Thank you, @sebastiankb . The updated figures look great.

**Comment by sebastiankb** [comment]
thanks
