### ISSUE TITLE
Publish `base` as html rendered representation?

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#1860]
*** **Please note the following comment has no impact on the TD specification itself** ***
 
Terms have a unique IRI. E.g., `observable` has the IRI https://www.w3.org/2019/wot/td#isObservable
When you click on this link, the browser shows the specific meaning of this term.

This seems to work well but it seems there is no IRI html representation for the term `base`. Based on the [TD ontology ](https://github.com/w3c/wot-thing-description/blob/c1f925b4b1b3318ed0b6c51d661460127b4c2ea2/ontology/td.ttl#L37) it should be https://www.w3.org/2019/wot/td#baseURI

It seems just a mistake and we should check the render script why the [html version](https://github.com/w3c/wot-thing-description/blob/main/ontology/td.html) `base` term is not onboard.

**Comment by egekorkan** [comment]
This is fixed via #1881
