### ISSUE TITLE
Resolving Editor's Notes before publication

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1869]
Under https://w3c.github.io/wot-thing-description/#media-type-section we have a lot of editor's notes that really need to be solved before REC. @sebastiankb can you have a look in the TD call tomorrow?

**Comment by sebastiankb** [comment]
I think, many of them are from @mmccool . My suggestion is to remove all comments to be aligned with the TD 1.0 version https://www.w3.org/TR/wot-thing-description10/#media-type-section
