### ISSUE TITLE
JSON Schema for TD Instance Validation too permissive

### ISSUE THREAD

**Issue by ToruKawaguchi** [w3c/wot-thing-description#187]
## 5.2 Core Vocabulary Definition

- InteractionPattern
	- Explanation is missing on "key" such as "on" in EXAMPLE 7

	  "properties": {
	  	"on": {
	  		"label": "On/Off",
	  		"type": "boolean"
	  	},

	  (same for ObjectSchema)

- Property
	- No explanation that Property inherits DataSchema, so fields such as type is not defined. 

- Event
	- There is a description that "The Event class has the same fields as the class Property.", but Event does not have observable and writable.
	- No explanation that Property inherits DataSchema, so fields such as type is not defined.

# A. JSON Schema for TD Instance Validation

- "properties" has "type": "object", so shouldn't this have "properties" instead of "items" ? (same for actions, events, definitions/properties, actions and events)

- "properties" and "events" does not include "definitions/data", so looks to have no way to describe actual data value.

- "definitions/dataSchema" is defined but not used

**Comment by ToruKawaguchi** [comment]
> ## 5.2 Core Vocabulary Definition
> 
> - InteractionPattern
> 	- Explanation is missing on "key" such as "on" in EXAMPLE 7
> 
> 	  "properties": {
> 	  	"on": {
> 	  		"label": "On/Off",
> 	  		"type": "boolean"
> 	  	},
> 
> 	  (same for ObjectSchema)
> 
> - Property
> 	- No explanation that Property inherits DataSchema, so fields such as type is not defined. 
> 
> - Event
> 	- There is a description that "The Event class has the same fields as the class Property.", but Event does not have observable and writable.
> 	- No explanation that Property inherits DataSchema, so fields such as type is not defined.

Above was covered by https://github.com/w3c/wot-thing-description/commit/acae989746494fe48e014efbb237c8e89e5a6afa. Thanks, @sebastiankb !

**Comment by mkovatsc** [comment]
We discussed this in the call on 8 Aug 2018 and concluded to leave the schema as is, but put an Editors' Note that this schema is too permissive.

We will fix it in the next release (instead of rushing it now).

**Comment by takuki** [comment]
Added an editor's note. Please see this [PR](https://github.com/w3c/wot-thing-description/pull/208).

**Comment by egekorkan** [comment]
This issue can be closed now since the editor's note clarifies it
