### ISSUE TITLE
Clarifying "Future updates to this Recommendation" section

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1894]
Coming from #1890:

Doing <p>Future updates to this Recommendation may incorporate <a href="https://www.w3.org/2023/Process-20230612/#allow-new-features">new features</a>.</p> implies doing an amendment to the specification to add a feature. @ashimura will take a look at the meaning of this sentence a bit more. A small PR might be needed based on the result of the analysis

**Comment by mmccool** [comment]
For the record: this was resolved by including the requested line in the REC version of the TD 1.1 document.
