### ISSUE TITLE
Best practices for standardising Linked Data Vocabularies

### ISSUE THREAD

**Issue by draggett** [w3c/wot-thing-description#19]
This issue is to discuss best practices for standardising Linked Data vocabularies and how we should approach this for the Linked Data vocabulary for interaction models for thing descriptions.

**Comment by draggett** [comment]
W3C has produced several W3C Recommendations for Linked Data Vocabularies, e.g.

* [The Organization Ontology](https://www.w3.org/TR/vocab-org/)
* [RDF Data Cube Vocabulary](https://www.w3.org/TR/vocab-data-cube/)
* [Data Catalog Vocabulary (DCAT)](https://www.w3.org/TR/vocab-dcat/)
* [PROV-O: The PROV Ontology](https://www.w3.org/TR/prov-o/)

I strongly suggest that we look at these specifications and identify best practices for use in structuring the thing description Linked Data Vocabulary.

One idea is to follow the [DCAT Recommendation](https://www.w3.org/TR/vocab-dcat/) which would give us the following structure:

1. A introduction giving the background and working assumptions.
2. Namespaces
3. Conformance
4. Vocabulary Overview
5. Vocabulary specification
6. Serialisation with JSON-LD
A. Acknowledgements
B. Change history
C. References

The introduction would provide the context and working assumptions. We could include a diagram illustrating the ontology following the precedents of the previous W3C Linked Data vocabulary Recommendations.

We would include a normative reference to the ontology on the w3.org site along with the default context for use with JSON-LD, but we probably don't need to include them explicitly in the specification itself.  We could add a normative reference to a SHACL shapes file, but I don’t see that as a priority and would prefer to deal with that later given our lack of experience with the new W3C SHACL Recommendation.

The DCAT specification defines each RDF property as a table with the range and domain for properties acting as predicates.  Maria feels that the table format is sub-optimal and could be replaced with prose text.  Maria should also be able to provide simpler diagrams that describe specific vocabulary terms.

The examples in section 4 would use Turtle as a neutral format, and one used heavily in previous W3C Recommendations. We would have a longer JSON-LD example in section 6. The plain JSON serialisation would be covered in a separate specification that I am hoping Mozilla will help us with.

I believe that to appeal to a broad audience, we should also publish a primer with a number of example use cases and links to open source for trying them out.

Note that I recommend we cover the vocabulary for protocol bindings in a separate Recommendation track document as we can then advance the bindings at their own pace without slowing the progress of the interaction model vocabulary along the REC track.

**Comment by vcharpenay** [comment]
_(copied from the WG member mailing-list)_

I wrote a small Node.js script to generate parts of the TD deliverable (more precisely, **5. Vocabulary specification**).

See https://github.com/vcharpenay/wot-thing-description.

This scripts loads the RDF vocabulary in a temporary store, runs a SPARQL queries that extracts the terms and renders `index.html` accordingly. It uses Dust.js, an HTML template engine maintained by LinkedIn.

The way I see it is that editors and contributors write in the file `index.html.template`, which is plain HTML for the most part, and render `index.html` by running `node render.js` when finished. Alternatively, we could automate the rendering step with Travis CI.

**Comment by vcharpenay** [comment]
OWL documentation generation tools, such as [Widoco](https://github.com/dgarijo/widoco), shoud also be considered.

**Comment by sebastiankb** [comment]
first public draft was submitted yesterday which took most of the advice here into account. We can close this issue.
