### ISSUE TITLE
TM Schema regex error

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1906]
In our TM Schema, we have a regex at https://github.com/w3c/wot-thing-description/blob/main/validation/tm-json-schema-validation.json#L1852 . This is sadly failing in golang and rust and subsequently the TM Schema cannot be used by many golang based JSON Schema validators (not sure about Rust yet). An alternative is available at https://regex101.com/r/qSBNcw/1 but that fails for Rust. Ideally we should fix this asap.

Note: `/` is not reserved character for regex but we are escaping it but I do not remember why

**Comment by egekorkan** [comment]
Basically, the backreference (`\1`) is the issue and it is not recommended by https://json-schema.org/understanding-json-schema/reference/regular_expressions as well. They say 

> complete syntax is not widely supported, therefore it is recommended that you stick to the subset of that syntax described below

**Comment by lu-zero** [comment]
The json schema validators I know are;
- https://github.com/s-panferov/valico, used by webthings.
- https://github.com/Stranger6667/jsonschema-rs, that should be nicer.

Which one are you using?

**Comment by egekorkan** [comment]
I am using https://regex101.com/ so not a JSON Schema validator. It seems that JSON Schema libraries offload regex to standard libraries of the language

**Comment by lu-zero** [comment]
rust does not have regex as part of the standard library.

**Comment by lu-zero** [comment]
Both `valico` and `jsonschema-rs` rely on `fancy-regex` to compile the regex and that crate supports pretty much anything the jsonschema specification may allow and some more.

**Comment by lu-zero** [comment]
From a quick look also a nice jsonschema impl in golang seems to be aware of their shortcoming: https://github.com/qri-io/jsonschema/issues/119. So either we make aware our downstreams that we expect that their jsonschema validators support regex-with-backreferences or we have to make sure we do not use those features.

**Comment by egekorkan** [comment]
Call of 25.10: 
- @lu-zero : The golang libraries that do not support the syntax should fix themselves, we should not be asked to change or fix implementations. +1 from Mahda
- @relu91 : We should document the corner case. It would be good to have "works with languages below" table with some notes in the readme. We should make it more correct
- @egekorkan : We accept too much at the moment as well, e.g. `/props/temp` is accepted

Decision: Make it more correct. Two regexes that can be combined:
1. https://regex101.com/r/Ovc1ht/1
2. https://regex101.com/r/n2HWgd/1

Also relevant for https://github.com/w3c/wot-thing-description/issues/1749
