### ISSUE TITLE
Unique Names for Properties, Events, and Actions

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#191]
Due to a limitation of JSON-LD, apparently all object "tags" document-wide need to be unique since they all get expressed as @id values in a single namespace.

What this means for TDs is that the names of properties, actions, and events have to be unique as a set: not only can you not duplicate a property name, you can't have (for example) an action and a property with the same name.   

This needs to be stated explicitly as a normative assertion.

BTW, once we add security definitions the same issue will occur, but will be a little bit weirder: it will not be possible to use the same name for a property (or action, or event) and a security definition, either.  Frankly, I'm hoping we can find some way to fix this, but for now, we should at least put in the normative assertion to make this restriction clear.

**Comment by sebastiankb** [comment]
issue solved by the PR #221
