### ISSUE TITLE
Documenting Ways to Further Automate the Toolchain

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#1924]
As initially discussed in TPAC with the breakout hosted by @pchampin and @egekorkan, there are tools that can help us automate some parts of the spec generation and avoid manual steps that are error prone and require managing duplicate information. @mahdanoura has done further analysis and found some other tools. We should document the current state of those tools to see which one is best suited for the various parts of the tooling we have.

**Comment by mahdanoura** [comment]
I am currently analyzing the following potential tools: 
1. Ontotext SOML: The semantic Objects Modeling Language (SOML), a yaml-based model to SHACL and GraphQL
2.  LinkML
3. TreeLDR
4. Eclipse Semantic Modeling Framework
5. schema_salad
6.  A.ML (https://a.ml/)

**Comment by mahdanoura** [comment]
There will be a separate markdown file that analyzes the existing tools in a PR later on.
