### ISSUE TITLE
RFC 8259 (JSON) does not define "keys", but names

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#194]
RFC 8259 talks about "name/value pairs (or members)", not "keys" as used in the TD spec. Should be fixed in the WD coming end of 2018 (not the upcoming Bundung release).

See https://tools.ietf.org/html/rfc8259#section-4

**Comment by mkovatsc** [comment]
Renaming "field" within TD spec to "member" would align further, as "member" has the meaning we want to express with "field".

**Comment by mlagally** [comment]
I agree that the current terminology needs some polishing. We also use "vocabulary term" very frequently,
which also should be renamed. "member" or "key" are both fine for me.

**Comment by takuki** [comment]
@sebastiankb , I reviewed the changes, and the name changes look all nice.

**Comment by sebastiankb** [comment]
@takuki thanks
