### ISSUE TITLE
Default value for mediaType

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#196]
from @mkovatsc pr #195 

> As default values are primarily reducing the size of TDs and IoT systems using
  JSON usually have less resource constraints, a more sensible
  default for <code>mediaType</code> might be "application/cbor".

So far, `application/json` is used as default in the TD specification. Please use this thread for discussion.

**Comment by takuki** [comment]
Is it about mediaType of forms? Or is it about section 6.2 Media Type?

**Comment by danielpeintner** [comment]
My personal feeling is that there seems to be a a common agreement on JSON. Besides that there were several discussions around a more efficient representation (e.g., CBOR, EXI, ...)

Having said that, these _discussions_ were never really taken serious nor leaded to actually pick one candidate.

**Comment by sebastiankb** [comment]
To avoid misunderstanding, its about the the default value of the mediaType within the form container and not about Thing Description encoding:

```JSON
...
    "properties": {
        "status": {
            "type": "string",
            "forms": [{
                "href": "https://mylamp.example.com/status",
                "mediaType": "application/json" 
            }]
        }
    }

```

**Comment by takuki** [comment]
The original argument was that if the default value for mediaType in form was "CBOR", it would have benefited resource-constrained devices by allowing to omit "mediaType": "application/cbor" in TD. Is my understanding correct?

**Comment by mlagally** [comment]
How do we handle the situation, if a property has different protocol bindings, as in the following example from the protocol binding spec? What assumption do we make about the default media type for other protocols, such as CoAP and MQTT?

     "form": [
        {
          "href": "/example/light/currentswitch",
          "mediaType": "application/json",
          "rel": ["readProperty"],
          "http:methodName": "GET"
        },
        {
          "href": "/example/light/currentswitch",
          "mediaType": "application/json",
          "rel": ["writeProperty"],
          "http:methodName": "POST"
        },
        {
          "href": "mqtt://example.com/example/light/currentswitch",
          "rel": ["observeProperty"],
          "mqtt:commandCode": 8
        }
      ]

**Comment by takuki** [comment]
In TD TF meeting, the attendees agreed to leave the default as JSON, and create a new issue to address the issue by another way. There will be a new issue created for that.
