### ISSUE TITLE
Content negotiation for TD namespace

### ISSUE THREAD

**Issue by draggett** [w3c/wot-thing-description#20]
This is to document the choices we're examining for using content negotiation for the TD namespace.

Victor proposes that we support the following on GET requests to /ns/td

* Accept: text/turtle --> /ns/td/td.ttl for the OWL ontology
* Accept: application/ld+json --> /ns/td/w3c-wot-td-context.jsonld for the JSON-LD default context

* Otherwise  return the /ns/td/index.html file that describes the purpose and status of the namespace

[Cool URIs for the Semantic Web](https://www.w3.org/TR/cooluris/#r303uri) states:

> When the RDF and HTML representations of the resource differ substantially, the previous setup should not be used. They are not two versions of the same document, but different documents altogether. Again, the Web server would be configured to answer requests with a 303 status code and a Location HTTP header that provides the URL of a document that represents the resource.

This seems to be the case above, given that the Turtle version is the OWL ontology, the JSON-LD version is the JSON-LD default context and the HTML version documents the purpose and status of the namespace, so that the three versions differ substantially in their role.

This can be implemented by the .htaccess file in the /ns directory

**Comment by sebastiankb** [comment]
@vcharpeny I think, this issue is solved now, isn't it?

**Comment by sebastiankb** [comment]
is solved
