### ISSUE TITLE
Why are default values mandatory in JSON-LD serialisation?

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#202]
According to the editor's note in section 5.1 default values are optional for a JSON serialisation but mandatory for a JSON-LD serialisation.

Why the difference?

**Comment by mlagally** [comment]
@takuki Thanks for your comment. 
If this is a normative requirement we should move it from an informative editors note to a normative section.

**Comment by sebastiankb** [comment]
issue is solved.
@mlagally This requirement is defined in the normative part in the TD. E.g., see description for [forms](https://w3c.github.io/wot-thing-description/#form-serialization-json)
