### ISSUE TITLE
Fix formatting of autogenerated section 5

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#206]
The autogenerated section 5 in the TD spec currently consists of a few very long lines.

It is impossible to review and comment on them in this form, so they need to be reformatted to use regular line lengths.

**Comment by sebastiankb** [comment]
Typically, editors support a document beautify/format function. E.g., in VS Code simple make a right click and select document format. 

Can we close this issue?

**Comment by sebastiankb** [comment]
I think, it is ok to close this issue.
