### ISSUE TITLE
Namespaces: clarify if HTTP namespace is normative

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#210]
>The namespace for the W3C TD vocabulary as defined in this document is http://www.w3.org/ns/td. Using content negotiation, this namespace serves either the TD ontology file (Turtle) or the TD context file (JSON-LD). 
The suggested  prefix for the TD namespace is td. 

is the prefix TD normative? If yes the language should use *MUST*

> TD will reuse existing vocabulary definitions such as for http from the http://www.w3.org/2011/http# namespace. In that case the prefix http is used. However, there are prefixes such as coap and mqtt which have no namespace yet. Currently there are efforts to have such namespace representations which will be referenced in the TD specification in the future. In the meantime, the [[!WOT-PROTOCOL-BINDING]] provides the list of terms that can be used to specify the protocol metadata in the Thing Description

This section is in an editors note, but the http namespace appears to be normative. Please clarify and add a normative reference.

**Comment by sebastiankb** [comment]
>is the prefix TD normative? If yes the language should use MUST
I think, this is not possible. Prefixes are like variables names in a programming languages. Important is that the TD prefix is  associated to the normative TD namespace.

>This section is in an editors note, but the http namespace appears to be normative. Please clarify and add a normative reference.
We are still waiting for some progress in https://github.com/w3c/wot-thing-description/issues/167 .
This will be discussed in Lyon.

**Comment by sebastiankb** [comment]
Since the TD should be protocol independent the http namespace can be integrated when necessary. The TD spec shows in some examples how this can work.

Please review.
