### ISSUE TITLE
Core Vocabulary Definition - fix schema links

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#211]
The references for the types (anyURI etc.) don't point to a proper type definition, rather to a generic XML schema page.

**Comment by mmccool** [comment]
I'm assuming Kaz will fix this...

**Comment by vcharpenay** [comment]
I already posted this comment in #205 but I repost it here, as it is more relevant in this thread:

These links do, in fact, point to their machine-readable definition (the XML schema namespace). It is then, in theory, the responsibility of the namespace holders to redirect to the adequate human-readable documentation. Here, they chose to expose a plain HTML documentation with links to the XML schema normative specifications. To me, this is a proper definition.

**Comment by takuki** [comment]
In 9/6 telecon, it was suggested to use direct links to datatype definitions in XML Schema 1.1 (e.g. anyURI, string, etc.) for Bundang version of TD release.
For example, "http://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/#anyURI" for anyURI.

**Comment by mkovatsc** [comment]
It might be worth to add some text that explains the columns of the class tables we have in the spec. In particular what does the "Type" mean, why is it suddenly XML Schema, although the TD does not use XML Schema (yes, it is because the Semantic Web decided to use it and we have it thus in our ontology...).

**Comment by sebastiankb** [comment]
all simple types in the TD model are pointed to the basic XML Schema type definitions. I think we can close this issue here.
