### ISSUE TITLE
vendor-specific TD extensions

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#212]
The spec currently is currently silent about vendor specific additional keys for Metadata, property fields, actions and events. It should permit extensions with additional keywords, as long as these are unique.

**Comment by mkovatsc** [comment]
This is indeed only indirectly mentioned throught the `@context` mechanism. It would be helpful to be more eplicit about additional vocabulary, but also other mechanism such as the designated Action and Event Descriptions.

**Comment by sebastiankb** [comment]
based on the TD web meeting Nov 30. 2018 there will be a _semantic_ chapter that will explain the opportunities in the TD regarding semantics and extensions

**Comment by sebastiankb** [comment]
There is now a chapter[ context extension ](https://w3c.github.io/wot-thing-description/#content-extension-section) that explains the opportunities to integrate external (e.g., vendor-specific) terms.

Please review this chapter and solve this issue here

**Comment by mlagally** [comment]
Comments on 2 paragraphs from the new chapter 
https://w3c.github.io/wot-thing-description/#content-extension-section  below.

The language in the new chapter does not define any guarantee on what it means to include another context in a TD. 
Since it is just _recommended_ (and not mandatory) to link a context, it is up to the TD author to do whatever he likes. Formal verification is not possible.  

> When adding additional vocabulary to a Thing Description instance, it is recommended that these vocabulary be linked to a namespace context that is within the JSON name @context container is specified.

The next section should explain how class definitions have to be described. Referencing RDF Schema or OWL gives context for autogenerated namespaces. However we should also explain, how a class definition / context file needs to be (manually) written, to declare classes that can be used in an @type annotation.
 
> If included namespaces are based on class definitions such as those provided by the RDF Schema or OWL, the Things Description also allows the use of @type known from JSON-LD to associate the affiliation to a class.

**Comment by sebastiankb** [comment]
>Since it is just recommended (and not mandatory) to link a context, it is up to the TD author to do whatever he likes. Formal verification is not possible.

Your proposal would be to make it mandatory? What does the others think? 

> However we should also explain, how a class definition / context file needs to be (manually) written, to declare classes that can be used in an @type annotation.

I think we don't want to reinvent the wheel of how a class is defined in the Semantic Web. I would recommend simply referring to the relevant standards.
