### ISSUE TITLE
clarify semantics of actions

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#213]
The spec should clarify the semantics of synchronous and asynchronous actions:

How can an asynchronous be monitored? How are execution failures (exceptions) communicated?

**Comment by draggett** [comment]
One example is where there is an "internal error" when executing the action. In the Arena Web Hub, this is signalled with a 5xx status code when using either HTTP or WebSockets for the protocol, and reported to clients via the Scripting API by rejecting the promise for the action along with a suitable error message.  Another example of an error is a timeout when the promise is left hanging for an excess amount of time.  In Arena, this too is signalled by rejecting the promise. 

I would advise against baking complex semantics into the TD spec as it is better handled at the application layer. The core abstract API should remain as simple as possible.  

I know that there are use cases where it is appropriate to have actions that can be cancelled, and use cases that require progress indicators. However, I consider these both to be application level requirements that can be implemented on top of the core notion of asynchronous actions with inputs and outputs.  For instance, if an action is cancellable it could output a reference to an ongoing process. Another action can then be used to cancel the process by passing the process ID.  Progress for some extended process could be signalled via a sequence of events.

@mlagally can you explain why you are asking for synchronous actions, given the web of things generally speaking involves action at a distance, making the abstract model for actions to be asynchronous/.

**Comment by draggett** [comment]
@mlagally wrote:

> WoT is defining a generic interface description language (like CORBA did many years ago) that provides an abstraction from devices via properties, actions and events. As such it needs to be flexible enough to handle operations on devices that can return immediately with a result (e.g. 200 OK in the simplest HTTP case) and operations that just return an "accepted" or "dispatched" status code. 

and

> However I think we should extend the current action definition in the TD spec with an additional "response code" and ideally a "response message", which corresponds to the status code in HTTP or a return code of a function call.

Do we really need to standardise that?   I suspect not as different contexts will involve different categories of responses. You are free to declare an action that returns an object with a numeric code together with a enum, string or JSOB object if that's what your application needs.  Some errors will be handled through the platform API, e.g. in Arena, actions return a Promise which is rejected when the server reports an internal error, there is a time out, or when the server rejects the security token passed with the request.

**Comment by draggett** [comment]
@benfrancis wrote

> Mozilla has the same use case of action requests which create a new resource that can be polled for action status or cancelled

You can model that as an action response, but then need to model how you deal with it. One idea is to model the fade process as a thing it its own right.  Another is to return an ID that you can listen for using a status event that contains the ID. A further idea is to declare another action for acting on long lasting processes. I recommend that we keep the core interaction model simple and allow applications to layer more complex interaction patterns on top, perhaps using libraries to simplify this. Otherwise we risk over complicating the Web of Things as more and more people come to us with their own interaction patterns demanding that the TD spec is updated to match.

**Comment by mlagally** [comment]
@draggett wrote:
> Do we really need to standardise that? I suspect not as different contexts will involve different categories of responses. You are free to declare an action that returns an object with a numeric code together with a enum, string or JSOB object if that's what your application needs. Some errors will be handled through the platform API, e.g. in Arena, actions return a Promise which is rejected when the server reports an internal error, there is a time out, or when the server rejects the security token passed with the request.

I guess we can get away by adding a response code and a response message to the output data schema, however this is completely up to the implementer.

**Comment by sebastiankb** [comment]
same situation as discussed here https://github.com/w3c/wot-thing-description/issues/303

This topic can be covered in a successor version of the TD.

**Comment by sebastiankb** [comment]
we will discuss this in today's TD call. Also see #890

**Comment by sebastiankb** [comment]
close this issue since TD now has `synchronous` in the action definition which can be used to signalize synchronous and asynchronous based actions
