### ISSUE TITLE
Interaction pattern - clarify unique name

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#214]
>InteractionPattern 
> <snip>
>Each instance of a Property , Action , and Event class has a (unique) name. See Section Representation Format for more details about JSON-LD 1.1 identifiers. 

Should be reworded to:

Each instance of a Property , Action , and Event class **MUST have** a unique name. See Section Representation Format for more details about JSON-LD 1.1 identifiers. 

It should also be clarified whether the same name can be used for actions and properties and events.

**Comment by mmccool** [comment]
See [PR221](https://github.com/w3c/wot-thing-description/pull/221).  I also added "globally" in front of "unique", and updated the normative assertions extraction.

**Comment by sebastiankb** [comment]
non active issue anymore. PR #221 was merged.
