### ISSUE TITLE
properties, actions and events need name **and** label field names

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#216]
There was a discussion about name and label some time ago, but apparently we need both:

The TD spec describes the label keyword as:
> Provides a label (e.g., display a text for UI representation) of the interaction pattern.

There  are no further further requirements, so a label could be something like "This is a long label". It is not a means to identify an interaction.

There's also this normative language:
> Each instance of a Property , Action , and Event class has a (unique) name. See Section Representation Format for more details about JSON-LD 1.1 identifiers. 

The tables in section 5 for properties, actions and events should include a name.

**Comment by benfrancis** [comment]
> Each instance of a Property , Action , and Event class has a (unique) name.

Does this date back to when properties were uniquely identified by a name field rather than an object key?

There's no need for a name property in addition to the key, unless "name" replaces "label".

See also https://github.com/w3c/wot-thing-description/issues/156 on name vs. label vs. title.

**Comment by mlagally** [comment]
The name is an entity in the ontology that allows to identify the property, action or event instance.
Label is a human readable text, that can be put on a button in a UI.

I agree, that the name will be mapped to an object key during the serialisation (JSON/JSON-LD), but this mapping is currently not specified, so there's an inconsistency in the current draft.
IMO the ontology needs to add a field for a unique identifier.

**Comment by takuki** [comment]
During 9/6 TD telecon, we agreed we should discuss this issue in TPAC 2018 at Lyon.

**Comment by zolkis** [comment]
Currently we don't seem to have a `name` property for [InteractionPattern](https://w3c.github.io/wot-thing-description/#interactionpattern). We do specify a `name` when adding the interaction, but currently it is handled as an object key as Ben mentioned and it's not saved in the objects. Do you mean to add this (as redundant information)?

**Comment by sebastiankb** [comment]
In the last TD web meeting we decided to have a more concrete explanation in the TD spec about the _name_ assignment of the interaction patterns Property, Action, and Event. In the same time it should be also make clear that the _name_ assignment should be also unique across all Property, Action, and Event definitions within a TD instance. 
Example: it should be not possible to define a property with the name "on" and an action with the name "on" at the same time.
TD Editors will decide to integrate this information in next iteration in the table of section 5.2.2 or spend an extra section about this.

**Comment by sebastiankb** [comment]
@zolkis There will be not an additional `name ` term. The idea is to provide more information to the reader how the _name_ of the interaction patterns are assigned.

**Comment by mkovatsc** [comment]
Note that this is related to https://github.com/w3c/wot-thing-description/issues/156

Each interaction has an identifier, as the object key maps to the `@id`, the identifier of the node describing the interaction.

We still could not decide how to call the term for the label / title / caption / name / ... which is for display in UIs and similar use cases.
