### ISSUE TITLE
Clarify "scope" field semantics

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#217]
The description of the field "scopes" is a bit vague:

> forms in order to identify what resources a client may access and how. 

We need an example or more descriptive text to understand this paragraph.

**Comment by mmccool** [comment]
Scopes are "explained" in the text but I agree an example is really needed to make the usage of this clear.  I don't have time to do it for this revision, but I intend to make OAuth a priority in the online plugfest and will work up (and test...) an example then, and then create a PR to add a version of the example to the Thing Description document.

**Comment by mmccool** [comment]
I added an example in PR https://github.com/w3c/wot-thing-description/pull/269.   For ease of review, I pull it out below:

  <p>As another more complex example, OAuth2 makes use of scopes.
  These are identifiers that
  may appear in tokens and must match with corresponding identifiers in a resource to allow
  access to that resource.
  For example, in the following, the "status" property can be
  read by users using bearer tokens containing the scope "regular" and the "configure" action can only be
  used when the interaction is invoked with a token containing the "special" scope.
  Scopes are not identical to roles but are often associated with them;
  for example, perhaps only those in an administrative role can perform "special" interactions.
  Tokens can have more than one scope.
  In this example, an administrator would
  probably be issued tokens with both the "regular" and "special" scopes while regular
  users would only be issued tokens with the "regular" scope.
  </p>
<pre class="example">
    ...
    "security": [{
        "scheme": "oauth2",
        ...
        "scopes": ["regular","special"]
    }],
    "properties": {
        "status": {
            ...
            "forms": [
                {
                    "href": "https://scopes.example.com/status",
                    "contentType": "application/json",
                    "scopes": ["regular"]
                }
            ]
        }
    },
    "action": {
        "configure": {
            ...
            "forms": [
                {
                    "href": "https://scopes.example.com/configure",
                    "contentType": "application/json",
                    "scopes": ["special"]
                }
            ]
        }
    },
    ...
</pre>

**Comment by takuki** [comment]
Do we need scopes fields both in "security" and "forms"?  It appears the scope setting in "forms" provides enough information for WoT client to interact with WoT server. Does the client need to know the full set of available scopes value?

**Comment by mlagally** [comment]
As discussed in the call on Nov 5th, the term "special" is a bit vague. Please consider using "extended" or "full".

**Comment by sebastiankb** [comment]
In TD spec, I see now some examples with `scopes` usage. Since there is no discussion here anymore, I will close this issue.
