### ISSUE TITLE
Clarify type value of "null" for properties

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#222]
Properties also include a DataSchema with a type key.

The type key can be null, what does that mean?

**Comment by handrews** [comment]
I believe this is the `type` inherited from JSON Schema, in which case `"null"` is a valid value (note that this is a _quoted string_) which means that the property can take on the value `null` (note that this is the _literal value_ `null`).

**Comment by mlagally** [comment]
could be addressed in a comment

**Comment by takuki** [comment]
During the WoT main call on 9/5, Matthias suggested to add NullSchema (or similar) as a subtype of DataSchema, and attached a description of what the value null is for.

**Comment by handrews** [comment]
@takuki perhaps I should start a separate issue or conversation for this, but is there a reason for segregating the schemas by type?  That removes a lot of JSON Schema functionality (although does simplify things by forbidding some complex cases which I'm guessing is why it was done?)

**Comment by sebastiankb** [comment]
fyi

I just checked OpenAPI about the `null ` usage and there, `null ` doesn't seems to be possible for definition:

https://swagger.io/docs/specification/data-models/data-types/#null

**Comment by sebastiankb** [comment]
as decided in the last TD session, we want to be compliant with the JSON scheme. Thus, "null" will be also specified in the TD.

**Comment by sebastiankb** [comment]
please review

**Comment by mlagally** [comment]
I'm still not sure, that a type of null for a data schema makes sense at all.
What would be the purpose?

**Comment by mlagally** [comment]
As discussed in the call on Dec 21st.

In the section  https://w3c.github.io/wot-thing-description/#dataschema 5.3.1 DataSchema
DataSchema has a type and it can be a null.

It is typically used as part of OneOf, where it is used to indicate, that a data schema can also be null. This comes from JSON schema typing.
We need an (Implementation/Editors/  note to make this fact known to implementers.

**Comment by sebastiankb** [comment]
I extended the description of null with a sample usage.

Please review.

**Comment by takuki** [comment]
@sebastiankb , I found 2 typos in NullSchema section description, and fixed in #373 .

**Comment by sebastiankb** [comment]
thanks
