### ISSUE TITLE
DataSchema for non-JSON / non-structured data

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#223]
What if a Property has an `image/jpeg` representation or some exotic format that can also have a schema to describe it, but not JSON Schema?

We basically have to decide whether

1) `DataSchema` becomes a class that can also hold other schemas (`type` is already optional)

or 

2) Create a new class for each new schema, which is then implemented by Thing Property instances (instead of `DataSchema`)

**Comment by handrews** [comment]
You could set a media type for the schema and default it to `application/schema+json; schema=<your-preferred-meta-schema>` (actually, that reminds me, I need to add the "schema" media type parameter to `application/schema+json`, I forgot to add that in the last draft).

**Comment by sebastiankb** [comment]
In the case of your jpeg sample you could define the Property in the following way:

```JSON
{
"..." : "...",
    "properties": {
        "LampImage": {
            "forms": [{
                "href": "https://mylamp.example.com/LampImage",
                "mediaType": "image/jpeg"
            }]
        },
"..." : "..."
}
```

The TD `type ` term is not mandatory and can be skipped. 

Options for alternative schemas was already considered at the very beginning. One approach was to define JSON Schema as default and provide mappings to other schemas. In the [first draft of the TD](https://www.w3.org/TR/2017/WD-wot-thing-description-20170914/#mapping-to-xml-schema) we did this for XML Schema. Alternative ideas was to provide a link to an existing schema. Web linking would be a good candidate for this. The interest on this topic seemed not very high and that was the reason why we removed this section in the successor TD drafts.

**Comment by mkovatsc** [comment]
This is not about just skipping the DataSchema for non-JSON media types. It is about how the TD Information Model can include other schemas in the future. This issue was raised recently again.

Yet with the options that I already discussed with @vcharpenay , I am happy with leaving it at this stage.
