### ISSUE TITLE
Duplicated description of `required` field in 5.3.3 ObjectSchema

### ISSUE THREAD

**Issue by verymuch** [w3c/wot-thing-description#232]
The description of `required` field in [ObjectSchema(5.3.3 ) ](https://w3c.github.io/wot-thing-description/#objectschema) is duplicated.

**Comment by takuki** [comment]
It appears that [json-schema.ttl](https://github.com/w3c/wot-thing-description/blob/52908f35563a5c9d62fa6a9cd294d32547be2459/ontology/json-schema.ttl) contains duplicate definitions for "required" field.
One is within "Object Properties" section, and the other is within "Data properties" section.

Do we need to keep both?

#################################################################
#    Object Properties
#################################################################

###  http://www.w3.org/ns/json-schema#required

<http://www.w3.org/ns/json-schema#required> rdf:type owl:ObjectProperty ;
                                            
                                            rdfs:label "required" ;
                                            
                                            rdfs:comment "Defines which members of an object type are mandatory."@en .

#################################################################
#    Data properties
#################################################################

###  http://www.w3.org/ns/json-schema#required

<http://www.w3.org/ns/json-schema#required> rdf:type owl:DatatypeProperty ;
                                            
                                            rdfs:label "required" ;
                                            
                                            rdfs:comment "Defines which members of the object type are mandatory."@en ;
                                            
                                            rdfs:range xsd:string .

**Comment by vcharpenay** [comment]
Thanks for reporting this bug! There should be only one declaration of `jsonschema:required` (as a datatype property). See my PR

**Comment by takuki** [comment]
Since this is a obvious error in description, yet is esthetically

**Comment by mkovatsc** [comment]
Fixed, so should be closed.
