### ISSUE TITLE
Same description of `identity` field in CertSecurityScheme/PublicSecurityScheme/PSKSecurityScheme

### ISSUE THREAD

**Issue by verymuch** [w3c/wot-thing-description#233]
The descriptions of `identity` field in 5.4.4 CertSecurityScheme/5.4.8 PublicSecurityScheme, which is `'Pre-shared key identity.'`, are same with that in PSKSecurityScheme.

1. The description in CertSecurityScheme perhaps should be `'Certificate-base asymmetric key.'`
2. The description in PublicSecurityScheme perhaps should be `'Raw public key asymmetric key.'`

**Comment by sebastiankb** [comment]
@mmccool is this issue solved?

**Comment by mmccool** [comment]
The definition of "identity" was meant to be generic so it could be used in multiple places.   I intentionally did not want to specialize it by stating the form in which the key was shared.   Whether you pre-share the key it as a raw public key or as a certificate, or whether the key is asymmetric or not, is not really relevant to the definition of the identity itself.

So, I am inclined to NOT change this.

**Comment by sebastiankb** [comment]
@verymuch If this ok for you?
