### ISSUE TITLE
Allow Form's "rel" to be a string or an array

### ISSUE THREAD

**Issue by AndreMaz** [w3c/wot-thing-description#236]
Current (01 October 2018) WoT spec defines Form's "rel" as a string that can take one of possible values: *"readproperty"*,  *"writeproperty"* , *"observeproperty"*, *"invokeaction"*, *"subscribeevent"* or *"unsubscribeevent"*.

[TD JSON Schema](https://w3c.github.io/wot-thing-description/#json-schema-4-validation) also specifies "rel" as string

```JSON
"rel": {
   "type": "string"
}
```
One the other hand, the latest (12 September 2018) Protocol Binding Templates spec defines "rel" as an [array](https://w3c.github.io/wot-binding-templates/#binding-examples).

```JSON
{
    "href": "/example/light/currentswitch",
    "rel": ["readproperty", "writeproperty", "observeproperty"],
    "mediaType": "application/json"
}
```

Can you please sync the docs? 

Suggestion, let "rel" be both (array or string) as does the [OCF](https://www.oneiota.org/revisions/2420) in their spec
```JSON
        "rel": {
          "oneOf":[
            {
              "type": "array",
              "items": {
                  "type": "string",
                  "maxLength": 64
                },
              "minItems": 1,
              "default": ["hosts"]
            },
            {
              "type": "string",
              "maxLength": 64,
              "default": "hosts"
            }
          ],
```

**Comment by handrews** [comment]
If it helps, the next draft of JSON Hyper-Schema will also allow for either a string or array-of-strings value for `rel` (in the context of links rather than forms, though).

**Comment by sebastiankb** [comment]
@AndreMaz Thanks for the hint. 

@egekorkan This must also be fixed in the TD playground. Thanks

**Comment by egekorkan** [comment]
The new validation schema and the playground now support both string and array of strings

**Comment by sebastiankb** [comment]
@vcharpenay how can this reflected in ttl?

**Comment by sebastiankb** [comment]
op can be also an array

**Comment by sebastiankb** [comment]
please review

**Comment by mlagally** [comment]
In the discussion on Dec 21th we agreed that there should be a recommendation that the values of these fields "should be" consistent with the values of readonly, writeonly, ...

**Comment by vcharpenay** [comment]
`op` cannot be an arbitrary array, though. It is only valid for the following combinations:
 - `readproperty`, `writeproperty`
 - `readproperty`, `observeproperty`
 - `readproperty`, `writeproperty`, `observeproperty`
 - `subscribeevent`, `unsubscribeevent`

What about defining one `op` value for each combination instead of defining it as a "string or array of string"?

**Comment by takuki** [comment]
It is implemented in [td-json-schema-validation.json](https://github.com/w3c/wot-thing-description/blob/326ff82ea4792022e5b9eaa2f4591e8c7d0a0640/validation/td-json-schema-validation.json) as one or more of values permitted depending on which interaction affordance (or a Thing) the form belongs to. For example, the form in Property interaction affordance is defined as follows.
 
```
    "oneOf": [
        {
            "type": "string",
            "enum": [
                "readproperty",
                "writeproperty",
                "observeproperty",
                "unobserveproperty"
            ]
        },
        {
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "readproperty",
                    "writeproperty",
                    "observeproperty",
                    "unobserveproperty"
                ]
            }
        }
    ]
```
