### ISSUE TITLE
read and write property : different payload formats

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#238]
The IoT cloud service uses different payload formats for reading and writing a property:

### Reading a property:

GET https://129.150.200.242/iot/api/v2/apps/0-AB/devices/39F59B17-8E7D-41A1-89C0-D8C5B4FD97FF/deviceModels/urn%3Acom%3Aoracle%3Aiot%3Aconnected-car/attributes/ASCD
{
    "ASCD": false
}

### Writing a property:
PUT https://129.150.200.242/iot/api/v2/apps/0-AB/devices/39F59B17-8E7D-41A1-89C0-D8C5B4FD97FF/deviceModels/urn%3Acom%3Aoracle%3Aiot%3Aconnected-car/attributes/ASCD
{
    "value": true
}

We need to find a way to express this behaviour in the TD.
The current workaround requires an additional object and is causing unnecessary overhead.

Example TD:
"properties": {
		"ASCD": {
			"name": "ASCD",
			"type": "object",
			"writable": true,
			"label": "ASCD",
			"properties": {
				"ASCD": {
					"type": "string",
					"writable": false
				},
				"value": {
					"type": "string",
					"writable": true
				}
			},
			"forms": [
				{
					"href": "https://129.150.200.242/iot/api/v2/apps/0-AB/devices/39F59B17-8E7D-41A1-89C0-D8C5B4FD97FF/deviceModels/urn%3Acom%3Aoracle%3Aiot%3Aconnected-car/attributes/ASCD",
					"mediaType": "application/json"
				}
			]
		},

**Comment by mkovatsc** [comment]
We have a similar use case where a write takes an additional Property. My proposal is also to use the data schema, where JSON Schema offers `readOnly` and `writeOnly`.

This is one argument why it might be worth to align our `writable` with `readOnly` of JSON Schema (see https://github.com/w3c/wot-thing-description/issues/209).

**Comment by benfrancis** [comment]
FWIW, this particular case is really a misuse of an HTTP `PUT` request. If the API followed the HTTP specification a workaround wouldn't be needed.

According to the [HTTP/1.1 Specification](https://tools.ietf.org/html/rfc2616.html) for [PUT](https://tools.ietf.org/html/rfc2616.html#section-9.6):

_"If the Request-URI refers to an already existing resource, the enclosed entity SHOULD be considered as a modified version of the one residing on the origin server."_

I would expect the above `PUT` request to replace the original content of the resource:
```
{
  "ASCD": false
}
```

with the new content:

```
{
   "value": true
}
```

If this cloud service API followed the HTTP specification and used a `GET` and a `PUT` with the same resource representation, defining the payload of the property resource would be much more straightforward. However, a POST could arguably be used on a property resource URL with a different payload as an "annotation" or "appendage" to the resource, in which case you would have the same problem.

What is even more complicated is trying to declaratively define the request/response payload formats of [actions](https://iot.mozilla.org/wot/#action-resource) (which may involve creating new resources) and [events](https://iot.mozilla.org/wot/#event-resource) (which may need to represent multiple instances of an event).

**Comment by mmccool** [comment]
Actually, I am running into a problem right now with an action that uses a POST but has a different input and output data schema AND mediaType.   I am trying to set up a camera that can grab cropped images (see https://github.com/w3c/wot/blob/master/plugfest/2018-lyon/TDs/Intel/SimpleWebCamera.json), so I used an action (invoked with a POST) that contains some JSON in the request body with the specification of the crop area, then returns a JPEG in the response.

So here not only the input and output schemas are different, the mediaTypes also are!   But we only have one mediaType in forms.   Is this for the input or output, or does it have to apply to both?  The latter makes sense in the REST pattern, but not in the RPC pattern implicitly supported by actions.

I happen to be evolving this interface to use query parameters for the crop region as a test of uriTemplates (still making it an action, but probably converting to a GET).  However, the initial issue (which maybe should be a new issue) remains: how to specify that input and output mediaTypes are different in actions when using a POST?

**Comment by mkovatsc** [comment]
With @vcharpenay and @mjkoster we discussed that a proper model should probably have a `response` field (or similar) in the form, which then takes metadata about possible responses:
```
      "forms": [
        {
          "href": "http://upsq1c.local:9191/api/frame/crop",
          "mediaType": "application/json",
          "op": ["invokeaction"],
          "http:methodName": "POST",
          "response": {
            "mediaType": "image/jpeg"
          }
        }
      ]
```
I am not sure how far this was already picked up by the TD task force.

Another discussion item is that `mediaType` technically cannot grasp all information needed. Some represenations also require media type parameters, which then forms a `contentType`. This would match the numeric `ct` defined in RFC 6690 for CoAP content formats.

**Comment by mlagally** [comment]
@mkovatsc I'm not sure that declaring a response mediaType (or contentType) at the form level solves the problem. 
In my example the mediaType for each payload is the same, however the parameter passing mechanism is different between a read and a write operation.
In my understanding, the TD spec does not describe the payload format of the read and write operations.

A call of:
GET https://129.150.200.242/iot/api/v2/apps/0-AB/devices/39F59B17-8E7D-41A1-89C0-D8C5B4FD97FF/deviceModels/urn%3Acom%3Aoracle%3Aiot%3Aconnected-car/attributes/ASCD

could return:

A:
{
"ASCD": false
}
-- 
B:
{
"value": false
}
--
C:
false

All of them are valid JSON.

**Comment by mkovatsc** [comment]
The response media type was in response to @mmccool 's, new issue.

In https://github.com/w3c/wot-thing-description/issues/238#issuecomment-428145143 I already answered that this is done with `readOnly` and `writeOnly`. You would do it like this:

```
properties": {
  "ASCD": {
    "title": "ASCD",
    "type": "object",
    "properties": {
      "ASCD": {
        "@type": "ex:ASCD",
        "type": "string",
        "readOnly": true
      },
      "value": {
        "@type": "ex:ASCD",
        "type": "string",
        "writeOnly": true
      }
    }
  }
}
```

**Comment by mkovatsc** [comment]
> A call of ... could return

My understanding was, that A is used in read, B is used for write. Where does C with the simple value come from?

**Comment by sebastiankb** [comment]
this issue is now covered in the TD spec. 

Please review.

**Comment by mlagally** [comment]
@sebastiankb This is nov covered in Example 24, many thanks.
