### ISSUE TITLE
Units in TD core vocabulary

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#244]
The support for units is a recurring topic for metadata provided by TD. I want to propose to include support in the core TD vocabulary, so that a minimal TD (without additional context) can provide this important piece of information

In https://github.com/w3c/wot-thing-description/issues/156, [UCUM](http://unitsofmeasure.org/ucum.html) was proposed, which is also used by CoRE/LWM2M/IPSO. It is a quite simple yet powerful system to attach units of measure with a good vocabulary. @maximelefrancois86 also [applied to RDF](https://ci.mines-stetienne.fr/lindt/v2/custom_datatypes.html#ucum).

Ideally, we can discuss this at upcoming TPAC 2018 in Lyon.

**Comment by sebastiankb** [comment]
In today's f2f meeting there was an agreement to have the "unit" term in the TD core. Further discussion is needed on whether there should be a link to a default unit value set such as from UCUM or should this be defined open for any unit definitions that exists.

**Comment by takuki** [comment]
In addition to the ability to make a reference to existing vocabulary such as UCUM, it is important to provide a way to describe the textual form of the unit symbol associated with a term in the vocabulary, especially for non-JSON-LD enabled applications. OGC's [SensorThings API](http://docs.opengeospatial.org/is/15-078r6/15-078r6.html) also uses UCUM as the default unit system.

**Comment by sebastiankb** [comment]
unit is now introduced with an example.

Please review.
