### ISSUE TITLE
Model possible responses in forms

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#250]
I am creating a Thing that has an action that is invoked with an http POST, but has different input and output data mediaTypes.  This does not seem to be supported by the current Thing Description, which only provides one mediaType in a form.

Specifically, in one of my test cases I am trying to set up a camera that can grab cropped images (see https://github.com/w3c/wot/blob/master/plugfest/2018-lyon/TDs/Intel/SimpleWebCamera.json), so I used an action (invoked with a POST) that contains some JSON in the request body (application/json) with the specification of the crop area.  The action then returns a JPEG (image/jpeg) in the response.

So here it is not the input and output schemas that are different, but the mediaTypes.   However, we only have one mediaType in forms. Is this for the input or output, or does it have to apply to both? The latter makes sense in the REST pattern, but not in the RPC pattern implicitly supported by actions.

I happen to be evolving this interface to use query parameters for the crop region as a test of uriTemplates (still making it an action, but probably converting to a GET).  This avoids the problem... however, the initial problem remains: how to specify that input and output mediaTypes are different in actions when using a POST?

As a test case then I will leave my current RPC-based "crop" interface alone and will add the uriTemplate version as an additional action with a different URL.

**Comment by mkovatsc** [comment]
With @vcharpenay and @mjkoster we discussed that a proper model should probably have a `response` field (or similar) in the form, which then takes metadata about possible responses:
```
      "forms": [
        {
          "href": "http://upsq1c.local:9191/api/frame/crop",
          "mediaType": "application/json",
          "op": ["invokeaction"],
          "http:methodName": "POST",
          "response": {
            "mediaType": "image/jpeg"
          }
        }
      ]
```
I am not sure how far this was already picked up by the TD task force.

Another discussion item is that `mediaType` technically cannot grasp all information needed. Some represenations also require media type parameters, which then forms a `contentType`. This would match the numeric `ct` defined in RFC 6690 for CoAP content formats.

**Comment by sebastiankb** [comment]
In today's f2f meeting there was a decision on this issue: We will follow the "response " proposal (as a array of mediaType/contenttype).

**Comment by mkovatsc** [comment]
We also need some rule for Property Forms or forms with GET in general: the `contentType` must also define the default value for the response. It is similar to the `type` attribute of Links, but is more than the media type (possible parameters in addition).

Question: Should responses only have `type` like the Web Linking media type HINTS or can we talk about something more binding, so that it is basically a fault if the server responds with a content type that was not listed in the possible responses?

In the first case, we should use `type` with the same defintion is in Web Linking.

In the second case, we should use `contentType` with a corresponding definition (an instruction if in a Form, a binding statement in PossibleResponse).

**Comment by sebastiankb** [comment]
AI: change mediaType to contentType

**Comment by sebastiankb** [comment]
there are proposals to rename the class name `Response ` to `ExpectedResponse`, `ResponseForm`, etc. . Please comment on this.

**Comment by sebastiankb** [comment]
since there are no further comments I will go for `ExpectedResponse`

**Comment by sebastiankb** [comment]
done, please review

**Comment by takuki** [comment]
I see section 5.2.9 title is now called "ExpectedResponse". On the other hand, the "response" member in section 5.2.6 Form is still called "response". Is this intended?

**Comment by mmccool** [comment]
I am happy with the current wording.  Please leave the "response" member as is.   In general, I think it is fine to make class names more verbose but members in the JSON document should be as concise as possible.

In my opinion the current state of the document has addressed this issue, and I have used it in an implementation to test it, so this issue can be closed.
