### ISSUE TITLE
Web Link definitions should be in an own namespaces

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#253]
In Lyon, we changed the term mediaType to the original name "type" to comply with IETF RFC 8288:
https://htmlpreview.github.io/?https://github.com/w3c/wot-thing-description/blob/td4lyon/index.html
  
So far, all terms regarding web linking are defined in the TD namespace. 
To be more modular it is suggested to define all web linking terms in an own namespace.

**Comment by egekorkan** [comment]
From Princeton Testfest:
We are going to do this. It doesn't change any serialization but only the semantic model

**Comment by vcharpenay** [comment]
questions on ontology modeling aspects:
- is `Form.href` ~  `Link.href`?
- is `Form.op` ~ `Link.rel`?
- `Form.contentType` is a target attribute according to RFC 8288 : should it be part of this Web linking ontology as well?

**Comment by vcharpenay** [comment]
For the record, terms coincide with those of the [JSON serialization of the CoRE Link Format](https://tools.ietf.org/html/draft-ietf-core-links-json-10). The ontology should reference it.

**Comment by sebastiankb** [comment]
This is is solved by https://github.com/w3c/wot-thing-description/pull/463, right?

**Comment by vcharpenay** [comment]
yes, correct.

**Comment by sebastiankb** [comment]
thanks
