### ISSUE TITLE
WoT Security Ontology incorrectly linked

### ISSUE THREAD

**Issue by jmcanterafonseca** [w3c/wot-thing-description#257]
The HTML page generated when getting access from a Web Browser to

https://www.w3.org/ns/wot-security 

at 

**wot-security.ttl**
An experimental Linked Data ontology for Web of Things security terms

contains an incorrect link to the WoT Security Ontology

The link points to

https://www.w3.org/ns/json-schema

and should point to 

https://www.w3.org/ns/wot-security.ttl

**Comment by vcharpenay** [comment]
Thanks for reporting this bug! @draggett could you fix it, please?

**Comment by sebastiankb** [comment]
@draggett is there some status information about this?

**Comment by draggett** [comment]
Now fixed - sorry for missing Victor's prompt earlier

**Comment by sebastiankb** [comment]
thanks, closing this issue
