### ISSUE TITLE
type should be provided always in TD

### ISSUE THREAD

**Issue by jmcanterafonseca** [w3c/wot-thing-description#258]
I think that for a matter of cleanliness "type" term should be provided not only in TD expressed in JSON-LD but also in JSON. 

Also it would be good to define a mapping in the @context "type": "@type". 

By the way it seems that in certain JSON-LD serialisation examples is included

https://www.w3.org/TR/wot-thing-description/#ex-19-mylampthing-with-semantic-annotations-based-on-a-valid-json-ld-1-1-representation 

but not in others

https://www.w3.org/TR/wot-thing-description/#thing-description-as-json-ld-1-1-serialization 

so there is some lack of consistency in the current published draft.

Recommendation: Define a mapping "type": "@type" in the @context. Use "type" always, both in the JSON and JSON-LD Representation of a Thing Descriptor.

**Comment by sebastiankb** [comment]
Based on the Lyon meeting we cannot follow JSON-LD 1.1 anymore. The TD offers now an own format with the opportunity of a transformation to JSON-LD 1.0. 

The `type` term in the TD is based on JSON Schema and has a different meaning as the `@type` from JSON-LD.
