### ISSUE TITLE
Alignment with SOSA/SSN (and iot.schema.org)

### ISSUE THREAD

**Issue by vcharpenay** [w3c/wot-thing-description#259]
A formal alignment of the TD model with SOSA/SSN should be provided to (1) keep a certain coherence between the work of all W3C groups and (2) to facilitate the semantic annotation of TDs, since most IoT vocabularies align with SSN.

Here is an example of the desired alignment ([WoT TD Draft, example 1](https://w3c.github.io/wot-thing-description/#simple-thing-description-sample)).

_TD Example_

```js
{
    "id": "urn:dev:wot:com:example:servient:lamp",
    "name": "MyLampThing",
    "security": [{"scheme": "basic"}],
    "properties": {
        "status" : {
            "type": "string",
            "forms": [{"href": "https://mylamp.example.com/status"}]
        }
    },
    "actions": {
        "toggle" : {
            "forms": [{"href": "https://mylamp.example.com/toggle"}]
        }
    },
    "events":{
        "overheating":{
            "data": {"type": "string"},
            "forms": [{
                "href": "https://mylamp.example.com/oh",
                "subprotocol": "longpoll"
            }]
        }
    }
}
```

_SOSA/SSN Equivalence (forms omitted)_

```turtle
<urn:dev:wot:com:example:servient:lamp> a sosa:FeatureOfInterest ;
                                        rdfs:label "MyLampThing" ;
                                        ssn:hasProperty <status> .

[] a ssn:System ; # owl:sameAs <urn:dev:wot:com:example:servient:lamp> here?
   sosa:observes <status> ;
   ssn:implements [
     a sosa:Procedure ;
     ssn:hasOutput [
       a jsons:DataSchema ;
       jsons:properties [ jsons:type "string" ]
     ]
   ], <toggle>, <overheating> .   

<overheating> a sosa:Procedure ;
              ssn:hasOutput [
                a jsons:DataSchema ;
                jsons:type "string"
              ] .
```

Currently, an axiomatic alignment using sub-class and sub-property relations is not possible. Here are questions that are still open:
 1. is the alignment `td:Thing` ~ `sosa:FeatureOfInterest` valid? Both have properties and their respective definition matches if we assume that `ssn:System`s can also be `sosa:FeatureOfInterest`s, like the lamp example. However, item 3. weakens this alignment.
 2. the discussion on the difference between `td:Property` (which represents the actual properties of a Thing) and `td:Action` and `td:Event` (which are _specifications_ of actual actions and events on a Thing) is still pending. See @mariapoveda's remarks on issue #140.
 3. `td:Property` does not align well with `ssn:Property` in its current version. Because it is coupled with a data schema, a `td:Property` relates to a specific servient. It cannot identify a property of a physical world object like a room temperature, as does `ssn:Property` (remark by @maximelefrancois86).
 4. how to interpret annotations on parts of a data schema? This question relates to the discussion open by @mjkoster on [data items and data instances](https://github.com/w3c/wot/blob/master/proposals/semantic-api/SemanticAPI.pdf).
 5. identical property names in a JSON schema yield erroneous RDF statements and require pre-processing on a JSON TD (which is a general "limitation" of JSON-LD).

**Comment by vcharpenay** [comment]
Given item 5., a pre-processing phase is likely to be necessary to turn a JSON TD into RDF. One way to address all these issues at once is to provide a more extensive transformation algorithm to turn a TD JSON into a JSON-LD representation that would allow for direct aligments with SOSA/SSN.

Here is a possilbe output for this algorithm (on the example above):

```js
[{
  "@id": "urn:dev:wot:com:example:servient:lamp",
  "name": "MyLampThing",
  "security": [{"scheme": "basic"}],
  "properties": [{
    "@id": "status",
    "forms": [{"href": "https://mylamp.example.com/status"}]
  }],
  "actions": [{
    "@id": "toggle",
    "forms": [{"href": "https://mylamp.example.com/toggle"}]
  }],
  "events": [{
    "@id": "overheating",
    "forms": [{
      "href": "https://mylamp.example.com/oh",
      "subprotocol": "longpoll"
    }]
  }]
}, {
  "observes": { "@id": "status" },
  "implements": [{
    "hasOutput": {
      "type": "string" 
    }
  }, { "@id": "toggle" }, {
    "@id": "overheating",
    "hasOutput": {
      "type": "string" 
    }
  }]
}]
```

The first object in the array is identical to the input TD for the most part. With this structure, we could then have strict alignments:

```turtle
td:Thing rdfs:subClassOf sosa:FeatureOfInterest .
td:Property rdfs:subClassOf ssn:Property .
td:Action rdfs:subClassOf sosa:Procedure .
td:Event rdfs:subClassOf sosa:Procedure .
```

It might even be possible to simplify the algorithm by adding more complex alignments (like property chain axioms) in the TD ontology.

**Comment by vcharpenay** [comment]
One remark though: the approach I present above does not directly address item 4. (annotations within JSON schema definitions).

**Comment by maximelefrancois86** [comment]
Hi Victor.

Actually I now think that when defining the TD **Ontology**, we should:

- not conflate the Thing and the Feature Of Interest/System/Platform it **is an abstraction of**. In fact, in the general case, a Thing may be the abstraction of several entities (see https://github.com/w3c/wot-architecture/issues/60).
- avoid naming clashes with SOSA/SSN, to avoid clashes when both are imported in iot.schema.org. (thus maybe use a class `td:PropertyResource` to represent the TD Property)

I therefore propose to introduce a OWL Object Properties `td:abstractionOf` that links a `td:Thing` to the actual entity it is an abstraction of (the range of this property may `schema:rangeIncludes` `sosa:FeatureOfInterest`, `sosa:Platform`, `ssn:System`, etc. 

Also, as we already discussed about a potential name for a OWL Object Property to link a `td:PropertyResource` to a `ssn:Property`: that could be `td:descriptionOf`.





# Semantic Annotation in the Thing Description 


Here is what I suggest: 

## Semantic annotations on the Thing


It is now clear that trying to use JSON-LD globally to map an arbitrary JSON to an arbitrary ontology is really challenging. I believe we should define a custom algorithm to generate RDF directly from the TD , and potentially rely on JSON-LD for specific sub-parts of the TD.
In the TD JSON-Schema of Thing we forbid the use of keys that are not defined in TD, but we add one special key `annotations` whose value is a JSON-LD object.

```
{
  "id": "urn:dev:wot:com:example:servient:lamp",
  "name": "MyLampThing",
  "base" : "coap://192.168.0.1/",
  "annotations": { 
      "@context" : { some custom context } ,
      "abstractionOf": "http://mybuildingmodel.com/room1/lamp" ,
      ...
   }
```

the annotation `{ ...  }` would be preprocessed. For example the `@id` annotation needs to be added, and another generic context for TD may be added  (see https://json-ld.org/spec/latest/json-ld/#ex-35-combining-external-and-local-contexts ):

```
{ "@context":  [  
     "http://w3.org/ns/td/contextForInteractionPatterns.jsonld",
     { some custom context }
  ] ,
"@id": "urn:dev:wot:com:example:servient:lamp" , 
"abstractionOf": "http://mybuildingmodel.com/room1/lamp" ,
...
}
```

And the RDF graph encoded in this JSON-LD document would be added to the overall RDF equivalent of the TD. 

```
<urn:dev:wot:com:example:servient:lamp> a td:Thing ;
  rdfs:label "MyLampThing" ;
  <http://example.org/abstractionOf> <http://mybuildingmodel.com/room1/lamp> .

...
```

This adds additional flexibility:

- simple TD implementations could just ignore these annotations
- anyone can provide a custom context there

## Semantic annotations on InteractionPatterns

needs to be further discussed

## 

On Links, RFC 8288, and the RDF representation of Links





``` 
[] a td:Form ;
  href": "/sensors/light" ;
  "title": "the title" ;
  "rel": "hosts";
  "rt": "light-lux core.sen-light";
  "name": "the name"
}
``` 



Also, td:abstractionOf to link a `td:Thing` to the actual entity it is an abstraction of (the range of this property may `schema:rangeIncludes` `sosa:FeatureOfInterest`, `sosa:Platform`, `ssn:System`, etc.

```
_:realLamp a ssn:System ;
  ssn:hasProperty _:realLampStatus ;

<urn:dev:wot:com:example:servient:lamp> a td:Thing , ssn:System ;
  rdfs:label "MyLampThing" ;
  td:hasPropertyResource _:statusProperty ;
  td:abstractionFor _:realLamp .

_:statusProperty a td:PropertyResource ;
  td:descriptionOf _:realLampStatus .

_:statusProperty a ssn:implements [
     a sosa:Procedure ;
     ssn:hasOutput [
       a jsons:DataSchema ;
       jsons:properties [ jsons:type "string" ]
     ]
   ], <toggle>, <overheating> .   

<overheating> a sosa:Procedure ;
              ssn:hasOutput [
                a jsons:DataSchema ;
                jsons:type "string"
              ] .
```

**Comment by maximelefrancois86** [comment]
BTW, watch out when making a `Sensor` implementing several procedures, because SSN contains the following axioms: 

```
sosa:usedProcedure 
  owl:propertyChainAxiom ( sosa:madeBySensor ssn:implements ) ;
  owl:propertyChainAxiom ( sosa:madeByActuator ssn:implements ) ;
  owl:propertyChainAxiom ( sosa:madeBySampler ssn:implements ) ;
  rdfs:isDefinedBy sosa: .
```

Then:

- an observation automatically uses all of the procedures that the sensor implements
- an actuation automatically uses all of the procedures that the actuator implements
- a sampling automatically uses all of the procedures that the sampler implements

As a side effect, one cannot have a sensor that implements different procedures. However, a System may perfectly implement different procedures. 

This was described in 

> Samya Sagar, Maxime Lefrançois, Issam Rebai, Khemaja Maha, Serge Garlatti, Jamel Feki, Lionel Médini. Modeling Smart Sensors on top of SOSA/SSN and WoT TD with the Semantic Smart Sensor Network (S3N) modular Ontology. In Emerging Topics in Semantic Technologies. ISWC 2018 Satellite Events. E. Demidova, A.J. Zaveri, E. Simperl (Eds.), ISBN: 978-3-89838-736-1, 2018, AKA Verlag Berlin.

**Comment by vcharpenay** [comment]
> watch out when making a Sensor implementing several procedures

Good to know. Intuitively, I would safely only introduce instances of `ssn:System` but an even more careful transformation would be to create a system for each interaction definition (and possibly as many `ssn:hasSubSystem` statements with a common super-system). I am not sure it is necessary, though.

> [we should] not conflate the Thing and the Feature Of Interest/System/Platform it is an abstraction of. In fact, in the general case, a Thing may be the abstraction of several entities.

Then, we would loose the coupling of Thing's properties and FoI's properties, which is an issue when annotating Thing's properties with independent vocabs. Typically, how should the class `iot:Temperature` be aligned? With `ssn:Property` or with `td:Property`? To me, there should be no difference.

Now, what you point out is still an issue. I think the group refers to it as "proxy" Things. I see two distinct cases:
 1. a (virtual) aggregation of data points for parallel control (e.g. all lights in a given street)
 2. an arbitrary aggregation of Things dictated by a network topology or deployment constraints specific to some automation system (e.g. a multi-purpose controller for light, temperature, humidity, blinds and other variables in a building)

The difference is as follows: in the first case, the original interactions are not exposed but a new one is created by _aggregating_ measurements or set points but in the second case, all interactions remain unchanged, their definitions are simply _merged_ in a single TD.

In the first case, the Thing could still be an FoI itself (the street or a portion of it) and it remains intuitive if the street has a light/brightness property (that would be a sort of metonymy).

In the second case, the FoI is likely the controlling device itself. In this case, the system and the feature of interest are the same and as far as I understood, this is acceptable in SOSA/SSN. It is maybe more dubious to have a temperature and the status of blinds as properties of the same FoI, though. What do you think?

In both cases anyway, since the FoI and the introduced instance of `ssn:System` have no direct relation, the proxified systems can still be materialized by `ssn:hasSubSystem` statements, without effects on the FoI.

**Comment by takuki** [comment]
Looking at [SOSA/SSN Observation diagram](https://www.w3.org/TR/vocab-ssn/images/SSN-Observation.png),  I was wondering if TD property may correspond to Observation (or a collection of observations) because it has a value as well as ObservableProperty which essentially is a type. Also Observation has FoI which can be a WoT Thing.

**Comment by vcharpenay** [comment]
In appendix [B. Complete Examples](https://www.w3.org/TR/vocab-ssn/#examples), there is e.g.:

```turtle
<Observation/346344> rdf:type sosa:Observation ;
  sosa:observedProperty <sensor/35-207306-844818-0/BMP282/atmosphericPressure> ;
  sosa:hasFeatureOfInterest  <earthAtmosphere> ;
  sosa:madeBySensor <sensor/35-207306-844818-0/BMP282> ;
  sosa:hasSimpleResult "1021.45 hPa"^^cdt:ucum ;
  sosa:resultTime "2017-06-06T12:36:12Z"^^xsd:dateTime .
```

which contains an actual measurement value and a timestamp. This would rather correspond to the result of a single `GET` request sent to the servient on a specific `td:Property`. There is also the contraint that a `sosa:Observation` has [exactly 1 timestamp](https://www.w3.org/TR/vocab-ssn/#SOSAObservation), while the state of a `td:Property` can be requested an arbitrary number of times.

That said, seeing a `td:Property` as a _collection_ of `sosa:Observation`s is a good idea. Is there a particular benefit to this modeling compared to having `td:Property` ~ `ssn:Property`? (The latter approach also include a link to a FoI.)

**Comment by takuki** [comment]
Looking at a diagram from iot.schema.org introduction material excerpted below, I agree with @vcharpenay , and WoT property is more like a sosa:ObservableProperty. By thinking this way, SOSA/SSN diagram and iot.schema.org diagram look consistent.
![foi](https://user-images.githubusercontent.com/12631135/48082009-45670400-e1a6-11e8-87c2-95f003955ddb.png)

**Comment by mariapoveda** [comment]
Here there are some comments about the discussion about the alignments between td and ssn ontologies @rgcmme and me would like to share:

_Alignment between td:Thing and  sosa:FeatureOfInterest:_

As @maximelefrancois86 mentioned, these are two different concepts, as for example is it not the same a lamp (instance of ssn:FeatureOfInterest) as the lamp web representation (instance of td:Thing). In addition, there could be many web representations of such lamp. That is, the td:Thing is not the FoI itself. This is similar to the case of a person and his/her website, which represent different entities with different attributes, for example, the person has no access protocol as attribute.

Therefore it would be more advisable to link by means of an ad-hoc property like "isAbstractionOf" or "represents" the td:Thing with the entities from the real world. In principle, we would link to owl:Thing as there can be physical things (sensors) and virtual things (services) that might have a virtual representation. In case a virtual or physical thing is measured, it becomes a feature of interest too, but it might not be the case. 

_Alignment td:Property and ssn:Property_ 

Also as @maximelefrancois86 mentioned, these two concepts represent different things. The ssn:Property represents the physical quality being observed. The td:Property represents the interaction pattern (e.g: web service) in which information about a ssn:Property could be queried. Again, the td concept is a web representation of a real world phenomena. 

Indeed, the three types of interactions patterns could be linked to ssn:Property if needed by means of the relation ssn:forProperty.

See some examples of the possible implementations:

![examples of FoI and td:Thing](https://github.com/mariapoveda/vicinity-ontology-core/raw/master/diagrams/exTDRaulAndMaria.png)

In this examples you can see that when you access the service described by a thing you expect to get information about the feature of interest, not about the td:Thing as they are different entities.

You can see how we are applying this solution in the VICINITY project: http://vicinity.iot.linkeddata.es/vicinity/

**Comment by vcharpenay** [comment]
Thank you, @mariapoveda & @rgcmme for this in-depth comment. Of course, what you and @maximelefrancois86 propose is consistent and doable. I don't argue with that. However, I do believe it is unnecessarily complex and makes the semantic annotation of TDs impractical, from the perspective of WoT developers (which the WoT recommendations are targeting).

_Alignment between td:Thing and sosa:FeatureOfInterest_

> A lamp (instance of ssn:FeatureOfInterest) is not the same as the lamp web representation (instance of td:Thing).

On the Web, everything has a Web representation. It sounds vacuous but given your comment, it looks like it is important to state it. Is it, really? To me, the Thing Description (i.e. the JSON document a WoT servient exposes) already _is_ the Web representation of the Thing it describes. Note that the TD spec encourages the use of URNs and other non-dereferenceable URIs to identify the Thing, to avoid confusion on this level.

> In principle, we would link to owl:Thing as there can be physical things (sensors) and virtual things (services) that might have a virtual representation.

The current definition for [Thing](https://github.com/w3c/wot-architecture/blob/master/terminology.md#thing), although it is perfectible, makes no mention of services. It is important to me that a Thing does not relate to everything. It does apply to _logical_ entities, like part of a physical entity but it does not inlude _intangible_ entities. The limit is very hard to define but here are a few examples I took from the [appendix B of SSN](https://www.w3.org/TR/vocab-ssn/#examples):
 - a human can be a `td:Thing`,
 - a human organization like a company or a government shouldn't;
 - a sample of the atmosphere can be a `td:Thing` ;
 - a physical quantity like its temperature or pressure shouldn't.
 - a printed circuit board can be a `td:Thing`,
 - the software running on it shouldn't.

Here I assume `td:Thing` = FoI but my reasoning is also valid with your approach. What I wanted to illustrate is that in any case, `td:Thing` ≠ `owl:Thing`. The way I constructed this list is simple: I looked at all instances of `sosa:Platform`, `ssn:System` and `sosa:FeatureOfInterest` and considered them as `td:Thing`s and excluded instances of all other SSN classes (like `ssn:Property` and `sosa:Procedure`).

_Alignment td:Property and ssn:Property:_

> The ssn:Property represents the physical quality being observed. The td:Property represents the interaction pattern (e.g: web service) in which information about a ssn:Property could be queried.

The concept of "interaction pattern" is subject to many interpretations. Its definition has changed changed several times for the past 3 years. Formally, its only characteristic is that it points to WoT form objects that hold interaction-related information. I understand at some point in time a `td:Property` was a _service to read a thing's property_ but, to me, this was a bug that needed to be fixed. In fact, the *starting point of this issue*, as far as I 'm concerned, was to figure out a way to have `td:Property` = `ssn:Property` while still keeping a certain modeling consistency (hence a script to "correct" the structure a TD before converting to RDF). The advantage of having direct alignments between TD & SSN is that data and model integration can be expressed exclusively in terms of SSN, without knowledge of the TD model.

Note: this view is partly what I present in the following paper (and develop in the thesis I am currently writing):
> "[Introducing Thing Descriptions and Interactions: an Ontology for the Web of Things](https://vcharpenay.github.io/publications/2016-swit.pdf)," in Joint Proceedings of the 3rd Stream Reasoning (SR 2016) and the 1st Semantic Web Technologies for the Internet of Things (SWIT 2016) workshops, Kobe, 2016.

**Comment by vcharpenay** [comment]
Concretely, here is my proposal, inspired by yours.

The three integration scenarios you refer to look good to me. Instead of focusing on FoIs, let's also consider `ssn:System` (and `ssn:Platform`, which I found relevant in the projects I was working on). We would have the following alignments:

```turtle
td:Thing rdfs:subClassOf [
  owl:unionOf (sosa:FeatureOfInterest, ssn:System ) # and sosa:Platform?
] .
td:properties rdfs:subPropertyOf ssn:forProperty .
td:Property rdfs:subClassOf ssn:Property .
td:Action rdfs:subClassOf sosa:Procedure . # not relevant here
td:Event rdfs:subClassOf sosa:Procedure . # not relevant here
```

and the following graph for each scenario:

![td-sosa-alignment-1](https://user-images.githubusercontent.com/6052970/48141702-b5ab7d80-e2ab-11e8-99fb-3de284ccfec4.png)
---
![td-sosa-alignment-2](https://user-images.githubusercontent.com/6052970/48141708-b80dd780-e2ab-11e8-8190-18b5b3f39296.png)
---
![td-sosa-alignment-3](https://user-images.githubusercontent.com/6052970/48141714-ba703180-e2ab-11e8-9d56-2a7b0d7b7b64.png)

**Comment by takuki** [comment]
Just FYI, oneM2M base ontology (see below) uses a technique to separate Service from Function, where service is a network representation of a  function. Aspect corresponds to sosa:ObservableProperty. In our WoT case, can we consider td:Property as a network representation of sosa:ObservableProperty?
![2016-05-06 onem2m](https://user-images.githubusercontent.com/12631135/48155978-20938f00-e281-11e8-9013-b836c7a8eb3c.png)

**Comment by maximelefrancois86** [comment]
In some simple cases, I assume it is fine to have an instance of `td:Property` also be a `ssn:Property`. But this doesn't hold when:

- the `td:Property` actually describes a feature of interest (ex, what lights are on?)
- the `td:Property` describes two or more `ssn:Property` (ex, the temp and humidity)
- the `td:Property` describes the history and min/max of a `ssn:Property` over a period of time

So @vcharpenay I don't think the following axioms you propose hold in the general case

```
td:properties rdfs:subPropertyOf ssn:forProperty .
td:Property rdfs:subClassOf ssn:Property .
```

Then for things, 

```
td:Thing rdfs:subClassOf [
  owl:unionOf (sosa:FeatureOfInterest, ssn:System ) # and sosa:Platform?
] .
```

Is it correct to use this axiom if a `td:Thing` is the abstraction of several rooms/lights for example?
fine for `td:isAbstractionOf` in the TD ontology.

Finally, @vcharpenay  said:

> I do believe it is unnecessarily complex and makes the semantic annotation of TDs impractical, from the perspective of WoT developers (which the WoT recommendations are targeting).

I agree only if we stick to JSON-LD. See proposal in issue #263

**Comment by mjkoster** [comment]
Sorry but I haven't read through all the preceding text and I don't fully understand all of the subtlety involved, but I see one idea popping up a lot that seems inappropriate.

I don't think we intend for a wot thing to be itself a Feature of Interest. 

The intention is for a wot thing to be something like a temperature sensor, which is involved in a sensing process to evaluate a property of some other feature of interest.

A wot property is a digital affordance, or "resource" in a REST API, from which a representation of a result of a sensing process may be obtained.

I think it is inappropriate to try to directly align wot property with the other notion of a sensed property, because it precisely leads to the fallacy of a wot thing being a FoI.

**Comment by mjkoster** [comment]
If we say a wot thing is, for example, a light bulb, then we have some common elements with a FoI, but I would still say that a wot thing represents the collection of affordances affordances that are associated with the pump, e.g. its on/off control, its RPM measurement, motor current, etc which are not the pump per se. 

In the case of a light bulb, the FoI is arguably the space which is illuminated by the light bulb. Is there a way for the FoI to be both the light bulb and the space which is illuminated by the light bulb? We would like to make the light bulb become an affordance through which  the space is illuminated, which itself has affordances to control the illumination provided.

Is there a way to represent patterns like this rather than trying to conceptually align like terms?

**Comment by mjkoster** [comment]
We would like to have patterns that allow for reasoning about the physical effects of digital affordances without having to process the concept of services and processes. We would also like to work with abstractions of capabilities, like temperature sensing or illumination, without having to process the concept of devices as features of interest.

Does this make sense?

**Comment by mjkoster** [comment]
Ceci n'est pas une chose... 

There are probably cases where a wot thing looks a lot like a FoI, for example if we want to make a TD for a heat exchanger that includes temperature measurement at several points. In this case, I would hope that it would be equally valid to declare the thing as a "multi-sensor" that "isAssociatedWith" a  heat exchanger as the FoI. I would expect that the reasoning would resolve in a similar way for both cases as long as the heat exchanger is defined as a FoI and the sensors are somehow associated with it's sub-features (tube side inlet, tube side outlet, shell side inlet, shell side outlet, ambient...). It seems a bit awkward to conflate the wot thing with the FoI.

**Comment by maximelefrancois86** [comment]
@mjkoster that's a lot of reponses at once, could you maybe wait for us to respond ?  :-) 

>  .. that "isAssociatedWith" a heat exchanger as  ...

Then I think we agree. The terminology for this link is discussed above, we proposed property `td:isAbstractionOf` .

Maybe it is time to close this issue and create more specific ones? I see at least two very distinct issues here:

- TD annotation to link a `td:Thing` to the FoI(s) it is an abstraction of, and annotation of these FoI
- Ontology name for TD Property, and TD annotation to link it to the `ssn:Property` that it describes (maybe more than one), and semantic annotation to link these `ssn:Property` to the FoI(s) they are properties of

**Comment by vcharpenay** [comment]
This partly addresses [your comment on properties](#issuecomment-436789919), @maximelefrancois86. Here are the 3 issues you pointed out: 

> the `td:Property` actually describes a feature of interest (ex, what lights are on?)

well, doesn't it describe the _on/off state_ of the feature of interest in that case (which is then the same as below)?

> the `td:Property` describes two or more ssn:Property (ex, the temp and humidity)

if we have the following TD:

```js
{
  "properties": {
    "temp": {
      "@type": "ex:Temperature",
      "type": "number"
    },
    "humidity": {
      "@type": "ex:Humidity",
      "type": "number"
    }
  }
}
```

then, the output of the transformation to RDF should be something like:

```turtle
[] a td:Thing, ssn:System ;
   ssn:forProperty [
     a ex:Temperature
     # ssn:isPropertyOf some FoI
   ], [
     a ex:Humidity
     # ssn:isPropertyOf some other FoI
   ] ;
   ssn:implements [
     ssn:hasOutput [ jsons:type "number" ]
     # with some link to temp? E.g. td:providesRepresentationFor
   ], [
     ssn:hasOutput [ jsons:type "number" ]
     # with some link to humidity? E.g. td:providesRepresentationFor
   ].
``` 

It is similar to my initial proposal but the Thing is now an `ssn:System` instead of an FoI. What is important to me is that, if the classes `ex:Temperature` and `ex:Humidity` are taken from vocabularies like QUDT or OM, then the produced RDF graph for the TD remains consistent.

Do you see any conflict with the SSN axioms, here?

> the `td:Property` describes the history and min/max of a ssn:Property over a period of time

Same as above for the history: the representation of the observation is independent from the property definition. However, for min/max, it is a bit more dubious to generate a _procedure_ for them. Maybe the transformation algorithm can take into account whether a property is an `ssn-system:SystemProperty` or not. What do you think?

**Comment by mkovatsc** [comment]
I tried to understand concrete issues and proposals from this discussion, but am having a real hard time. In particular, I tried to understand the limitations of currently not being aligned with SSN, concrete benefits if we align, and ideally what we would need to change to be aligned. For the latter, I would like to avoid custom rules how to derive SSN-aligned triples from a TD document as the default semantic processing of a TD.

Can we at least assume that Issues #262 , #263, and #282 cover all issues raised in this discussion?

**Comment by vcharpenay** [comment]
This issue goes beyond the scope of the current WoT WG charter. At this point, the reference modeling choice for this alignment should be [the one introduced](https://github.com/w3c/wot-thing-description/issues/259#issuecomment-436604036) by @mariapoveda.
