### ISSUE TITLE
contenttype for forms

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#260]
A media type technically cannot grasp all information possibly needed by a client to send correct messages. Some representation formats also require media type parameters, which are added to the media type string using semicolons (e.g., `text/plain; charset="utf8"` or `application/cose; cose-type="cose-sign"`). The media type, however, is only the fist part (e.g., `text/plain`): https://tools.ietf.org/html/rfc6838#section-4.2

A content type is defined to also take parameters and this combination of both is also what CoAP uses in its Content-Format option.

As a result of a discussion with @cabo at the IETF, we are proposing to use the term `contenttype` in TD forms, to be able to describe all the information needed to send a correct message to a Thing. This term would also match the numeric `ct` attribute defined in RFC 6690 for CoAP Content-Formats.

**Comment by sebastiankb** [comment]
In today's f2f meeting there was a decision on this issue: we rename `mediaType `to `contenttype `and allow parameters.

**Comment by sebastiankb** [comment]
changed contenttype to contentType
Please review and close the issue

**Comment by mmccool** [comment]
There are still many mentions in the text of "media type" which is a little confusing.  Even though these are referring to the concept an not the specific term in the TD, maybe these should also be edited to say "content type" to be consistent (and/or an explanation given that "media type" refers to the type without parameters, but I thing the simpler solution of just using "content type" everywhere would be... er... simpler).

**Comment by sebastiankb** [comment]
thanks for your feedback. I did some edits + usage explanation in the form section. Please review again.

**Comment by danielpeintner** [comment]
Editorial comments:

- Example 14 still contains `"mediaType"` twice

- JSON schema in appendix needs update also

**Comment by sebastiankb** [comment]
fixed this issue in my last push. I think we can close this issue.

**Comment by danielpeintner** [comment]
The JSON schema needs to be updated also to reflect the change...

**Comment by sebastiankb** [comment]
JSON Schema is updated to contentType
