### ISSUE TITLE
Delete writeOnly

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#266]
Currently there are both writeOnly and readOnly attributes on property interactions.
I assume this is a mistake and writeOnly should be deleted, since we agreed at TPAC that readOnly is what we want to use going forward.  Having both is logically inconsistent...

**Comment by vcharpenay** [comment]
as far as the ontology is concerned, `readOnly` and `writeOnly` are defined [in JSON schema](http://json-schema.org/latest/json-schema-validation.html#rfc.section.10.3), not in the TD core model. What you probably discussed in Lyon is how to interpret `readOnly` in case a schema definition is also an instance of `td:Property`, as there are implications in protocol bindings. But I see two separate issues here (`writeOnly` as property of `DataSchema` and how to interpret it for `td:Property`).

**Comment by vcharpenay** [comment]
In PR #264, there is no mention of `td:Property`. I would therefore not _delete_ `writeOnly` from the JSON schema vocab but clarify its use for `td:Property`, instead.

**Comment by mkovatsc** [comment]
`writeOnly` is a feature from JSON Schema, which needs to be modeled anyway. We need for #238, for instance. It only indicates that the data item will not be included when performing a read. Thus it only makes sense for sub-properties, where at least one sibling data item is returned. A pure writeOnly Property should be modeled as Action, as there is no state exposed.

What needs to be added beside this, is an assertion similar to "If a Property Interaction is marked as readOnly, a WoT Client MUST NOT attempt to write it."

**Comment by zolkis** [comment]
Write policy should not be cooperative, but should be enforced at the server side. 
One cannot make a normative statement like "client MUST NOT attempt to write it". 
Instead, we should say "the server MUST respond with xxxError when a readonly property is attempted to be written". 
Test clients actually SHOULD attempt writing the property, and ignorant or malicious clients will do it as well. It is the server that MUST be prepared to enforce such a policy.

**Comment by handrews** [comment]
@zolkis `readOnly` is intended to be a flexible annotation, which applications may further constrain.  In the context of JSON Schema, or specifically Hyper-Schema for client/server behavior, a `readOnly` field may mean any of:

* The server produces an error if you attempt to change it
* The server ignores attempts to change it (this allows GET-modify-PUT to work with fields like auto-update timestamps, for example)
* The error vs ignore behavior is determined by the value of the `Prefer` HTTP header (`handling=strict` vs `handling=lenient`)

If the TD wants to constrain the meaning of `readOnly` to producing errors, it can, but that does cause some usability problems when ignoring the apparent attempted change makes more sense.

While you can use `readOnly` at the root of a schema to indicate that the entire instance is read-only, I would tend to handle that with a 405 Method Not Allowed rather than the sort of error you would get for attempting to change a read-only field within a generally writeable resource (depending on circumstances, I might use any of 400, 403, 409, or 423 for that).

**Comment by zolkis** [comment]
It is fine to set any policy like the above, my point was that such policies can only be enforced at the server level, therefore normative text should describe the server behavior, not the client behavior.

**Comment by takuki** [comment]
I did not hear anything about writeOnly discussed in Lyon meeting, either. Having said that, since Property is a subclass of DataSchema, I think it makes sense to be consistent with JSON Schema. Therefore, adding writeOnly also makes sense to me.

**Comment by mkovatsc** [comment]
> Write policy should not be cooperative, but should be enforced at the server side.
One cannot make a normative statement like "client MUST NOT attempt to write it".
Instead, we should say "the server MUST respond with xxxError when a readonly property is attempted to be written".

Note that TDs often describe existing devices, whose implementation is out of reach and cannot be changed. Yet I agree that "WoT Clients SHOULD NOT attempt" is probably the better wording.

**Comment by mmccool** [comment]
Interesting discussion.  By the way, I have been thinking in general how to state normative assertions about the “behaviour” of Things.  Given that TDs describe the behaviour of servers, but do not constrain them (since they are not prescriptive) we can’t really talk about the “contract” between client and server.

What I want to propose we do it to make all normative assertions in the soec about the validity of the TD.  Then there are still two kinds of assertions: those about the syntax of the TD (relatively easy to understand) and those about the behaviour of the device it describes.  However, normative assertions should be stated such that the *TD* is invalid if it does not correctly describe the actual behaviour of the Thing’s network interface.   So, for example, if the TD says the Thing uses “basic” authentication but the device actually requires “digest”, then the TD is invalid.   This has implications for testing...

Regarding the current discussion, how can we word assertions around these features so they make sense from the point of view of TD validity?

**Comment by mmccool** [comment]
BTW my counter-case against asserting read-write property value invariance: assuming a Thing has multiple concurrent processes writing to a property.  Then if we write a property and read it back, it might have gotten changed since we read it.   Such processes could be internal to the Thing, or through the network interface.   If internal we can’t even say “if no other network interactions take place between the read and write”.

I’m not saying this would be a *good* design for a Thing.  My main point is that it’s not in our power to constrain it from happening.  Whether we want to *describe* such (unexpected) behaviour is a different matter (eg with a “volatile” flag, not that I’m saying we should add one...).

**Comment by mmccool** [comment]
An additional assertion that a valid TD must not state both readOnly and writeOnly are true might also be useful (since you need at least one form, and that form needs an op, it’s logically inconsistent to disallow both readproperty and writeproperty...).

**Comment by handrews** [comment]
So I think it would be bad to use `readable` and `writeable` in what otherwise looks like JSON Schema, because it's a confusing inversion of the standard JSON Schema vocabulary.  But if you don't use either and instead rely on form definitions elsewhere in the TD, that would make sense to me.

**Comment by mmccool** [comment]
Because of the redundancy, which is just asking for trouble/inconsistency, I’m now thinking the best approach here is just to eliminate readOnly and writeOnly, and depend on the op field in forms (eg if there is a form with op set to writeproperty, it’s writable).   This also begs the question of whether we want “observable”, since it’s redundant in the exact same way.

**Comment by mlagally** [comment]
I think we should consider real world examples and not be too much guided by JSON-Schema, which is a meta language to describe valid TD documents. 

Most likely only few people read/write JSON-Schema documents, and these people are able to distinguish between JSON-Schema keywords and TD tokens. 

A vast majority of people will only work with TDs and for them writeOnly or readOnly would be most intuitive.

**Comment by mkovatsc** [comment]
@mmccool 
> I’m now thinking the best approach here is just to eliminate readOnly and writeOnly

I hope we are not going overboard here and at the same time forget the purpose...

These terms are required for the data schema, where they are also defined now -- not in `td:Property`. They describe how the server will handle attempts to read or write. As @handrews said, `readOnly` and `writeOnly` are mainly intended for complex types, for which we definitely need them. Yet they also work for simple types and in that course obsoleted the `writable` term on `td:Property`.

These terms are also used by the Scripting API to from that direction declare how the Runtime should handle attempts to read or write a Property. Thus, +1 to "we need them".

There is definitely an overlap with the `op` terms, but remember that they work on a different level. Properties can be readable, writable, and observable, but one protocol only supports read/write, the other one only observe, and maybe one only read. Thus, a writable Property still might not have `writeproperty` given in a form.

We used the overlap with the `op` terms to derive the default value for them, when `op` is not given explicitly. We derived them from `writable` and `observable` and could now derive them from `readOnly` and `observable`. However, I like the direction of reducing redundancy, that is, also to obsolete `observable`. To my understanding, a Property is always observable in terms of the model, however, there needs to be a corresponding binding available to realize it -- which is indicated by the `op` field.

Now, we could either make the `op` field mandatory without default value or rethink how we derive the default value. To me, it feels best to keep simplicity, i.e., keep default value and make it `["readproperty", "writeproperty"]`. This fits the defaults for `readOnly`, the nature of HTTP, and the fact that CoAP Observe is an optional extension to CoAP. Once `readOnly` is set to true for a simple type or all elements of a complex type, we could have a SHOULD on giving only `"readproperty"` explicitly for `op` and potentially a SHOULD on clients should not attempt to write when the data schema says read-only for the whole Property (and missing `op`).

@mlagally 
> A vast majority of people will only work with TDs and for them writeOnly or readOnly would be most intuitive.

One intention going to `readOnly` was to align and only have only one way to do it. So there would not be a TD vs JSON Schema people. From the "Web developer community" we mostly got feedback that writable: true / readOnly: false is their natural default assumption. `writeOnly` might indeed be a bit counter-intuitive for a Property, yet you even had the use case for it in #238

**Comment by sebastiankb** [comment]
writeOnly is in the TD spec justified on the #238 use case

the default value of the `readOnly` term is set to true and the `writeOnle` to false (=this reflects the same assumption which we had in the past based on the `writable` term). 
In addition we need an assertion for readOnly and writeOnly that can both not be true at same time.

**Comment by draggett** [comment]
> default value of the readOnly term is set to true

isn't that the opposite of what @mkovatsc said:

> From the "Web developer community" we mostly got feedback that writable: true / readOnly: false is their natural default assumption.

**Comment by sebastiankb** [comment]
do you think, it makes really sense to have an interaction property that is not readable per default?

**Comment by draggett** [comment]
That's a separate issue and should be based upon how important the use cases for write only properties are.  One scenario is where data is being streamed to an actuator. But even here there is no harm in being able to read the current value at some point in the stream.

**Comment by sebastiankb** [comment]
I think there's been a misunderstanding. We talking here about the terms `readOnly` and `writeOnly` that can be appear both at the property interaction level and within the data schema / JSON schema definition.

**Comment by handrews** [comment]
@sebastiankb I also feel that you are misinterpreting @mkovatsc regarding the default for `readOnly`, although perhaps he can comment.  I am looking at:

> From the "Web developer community" we mostly got feedback that writable: true / readOnly: false is their natural default assumption.

As the maintainer of JSON Schema, while I have no opinion on default behavior for the TD, I feel strongly that you should only use the JSON Schema keywords if you use not only their syntax but also their defaults.  Default inversion is an extremely bad developer experience for anyone working in both systems- it is a silent failure for one side or the other depending on where you started.  A default value of `true` for `readOnly` is fundamentally opposed to how JSON Schema works- the empty schema always permits everything.  Keywords add constraints, never remove them.

That said, if you want different defaulting behavior, the correct thing is to use keywords that cannot be confused for standard JSON Schema keyword.  `readOnly` with a default of `true` looks like a JSON Schema keyword but is not actually one.

**Comment by danielpeintner** [comment]
Maybe there was an inconsistent version at a certain point in time.
Having said that, `readOnly` and `writeOnly` are `false` by default now.

see https://w3c.github.io/wot-thing-description/#dataschema

I assume this matches your understanding/expectation?

**Comment by mmccool** [comment]
I re-read the JSON spec definitions of these and I now think it is acceptable to have them both, but with default values (in which case they do not have to appear in a TD, even though they are "mandatory").   

I'm not completely happy with the names, but that's what JSON Schema uses, and so for compatibility, that's what we should use.   Semantically they do make sense at the "properties" interaction level... especially if we also add a real-all-properties capability.

**Comment by egekorkan** [comment]
From Testfest:
We have to explain them better, like in JSON Schema. We cannot rely on the natural language

**Comment by mmccool** [comment]
To resolve this issue we need someone to make a PR with some explanatory language, borrowed from the JSON Schema specification.
