### ISSUE TITLE
Stray mentions of "rel" under "forms"

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#267]
We recently changed "rel" in forms to "op" but there are still some stray mentions of "rel" around that need to be cleaned up.  In particular, in the description of "op" itself there is a mention of "rel" that should be changed either to "op" or "this attribute".

Note: we still use "rel" in links, and those mentions should not be changed, of course.

**Comment by takuki** [comment]
I just fixed the particular mention of "rel" in the description of "op" itself in PR [271](https://github.com/w3c/wot-thing-description/pull/271).

**Comment by sebastiankb** [comment]
thanks. PR is merged
