### ISSUE TITLE
[FPWD] Class issue vs. ednote

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#27]
This is a very minor point but I would like to point the editors to the current TD document which uses the `class="issue"` for paragraphs that (I think) are editorial notes. For example issue #1 and #2 are tasks the editors need to take care of.

Issue#3 is a "real" issue that we may need to solve.

Note: we may also want to clarify when to use which class.

**Comment by takuki** [comment]
I updated the document. Please see this [update](https://github.com/w3c/wot-thing-description/commit/30fb45a392be5087c6c2113aa96293ccc32e025e).

**Comment by sebastiankb** [comment]
Thanks for this hint. I will close this issue since it is solved by @takuki
