### ISSUE TITLE
Automatic generation of diagrams (Sec. 5.1)

### ISSUE THREAD

**Issue by vcharpenay** [w3c/wot-thing-description#276]
I wrote a script to automatically generate diagrams for the TD model (and JSON schema/security modules). It creates files in the [DOT format](https://graphviz.gitlab.io/_pages/doc/info/lang.html) that can then be rendered with [GraphViz](https://graphviz.gitlab.io/).

See vcharpenay/wot-thing-description@ee0acf44e59b4c13ddcafe0e07e23e40b14ff49e (folder `/visualization`) for the rendering script. The rendered result is as follows:

![td](https://user-images.githubusercontent.com/6052970/47779002-650ab200-dcf8-11e8-937d-0b318a9aa032.png)

What do you think of the general aspect of the diagram? Does it look satisfactory to the group to be incorporated in the general spec rendering process?

**Comment by vcharpenay** [comment]
![td](https://user-images.githubusercontent.com/6052970/48269617-4ca54080-e438-11e8-9e2b-dd1ffef732cb.png)

**Comment by vcharpenay** [comment]
(cardinalities and default/mandatory properties were added)

**Comment by takuki** [comment]
@vcharpenay When there is a default value for a value property, wouldn't that mean it is a mandatory field? This is because [section 5](https://www.w3.org/TR/2018/WD-wot-thing-description-20181021/#sec-vocabulary-definition) is about the model, not about serialization. I am not sure if we need to mention about default value in the diagram because it is not about serialization.

**Comment by vcharpenay** [comment]
well, I was merely imitating the choice of @sebastiankb to highlight mandatory fields, I didn't think much about it. But, thinking about it, the UML spec includes default values and I also think it is relevant. 

What I can do, however, is to remove the `(mandatory)` token whenever a default value is defined.

**Comment by sebastiankb** [comment]
The diagrams are now in the TD spec.

Lets discuss in tomorrow's web meeting about the mandatory and default members.

**Comment by sebastiankb** [comment]
AI: make a editor note that the diagrams will be improved in layout.

**Comment by sebastiankb** [comment]
I made an own issue for the id bug #317 
I will close this issue.
