### ISSUE TITLE
Thing Interfaces / Thing Models

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#279]
This issue summarizes discussions we had in different contexts:
(See also issue https://github.com/w3c/wot-thing-description/issues/91)

We propose an *interface TD* that allows to define an *interface* for a class of things,
i.e. define common metadata, properties, actions and events.
This *interface* is a logical description of the interaction with devices 
(properties, actions and events), however it does not contain device-specific
information, such as a serial number, GPS location, or concrete protocol endpoints.

The *same interface TD* can be implemented by things from *multiple vendors*,
a thing can implement *multiple interface TDs*, define additional metadata 
(vendor, location, security) and define bindings to concrete protocols. 

An *interface TD* can be included in a TD either directly or be imported with an *import* statement.

This common interface TD permits to write common applications across vendors and 
creates a more attractive market for application developers.
A concrete thing (instance) can implement multiple *interface TDs* and 
aggregate function blocks into a combined device.

All devices with the same interface can be managed in the same way by cloud applications
and the business models of cloud vendors are typically built on managing thousands of identical devices.
It is simple to create multiple simulated devices, if the interface and the instance are treated separately.

Semantic annotations only partially address this problem and don't work for plain JSON serialisations.

**Comment by sebastiankb** [comment]
This approach can be implemented by TD templates (= have a TD without binding information) and can be implemented with the current TD specification. A conflict can be the relative new "id" field, which is mandatory and _Thing_ specific.

**Comment by mlagally** [comment]
I agree - the current TD spec does enable this feature.

I will create a section for the TD spec to describe thing templates, will have a draft available for review at the next TD call (16.11.)

**Comment by sebastiankb** [comment]
ok, thanks. I will put this on the agenda.

**Comment by mlagally** [comment]
Here is the pull request:
https://github.com/w3c/wot-thing-description/pull/205

**Comment by sebastiankb** [comment]
Thanks. A TD sample would be nice. 
Lets talk about this in tomorrows web meeting.

**Comment by sebastiankb** [comment]
Thing Template concept can be found in Annex https://w3c.github.io/wot-thing-description/#Thing%20Templates

Please review.

**Comment by mlagally** [comment]
I have reviewed the thing template section in Annex B, which is fine for me.

**Comment by ToruKawaguchi** [comment]
[5.2](https://w3c.github.io/wot-thing-description/#interactionpattern) shows "forms" are mandatory and actually validation of [Example 31](https://w3c.github.io/wot-thing-description/#ex-31-mylampthingtemplate-serialized-in-json) fails. Maybe we need to ether 1) make forms optional in spec, 2) put empty forms array in TD template or 3) clearly state in the spec that the thing template is not TD itself thus cannot be validated.

**Comment by sebastiankb** [comment]
I'm agree with @ToruKawaguchi to be more clear here about the relation to the Thing Description.

@mlagally I think this paragraph have to be modified here:
>Since a Thing Template is a Thing Description, where some optional parts are not present, it can be serialized in the same way and into the same formats as a thing description. 

Proposal:
Since a Thing Template is a subset of the Thing Description in which some optional and mandatory vocabulary terms does not exist, however, it can be serialized in the same way and in the same formats as a Thing Description. Note that Thing Template instances cannot be validated in the same way as Thing Description instances due to missing mandatory terms.

What do you think?
