### ISSUE TITLE
Assertions for namespace / JSON-LD context file

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#280]
Related issue: https://github.com/w3c/wot-thing-description/issues/56

Chapter 5 is normative and is referencing Chapter 3. 
It should be clarified if Chapter 3 is normative as well.
If it is, it needs to be clarified, if the linked resources at https://www.w3.org/ns/td are also normative.
They are currently marked as "experimental".

**Comment by maximelefrancois86** [comment]
The namespace definition has no meaning for the JSON TD. This section should be maked non-normative, at minimum.

What I propose is to take up an action to move all references to namespaces, JSON-LD, context, ontologies, RDF, to a separate Group Note (i.e., non normative).
We already discussed about this with @vcharpenay and I started to draft this separate document.

**Comment by takuki** [comment]
@maximelefrancois86 , I think we still need to preserve text in [section 6.1 Representation Format](https://www.w3.org/TR/2018/WD-wot-thing-description-20181021/#json-serializiation-section) that says "Thing Description instances MAY contain JSON-LD 1.1 keywords such as @context and @type." in order to enable adding such annotations described in a separate Note.

**Comment by mkovatsc** [comment]
If Section 3 is non-normative, how do we standardize which terms are allowed and what meaning they have?

**Comment by mkovatsc** [comment]
Right, they are all "printed out" in Section 5.

**Comment by mlagally** [comment]
@mkovatsc Section 5 is agnostic of any serialisation, so it does not know about JSON-LD. Do you mean section 6?
This brings back another problem, we discussed some time ago. 
How are other JSON-LD keywords treated - are they permitted, forbidden, do they have a meaning?

**Comment by mlagally** [comment]
After discussion with @mkovatsc we identified a possible solution for the "chapter 3" question.

If the JSON-LD context file is used for some automatic processing when parsing a TD, 
it cannot be in the current state of a being "experimental".
There needs to be (an) assertion(s) in the JSON-LD serialisation chapter of chapter 6 to
clarify, if the context file can be used for validation of a TD and which additional guarantees
on the format of a TD this assertion(s) implies.

**Comment by mkovatsc** [comment]
> Section 5 is agnostic of any serialisation, so it does not know about JSON-LD. Do you mean section 6?

As we discussed, the question is not if some piece of information is normative or not, but if there is a normative assertion (RFC 2119 language) that refers to such a piece of information. Without such an assertion there is no sensible meaning.

Thus, what is missing is one or more assertion that state how to handle the terms included in the namespace and listed in Section 5 (e.g., "All TD serializations MUST contain all mandatory TD fields and MAY contain the optional TD fields as defined in Section 5"). Again, the question is the not which section is normative, but in which section we put the assertion (which makes a section normative -- the statement "this section is (non-)normative" is just a hint for the reader).

**Comment by mkovatsc** [comment]
> How are other JSON-LD keywords treated - are they permitted, forbidden, do they have a meaning?

In Section 6.1 we have "In addition, Thing Description instances MAY contain JSON-LD 1.1 keywords such as @context and @type." So yes.

Probably we need additional statements for how raw JSON parsers shall handle them.

**Comment by maximelefrancois86** [comment]
I think the best option is to have JSON-LD in *sub-documents*, to account for arbitrary semantic annotations that TD parsers could safely ignore. These could be the values for some key `annotation` that could be placed in different places in the TD: 

"The value of key `annotation` is free and SHOULD be a valid JSON-LD 1.1 document, with keywords such as @context and @type."

**Comment by vcharpenay** [comment]
If annotations are to be provided outside property, action and event definitions, then we would be better off if they were provided in _separate_ documents. Every entity in a TD is indeed identified by an IRI that can be computed from the Thing's `id` field, meaning that the TD can be integrated in any RDF store. This approach would at least make the case for using RDF in WoT.
