### ISSUE TITLE
Fix links on the HTML documentation of wot-security and json-schema vocabularies

### ISSUE THREAD

**Issue by vcharpenay** [w3c/wot-thing-description#287]
@draggett, the links point both to http://www.w3.org/ns/json-schema (wihtout the `.ttl` extension), humans cannot access the Turtle files.

**Comment by sebastiankb** [comment]
@draggett this issue seems to be still valid

**Comment by sebastiankb** [comment]
close this one since we have this issue here https://github.com/w3c/wot-thing-description/issues/432
