### ISSUE TITLE
Copy paste error in the description in Example 21

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#288]
The *JSON* serialization example in Example 21 mentions *JSON-LD 1.1 serialization*, this should be *JSON* serialization.

<pre class="example" title="MyLampThing represented as a compact JSON serialization">
{
    "id": "urn:dev:wot:com:example:servient:lamp",
    "name": "MyLampThing",
    "description" : "MyLampThing uses JSON-LD 1.1 serialization",

**Comment by sebastiankb** [comment]
thanks. just fixed that
