### ISSUE TITLE
Update information model figures to account for Security Definitions

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#289]
The Security Definitions update (https://github.com/w3c/wot-thing-description/pull/284) recently merged changes the information model since now "security" should refer to an array of named SecuritySchemes given in a securityDefinition block, not contain SecurityScheme objects itself.

But this is not what the main class diagram shows.   It needs to be updated, and this issue is to remind ourselves to do so (presently manually, although if these figures become autogenerated that would be another way to resolve this issue).

**Comment by sebastiankb** [comment]
the figures are now auto generated based on the semantic definitions. I think, this issue can be closed.

**Comment by mmccool** [comment]
Done.
