### ISSUE TITLE
(Intentional?) Removal of stability in property

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#29]
The "last" Current Practices document had the possibility to specify `stability` (see [here](http://w3c.github.io/wot/current-practices/wot-practices-duesseldorf-2017.html#property)).

This term was meant describe  the expected period in ms the Property value is expected not to change.

The current [TD specification](https://w3c.github.io/wot-thing-description/) misses this term. Even though I do not have a specific use case in mind I do not recall a discussion about removing it.

**Comment by takuki** [comment]
Hi @danielpeintner . 
To implement this request, I think we need to modify the model to incorporate it,
I do not remember if we have discussed on "stability" as part of the model discussion or not.

**Comment by takuki** [comment]
The least we can introduce is whether a property is mutable or not. If not mutable, the property value will never change, therefore, other things do not check the value again. In general, how often a value gets changed may not be inherent to the kind of property, but the use cases and context that use the device. For example, a light in a 24-hour convenience store seldom gets turned off.

**Comment by sebastiankb** [comment]
Based on the new features provided by the new [protocol template deliverable](https://rawgit.com/mjkoster/wot-binding-templates/initial-spec-contribution/index.html) the 'Obserable' variable does no make sense anymore. I would prefer to go back to stability/mutable flag since this can be seen as protocol independent information. What do you think?

**Comment by sebastiankb** [comment]
This discussion is outdated. The _observable_ term seems to be established.
