### ISSUE TITLE
range of jsonschema:minimum and jsonschema:maximum

### ISSUE THREAD

**Issue by maximelefrancois86** [w3c/wot-thing-description#295]
In the JSON Schema ontology,

the range of `jsonschema:minimum` and `jsonschema:maximum` is set to `xsd:double`

the `jsonschema:IntegerSchema` class has a local restriction that values for `jsonschema:minimum` and `jsonschema:maximum` are `xsd:integer`s.

this causes the following issue:

if I add:

```
[] rdf:type jsonschema:IntegerSchema ; jsonschema:minimum 3 . 
```

then the resulting ontology is inconsistent.

**Proposed solution:**

* delete the range of `jsonschema:minimum` and `jsonschema:maximum`.
* keep local restrictions,

**Comment by vcharpenay** [comment]
almost all axioms have been removed, in preparation for a more careful axiomatization of the WoT-related vocabularies, if time allows it.
