### ISSUE TITLE
td:scope is used but does not defined

### ISSUE THREAD

**Issue by maximelefrancois86** [w3c/wot-thing-description#296]
In the TD ontology document,

`td:Action` has a local restriction on property `td:scope`, and the object is `td:Specification` .

* `td:scope` is not defined in the TD ontology
* The spec state that the object of key `scopes` is an arry of strings (an not an array of specifications)

**Proposed solution**

Delete this restriction

**Comment by mmccool** [comment]
Hmmm... "scopes" is defined in wot-security.   Is this perhaps a typo, or was td:scope meant to have a different meaning entirely?

**Comment by vcharpenay** [comment]
probably not. I have just removed almost all axioms anyway, as axiomatization was generally not consistent.
