### ISSUE TITLE
Property names should be singular

### ISSUE THREAD

**Issue by maximelefrancois86** [w3c/wot-thing-description#297]
Several properties in the TD Ontology end with an 's' , although they should not

`td:properties`, `td:actions`, `td:links`, `td:forms`, `td:events`

with definition (e.g. `td:events`: "All Event-based interaction patterns of the Thing")

**Proposed resolution**

Adopt best practice to **use singular for properties in the ontology**

(e.g. `td:event`: "Links a Thing to an event-based interaction pattern of that Thing")

**Comment by zolkis** [comment]
I guess it's because they denote multiplicity and it's intuitive to use plural.
What is the rationale for using singular name for a set of similar items?

**Comment by maximelefrancois86** [comment]
Well, 

JSON-wise, plural is fine: the object is an array of things:

```
{ 
 "@id": "mything",
  "properties": [  {prop1} , {prop2 ]
}
```

ontology-wise, the predicate is used multiple times: 

```
hasProperty( mything , prop1 )    AND   hasProperty( mything , prop2 )
```

in RDF:

```
<mything> td:hasProperty  <prop1> .
<mything> td:hasProperty  <prop2> .
```

So you really want to use singular here.

http://wiki.opensemanticframework.org/index.php/Ontology_Best_Practices#Naming_and_Vocabulary_Best_Practices

**Comment by mmccool** [comment]
We've already been gone back and forth on this issue multiple times.  In the JSON file itself the plural is more natural, IMO.   Also, we have other things to worry about, I don't think we should change this (again).

**Comment by maximelefrancois86** [comment]
@mmccool, right! No change in the JSON, I definitely don't want to slow the process towards REC track !

**Comment by draggett** [comment]
The RDF predicate for asserting something is a property is defined in the default JSON-LD context, right, so there should be no difficulty in mapping "properties" in the JSON into td:property in RDF, right?

**Comment by maximelefrancois86** [comment]
Right Dave, 

This issue is only related to the TD *Ontology*

It is not a problem to have plural in the JSON and singular in the ontology

All, this issue is labeled  rdf, we use this label to mark discussions related to the TD ontology (and the mapping from TD-JSON to RDF). Feel free to ignore them and concentrate on the TD document, as the ontology may be described in a separate document with a different status and different timeline: 

 - TD-JSON as a REC: will go through stages Last Call WD -> Candidate REC -> Proposed REC -> REC (tight timeline)
 - the TD ontology as a group Note -> will just require a vote by the group to be published

**Comment by vcharpenay** [comment]
has been fixed today. See [ontology doc](https://w3c.github.io/wot-thing-description/ontology/td.html).
