### ISSUE TITLE
Include JSON Schema's "anyOf", "allOf" and "not"?

### ISSUE THREAD

**Issue by vcharpenay** [w3c/wot-thing-description#298]
There was a discussion to include JSON Schema's `oneOf` to be able to define human-readable labels for enumeration values (see #156). JSON Schema also defines the following keywords:
 - `anyOf`
 - `allOf`
 - `not`

Shall we consider adding them to the TD model as well?

**Comment by mmccool** [comment]
I should also note that we don't have test cases for devices that use these even in payloads.  However, there are certainly examples where they make sense (for example, a text field that might be a simple string OR a multi-language object).

**Comment by sebastiankb** [comment]
please see issue  #406
