### ISSUE TITLE
Assertions should be self-contained

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#301]
Assertions should be self-contained and not use pronouns (like "this" or "it") or otherwise depend on context.   This is important for when we cite their text out of the immediate context of the spec, most importantly in the implementation report.   It also helps to reduce ambiguity.

For example, there are few assertions that all have the same/similar text, but in fact one set refers to Actions and other to Events.   In context they make sense, since they are in those sections (in fact in a list of related assertions), but out of context they are ambiguous.  Probably these should be worded so they each explicitly mention Actions and Events, respectively.  

Another example is that some assertions include Section references that depend on ReSpec filling in the section title (when the body of an anchor is blank) but that is broken when the assertion is used out of context, e.g. in the Implementation Report.   In the draft Implementation Report right now there are a bunch of assertions that end in "in".   In the spec body these are actually referring to a section, but the title is blank in the Implementation Report.   We *could* fill in the section reference manually... but breaking automation is annoying and error prone, and the section reference also makes the assertion non-self-contained.   Perhaps we should fill in the section title (only) manually in the spec itself if we must use it.

**Comment by sebastiankb** [comment]
I think, this is not relevant anymore.
