### ISSUE TITLE
Form contentType vs. Link type

### ISSUE THREAD

**Issue by benfrancis** [w3c/wot-thing-description#306]
I noticed that in #260 `mediaType` was renamed to `contentType`, but that while forms now use `contentType`, links use `type`. Is there a reason for this difference, or should links now be `contentType` as well?

**Comment by mkovatsc** [comment]
Forms have `contentType` with its own definition, an instruction for clients to use this content type in requests and it also being the expected content type of responses (with the content type header field still taking precedence).

Links are now following RFC 8288 vocabulary without renaming, where `type` is a hint for the target's media type (no parameter support).

**Comment by sebastiankb** [comment]
close the issue.
@mkovatsc answered regarding the use of the `contentType` in the TD and the relationship to web linking.
