### ISSUE TITLE
support term should be a URI type

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#310]
URI are typically used to signalize support information such as email = "mailto:someone@example.com" or telephone number = "tel:+1-201-555-0123".

So, we should retype "support" term from string to uri

**Comment by sebastiankb** [comment]
also see https://www.ietf.org/rfc/rfc3966.txt and https://en.wikipedia.org/wiki/Mailto

**Comment by danielpeintner** [comment]
I agree that in some cases the URI type is probably a good advice to use. 

Anyhow,  I personally do not see a very convincing argument to limit the term. Can anyone point me to these arguments...
Being more generic, by at the same time stating a good practice, sounds better to me.

**Comment by mmccool** [comment]
I personally think we should start with a general string.  In a future update to the standard (WoT next), we would still allow either strings or objects with specific support metadata, some of which can be URIs.  The problem with using a URI is that you have to parse it to figure out (eg infer) what kind of support metadata is being provided.

I think restricting this to a URI is counter-productive   I agree with @danielpeintner that being generic while stating a good practice would be better.

**Comment by sebastiankb** [comment]
ok, it seems to be the tendency to go back to string definition.

**Comment by sebastiankb** [comment]
please review
