### ISSUE TITLE
top level assertions

### ISSUE THREAD

**Issue by draggett** [w3c/wot-thing-description#312]
A collection of observations after thinking about testing.

The TD specification should state that valid TDs MUST be valid JSON-LD. This would also imply that valid TDs MUST be valid JSON. In other words, valid TDs are a subset of valid JSON-LD documents, which in turn is a subset of valid JSON documents.

In the testing discussion, we agreed that we believe that the TD specification doesn't define the behaviour of implementations in respect to invalid TDs, is that correct?

The TD specification can be considered as defining a syntax for the set of valid TD documents, and the required behaviour in respect to valid TDs.  We presumably expect the TD specification to define the behaviour for both producers and consumers of TDs, right?

Some examples of what I mean by that:

A consumer of TDs should signal an error to the consumer application when the application attempts to set a property to a value that conflicts with the data schema defined in the TD for that property.

A producer of TDs should signal an error to the producer application when the application attempts to set a property to a value that conflicts with the data schema defined in the TD for that property.

Likewise, a producer application raises an event with data that conflicts with the data schema defined in the TD for that event.

Likewise for values passed to, or returned from actions: 

A producer of TDs should signal an error to the producer application when it attempts to return a value that conflicts with the data schema defined in the TD for that action.

A consumer of TDs  should signal an error to the consumer application when it attempts to pass a value to an action that conflicts with the data schema defined in the TD for that action.

A consumer of TDs  should signal an error to the consumer application when the action has failed to complete as expected, e.g. due to an internal error in the producer application or due to a network failure.

Do we want to require producers of TDs to signal an error when the producer application attempts to  set the value of a property that is missing from the TD?   Likewise for invoking undeclared actions and events?

Some other kinds of errors the TD specification could cover include timeouts when the expected behaviour is not completed within the time expected, when a bearer token is invalid, so that the expected behaviour was not carried out. Are producers and consumers of TDs expected to signal to their applications network errors, e.g. the loss of connectivity?

Finally, as Michael Lagally noted, the TD specification should clearly state that additional metadata fields are permitted rather than limiting valid TDs to just the vocabulary terms defined by the TD specification.

**Comment by mmccool** [comment]
Anyway, Dave, I noticed a lot of your proposed assertions on "TD Producers" also assume the TD Producer is also the Thing.   This is not a good general assumption, there are lots of cases where a TD is provided by a separate network service, not by the Thing itself.   Of course the latter is an important use case, but I think we need to keep these roles separate.

Of course, if a Thing DOES know about the TD and is a made-for-WoT device, than it can take advantage of that to provide enhanced error checking, etc.  But I don't think we can require it in the specification due to the need to support retro-fitted devices.

**Comment by draggett** [comment]
I agree and think it would be helpful if we could clarify this further as part of the implementation report and CR exit criteria. 

If the TD describes a separate device that clients connect to directly, then I would expect that the TD provides a faithful description, e.g. that property values correspond to the types declared in the TD, and likewise that the events and actions are as described and will work as expected. I agree that we not in a position to alter the behaviour of such devices. For the CR exit criteria, I think this means that we should only count devices that comply with the TDs that describe them.

For things exposed by WoT platforms, we can go further and constrain the expected behaviour at an abstract level without the need to bind to a specific API.  This suggests that we should have additional tests for the producer side abstract API, e.g. raising errors when the producer application tries to set a property value, event  or action response that conflicts with the TD.
