### ISSUE TITLE
Term "form" left in Example

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#313]
Minor editorial issue in Example 12
https://w3c.github.io/wot-thing-description/#ex-12-example-12-actions-leftdown-urivariables-p-type-integer-minimum-0-maximum-16-type-example-somekindofangle-d-type-integer-minimum-0-maximum-1-type-example-direction-form-http-method-get-href-http-192-168-1-25-left-p-d

It still contains the term `"form"` while I think it should be `"forms"`

**Comment by sebastiankb** [comment]
thanks. just fixed that.
