### ISSUE TITLE
Relation ObjectSchema to DataSchema should be 0..N

### ISSUE THREAD

**Issue by DerTanzschuh** [w3c/wot-thing-description#315]
In [Figure 2 TD data schema model](https://www.w3.org/TR/wot-thing-description/#overview) the relation from class `ObjectSchema` to `DataSchema` is annotated with cardinality `0..1`. According to the samples, in particular [example 7](https://www.w3.org/TR/wot-thing-description/#ex-7-example-7-properties-on-label-on-off-type-boolean-forms-status-type-object-properties-brightness-type-number-minimum-0-0-maximum-100-0-rgb-type-array-items-type-number-minimum-0-maximum-255-minitems-3-maxitems-3-required-brightness-rgb-forms), this should be `0..N`. Since a property of type `object` can have more than one child property (in this example `brightness` and `rgb`).

Or am I wrong and have I misunderstood this point?

**Comment by sebastiankb** [comment]
Thanks for your comment. Your mentioned relationship refers to the term 'properties', which can only be used once in each level.  The properties term is serialized as JSON object where the member are use case specific such as `brightness ` and `rgb`. More details about this can be found here: http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.5.4

In general, there is no chapter in the TD that explains the use of the subset of JSON schema usage in more detail. I will try to address this this week.

**Comment by sebastiankb** [comment]
there is now a section explaining the data schema usage 

https://w3c.github.io/wot-thing-description/#data-schema-serialization-json

please review.
