### ISSUE TITLE
Example 1 missing contentType

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#319]
contentType of forms are mandatory in the spec but Example 1 doesn't have any form with contentType

**Comment by sebastiankb** [comment]
this is not a bug. If mandatory terms with a default value are missing then there is the implicit default assumptions that this term is applied with the default value. Explaination are giving here: https://w3c.github.io/wot-thing-description/#Implementation-Note-section

**Comment by egekorkan** [comment]
Ok then I close this issue
