### ISSUE TITLE
Assertion/Schema mismatch for td-{property,event,action}-arrays

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#321]
The assertions for td-property-arrays and td-event-arrays mention that the values of "required" and "enum" should be serialized as arrays but there are no specifications for this in the master JSON Schema, which is probably a bug in the schema. The assertion for td-action-arrays does not mention these but I suspect that is a bug in the assertion.

Discovered during TestFest while trying to write tests for these.   See https://github.com/egekorkan/thingweb-playground/pull/2

**Comment by sebastiankb** [comment]
Is this issue solved based on your PR https://github.com/egekorkan/thingweb-playground/pull/2 ?

**Comment by sebastiankb** [comment]
I think, this problem is solved based on the comments above

**Comment by takuki** [comment]
Both assertions td-property-arrays and td-event-arrays are about "forms", which is different from @mmccool says are about "required" and "enum". Maybe those ids were re-assigned recently. I agree it is clearly mentioned now in the new section @sebastiankb pointed to.
