### ISSUE TITLE
readOnly and writeOnly should be optional for action parameters

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#322]
These flags don't make sense for the input and output parameters of an action.
Since both of them already are defined with a default value, 
which would give them a defined behaviour if they were omitted on properties too, 
they should be optional in general.

**Comment by sebastiankb** [comment]
thanks for the hint. This was a bug. In the past, the old `writable ` term was always optional. I also changed the default value for `readOnly ` to `true`.

Please review.

**Comment by mmccool** [comment]
Actually, while writing test cases I noticed that readOnly and writeOnly only recently became optional (they are marked as mandatory "no" in the tables).  I concur that if they have default values they should be optional in general.   This is good as it reduces verbosity... but the JSON Schema is currently incorrect, and marks these as "required", and so TDs that omit them fail validation.

To clarify: the JSON schema in the Editor's draft is even MORE wrong as it still refers to "writable".   I'm referring to the version of the JSON schema we are using for the Test Fest, which is currently in a PR submitted by Ege.

**Comment by mlagally** [comment]
These fields are still mandatory in the latest editors draft at https://w3c.github.io/wot-thing-description/

**Comment by mkovatsc** [comment]
Fields with a default value are mandatory, but because they have a default value, they do not have to be serialized. Optional fields can be left undefined.

Why the change to a non-false default value?! This is against general design patterns (cf. undefined evaluates to false).

`readOnly: false` is also the better choice for Action parameters / `input`. It can then be omitted. For `output`, it has no meaning. If you keep readOnly default true, you have to state it in every schema for Action inputs.

**Comment by sebastiankb** [comment]
both vocabulary terms are mandatory with the default value = false. Section 6.1 Basic Representation Format Assumptions explains that such terms (and others) can be omitted in the serialization. 

Please review if this ok for you.

**Comment by mlagally** [comment]
@sebastiankb I reviewed the section 6.1., we can close this issue.

**Comment by mlagally** [comment]
During the testfest it became apparent, that readOnly and writeOnly for input
and output parameters of actions don't make a lot of sense.

Input parameters and output parameters are just passed in and out,
but the notion of readOnly/writeOnly does not really match.

**Comment by sebastiankb** [comment]
readOnly and writeOnly can be omitted for the input and output
