### ISSUE TITLE
Require UTF-8 encoding of TDs

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#331]
In [RFC8259, section 8.1](https://tools.ietf.org/html/rfc8259#page-8), it states that JSON used outside of "closed ecosystems" MUST be encoded using UTF-8.

We should state this requirement explicitly for TDs, since they are meant to be used in open ecosystems, and note this in the spec.

This is especially important for TDs using the multi-language features and non-Latin-1 languages.

**Comment by mmccool** [comment]
In fact it's a little more complex than that... here are the exact constraints from RFC8259 (the entirety of section 8.1):
```
   JSON text exchanged between systems that are not part of a closed
   ecosystem MUST be encoded using UTF-8 [RFC3629].

   Previous specifications of JSON have not required the use of UTF-8
   when transmitting JSON text.  However, the vast majority of JSON-
   based software implementations have chosen to use the UTF-8 encoding,
   to the extent that it is the only encoding that achieves
   interoperability.

   Implementations MUST NOT add a byte order mark (U+FEFF) to the
   beginning of a networked-transmitted JSON text.  In the interests of
   interoperability, implementations that parse JSON texts MAY ignore
   the presence of a byte order mark rather than treating it as an
   error.
```

**Comment by sebastiankb** [comment]
Since we now relying on JSON-LD 1.1 again, do we need this kind of information?

**Comment by sebastiankb** [comment]
@mmccool makes a PR

**Comment by mmccool** [comment]
Going to add the PR, using the text suggested above.   JSON-LD 1.1 documents are still JSON documents.  Basically what the above does is limit options to enhance interoperability and simplify implementations... but doesn't really change what people *should* be doing.

**Comment by mmccool** [comment]
See PR https://github.com/w3c/wot-thing-description/pull/543.   I shortened the above text but it does add four assertions.
