### ISSUE TITLE
TD Event in Thing-to-Thing interactions

### ISSUE THREAD

**Issue by AndreMaz** [w3c/wot-thing-description#333]
The latest (Draft 20 December 2018) `Event` specification introduces the `data`, `subscription` and `cancellation` params. Where:

- `subscription` defines *data that needs to be passed upon subscription, e.g., filters or message format for setting up Webhooks.*
- `data` defines *the data schema of the Event instance messages pushed by the Thing.*

The `subscription` definition refers the possibility of using webhooks. So the following situation is possible:

![v2](https://user-images.githubusercontent.com/9802754/50493825-c65cb200-0a17-11e9-8773-d11299879e6c.jpg)
> **Note**: Since there is no specification of `subscription` internal structure I've created a dummy payload to represent an *Event Subscription* request.

This figure represents a situation where a user configures a relation between a `Button` and a `Light`. When the `Button` is pressed it pushes `clicked` Event to `Light`´s Action endpoint (`light.com/action/on_off`) to turn it `on`.

However, according to current Event spec, the pushed data is static and it is defined in Event's `data` tag. Due to this, the `Light`, which doesn't have any context about the subscription, won't know how to parse the incoming `data` and, therefore, it will reject it. Am I right?

My question is: how to model this example? Who will be responsible for transforming the `clicked` Event into the `Light`´s Action acceptable input (`on` or `off`)? Overall, this kind of interactions are in or out of TD's scope?

I think that in most cases this won´t be an issue as Things will be managed by a gateway, which will be responsible for such translations (e.g.: Mozilla Gateway with their Rules)
However, in situations where gateway in not available, Thing-to-Thing interactions will still happen so how to deal with them?

**Comment by AndreMaz** [comment]
> In general, the purpose of the Events are that clients can make subscription on it and not vice versa.

In this case, I think that Event's description should be clearer. IMO the `subscription` and `cancellation` descriptions give an impression that the preferred method is Webhook. The [Thing-to-Thing example](https://w3c.github.io/wot-architecture) in WoT Arch also led me to believe that Webhook is preferred.

> To overcome your issue, there are multiple ways to solve it

It's not an actual issue, I was just thinking about T2T interactions from a consumer point of view. I've simply imagined a hypothetical situation of buying a `TD Light` and a `TD Button`. As a consumer I wouldn't be able to program either of them. Only configure. The goal were to find out how to create a simple situation like: _when Button's Event is triggered the Light Action should be invoked_.

Both of your solutions are valid. However:

#### Solution 1 - Light (Server + Client) + Button (Server)

> The Light has also a client running that makes a subscription on the click event of the button. If a new click event arrives, the lamp is toggled. To setup this relation via smartphone, an additional action can be offered by the Lamp.

I agree that this is the best and most flexible approach... The responsibility of parsing/processing the incoming Events would be on the client side and the TD would be simple and clean. Still, there will be Things that won't have an embedded client and the "no-client-no-T2T-interaction" approach seems restrictive.

#### Solution 2 - Light (Server) + Button (Server + Client)

> The button offers an action to setup the button client such as that an onOff action of the lamp has to be called when button was pushed.

I was thinking along the same lines but I haven't considered the possibility of an additional Action on `Button` side. It will work but it doesn't seem to be a straightforward way of doing T2T interactions.

---

Why not make the Event more flexible? I will try to explain better what I mean.

As I see the events can be transferred from Button to Light either by:

- **Case A** `Observation/Polling` where Light's embedded client would be responsible for getting and processing the data. This situation falls under the **Solution 1** that you've proposed and no changes has to be done to the Event.

- **Case B** `Push` where Button's embedded client would `POST/PUT` notifications, when Button is clicked, to a certain URI (e.g.: Light's Action).

For **Case B**: why not allow the Event to (optionally) push a custom notification?

In the [Light + Button + Smartphone example](https://user-images.githubusercontent.com/9802754/50493825-c65cb200-0a17-11e9-8773-d11299879e6c.jpg) the smartphone would have to provide: `filter params` + `destination URI` + `custom notification`. Then, instead of pushing static `data` as defined in current spec, a `custom notification` would be sent.

Overall, the Event behavior could be as follows:

**Default behavior** - Event's `data` is pushed.

In this case, during the `subscription` the client would have to provide the `filter-params` + the `destination URI`. Then, by default, the Event would push `data`.

The default behavior would simply provide a log of events.

**Custom behavior** - Event pushes `custom notification`.

In this case, during the `subscription` the client would have to provide the `filter-params` + the `destination URI` + a `custom notification`. Then, every time the `filter-params` are satisfied the `custom notification` is sent to de `destination URI`.

The custom behavior would act as a local If-This-Then-That.

---

I know beforehand that this would make TD more complex but it would provide freedom to the creators/developers of the Things. It would be up to them to implement Event as they like (either with default behavior or with custom behavior).

**Comment by AndreMaz** [comment]
Also, in some `Observation` situations the static `data` may not be really need. 

For example: Client makes subscription request to an Event with a filter parameter (e.g: example `threshold=25` or `state=clicked`). In this case there is no need to send the `data` every time the filter params are met.
Since the subscription was initiated by the Client, it can infer that the Event has occurred only by looking at the headers of incoming message. The actual contents of `data` are optional.

Should there be a special keyword to inform the Server that there is no need to send the `data`?

**Comment by sebastiankb** [comment]
At the moment the TD TestFest is running and for the event I tried to set up a TD, which should follow your desired goal. Please take a look at this example and let me know if this is the direction you would expect.

https://github.com/w3c/wot/blob/master/testfest/2019-02-princeton/TDs/Siemens/eventTest-siemens.json

**Comment by AndreMaz** [comment]
Also, are you using some specific vocab in your example?

**Comment by takuki** [comment]
Can we use uriVariables (or similar) for customizing data so that the event recipient can process the data properly?
