### ISSUE TITLE
In section 5.4, CoAP, MQTT are refered.

### ISSUE THREAD

**Issue by PaulJeong14** [w3c/wot-thing-description#334]
CoAP and MQTT are referred In the section of 5.4 Security Vocabulary Definition, and also in the section of 1. Introduction.

> In general, the TD provides metadata for different communication bindings identified by URI schemes (e.g., "http", "coap", "mqtt", etc.), content types (e.g., "application/json", "application/xml", "application/cbor", "application/exi" etc.), and security mechanisms (for authentication, authorization, confidentiality, etc.).

> Security schemes appropriate for IoT-centered protocols such as CoAP and MQTT are therefore also included.

But no references in the references section. 
I suggest put below references into the section E.

[RFC7252]
The Constrained Application Protocol (CoAP). Z. Shelby, K. Hartke, June 2014. IETF. URL: https://tools.ietf.org/html/rfc7252

[MQTT] 
Message Queuing Telemetry Transport. Richard Coppen. Andrew Banks, Ed Briggs, Ken Borgendale, Rahul Gupta. OASIS. 31 Oct 2018. URL: https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html

**Comment by sebastiankb** [comment]
references are not in there. 

please review.
