### ISSUE TITLE
confused in using JSON-LD

### ISSUE THREAD

**Issue by PaulJeong14** [w3c/wot-thing-description#335]
TD uses JSON-LD. JSON LD is now under development to version 1.1. 

JSON LD standards in development are below : 

- JSON LD 1.1 syntax 
- JSON LD 1.1 Processing Algorithms and API
- JSON LD 1.1 framing 

In the TD document, the version of JSON LD is used in confusion.

For example, JSON LD 1.1 is referred to in section 5.2.2

> Each instance of a Property, Action, and Event class MUST have an identifier that is unique within the context of a Thing Description document. See Section Representation Format for more details about JSON-LD 1.1 identifiers.

but JSON LD 1.0 is referred to in section 6.4.2

> To interpret the semantic meaning of a Thing Description in terms of RDF triples, a Thing Description instance can be simple transformed into a RDF-based serializiation format by JSON-LD 1.0.

I don't know exactly how to handle this confusion in case of referring incompleted standard. 
However, to avoid this confusion, I suggest using only one version and put some editor's note for the risk that JSON LD 1.1 is not completed.

**Comment by sebastiankb** [comment]
Thank you very much for your comment. Originally, the plan was to be aligned with JSON-LD 1.1. However, the last f2f meeting in Lyon made it clear that some problems could not be solved in time. This means that we will have our own TD format with the option to convert to JSON-LD 1.0 (will be explained shortly at https://w3c.github.io/wot-thing-description/#note-jsonld10-processing).

Maybe in a future new TD version (e.g. TD 1.1) and when JSON-LD 1.1 is ready, I am pretty sure that we can rely directly on JSON-LD 1.1.

In the latest specification I removed all references to JSON-LD 1.1.
