### ISSUE TITLE
Group *similar* vocabulary terms together

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#336]
_PURELY EDITORIAL_

In some vocabulary term tables (e.g., for [DataSchema](https://w3c.github.io/wot-thing-description/#dataschema)) certain terms that according to my understanding belong together are spread _somehow_.

* `titles` is in the beginning of the table while `title` is almost at the end
* `description` is first and after some other terms `descriptions` follows
  * this is also a different order w.r.t to `titles` and `title`
* ...

I do know that this is a minor issue but from the users (readers) perceptive it would be beneficial to have similar terms next to each other.

**Comment by takuki** [comment]
@danielpeintner , I made changes to address this issue. Please review.

**Comment by danielpeintner** [comment]
Thanks!
