### ISSUE TITLE
Property extending DataSchema

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#338]
The TD spec states in [Section 5.3.2 Property](https://w3c.github.io/wot-thing-description/#property)  that 

> Property instances are also instances of the class DataSchema. 

Looking at the [Information Model](https://w3c.github.io/wot-thing-description/#sec-vocabulary-definition) and Figure 1 this seems not to be the case. The automatically generated [figure](https://w3c.github.io/wot-thing-description/visualization/td.svg) does not show any relation.

@vcharpenay is this missing in the ontology?

**Comment by vcharpenay** [comment]
There was a debate in TD telcos about this and no decision was taken, hence no relation in the ontology. @mariapoveda, @maximelefrancois86, how to deal with this issue?

At some point, there was the idea that properties differentiate from actions' input/output insofar that they represented schema _instances_. This view is not relevant anymore, after the discussion of #259 in which we established that an alignment `ssn:Property` ~ `td:Property` was not a good choice. Today, I think we can add `td:Property` < `schema:DataSchema`, maybe in a separate file.

**Comment by mariapoveda** [comment]
In my opinion the ontology does not need to include td:Property < schema:DataSchema in order to allow property instances to be also DataSchema instances, it is enough not making such classes disjoint. 

The td:Property < schema:DataSchema could be added in a separate file as extension rather than part of the model.

**Comment by sebastiankb** [comment]
Still, there is a arrow missing between property and DataSchema.

here is a similar issue about this https://github.com/w3c/wot-thing-description/issues/495 . we should wait until this issue is clarified.

**Comment by vcharpenay** [comment]
see #509.
