### ISSUE TITLE
Map of type

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#345]
The information model definitions (according to my understanding) are not 100% clear about which types are actually used.

Please take a look for example at [Thing](https://w3c.github.io/wot-thing-description/#thing) definition. It states that `securityDefinitions` is of type `SecurityScheme`. I think this is not correct, it should read `map of SecurityScheme` similar to the `array of` types.

e.g.,
```
"securityDefinitions": {
      "basic_sc": {"scheme":"basic", "in":"header"}
  }
```

`SecurityScheme` only defines the *inner* part: `{"scheme":"basic", "in":"header"}` and not that it needs to be wrapped in a map with a key.

A similar case applies for `properties`, `actions`, and `events`.

**Comment by ToruKawaguchi** [comment]
"version" also, right?

**Comment by ToruKawaguchi** [comment]
Additionally, there are explanations at "securityDefinitions and security" and "version" which are unclear what "JSON name" points. For example at <https://w3c.github.io/wot-thing-description/#security-serialization-json> : 
> Each mandatory and optional vocabulary term as defined in the class SecurityScheme, MUST be serialized as a JSON name.

There are similar descriptions at "property", "action" and "event" which are relatively clearer. For example, at "property" <https://w3c.github.io/wot-thing-description/#property-serialization-json>: 
> Properties (and sub-properties) offered by a Thing MUST be collected in the JSON-object based properties member with (unique) Property names as JSON names.

**Comment by danielpeintner** [comment]
> "version" also, right?

Mhh, I am not sure about `version`.
In this case it seems OK to me but let's clarify this also...

**Comment by ToruKawaguchi** [comment]
@danielpeintner thanks. Understood that version is not the case for "map".

**Comment by egekorkan** [comment]
I was handling this in the validation schema but just with human understanding skills, it should be clearer like mentioned :)

**Comment by egekorkan** [comment]
Following the discussion in Princeton Testfest:
"Map Of" seems to be accepted even though it is not an XML Schema. We have to handle it in a custom way, like a table that contains these cases. 
Also we would have to explain what "Map Of" means. 
Arrays would not be possible since we use real arrays for other vocab terms

**Comment by mmccool** [comment]
The definition of "Map of" should also state that keys should be unique, to resolve some remaining ambiguity around the use of "unique" in certain assertions.  Basically, we should state that keys within a map should be unique.  (but they no longer have to be unique AMONG different maps; see PR https://github.com/w3c/wot-thing-description/pull/436)

**Comment by mmccool** [comment]
I created a PR to render "map of" for the appropriate entries and define "map".   See PR https://github.com/w3c/wot-thing-description/pull/437.

**Comment by egekorkan** [comment]
This decision seems to be applied everywhere except securityDefinitions in Thing level (the initial issue reported by @danielpeintner )

**Comment by mmccool** [comment]
This seems to be related to the fact that templates.txt was updated to do this automatically somehow, using a strange rule I don't understand.  @danielpeintner or @vcharpenay may have to fix this.

**Comment by mmccool** [comment]
See PR https://github.com/w3c/wot-thing-description/pull/538

**Comment by mmccool** [comment]
I think think is fixed now and can be closed.
