### ISSUE TITLE
Differnt colors for <code> markup

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#349]
The tables in section 5 use the color red for both data types and constants.
It would be clearer if they had different colours to distinguish between them.

**Comment by mkovatsc** [comment]
I checked Section 5 and most all terms highlighted as red code are Vocabulary Terms. We could change the color of the XSD data types and maybe other terms I overlooked, which are not defined by us.

I propose dark blue.

**Comment by mkovatsc** [comment]
We now have a formal model based on Terms. There is actually nothing like constant vs data type anymore.

Could keep it on the backburner... marked it as propose closing.

**Comment by mmccool** [comment]
I see Matthias is proposing closing this.  We could keep it open but deal with it during the CR period as it is editorial.
If we do change the color of constants, don’t overlook the language tag examples in the text (en, az-Latn, etc).

**Comment by mkovatsc** [comment]
Let's check after some recovery if we can improve the text already in `code` markup further using different colors, e.g., Vocabulary Terms (maybe this is meant by constants) vs values.

**Comment by takuki** [comment]
I plan to work on this during CR period.

**Comment by sebastiankb** [comment]
I'm not sure if it still relevant?

**Comment by egekorkan** [comment]
In the call of 21.07.2021 we have decided to close this issue since it is not relevant anymore
