### ISSUE TITLE
[FPWD] Property has a field "writable" or "isWritable"? (in Section 4.2.3 Property)

### ISSUE THREAD

**Issue by takuki** [w3c/wot-thing-description#35]
In Section 4.2.3 Property., a term "isWritable"  is used, whereas it is "writable" in the figure in Section 4.1 Overview.

**Comment by takuki** [comment]
Edited the title of the issue.

**Comment by takuki** [comment]
Edited the title of the issue.

**Comment by zolkis** [comment]
Should be `writable` IMHO.

**Comment by takuki** [comment]
Thank you, @zolkis. 
Can @vcharpenay comfirm this?

**Comment by sebastiankb** [comment]
yes, is **writable** I will update the TD ontology

**Comment by sebastiankb** [comment]
done! I will close the issue
