### ISSUE TITLE
security in forms mentions lower levels

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#350]
The security key at form level has the following text:

> Set of security definition names, chosen from those defined in securityDefinitions. These must all be satisfied for access to resources at or below the current level, if not overridden at a lower level.

However, I think it should be:

> Set of security definition names, chosen from those defined in securityDefinitions. These must all be satisfied for access to resources at the current level.

This can be confusing due to two reasons:

1. In an interaction, there is nothing lower than the forms field.
2. In case there is forms field in the thing level to describe readallproperties etc. with a security scheme, one can understand that a single action in the "lower level" can require this security scheme.

**Comment by mmccool** [comment]
Addressed in PR https://github.com/w3c/wot-thing-description/pull/538.   I actually made it even simpler: "These must all be satisfied for access to resources."   The overriding behavior is specified by another set of assertions, so defining it here was redundant anyway.   But we do need to state the "all must be satisfied"

**Comment by mmccool** [comment]
PR merged, so this should be taken care of now.

**Comment by egekorkan** [comment]
Seems to be fixed
