### ISSUE TITLE
Event examples are not enough

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#351]
When it comes to events, I don't think that there are enough examples. It would help to show how subscription, cancellation key would look like. Also use of subscribeevent and unsubscribe event in the op field can be shown with an example, similar to Example 30. Maybe it can be added to this example

**Comment by egekorkan** [comment]
From Princeton:
Siemens showed an example TD, found in [inputs of the testfest repo](https://github.com/w3c/wot/blob/master/testfest/2019-02-princeton/inputs/Siemens/siemens-node-wot/eventTest-siemens.json).  We have to clarify how to subscription and cancellation would work.

**Comment by sebastiankb** [comment]
There is now an example provided in https://w3c.github.io/wot-thing-description/#t2t-event-example-serialization

Please review.

**Comment by egekorkan** [comment]
I think that this example makes everything more clear. However, I find that having targetURL as an input to the subscription can be confusing. One can ask what is the difference between the form with subscribeevent and the input for subscription, i.e. should I copy the form href for the targetURL? I think a better example would be having a frequency as an input to the subscription. Also I think description field in output would need some rephrasing. Proposal:
```
"subscription": {
            "input": {"frequency": {
                "type": "number",
                "description": "Indicates how frequently the event will be emitted by the event source"
            }},
            "output": {"subscriptionID": {
                "type": "integer",
                "description": "A unique subscription ID assigned by the event source"
            }}
        },
```

**Comment by mkovatsc** [comment]
There is a new Webhook Event example.

**Comment by egekorkan** [comment]
I find the example very good, it even emphasizes writeOnly/readOnly mechanism. Thank you @mkovatsc
