### ISSUE TITLE
use of scopes not clear

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#355]
Even though it is possible to use scopes in interaction level, there are no examples on this. All the examples are either to define the securityDefinition with scopes or in forms. 

If an interaction has scopes key in the interaction level, do all the forms of this interaction inherit it?

**Comment by mmccool** [comment]
Yes, all of the interactions would inherit it, just like any other security metadata declaration.  Listing it at the Thing or Interaction level is to be considered sematically equivalent to listing the same metadata in every form.

**Comment by egekorkan** [comment]
In this case, what happens if I have one form with oauth and one with nosec, how does nosec inherit this? In the spec there is also no example that use scopes with a security scheme other than oauth. Thus, I cannot see how other security schemes benefit from this.

**Comment by egekorkan** [comment]
Note: It should not appear in 5.2.2 InteractionPattern

**Comment by mmccool** [comment]
We also looked at the assertions and nobody used "security" at the interaction level either... it was used only at the Thing and Form levels.   So I propose removing both "scopes" and "security" at the Interaction level completely.

**Comment by sebastiankb** [comment]
just see, that `scope` term was removed from the InteractionAffordance class

**Comment by egekorkan** [comment]
It is fixed
