### ISSUE TITLE
td-event-response-arrays assertion is wrong

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#365]
In the spec there is the following text: "If required, the type of the member response MUST be serialized as a JSON array."
However, the model nor the vocabulary specify such a thing. I would also say that it does not make sense to use an array for response.
I would suggest removing this text and assertion altogether.

**Comment by sebastiankb** [comment]
thanks. Fixed this issue. The right type assignment is JSON object and not array. 

Please review.

**Comment by egekorkan** [comment]
The text is correct however the assertion id is still `td-event-response-arrays` I would offer to name it as `td-event-response-object`

**Comment by egekorkan** [comment]
This is fixed and can be closed
