### ISSUE TITLE
Rename 'Versioning' as 'VersionInfo'

### ISSUE THREAD

**Issue by vcharpenay** [w3c/wot-thing-description#370]
the term 'version info' (e.g. in [Android for IoT](https://developer.android.com/reference/com/google/android/things/update/VersionInfo) or the [Apache HTTP lib](https://hc.apache.org/httpcomponents-core-ga/httpcore/apidocs/org/apache/http/util/VersionInfo.html)) can be found elsewhere in similar contexts and is arguably more precise (as opposed to 'versioning' that may also refer to the general process of giving a version number to software artifacts).

**Comment by egekorkan** [comment]
I would be up for the change. It seems that the "Versioning" is used when we are talking about making versions of software whereas "VersionInfo" is used when we want to specify it in software. So if you google versioning you will find articles about how to properly name the versions and these articles will give examples using the word "VersionInfo", like @vcharpenay 's examples

**Comment by egekorkan** [comment]
Princeton Testfest:
It is agreed to use this new class name

**Comment by takuki** [comment]
I made this change. Please see the change [here](https://cdn.staticaly.com/gh/w3c/wot-thing-description/57831e2d4d05cf5fe04b6d165c2ab766b813ed6c/index.html#versioninfo).
