### ISSUE TITLE
uriVariable does not seem to be proper defined or example is wrong

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#376]
The [InteractionPattern](https://w3c.github.io/wot-thing-description/#interactionpattern) defines `uriVariables` as `DataSchema`.

However Example 11 looks as follow

```
"actions": {
    "LeftDown": {
      "uriVariables": {
        "p" : { "type": "integer", "minimum": 0, "maximum": 16, "@type": "eg:SomeKindOfAngle" },
        "d" : { "type": "integer", "minimum": 0, "maximum": 1, "@type": "eg:Direction" }
        }
      },
      "forms": [{
        "http:method": "GET",
        "href" : "http://192.168.1.25/left{?p,d}"
      }]
    }
```

Having said that either `uriVariables` needs to be wrapped into an _outer_ "type": "object" container or `uriVariables` is a set of `DataSchema`'s.

**Comment by danielpeintner** [comment]
Does this relate to https://github.com/w3c/wot-thing-description/issues/345 ?

**Comment by sebastiankb** [comment]
should be a map of `DataSchema`. Similar we using DataSchema's `properties `.

**Comment by egekorkan** [comment]
This was also left out in the validation schema, thank you for pointing it out

**Comment by mmccool** [comment]
It seems to me that all "Map of ..." items will be subject to the "globally unique @id" problem noted in https://github.com/w3c/wot-thing-description/issues/292.  I agree that uriVariables should also be a Map and so is also subject to this constraint, and so should be added to the list... as well as any other "Map of ...".   I have added a back-reference from that issue to this one as well.

**Comment by mmccool** [comment]
Ah, never mind, https://github.com/w3c/wot-thing-description/issues/292 was resolved by @vcharpenay updating the algorithm for JSON-LD conversion to include the JSON pointer in all generated @id.   With that fix the uniqueness problem goes away (of course keys must still be unique *within* an object, but that is a normal JSON constraint).

**Comment by sebastiankb** [comment]
"uriVariables" is now a "map of DataSchema" in the "InteractionAffordance" class
