### ISSUE TITLE
No "deceleration" in example 30

### ISSUE THREAD

**Issue by takuki** [w3c/wot-thing-description#378]
In the paragraph just before section [6.3 Media Type](https://cdn.staticaly.com/gh/w3c/wot-thing-description/fec46470/index.html#media-type-section), there is a mention of "deceleration".

I think this probably should be "brightness" instead.

**Comment by sebastiankb** [comment]
right

**Comment by sebastiankb** [comment]
I did some text update to make it more clear

**Comment by egekorkan** [comment]
Seems to be fixed, can be closed
