### ISSUE TITLE
Missing reference for Webhooks

### ISSUE THREAD

**Issue by takuki** [w3c/wot-thing-description#380]
Section [Event](https://cdn.staticaly.com/gh/w3c/wot-thing-description/fec46470/index.html#event) mentions Webhooks. Is there any specifications that we can use as a reference in TD spec?

**Comment by takuki** [comment]
We should make a reference to [Websub](https://www.w3.org/TR/websub/).

**Comment by mmccool** [comment]
We agreed in the Feb 15 TD meeting to change this to 'websub' and add a reference to the appropriate W3C REC.   As an aside, we also agreed to add 'sse' and reference the eventsource REC, and to add some inline explanation of longpoll (unless someone has a normative reference we could refer to; no-one could come up with one).

**Comment by sebastiankb** [comment]
there is now a reference used for websub in TD spec, also see https://w3c.github.io/wot-thing-description/#form
