### ISSUE TITLE
[question] Forms without href if base is defined

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#383]
This is a question. In case I have multiple interactions that use the same URI but differentiate via method name or via uriVariables, they would have the same href value in their forms. Would it be possible to omit href if there is a baseUri? This would mean that an interaction without href would take the URI of base URI. 
Similarly, are empty href string values allowed? anyUri definition in XML schema (which we reference) allows it.

**Comment by danielpeintner** [comment]
I think it is easier to keep saying "href" is mandatory.

Having said that, IF the combination "baseUri" + "href" forms a valid URI this seems fine by me. 
Hence, an empty ("") href sounds reasonable to me in some cases.

my two cents

**Comment by sebastiankb** [comment]
feature that can be think about the next TD version

**Comment by mkovatsc** [comment]
Yes, `href` is mandatory, no default value. So in your case you would need `"href": ""`.

**Comment by egekorkan** [comment]
In this case we can close this issue and not label it as Next TD version
