### ISSUE TITLE
[Editorial] Links to serialization examples from the vocabulary

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#384]
For a first time reader, I think it would be very useful to have an example of how a vocabulary would look like. For example, somewhere in the text of 5.2.3 Property, we can have a link to 6.1.2 properties. 

This might disturb the nice separation of vocabulary and serialization but it is worth considering.

**Comment by mkovatsc** [comment]
I think this is already taken care of by providing "preview" examples in the Introduction section.
