### ISSUE TITLE
[Editorial] Introduction paragraph 3, not-clear mention of "simple"

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#385]
In the Introduction section, we give an example of a simple and full TD however the text mentions of a "simple" TD:

> Example 1 shows a simple TD instance in such a JSON serializiation and depicts WoT's Properties, Actions, and Events paradigm by describing a lamp Thing with the name MyLampThing. 

I think this paragraph has not been changed after the introduction of full TD. Before simple TD meant a TD with least features.

Same issue applies to Example 2 as well.

**Comment by sebastiankb** [comment]
Section 6.1 introduce the definition of simple and full. 

Please review

**Comment by egekorkan** [comment]
I find the definitions in Section 6.1 very clear. However, isn't it too late given that Example 1 already mentions two different versions? One would not understand the difference until reading all the way to Section 6.

**Comment by sebastiankb** [comment]
thanks for the comment. I updated the introduction to make it more clear.

**Comment by egekorkan** [comment]
The updated introduction gives the required hint that they are equivalent. The issue can be closed if there aren't any further comments
