### ISSUE TITLE
Default values for op

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#386]
Based on the interaction properties, one can assume a default value for the op field of a form. For example, if a property is readOnly and not observable, AND the op field in a form is absent, one can assume that it has to be `readproperty`. There are of course multiple combinations of this which can get complicated. Should this at least be a note somewhere?

**Comment by egekorkan** [comment]
After discussion with @sebastiankb this would start to make TD look complicated since it introduces dependencies for default value generation. Waiting for more comments.

**Comment by egekorkan** [comment]
From Princeton Testfest:
This will be sort of fixed with #405

**Comment by mkovatsc** [comment]
See also https://github.com/w3c/wot-thing-description/issues/405#issuecomment-466947935

**Comment by sebastiankb** [comment]
this issue is solved by https://github.com/w3c/wot-thing-description/issues/405
