### ISSUE TITLE
Testing "type = array of X" assertions

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#388]
(Placeholder for discussion)
Spec contains assertions like the following:
* op: array of string Each entry representing an interaction verb (one of readproperty, writeproperty, observeproperty, invokeaction, subscribeevent, unsubscribeevent, readallproperties, writeallproperties, readmultipleproperties, or writemultipleproperties)

* in: (one of header, query, body, or cookie)

However, we are never checking whether there is an implementation that can produce a TD with "in":"cookie" etc. This means that maybe this feature is not implementable. 
Should this be checked, e.g. as a child assertion. See also #387

**Comment by egekorkan** [comment]
This has been implemented in [AssertionTester](https://github.com/thingweb/thingweb-playground).
@mmccool can you do another run so that they are shown in the implementation report?

**Comment by sebastiankb** [comment]
@mmccool what is the status? can we close this issue?

**Comment by egekorkan** [comment]
After checking the implementation report, I see td-vocab-op--Form not having any sub assertions so the status is still the same as my previous comment

**Comment by mmccool** [comment]
I updated to the latest version of the AssertionTester and regenerated the report.   We can check in the call today to see if this has been fixed.

**Comment by mmccool** [comment]
I still don't see any child assertions for td-vocab-op--Form.  However I think I need to create "extra" assertions for these manually.   Let's discuss in the call today.

**Comment by egekorkan** [comment]
As I was not in the TD call I don't know what is the last state of the discussion. There is no mention of this issue in the minutes either. Should I create the extra assertions or was there a decision to not do this?

**Comment by mmccool** [comment]
As an update, I was reminded of this and will look into it when I update the other things in the IR (eg client/server terminology).

**Comment by mmccool** [comment]
I just checked and these have been added and exist in the IR.   So I am closing this issue.
