### ISSUE TITLE
Model has no formal ground

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#393]
Following @mkovatsc 's presentation in Princeton Testfest:
We are showing the UML graphs but we are not giving a formal definition of what vocabulary we are using. Maybe relating to already existing vocabularies

**Comment by vcharpenay** [comment]
I'm not sure I understand this issue. Do you want to make explicit in the document what namespaces apply for each class/property?

**Comment by mkovatsc** [comment]
At the time of the Princeton F2F, all references to RDF had been removed. The Information Model section directly started talking about classes without giving any context what they mean.

We now have this sentence again, which says it is RDF, but without much explanation:

> To increase interoperability the vocabulary terms are defined using the Resource Description Framework (RDF)

My proposal was to give a bit more background on what we define and how it can be used, that is, it is a graph-based model that can be implemented with triple stores or property graphs. I am not sure what axioms or definitions we have to add around the "graph-based model" statement to have a proper model definition.

**Comment by mkovatsc** [comment]
Victor added a formal model in a recent PR. There are some minor fixes open, see comments in PR #626

**Comment by mkovatsc** [comment]
My issue is addressed. A more graph/tree oriented definition of the model could have been nice, but well... closing.
