### ISSUE TITLE
6.1 talks only about unsigned int

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#395]
Following Princeton Testfest:
6.1 Basic Representation Format Assumptions, the bullet points before the table talk about unsigned integers but not of signed integers. This means that if one implements a signed integer, we cannot serialize it.

**Comment by takuki** [comment]
Now the spec says:
Vocabulary terms that use simple type integer MUST be serialized as JSON number.

**Comment by egekorkan** [comment]
This seems to be fixed, closing
