### ISSUE TITLE
Must be serialized as array

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#396]
Following Princeton Testfest discussions and @mkovatsc 's presentation:

We have to be consistent when something can be serialized as an array of strings or just as a string.

**Comment by mkovatsc** [comment]
In the beginning, we intended to enforce arrays wherever an array is possible to simplify parser implementation. This received pushback mainly from Web developer representatives. Thus, we dropped this artificial constrained and followed JSON-LD practice to allow also single elements without array, if there is only a single item.

The change back to enforcing arrays came as surprise to me. We need new consensus.

**Comment by mmccool** [comment]
For the record I am OK with either approach as long as we are consistent... or as consistent as possible, anyway.   Generally making the system more tolerant of variant inputs as long as there is no ambiguity is probably a good thing, and I don't think this will complicate the parser THAT much.

**Comment by danielpeintner** [comment]
I wonder whether the other  *artificial* constraint of having arrays with _one or more_ entries falls into the same category.

As said during a TD call I would be ok with allowing

`@type = null` or
`@type = []`

or does this open yet another can of worms?

**Comment by sebastiankb** [comment]
in today's TD meeting we decided to change the following: 

Proposal: In Section 6 explains that arrays that have only a single string entry can also be typed as string based value.

**Comment by sebastiankb** [comment]
to be stringent (e.g., as you can find for op), I extend the model for the term scopes, security, and @type as string and array of string.

please review

**Comment by egekorkan** [comment]
The tables seem to have incorporated this change but Figure 1 still says an array of string. Since having an OR would clutter the figure, actually it might be better to not change the figure.

**Comment by sebastiankb** [comment]
good point

**Comment by vcharpenay** [comment]
what I did for `Form.op` is that I put `array of` in parenthesis in the figure. You may want to do the same for the other terms.

**Comment by egekorkan** [comment]
Fixed with #562, please review

**Comment by sebastiankb** [comment]
I see that @context in the figure is defined only as array. However, it can be a string or array

**Comment by sebastiankb** [comment]
close this one since this my comment is also addressed here 

https://github.com/w3c/wot-thing-description/issues/471
