### ISSUE TITLE
Rename ID term td-readOnly-observable-default to td-safe-idempotent-default

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#399]
otherwise it does not make sense

**Comment by mmccool** [comment]
Actually, these should go away if we get rid of section 7... they are redundant since defaults are already handled (all defaults) with a separate table now.

**Comment by sebastiankb** [comment]
Has no input within the TD spec.  
@mmccool I will assign this to you because it seems to be relevant for the assertion tests.

**Comment by sebastiankb** [comment]
its done
