### ISSUE TITLE
[ImplementationReport] numbered ids are not properly linked to the spec

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#404]
when an assertion id appears multiple times in the TD spec, the implementation report numbers them with -1 -2 etc. However, the link to the TD spec still contains this number, which actually doesn't exist in the spec. We have to think of another way to name these kind of assertions

**Comment by sebastiankb** [comment]
I do not understand the issue. Is there a bug in the TD spec (redundant assertion ids?) or of the assertion tool (why it adds -1 -2 ..)?

**Comment by egekorkan** [comment]
>  Is there a bug in the TD spec (redundant assertion ids?)

This is the main reason but apparently, these ids are assigned automatically (I might be wrong on this). Since these assertions have different meanings (like name in security and in Thing level) they should have different ids to be tested. For this reason, it was an intentional decision to add the -1, -2 etc.

If there are unique ids for each assertion, the issue would be solved in the cleanest way possible.

**Comment by mmccool** [comment]
This has been resolved now.  Numbered ids were created by the tool when it discovered duplicate ids in the spec, which occurred when a vocabulary term was used in more than one context.   I updated the templates.txt file to add the context to vocabulary IDs.  This is a much better solution to the problem.  This fix is now basically complete and I am going to close this issue.
