### ISSUE TITLE
Adding new subprotocols

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#410]
From Princeton Testfest:
Having only longpoll for subprotocol looks weird. We are proposing to have other possibilities such as webhook etc.
They should be explained like mentioned in #409

**Comment by sebastiankb** [comment]
I added webhook. Is there another prominent subprotocol?

**Comment by sebastiankb** [comment]
based on today's TD web meeting: we should also add 'sse' (aka 'server sent events')

**Comment by sebastiankb** [comment]
+ 'websub' (also see https://w3c.github.io/websub/)

**Comment by sebastiankb** [comment]
rename webhooks to websub

**Comment by sebastiankb** [comment]
provide short explanation about long polling. Other subprotocols references to the specification will be provided.

**Comment by sebastiankb** [comment]
the list should be extendable and there should be no 'one of'. Based on today's TD web meeting we remove the existing selection. Below of the table 5.2.6. there should be the explaination about the predefined values such as longpoll, websub, sse and that can be also others.

@vcharpenay take care on it

**Comment by egekorkan** [comment]
As a placeholder, once the list of subprotocols are fixed, the examples should reflect that since at the moment we have only `longpoll` in the examples.

**Comment by vcharpenay** [comment]
see #508.
