### ISSUE TITLE
ThingTemplate definition is missing in td.ttl

### ISSUE THREAD

**Issue by takuki** [w3c/wot-thing-description#416]
Example [B.1.1 Thing Template: Lamp](https://cdn.staticaly.com/gh/w3c/wot-thing-description/72b51250/index.html#lamp-thing-template) uses "@type" : "ThingTemplate". Its definition is missing in td.ttl.

**Comment by vcharpenay** [comment]
Could we simply remove `@context` and `@type` from these examples? They're indeed no documents to be publicly exposed on the Web, as far as I understood.

**Comment by mlagally** [comment]
@vcharpenay : we should not make the examples invalid. It is easy to include another type in the td.ttl. I will create a PR.

**Comment by sebastiankb** [comment]
@mlagally What do you mean by invalid? All examples in [B.1](https://w3c.github.io/wot-thing-description/#thing-template-examples) are not valid regarding JSON Schema validation.

**Comment by sebastiankb** [comment]
label this as topic for the next generation of the TD. Also see https://github.com/w3c/wot-thing-description/issues/490

**Comment by sebastiankb** [comment]
based on the latest development, the term should be called "ThingModel". Also see https://w3c.github.io/wot-thing-description/#thing-model-declaration

**Comment by sebastiankb** [comment]
issue is addressed by the latest draft (see TM section)
