### ISSUE TITLE
Link's href description talks about interaction pattern

### ISSUE THREAD

**Issue by takuki** [w3c/wot-thing-description#421]
In [Section 5.2.7 Link,](https://cdn.staticaly.com/gh/w3c/wot-thing-description/350dd5dd4718d844a4741360892e0dcce99e5b26/index.html#link)  "href" is described as:
"URI of the endpoint where an interaction pattern is provided. "
Link has nothing to do with interaction patterns,

**Comment by vcharpenay** [comment]
good point. This comment relates to #253: the description should only refer to other terms defined in an independent namespace for Web linking.

**Comment by sebastiankb** [comment]
quick question: what is the status about the separate model for Web Linking as mentioned in #253?

**Comment by vcharpenay** [comment]
I have a draft on my machine. I can upload it by the end of the week.

**Comment by sebastiankb** [comment]
I think, this issue is done, by https://github.com/w3c/wot-thing-description/pull/463

**Comment by vcharpenay** [comment]
yes, correct.
