### ISSUE TITLE
What does "convergence" mean in "Basic Representation Format Assumptions" section?

### ISSUE THREAD

**Issue by takuki** [w3c/wot-thing-description#426]
Section [6.1 Basic Representation Format Assumptions](https://cdn.staticaly.com/gh/w3c/wot-thing-description/db19a018d985abdfb79d3c602484540852216cc0/index.html#json-serializiation-section) starts by saying "In order to enable this convergence".

What does this convergence mean in this context?

**Comment by sebastiankb** [comment]
right, does not make really sense..

How about "As a fundamental basis, all vocabulary define ..."

or simple start

"All vocabulary define..."

**Comment by sebastiankb** [comment]
ok
