### ISSUE TITLE
Assertions in section 7.1 redundant?

### ISSUE THREAD

**Issue by vcharpenay** [w3c/wot-thing-description#434]
[Section 7.1](https://w3c.github.io/wot-thing-description/#note-json-processing) contains assertions that seem redundant with the beginning of [section 6.1](https://w3c.github.io/wot-thing-description/#json-serializiation-section). Is there a consensus on that?

If so, it could be refactored in the form of an "algorithm" to add default values, with the same structure as section 7.2.

**Comment by sebastiankb** [comment]
You are right. However, we should wait since the defaults values will be moved back to Section 5. 

Also see https://github.com/w3c/wot-thing-description/issues/337

**Comment by vcharpenay** [comment]
The issue was addressed in PR #492.
