### ISSUE TITLE
Could not create representation for the ontology server webservice.

### ISSUE THREAD

**Issue by yamagile** [w3c/wot-thing-description#438]
I'd like to add some "unit"s to my TDs, but the namespace "http://www.wurvoc.org/vocabularies/om-1.8/" in the TD specs ( [example-26](https://w3c.github.io/wot-thing-description/#example-26) and [example-29](https://w3c.github.io/wot-thing-description/#example-29) ) returns 500 Internal Server Error. If it is not a temporary problem, TD specs might need to be updated.

**Comment by sebastiankb** [comment]
thanks. I think, we need more a stable namespace. 

@vcharpenay can you update the examples?

**Comment by yamagile** [comment]
@sebastiankb @vcharpenay thank you for taking your time to consider this issue. The namespace "http://www.wurvoc.org/vocabularies/om-1.8/" is working fine now. I'll close this issue.

**Comment by vcharpenay** [comment]
good news, thanks!
