### ISSUE TITLE
Moving property, action, event under InteractionPattern

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#439]
[Editorial?]
This was feedback from Luis Bermudez of OGC.

He said that he was surprised to see Interaction Pattern/Affordance and property, action, event at the same level as Link, VersionInfo etc. From his point of view, Interaction Pattern should have his own section like 5.3 DataSchema since this is the "most important contribution".
I think this is a bit too much of a change but we can at least have:
```
5.2.2 Interaction Pattern
5.2.2.1 Property
5.2.2.2 Action
5.2.2.3 Event
```
This way, it will be obvious in the sidebar that property, action and event are subclasses of Interaction Pattern. 
Any thoughts on this?

**Comment by zolkis** [comment]
Sounds good.

**Comment by egekorkan** [comment]
Seems that this was accepted and integrated into the spec
