### ISSUE TITLE
DataSchema has DataSchema

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#440]
I think this is a small copy paste mistake but in the spec there is:
5.3.1 DataSchema
5.3.1.1 DataSchema
5.3.2 ArraySchema

I think 5.3.1.1 DataSchema should be removed otherwise we should also have 5.4.1.1 SecurityScheme and 5.2.2.1 InteractionSchema

**Comment by takuki** [comment]
I no longer see section 5.3.1.1 DataSchema.
Has it been already fixed?

**Comment by egekorkan** [comment]
Yes, this must have been a small mistake that got overwritten
