### ISSUE TITLE
Using "http" as a term is strange

### ISSUE THREAD

**Issue by msporny** [w3c/wot-thing-description#443]
I note that you do this in the current specification:
```
        {"http": "http://www.w3.org/2011/http#"}
```

... which is technically ok (I think, I can't remember if there is a corner case that doesn't make it ok), but causes a lot of us in the JSON-LD community to wring our hands because seeing "http:example" has caused at least two Web developers to go "Oh, that URL is wrong, let me fix that" and then change it to "http://example.com", which is definitely not what the original author intended

I suggest instead something like:

```
        {"htv": "http://www.w3.org/2011/http#"}
```

or:

```
        {"hto": "http://www.w3.org/2011/http#"}
```

or almost anything else that can't be mistaken for an actual http URL. :)

**Comment by vcharpenay** [comment]
`http` is the prefix declared in the vocabulary spec: [HTTP Vocabulary in RDF 1.0](https://www.w3.org/TR/HTTP-in-RDF/). We didn't think much further.

I would even suggest something more verbose that can be declined to any protocol metadata, like `http-voc`.

**Comment by mmccool** [comment]
I vote we use "h" for http, "c" for coap, and "m" for mqtt.   These "abbreviations" are as simple as possible without being confusable with URL schemes, whereas something like "hto" or "htp" are not obviously a pointer to http; they just look like some OTHER protocol.

**Comment by sebastiankb** [comment]
done. 

I followed @msporny proposal: htv

Single prefix character can be conflicting. E.g., what are you doing when COAPS is used?

**Comment by vcharpenay** [comment]
what about:
 - `http-voc`
 - `mqtt-voc`
 - `coap-voc`
 - `coaps-voc`

**Comment by sebastiankb** [comment]
there are no samples in the TD spec that uses additional vocabularies for coap and mqtt.

**Comment by msporny** [comment]
> what about: http-voc

Avoid using dashes, if possible... I don't know of many (any?) widely used prefixes that use dashes.
