### ISSUE TITLE
Example1, Example2 and Example35 contain validation errors

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#448]
When validating these two examples with the playground, I noticed some validation errors.

These relate to a missing "id" field at the top level and an extraneous "@id" field in the
security definitions and a missing array.

**Comment by sebastiankb** [comment]
I just tested Example1 and Example2 with the TD playground and both tell me to be correct.

Example35 indeed have an error.

**Comment by mlagally** [comment]
Are we using the same playground?

**Comment by sebastiankb** [comment]
example 1:
![image](https://user-images.githubusercontent.com/13832739/53172981-ff17a280-35e6-11e9-84c9-82ec2cedb548.png)

example 2:

![image](https://user-images.githubusercontent.com/13832739/53173019-122a7280-35e7-11e9-9b17-7a2bbf3a02fc.png)

**Comment by sebastiankb** [comment]
Please use only the TD simple or full version as defined in the TD spec. The JSON-LD form is non-normative yet.

**Comment by mlagally** [comment]
You are right, I validated the JSON-LD versions.
My PR fixes the problems and they can be validated.

(On example 2 there's still the problem with the @context contents which I described In #447,
but this needs to be addressed in the schema)

**Comment by sebastiankb** [comment]
https://github.com/w3c/wot-thing-description/issues/447 is solved and this issue can be closed
