### ISSUE TITLE
base URI definition in Thing class is a bit confusing

### ISSUE THREAD

**Issue by takuki** [w3c/wot-thing-description#454]
The definition of "base" member of [Thing](https://cdn.staticaly.com/gh/w3c/wot-thing-description/5e7ec0e25525cff2ae14edee3df9a09abb0ccf2b/index.html#thing) class says:

> Define the base URI that is valid for all defined local interaction resources. All other URIs in the TD must then be resolved using the algorithm defined in [RFC3986].

I think this statement is a bit confusing.

This base URI, is this only the base for interaction resources? What about other URIs in TD such as links and security schemes?

**Comment by sebastiankb** [comment]
good question. For me, the base optimization should be valid for the whole TD document.

**Comment by mkovatsc** [comment]
The base URI should be used as base for all relative hyper references (all `href` fields) in the TD. It does not apply to the (Linked Data) vocabulary IRIs.

**Comment by sebastiankb** [comment]
ok, lets point out this more clearly in the TD spec. 

@takuki can you do this?

**Comment by takuki** [comment]
I reflected the discussion here to the draft spec. Please review.
