### ISSUE TITLE
names in Thing level should be MultiLanguage and not mandatory

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#464]
names in Thing level is shown to be mandatory and of type string. If it is a mandatory key with a default value, what should be its default value? I can think of it being an object and taking the value of `name` for english language:
```
    "name": "LightThing",
    "names": {
        "en":"LightThing"
    },
``` 
Other than this (which I don't find nice) I couldn't think of another solution.

**Comment by egekorkan** [comment]
@takuki  can you comment on this?

**Comment by mmccool** [comment]
I think this is simply a mistake in the ontology... its type should be “Multilanguage”, not “string”.

**Comment by sebastiankb** [comment]
I think it's more about why there's suddenly a `names` term. I can't remember such a discussion.  Maybe I missed something. 

For me the term `name` would be sufficient, because it is a kind of human readable identifier like Raspberry Pi etc..

**Comment by takuki** [comment]
> 
> @takuki can you comment on this?

@egekorkan , I am not sure when and why it is in here.

**Comment by sebastiankb** [comment]
in today's TD meeting we decided to remove it again. Seems to be a mistake.

**Comment by mmccool** [comment]
I think we DO need "names".  See https://github.com/w3c/wot-thing-description/issues/598

**Comment by mkovatsc** [comment]
The `name` is an identifier that needn't be unique across Things (unlike `id`). However, there should be only one name for a Thing. Thus no `names`. I assume that the name can usually be changed by the user. It underlies the default language.

**Comment by egekorkan** [comment]
I also think names gives a bad impression that the Thing can have multiple names even though they are used only for different languages. Also, this would be a rather big update in the current stage. Should we close this issue?

**Comment by mmccool** [comment]
I have been talked around to Matthias' view that the name should not change and that there should not be multiple names.  But this raises another issue that the language (and text direction) cannot change if the default language changes i.e. as part of a protocol negotiation.  I have proposed a fix for this latter problem (which is definitely a corner case, but we should cover it).   The fix also applies to "support".
See https://github.com/mmccool/wot-thing-description/pull/8.

Anyhow, I think we can close this issue one way or the other, as we have (re-)decided not to re-introduce names.

**Comment by egekorkan** [comment]
Ok we can follow up on the PR as well
