### ISSUE TITLE
[Editorial] DataSchema subclass order is not consistent

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#467]
(nitpicking?) 
The order of DataSchema subclasses are listed in different order at:
* Under the table at 5.3.1
* Table of Contents (order they appear in the document)

**Comment by egekorkan** [comment]
@vcharpenay will look at the scripts that generates the order

**Comment by vcharpenay** [comment]
Fixed by 72188d1. Please review before I close the issue.

**Comment by egekorkan** [comment]
It looks to be fixed, issue can be closed
