### ISSUE TITLE
[Editorial] inline JSON is formatted like normal text

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#468]
I am not sure if this is intentional but at many places in the specification text, there are inline JSON snippets like as normal text:
* 5.3.3 => ("type": "boolean") 
* 5.4.2 => ("scheme": "nosec")
In some other places, they are formatted in this brick-red color and different font type, e.g. "@type": "Thing" at 6.1.1 under Example 6.

Additionally, sometimes the JSON values (not the entire JSON) given are normal text like:
* 5.2.6 => (e.g., en, de, ja, zh-Hans, zh-Hant)
* 6.1.5 => href may also carry an URI that contains dynamic variables such as p and d in http://192.168.1.25/left?p=2&d=1

**Comment by egekorkan** [comment]
Fixed a bit by #562

**Comment by sebastiankb** [comment]
is your proposal to use the <code> environment?

**Comment by egekorkan** [comment]
> is your proposal to use the environment?

I haven't understood what this means but I had done the fixes with `<code>` tags like in `<code>EventAffordance</code>`

**Comment by sebastiankb** [comment]
I missed the code term...

**Comment by mkovatsc** [comment]
Also see #613

**Comment by egekorkan** [comment]
This issue can be closed, it is fixed

**Comment by sebastiankb** [comment]
thanks
