### ISSUE TITLE
scopes explanation in form is not linked to oauth2 in securityDefinitions

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#470]
The explanation of scopes in Form is currently the following:

> Set of authorization scope identifiers, provided as an array. These are provided in tokens returned by an authorization server and associated with forms in order to identify what resources a client may access and how.

Which doesn't link where the scope values are defined. For example, for security we have currently the following text:

> Set of security definition names, chosen from those defined in securityDefinitions. These must all be satisfied for access to resources at or below the current level, if not overridden at a lower level.

Here we say that a string given in security array should be defined in securityDefinitions. Since scopes is used only with oauth2, we should say something like the following: 

> The set of scopes names chosen from those defined in an "oauth2" security scheme defined in securityDefinitions.

**Comment by mmccool** [comment]
Addressed in PR https://github.com/w3c/wot-thing-description/pull/538.

**Comment by egekorkan** [comment]
Seems to be fixed
