### ISSUE TITLE
@context defined as of type array only

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#471]
The TD spec defines `@context` as of type `array` only (see https://w3c.github.io/wot-thing-description/#thing).

I believe `@context` can be of type `string`, `array`, and `map`.

This issue seems to relate to https://github.com/w3c/wot-thing-description/issues/396.

**Comment by sebastiankb** [comment]
defined as array or string

**Comment by jmcanterafonseca** [comment]
it can also be an object ....

**Comment by sebastiankb** [comment]
@vcharpenay the Figure have to be updated. so far it has only array in there

**Comment by vcharpenay** [comment]
see 62e7095b53f9b7c5f930366c421d1265a83b10fe.
