### ISSUE TITLE
Should the Full Validation Schema be referenced

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#473]
Given that we have some mandatory items that are not mandatory outside of default value generation, I had created two versions of the validation schema. The one in the specification is the simple version that does not oblige the keys that would be generated with "a default value generator". Should the full schema be also referenced (not the entire schema), maybe with default values?

* Full Schema: https://github.com/thingweb/thingweb-playground/blob/master/WebContent/td-schema-full.json
* Simple Schema: https://github.com/thingweb/thingweb-playground/blob/master/WebContent/td-schema.json

**Comment by sebastiankb** [comment]
please note that the "full" TD is now JSON-LD 1.1 compliant. Lets decide this in tomorrows TD meeting

**Comment by sebastiankb** [comment]
In today's TD meeting we decided to have also the "full" JSON Schema in the TD annex. It should be stated what is the different between both schemas and its purpose. 

@egekorkan can you make a PR?

**Comment by egekorkan** [comment]
Done via #516
