### ISSUE TITLE
Consider adding "scopes" to bearer and pop SecuritySchemes

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#475]
Currently scopes are only defined for the "oauth2" scheme but since they are encoded in bearer tokens, perhaps they should also be supported in "bearer" and perhaps the "pop" token SecuritySchemes.  Consider however the following note:
https://swagger.io/docs/specification/authentication/bearer-authentication/
In OpenAPI, the "bearer" scheme does not include "scopes" because although they are encoded in bearer tokens when using OAuth2, they are technically an OAuth2 concept.   However... for Things, it is possible that bearer tokens might be generated with scopes using a process not visible to the Thing, so adding them to the "bearer" scheme might be a good idea.   As an extension, "pop" tokens are supposed to be functionally equivalent to bearer tokens so if bearer tokens have scopes, "pop" tokens probably should too.

Discussion?   Note that if we REMOVE the OAuth2 scheme (which we might have to if we don't get two implementations done in time...) then we MUST add scopes to "bearer" and "pop" to allow OAuth2 to be used with Things.  So I propose we do this change proactively ;)

**Comment by mmccool** [comment]
Note that RFC6750 explicitly states that bearer tokens may be used in both OAuth2 and non-OAuth2 contexts:
https://tools.ietf.org/html/rfc6750

**Comment by mmccool** [comment]
See also https://tools.ietf.org/html/rfc6749#section-3.3
Note that "scopes" are used in negotiation with the authorization server as well (specifically, when getting a token from an authorization server, a set of scopes needs to be requested using a header parameter).

**Comment by mmccool** [comment]
PoP tokens just appear to be a set of additional transport/encryption "wrappers" around bearer tokens so whatever we do for bearer tokens should also be supported for PoP tokens.

**Comment by mmccool** [comment]
Since scopes are specifically an OAuth2 concept I propose dropping this with the resolution NOT to add scopes to Bearer etc.  That means we can mark this issue as "won't fix" and close it.  Comments?

**Comment by egekorkan** [comment]
During testfests we see a good number of bearer implementations but none use scopes (which is allowed if they need to). If there's no need for it, we shouldn't add it and close this issue
