### ISSUE TITLE
"anchor" needs an example

### ISSUE THREAD

**Issue by takuki** [w3c/wot-thing-description#477]
During TestFest telecon on 2/27, it was pointed out that we need an example for "anchor" term of Link class. 

@mjkoster volunteered to provide one.

**Comment by sebastiankb** [comment]
@mjkoster what is the status?

**Comment by takuki** [comment]
@mjkoster and @mkovatsc provided an [example](https://lists.w3.org/Archives/Member/member-wot-wg/2019Apr/0002.html).

>   "links": [
>     {
>       "anchor": "http://159.203.213.90:1880/Illuminance",
>       "rel": "describedBy",
>       "href": " http://iotschema.org/Illuminance",
>       "type": "text/html"    },
>     {
>       "anchor": "mqtt://0m2m.net:1883/sns-portable-demo/3301/0/5700",
>       "rel": "describedBy",
>       "href": "http://iotschema.org/IlluminanceChanged",
>       "type": "text/html"
>      }
>   ]
> 
> *         href should always have dereferencable URIs, no LD terms or shorthands
> *         Changed to HTML for human-readable documentation
>

**Comment by sebastiankb** [comment]
after chatting with @mkovatsc  there is not really a need to have an example in the TD spec since there will be not a useful usecase in the TD.
