### ISSUE TITLE
"format" in DataSchema needs an example

### ISSUE THREAD

**Issue by takuki** [w3c/wot-thing-description#478]
During TestFest telecon on 2/27, it was pointed out that we need an example for "format" term of DataSchema class.

**Comment by sebastiankb** [comment]
updated Example 33 with a 'format' usage

**Comment by jmcanterafonseca** [comment]
@sebastiankb when you talk about example #number, where can I find those examples?

**Comment by egekorkan** [comment]
@jmcanterafonseca you can find the examples in the TD document here: https://w3c.github.io/wot-thing-description/#example-33-mylightsensor-with-mqtt-binding
However, it seems that @sebastiankb meant Example 34 https://w3c.github.io/wot-thing-description/#example-34-temperature-event-with-subscripton-and-cancellation-for-a-thing-2-thing-interaction

**Comment by jmcanterafonseca** [comment]
@egekorkan thanks!

perhaps it would be good to have them externalized as files. I don't know if the template allows content inclusion from an external file

**Comment by sebastiankb** [comment]
example can be found here https://w3c.github.io/wot-thing-description/#example-36-temperature-event-with-subscripton-and-cancellation-for-a-thing-2-thing-interaction
