### ISSUE TITLE
[FPWD] Read through and comments

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#49]
I read the TD document https://w3c.github.io/wot-thing-description/ labeled as "W3C Editor's Draft 06 September 2017".

Please find below my comments. Some can be surely post-poned, others are just minor fixes/improvements, and yet others may be also invalid.

Hope you find the input useful.

# A
https://w3c.github.io/wot-thing-description/#introduction

2nd para, first line reads as follows "Properties can be used for controlling  parameters, such as a set point or operation state."

I propose to change it slighlty to reflect besides setter functionality also getter functionality.

e.g., 
"Properties can be used for controlling (or retrieving) parameters, such as a  setting an operation state (or getting the current value)."

# B
https://w3c.github.io/wot-thing-description/#introduction

2nd para lists bindings for example "(MQTT?)"

I suggest removing MQTT if the editors are not sure about OR add an editorial  note asking for feedback/comments.

# C
https://w3c.github.io/wot-thing-description/#introduction

Example 1 has 
"@type": "Thing"

I think we decided that "@type" MUST be an array? --> "@type": ["Thing"]

# D
https://w3c.github.io/wot-thing-description/#namespaces

I wonder whether we want to add an editorial note mentioning that 

"http://www.w3.org/ns/td#" points to the last spec/document and there will be  dated uris pointing to a given snapshot for interoperability?
I think it would be of benefit to have such a not asking for feedback whether that approach sounds sensible for others?

# E
https://w3c.github.io/wot-thing-description/#conformance

3 para points to
"Section 3. Vocabulary Definition"
while it should point to
"Section 5. Vocabulary Definition" ?

4 para points to
"4. Serialization"
while it should be
"6. JSON-LD Serialization"

# F
https://w3c.github.io/wot-thing-description/#conformance
"ISSUE 1" might be better described so that readers know what it is about and  can provide feedback.

# G
https://w3c.github.io/wot-thing-description/#overview

A more general question. Property seems to have outputData only. Could there  be cases where setting a property with a different "inputData" makes sense. 

Also, the more I think  about the more the term "outputData" for me is a bit misleading given that it is used for input and output.

# H
https://w3c.github.io/wot-thing-description/#overview

Is there a need to add @type and such to the model/figure also? Or is it purely JSON-LD that requires it?

# I
https://w3c.github.io/wot-thing-description/#thing

Column "Optional / Mandatory" --> prefer having one term e.g. "mandatory"  which allows to have simple yes/no answer

# J
https://w3c.github.io/wot-thing-description/#thing

base points to string (http://www.w3.org/2001/XMLSchema#string)

I wonder why it does not point to http://www.w3.org/2001/XMLSchema#anyURI ?

# K
https://w3c.github.io/wot-thing-description/#interactionpattern

1 para.
I propose to start with the last sentences first to state immeditaley what Interactions are.

"Three interaction patterns are defined as subclasses: Property, Action and Event. When a concrete Property, Action or Event is defined in a Thing  Description, it is called an "interaction resource". "

Currently its starts a bit vague.

Note: in the end of Section 5.2.2 the subclasses are mentioned again. Maybe we  can combine it somehow?

# L
https://w3c.github.io/wot-thing-description/#property

very minor: I think etc in e.g. is not needed
(e.g., supported mode, rated output voltage, etc.)

# M
https://w3c.github.io/wot-thing-description/#event

I believe that events are still somewhat fuzzy. Maybe we can pick up a  previous example to make it clearer.

"The Event interaction pattern enables a mechanism for events to be notified by a Thing on a certain condition (e.g., the fill level of the water tank reached a given threshold). " 

# N
https://w3c.github.io/wot-thing-description/#dataschema

Maybe it is just me but n-ary class and pairs (data type, unit of measure) do not make it obvious to me whether it can be nested datatypes.
Do you think we can improve that or am I just not familiar with the term "n-ary" class? 

# O
https://w3c.github.io/wot-thing-description/#link

Similar to a previous comment I wonder why href points to string and not to anyURI?

# P
https://w3c.github.io/wot-thing-description/#link-serialization
Similar to a previous comment I think it is easier to name the column Optional  or Mandatory and use yes/no

# Q
https://w3c.github.io/wot-thing-description/#link-serialization

The description of href is a bit strange
"URI. A relative URIs are relative to base URI"
-->
"URI. All relative URIs are relative to base URI" ?

# R
https://w3c.github.io/wot-thing-description/#property-serialization

The text/content is almost the same as in https://w3c.github.io/wot-thing-description/#property

We might consider (even in a future draft) to align the classes and the  default serialization in one form or the other. What do you think?

Note: the term @type is nowhere described and why it is there. (Among other reasons the field @type is needed to identify the class of the interaction pattern (Action, vs Event vs Propery) etc)

# S
https://w3c.github.io/wot-thing-description/#event-serialization

States "There are are two mandatory and two optional terms defined within the Event pattern:"

Later all 4 fields are marked as "required" ?

# T
https://w3c.github.io/wot-thing-description/#thing-as-a-whole

states "base" is required. Is this really true? Why can't I use purely absolute URIs?

# U
https://w3c.github.io/wot-thing-description/#thing-as-a-whole

The description of @context states array MUST contain 
"https://w3c.github.io/wot/w3c-wot-td-context.jsonld"
while the text softens this statement to "shall include".

I think it is a MUST.

Note: the editors note in the end of Section 6.4 states context might not be  necessary at all. We might need to agree on one statement.

# V
https://w3c.github.io/wot-thing-description/#type-system-object

The composed type used the fieldname "fields" while JSON schema uses  "properties". Is there a reason why we chose to use a different term? 
I see, "fields" is different to "properties" the way it is defined.

Hence the mentioning of "type system is designed to be compatible with JSON schema" is a bit misleading?

# W
https://w3c.github.io/wot-thing-description/#structured-data

Either Example 13 uses `<number>184</number>` or Example 16 uses `<integer>1314520</integer>` given that it points to the same type.

I think it should be `<number>`.

# X
https://w3c.github.io/wot-thing-description/#mapping-to-xml-schema

The XML (schema) mapping comes to late or should be referenced before the first Example 13 is given.

OR

IS it OK to extract the content in another document and refer to it?

Not sure what is the best way given that it is also a bit lengthy ...

# Y1
https://w3c.github.io/wot-thing-description/#examples

States "In the following, we give three examples of a full TD."

I think there are currently only 2 examples.

# Y2
https://w3c.github.io/wot-thing-description/#temperature-sensor

Example 26 should have @type modelled as array not string.

Should
"property": "temp"
in the event not be
"property": "myTemp" to allow the reference?

# Z
https://w3c.github.io/wot-thing-description/#led-master-switch

Example 27 uses "associations". This is the first time the readers gets to know this term?

Further, I do not fully understand what "associations" is about.

I think the last par should be put in a warning or note to make clear that  associations have been specified yet.
I also wonder whether we need this example at all at the moment?

# SEC A
https://w3c.github.io/wot-thing-description/#general

Not sure about the plan for the security sections but some statements should be fixed or moved.

For example it speaks about "Scripting API" which is not the right place here.

# GENERAL

Shall we mention somewhere other constraints such as

* property names MUST be unique

**Comment by sebastiankb** [comment]
Many thanks for the review! I just start to go over your comments.

**Comment by sebastiankb** [comment]
A --> ok for me, I take your proposal

**Comment by sebastiankb** [comment]
B --> I think we should mention MQTT as well since this is the plan to cover this as well. I will remove the bracket and question symbol

**Comment by sebastiankb** [comment]
C --> is fixed

**Comment by sebastiankb** [comment]
D --> I'm also thinking about to remove the table since we only use the td prefix and namespace. What the others think about this?

**Comment by sebastiankb** [comment]
E --> is fixed

**Comment by sebastiankb** [comment]
F --> I add more text

**Comment by sebastiankb** [comment]
G --> is general question

**Comment by sebastiankb** [comment]
H--> this should be independent since different serializiation formats can be used to represent this RDF-based data (e.g., JSON-LD, RDF/XML, etc.). Each format has different mechanism to refer RDF classes

**Comment by sebastiankb** [comment]
I --> OK

**Comment by sebastiankb** [comment]
J --> good point, I changed this

**Comment by sebastiankb** [comment]
K --> Ok, I moved the sentence to the beginning

**Comment by sebastiankb** [comment]
L --> I will keep it. Why not..

**Comment by sebastiankb** [comment]
N --> yes, it is not clear. I changed the text since we now rely on JSON-Schema declarations: 

> This class embeds JSON Schema declaration in a linked data form to allow the representation of pairs (data type, unit of measure) that are expected as input data or output data of a given interaction pattern.

**Comment by sebastiankb** [comment]
O --> fixed this

**Comment by sebastiankb** [comment]
P --> done

**Comment by sebastiankb** [comment]
Q --> changed to 
>URI. If a relative URI is given then this URI is relative to base URI.

**Comment by sebastiankb** [comment]
Q --> I think this is ok. Serializiation gives a more concrete explanation. btw: @type is explained in the table

**Comment by sebastiankb** [comment]
S --> fixed this

**Comment by sebastiankb** [comment]
T -->is optional, I fixed it

**Comment by sebastiankb** [comment]
U --> changed this

**Comment by sebastiankb** [comment]
V --> this section is still under development

**Comment by sebastiankb** [comment]
W--> you mean integer since this is defined in EXAMPLE 14

**Comment by sebastiankb** [comment]
X --> @takuki what do you think?

**Comment by sebastiankb** [comment]
y1 --> changed to only "examples"

**Comment by sebastiankb** [comment]
Y2--> fixed

**Comment by sebastiankb** [comment]
Z --> @vcharpenay if ok, I remove the **associations**

**Comment by sebastiankb** [comment]
GENERAL --> good questions, what the others thinks?

**Comment by vcharpenay** [comment]
Z --> you can maybe remove it and add an editor's note mentioning that referencing/linking to other Things was a requirement for some WG members (e.g. to specify a master switch or a building/room/device hierarchy) and, therefore, that a field such as `association` or `child` might be specified in the future.

**Comment by sebastiankb** [comment]
close this issue since TD draft is submitted
