### ISSUE TITLE
Consider adding "components" to TD ontology 

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#490]
It is useful to structure a thing into several components.

This helps to organize complex things into smaller logical blocks,
which are easier to understand and reflect the conceptual structure.

Thing templates required a mechanism to define things that are 
based on different templates and offer combined functionality.
They use the keyword "thing-templates:components" from a dedicated namespace,
which is used to define these components.

It should be considered to also incorporate the component concept into
the core TD model/ontology to provide this structural element also for structuring _plain_ things,
i.e. things that don't depend on templates.

**Comment by mmccool** [comment]
I think this is a reasonable goal, however I'm not convinced it should be done exactly as in the example given in the TD draft spec, hence my reluctance to push it out at this point.   In particular, I think relationships like "this TD is an instance of that TD template" and "this TD describes a component of this other TD" should be expressed as links.  In that case we need to do something completely different: define some "rel" values for the link mechanism we already have.

**Comment by mmccool** [comment]
So... I was reading through the spec and noticed that "components" were only used in the context of Thing Templates.   Is the intention that components would be limited to this use case, or would you expect using them in full TDs as well?

**Comment by mlagally** [comment]
I think they would be useful for things in general to structure complex things.

**Comment by sebastiankb** [comment]
quite old topic and definitively out of scope of this TD version.

**Comment by sebastiankb** [comment]
also see https://github.com/w3c/wot-thing-description/issues/168

**Comment by egekorkan** [comment]
Also used in open api: https://swagger.io/docs/specification/components/

**Comment by sebastiankb** [comment]
ThingModel introduced [import](https://w3c.github.io/wot-thing-description/#thing-model-extension-import) mechanism.
