### ISSUE TITLE
@type in PropertyAffordance level can relate to DataSchema AND InteractionAffordance

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#495]
(Writing with full awareness of the changes this implies)

Since a PropertyAffordance can include elements of DataSchema, it can also include the newly introduced `@type` of DataSchema class. In this case, how can one understand if the `@type` is for the DataSchema of PropertyAffordance or for the InteractionAffordance, like in the example below:
```
...
"properties": {
    "myProperty": {
      "type": "integer", "minimum": 0, "maximum": 16, 
      "@type": "eg:degree",
       "forms": [{
         "htv:method": "GET",
          "href" : "http://192.168.1.25/my"
        }]
    }
...
```
When the DataSchema is encapsulated like in uriVariables, input, output, data etc., this ambiguity would not exist. A solution would be:
```
...
"properties": {
    "myAngle": {
      "data":{
        "type": "integer", "minimum": 0, "maximum": 16, 
        "@type": "eg:degree"
      },
      "@type":"eg:angleOfAttack",
      "forms": [{
        "htv:method": "GET",
        "href" : "http://192.168.1.25/myAngle"
      }]
    }
...
```
Having a key called `data` in PropertyAffordance, like in EventAffordance, would fix this and other problems such as:
* The note at the end of 5.2.2.1 which introduces something that might be difficult to understand.
* The testing overhead: One of the many examples is the `td-property-names` assertion that needs to also test whether DataSchema names are included in a property. 

I would even say that this makes all the InteractionAffordance classes more homogenous since for each of them, the InteractionAffordance vocabulary and DataSchema vocabulary would be on the same levels. This used to be the case in versions https://www.w3.org/TR/2018/WD-wot-thing-description-20180405/ and before where we used the `schema` keyword.

**Comment by sebastiankb** [comment]
@vcharpenay are there some similar use cases from the semantic web? How is this solved there?

**Comment by sebastiankb** [comment]
In my understanding, if we can be aligned with JSON-LD 1.1 then we can remove @type (and @context) from the TD model. This should overcome this issue, right?

**Comment by vcharpenay** [comment]
what you are exposing is a problem related to multiple inheritance. As far as I know, it is a problem when class members have default values. It is not the case here, so there should not be any conflict related to `@type`.

In RDF, "default values" are definitions that are stated for all class instances, regardless of other definitions the instance has. They are more like constants, in fact. And in the case an instance is in the intersection of 2 classes, these defaults/constants get merged into an array.

For instance, given the following class definitions (in Turtle)

```turtle
# if a instanceof C, then a.p == "SOME_CONSTANT"
:C a owl:Class ;
   rdfs:subClassOf [
     owl:onProperty :p
     owl:hasValue "SOME_CONSTANT"
   ] .

# if b instanceof D, then b.p == "SOME_OTHER_CONSTANT"
:D a owl:Class ;
   rdfs:subClassOf [
     owl:onProperty :p
     owl:hasValue "SOME_OTHER_CONSTANT"
   ] .
```

we will end up with th following instance (in JSON-LD)

```json
{
  "@type": [ ":C", ":D" ],
  "p": [ "SOME_CONSTANT", "SOME_OTHER_CONSTANT" ]
}
```

**Comment by takuki** [comment]
> In my understanding, if we can be aligned with JSON-LD 1.1 then we can remove @type (and @context) from the TD model. This should overcome this issue, right?

For ＠context, the spec also defines three default values in [5.1.1 Default Values for Vocabulary Terms](https://w3c.github.io/wot-thing-description/#sec-default-values). In order to preserve this information in the spec, I think maybe we can keep ＠context in the TD information model for now.

**Comment by vcharpenay** [comment]
well, in fact, these defaults for `@context` are not relevant anymore if we go back to JSON-LD 1.1. More precisely, we only need one single context declaration at the Thing level.

**Comment by takuki** [comment]
We still have simple TD, and simple TD I think is not per se JSON-LD 1.1. Since simple form does not have @context, so we may still need to define the default value at least at the top level. Is it not the case?

**Comment by sebastiankb** [comment]
based on the usage of JSON-LD 1.1 we can use @context from the Thing class and this is valid in the whole TD document. That should solve this issue. 
There will be a separate issue that discuss the @context (format etc) usage in the TD at all.
