### ISSUE TITLE
Possible typo at the explanation of format

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#496]
The DataSchema vocabulary term format has the following text in the explanation

> or other (customer-based) definitions. .

Is this a typo and should be "custom-based" ?

**Comment by danielpeintner** [comment]
Not sure about "customer-based" vs. "custom-based".

Having said that, the 2 trailing dots may be fixed also...

**Comment by sebastiankb** [comment]
thanks, I will fix this
