### ISSUE TITLE
Clarify how new security schemes can be given in extensions

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#501]
Currently it looks highly likely at least some of the security schemes will be at-risk and in danger of being dropped.   This includes potentially useful schemes like PSK and OAuth2.   This is not a big deal IF we can define these later as needed with extensions.   However, we need to clarify exactly how this will work, and maybe provide an example in the text.

One issue is that the definitions of `scheme` and `@type` overlap.   Right now `scheme` is mandatory and must be one of a specific set of values.  But if we use an extension to define a new scheme, we would include an `@context` to pull in the new vocabulary and use an `@type` to identify the class.   Say for example we had to get rid of OAuth2, and support it in an extension.   Then a security scheme using that extension might look like

```
{
     "@context": [ "http://...."],
     "@type": ["OAuth2SecurityScheme"],
     "scheme": "?",
     ...
}
```

What should `scheme` be in this case?  If it is `"oauth2"` where does that value come from?  How can we ensure that `scheme` and `@type` are consistent?  Isn't this redundant?   What if a user makes a mistake and uses something else for `scheme`, like (for example) `"digest"`?  Is that an error, or does one of the two values take precedence?  

I see a couple of solutions to this:

1. Make `scheme` optional, but allow it to be omitted (and perhaps require it to be omitted to avoid redundancy and possible conflicting information) if there is an `@type`.   
2. Get rid of `scheme` and make `@type` mandatory inside a `SecurityScheme`; its functionality therefore replaces `scheme`.

Option 2 would be the most consistent but would require some pretty major changes to all our current TDs, and goes against the convention we have been using that values beginning with `@` can be omitted if you are not doing semantics.  So I prefer option 1.  We should also make sure that we can drop the string values referring to at-risk items if we drop those at-risk schemes.  I also prefer *requiring* `scheme` to be omitted if there is an `@type`; then we avoid the whole issue of having to define new string values for `scheme` and also avoid the possibility of conflicting definitions.   In this case `scheme` is just a short-hand way of defining the `@type` so the normalization (during conversion to JSON-LD) would be to delete `scheme` if it is given and generate the corresponding `@type` value.

**Comment by mmccool** [comment]
The tricky bit here is making `scheme` semi-optional... what we really want is to say there is either an `@type` OR a `scheme` but never both (eg a oneOf relationship), and never neither.

**Comment by mmccool** [comment]
Yes, I know this is unnecessarily complicated.   If someone has a better idea...

**Comment by mmccool** [comment]
Conclusion from meeting: we should use option 1, using either @type or scheme but not both.   I will create a PR to add an assertion to that effect to the spec, and an example based on OAuth2 (which also raises the issue of how to deal with "scope"...).   Apparently type/@type in DataSchema needs a different solution that does allow both to be used together, however; let's let sleeping dogs lie, there.

**Comment by vcharpenay** [comment]
**Update to last meeting's comment**: this example will NOT give an error when using JSON-LD processing. When expanding the object, `scheme` will simply be replaced by `rdf:type`. As a result, the two statements will be merged when turning into RDF but they are kept separate as long as they are represented in JSON-LD.

```json
{
  "@context": { "wotsec": "http://www.w3.org/ns/wotsec#" },
  "@type": "wotsec:OAuth2SecurityScheme",
  "scheme": "..."
}
```
when expanded, gives:

```json
{
  "@type": "http://www.w3.org/ns/wotsec#OAuth2SecurityScheme",
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#type": "..."
}
```

But in fact, the best solution to me would be to allow extensions within `scheme`. I remember discussing whether the list of possible values for `Form.op` was exclusive or not. It would make sense here, as well as for `Form.subprotocol`. It does not, however, for `Form.op` and `DataSchema.type`. What do you think?

**Comment by mmccool** [comment]
I think it would be nicer to allow the specifications of extensions within "scheme".   If we have to declare contexts globally, and we have to use prefixes, then something like

{
    "scheme": "oauth2:scheme",
    ...
}

might be one convention.   But if local per-scheme contexts are used, then perhaps the scheme could be implied.

**Comment by mmccool** [comment]
To follow up on my other suggestion that use of a local @context could perhaps imply the local value of "scheme"... in which case you would not have to give it.   So something like
```json
{
"@context": "{URL for OAuth2 extension",
"token": "....",
"authorization": "...",
...
}
```

**Comment by mmccool** [comment]
By the way it would also be good to define standard URLs for security schemes; ideally all of them for consistency, but definitely the ones we are taking out of the spec because they are at-risk.   I am thinking something like
```
http://www.w3.org/ns/wotsec/psk
http://www.w3.org/ns/wotsec/oauth2
http://www.w3.org/ns/wotsec/cert
```
and so forth.   So the scheme name is right there in the URL.

**Comment by mmccool** [comment]
OK, now that we have gotten rid of `@context` in SecurityScheme this becomes simpler.   I am working on a PR (finally) and hope to be able to discuss it in the call today.  I am going to go with the "allow extensions to provide new values for `scheme`" approach; then we just have to debate whether it is implementable.  I will assume everything has a prefix.   My example will look something like

```
{
    "scheme": "oauth2:scheme",
    "oauth2:token": "....",
    "oauth2:authorization": "...",
    ...
}
```

**Comment by mmccool** [comment]
See PR https://github.com/w3c/wot-thing-description/pull/538

**Comment by mmccool** [comment]
Extended to also take care of Issue https://github.com/w3c/wot-thing-description/issues/470.

**Comment by vcharpenay** [comment]
See Section 6.3.3 Adding Security Schemes of PR #590. Changes are the following:
 - `scheme` is now an open list, new schemes can be added
 - instead of an illustrative namespace for OAuth, the `wotsec:` namespace is being used in the example
 - the textual description with example has been moved to a dedicated section under 6.3 Context Extension

**Comment by sebastiankb** [comment]
https://w3c.github.io/wot-thing-description/#example-30 has now an updated example with ACE.
