### ISSUE TITLE
JSON-LD Examples are not valid according to schema

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#511]
The JSON-LD tabs in examples 1 and 2 contain `@context` on data schema level as an object. However, this is not allowed since `@context` should be first a string or an array with a string + an object

**Comment by vcharpenay** [comment]
this won't be the case after PR #510 is merged.

**Comment by vcharpenay** [comment]
this won't be the case after PR #510 is merged. However, is there such a strict assertion in the spec? From JSON-LD, it can also be an array with an arbitrary number of elements.

**Comment by egekorkan** [comment]
After #510 this can be closed
