### ISSUE TITLE
Standard format for time stamps

### ISSUE THREAD

**Issue by akeranen** [w3c/wot-thing-description#522]
The time stamps for "created" and "lastModified" should follow the ISO 8601 standard to be machine-readable. If there's need for non-standard time information for human consumption, that could be in the description part.

**Comment by mmccool** [comment]
I agree!   Now is the time to insist these follow a standard.

**Comment by sebastiankb** [comment]
In today's TD meeting we agreed to follow this proposal and there must be assertion that MUST be followed.

**Comment by jmcanterafonseca** [comment]
what subset of ISO8601 are you going to follow?

It would be good to align your work with ETSI NGSI-LD, you can take our content directly see 

https://www.etsi.org/deliver/etsi_gs/CIM/001_099/009/01.01.01_60/gs_CIM009v010101p.pdf , section 4.6.3

**Comment by sebastiankb** [comment]
the issue will be simple solved by declaring the "created" and "lastModified" as [xsd:dataTime](https://www.w3.org/TR/xmlschema-2/#dateTime) in the TD model.

**Comment by vcharpenay** [comment]
see [Section 6.1.1 Mapping to JSON Types](https://w3c.github.io/wot-thing-description/#td-basic-types-mapping).

The format is a subset of both `xsd:dateTime` and what NGSI-LD specifies.
