### ISSUE TITLE
Top level versus root versus thing resource

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#535]
There seems to be a mixed use of *thing resource*, *top level* and *root*. Below are some examples:

Section 5.2.1:
> When a concrete Thing is defined in a Thing Description, it is called a thing resource

> See an example for an usage of form in a thing resource.

Section 6.1.1
> The root object of a Thing Description instance MAY include the `@context` name

Below Example 13:
> When forms is present at the top level, it can be used to describe meta interactions supported by a Thing instance.

At least we should remove root or top level since they mean exactly the same thing. However, thing resource seems to be used only a couple of times, making it a new term to understand for the reader while it doesn't seem to be very important. The sentence `See an example for an usage of form in a thing resource` should be replaced with `See an example for an usage of form at the top level`.

**Comment by mkovatsc** [comment]
This whole notion of "interaction resource" should be dropped. We have operations on the Thing that are described by Forms and we have operations on the Interaction Affordances, also described by Forms.

**Comment by mkovatsc** [comment]
Also "payloads are assigned an object type schema with its properties equal to the Thing's property resources" in 5.2.1 must be fixed.

**Comment by sebastiankb** [comment]
I asked @takuki, this issue is already addressed and can be closed.
