### ISSUE TITLE
@context for security and data schema

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#536]
`@context` has been removed from the vocabulary definitions of Data Schema and Security Scheme but its assertions and thus the associated paragraphs are still present at the end of section 5.3.1 and 5.4.1.

**Comment by sebastiankb** [comment]
good point! This has to removed.

**Comment by mmccool** [comment]
I was wondering... I was trying to update the implementation report just now (to match the at-risk highlighting in the TAG version, among other things) and ran into this just now.   How about I include removing these as part of my PR to update the atrisk highlighting?

**Comment by mmccool** [comment]
OK, PR https://github.com/w3c/wot-thing-description/pull/537 removes those assertions.
Note I left the "sh:description" for SecurityScheme there, but blank, in case we need to add back some other assertions.

**Comment by egekorkan** [comment]
This has been fixed
