### ISSUE TITLE
Rename created --> createdAt. lastModified --> modifiedAt

### ISSUE THREAD

**Issue by jmcanterafonseca** [w3c/wot-thing-description#546]
It would be good to rename 

`created` to `createdAt` and `lastModified` to `modifiedAt`.  it is more elegant and consistent. 

It would align with ETSI NGSI-LD https://www.etsi.org/deliver/etsi_gs/CIM/001_099/009/01.01.01_60/gs_CIM009v010101p.pdf 

Another option is to rename just `lastModified` to `modified` to align with Dublin Core, 

but the current naming is not consistent, either way `created` , `modified` or `createdAt`  `modifiedAt` can work for me (although I would prefer the latter).

**Comment by sebastiankb** [comment]
@mlagally what do you think?

**Comment by mlagally** [comment]
fine by me

**Comment by sebastiankb** [comment]
in today's TD meeting we decided to change only `lastModified` to `modified`

**Comment by jmcanterafonseca** [comment]
would it be possible to append the "At" at the end. I believe it would make
it clearer ...

**Comment by sebastiankb** [comment]
in the TD call we preferred the Dublin Core approach since it is more _compact_. This is also the reason to stay with `created`

**Comment by jmcanterafonseca** [comment]
ok, fair enough
