### ISSUE TITLE
[Editorial] Example hrefs are inconsistent

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#547]
Each example in the TD document has a link to their title but they are inconsistent in their format which cause linking problems in the future. Examples:
Example 1: https://w3c.github.io/wot-thing-description/#simple-thing-description-sample
Example 3: https://w3c.github.io/wot-thing-description/#example-3
Example 34: https://w3c.github.io/wot-thing-description/#example-34-temperature-event-with-subscripton-and-cancellation-for-a-thing-2-thing-interaction

Examples 3-30 seem to use the format of Example 3 and I think this is the best one

**Comment by sebastiankb** [comment]
Numbering such as examples 3-30 are auto generated href IDs from ReSpec. The others are human-made.

**Comment by mkovatsc** [comment]
This issue is about the manually assigned id, which becomes the fragment identifier in the link.

**Comment by egekorkan** [comment]
> Numbering such as examples 3-30 are auto generated href IDs from ReSpec.

In this case, why not use the auto generation for all the examples?

**Comment by sebastiankb** [comment]
since there is a change in the ReSpec script almost every day and we don't know if the ID pattern is changed. i want to prevent us from running into broken links.

**Comment by egekorkan** [comment]
I will close this issue
