### ISSUE TITLE
Is @context properly specified in JSON-LD examples?

### ISSUE THREAD

**Issue by jmcanterafonseca** [w3c/wot-thing-description#548]
For instance in example 1.1 

```
{
    "@context": "http://www.w3.org/ns/td",
    "id": "urn:dev:wot:com:example:servient:lamp",
    "name": "MyLampThing",
  .... 
```
@context it is pointing to some kind of namespace prefix I guess, However it should point to the JSON-LD @context definition file, wherever it is going to be published. 

Probably what you intend to do is:

```
{
   "@context": {
      "@vocab": "http://www.w3.org/ns/td#"
  } ,
  ... 
}
```

**Comment by vcharpenay** [comment]
Hi, thanks for your question. According to [JSON-LD, Section 5.1 "The Context"](https://www.w3.org/TR/json-ld/#the-context):

> Contexts can either be directly embedded into the document or be referenced.

Here, the JSON-LD context is referenced by the TD namespace URI. The following HTTP request will return the `@context` definition file:

```http
GET /ns/td HTTP/1.1
Host: www.w3.org
Accept: application/ld+json
```

It is intended to be a shorthand, it is not a mistake. The context definition you suggest, with `@vocab`, will work in most cases but there are corner cases that are dealt with in the referenced context.
