### ISSUE TITLE
Use JSON-Schema Draft07 in JSON Schemas

### ISSUE THREAD

**Issue by jmcanterafonseca** [w3c/wot-thing-description#549]
I think it would be good to use draft07 of JSON Schemas.

**Comment by jmcanterafonseca** [comment]
I can contribute if agreed

**Comment by egekorkan** [comment]
What keywords of Draft 7 do you want to use and what will be their advantage?

**Comment by jmcanterafonseca** [comment]
I think taking the last version is safer in terms of tool support. For instance, format: iri it is a good addition, btw are TD ids to be URIs or IRIs?

**Comment by egekorkan** [comment]
> I think taking the last version is safer in terms of tool support.

I agree with this.

> btw are TD ids to be URIs or IRIs?

I am not completely sure on this. After your comment I have checked this and we should have been using IRIs due to https://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/#anyURI

If we confirm this, I can do the change.

**Comment by sebastiankb** [comment]
@handrews  would be great if you can comment on this?

**Comment by vcharpenay** [comment]
> btw are TD ids to be URIs or IRIs?

`id` being an alias for `@id`, values can very well be IRIs, as [specified by the JSON-LD recommendation](https://www.w3.org/TR/json-ld/#iris). The ultimate answer depends on the media type associated to individual TD documents:

 - if the media type is `application/ld+json` (with a TD profile), the value may be an IRI and it should be understood by clients (but it is not defined whether the TD can be serialized as a pure TD, see below)
 - if it is `application/td+json`, then the value for `id` should be a URI, as per the information model.

As far as I can tell, the current plan is to allow both options.

**Comment by egekorkan** [comment]
A tested version with draft 7 is found here: https://github.com/egekorkan/wot-thing-description/blob/master/validation/td-json-schema-validation.json

**Comment by sebastiankb** [comment]
issue is solved by PR above. TD spec uses 07 draft
