### ISSUE TITLE
In JSON Schemas put definitions at the beginning

### ISSUE THREAD

**Issue by jmcanterafonseca** [w3c/wot-thing-description#550]
I usually see in JSON Schemas definitions at the beginning

I can contribute fixing this

**Comment by egekorkan** [comment]
Do you mean the following:

Currently:
```
{
    "title": "WoT TD Schema - March 2019",
    "$schema ": "http://json-schema.org/draft-06/schema#",
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "format": "uri"
        },
     ...
    },
    "definitions": {
        "thing-context": {
    ...
    }
}
```
Your proposal:
```
{
    "title": "WoT TD Schema - March 2019",
    "$schema ": "http://json-schema.org/draft-06/schema#",
    "definitions": {
        "thing-context": {
    ...
    },
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "format": "uri"
        },
     ...
    }
}
```

**Comment by jmcanterafonseca** [comment]
yep

**Comment by egekorkan** [comment]
I would be tempted to say that it would be confusing to read a schema like this since one is met with a lot of definitions that are maybe used later.

**Comment by jmcanterafonseca** [comment]
I could say the other way round. it would be confusing to read a schema referencing structures not already seen in the document ...

**Comment by egekorkan** [comment]
That is also a valid point ^^. After checking the examples provided by JSON schema I see that your point is valid

**Comment by jmcanterafonseca** [comment]
it seems this is fixed in latest version of the JSON Schema

**Comment by egekorkan** [comment]
Can be closed?

**Comment by jmcanterafonseca** [comment]
yep, fixed!
