### ISSUE TITLE
JSON Schema security scheme could be moved to a separate file and referenced from the main schema

### ISSUE THREAD

**Issue by jmcanterafonseca** [w3c/wot-thing-description#551]
I can contribute to this if required

**Comment by egekorkan** [comment]
This is always a possibility but then there would be also a full/simple for security schemes. Is this mainly to make the schemas more compact or is there another benefit?

**Comment by jmcanterafonseca** [comment]
benefit is a shorter schema, more modular, why the full cannot be just an extension (allOf) of the simplified?

**Comment by egekorkan** [comment]
> why the full cannot be just an extension (allOf) of the simplified?

I had done tests on inheriting schemas in the beginning but haven't managed to do so and went with this non-elegant solution. I don't see how `allOf`fixes it though?

**Comment by sebastiankb** [comment]
for now I see it as 'nice to have' and such kind approach can also organized individual based on the given TD Proposal to defer
