### ISSUE TITLE
Usage of "endpoint" throughout document

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#554]
This comes from the joint review with IETF.

The term "endpoint" is used quite at ease although better choices exist (e.g., submission target for forms).

**Comment by sebastiankb** [comment]
- should be renamed inside the href definition and forms. the **words submission** target should be used instead.

**Comment by sebastiankb** [comment]
http and forms do not use endpoints anymore

**Comment by mkovatsc** [comment]
Only mentions, where we mean endpoint in the IETF sense (socket address). Closing.
