### ISSUE TITLE
Define form context

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#555]
Forms must have a form context. For TD, the form context is always the surrounding Interaction Affordance or Thing, when a Thing-level form.

See https://w3c.github.io/wot-architecture/#sec-hypermedia-forms

**Comment by sebastiankb** [comment]
is this just a hint or shall we provide more information in the spec?

**Comment by sebastiankb** [comment]
I would simple add after 

> A form can be viewed as a statement of "To perform an operation type operation on form context , make a request method request to submission target" where the optional form fields may further describe the required request.

The form context is given by the surrounding Property, Action, or Event Interaction Affordance.

What do you think?

**Comment by mkovatsc** [comment]
In Thing Descriptions, the form context is the surrounding Object, such as Properties, Actions, and Events or the Thing itself for meta-interactions.

**Comment by mkovatsc** [comment]
Conceptionally a good fix, please include! Thx.
