### ISSUE TITLE
contentEncoding form field

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#557]
The IETF received inquiries for content coding (gzip, deflate, ...) support in CoAP and also has discussion in SenML to allow for its definition.

TD currently only supports content type, but not content coding (which is defined in the Content-**En**coding header field): https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding

Should we add a new term `contentEncoding` with range from here: https://www.iana.org/assignments/http-parameters/http-parameters.xhtml#content-coding ?

Could be an at-risk feature...

**Comment by ektrah** [comment]
Should be called `contentCoding` in accordance with the terminology used in [RFC7230](https://tools.ietf.org/html/rfc7230)/[7231](https://tools.ietf.org/html/rfc7231). The header field name "Content-Encoding" is only still there for historical reasons,

**Comment by takuki** [comment]
Is a WoT client required to make a form request using the specified content-coding if one is provided?
Or is it just a hint that a WoT server can process the content-coding?

**Comment by ektrah** [comment]
@takuki That would depend on how you define it. I guess that you should be able to express support for a content type with or without some content coding or both, since not all Things might support everything.

**Comment by mkovatsc** [comment]
This issue was raised because there are IoT solutions out there that make use of content coding. To have useful support in TD, it should behave similar to content type, i.e., when it is defined in a form it must be used for request payload and it may apply to the possible response; it must also be definable in the response field of forms. When it is absent, no content coding applies.

**Comment by sebastiankb** [comment]
in today's TD call we decided to have `contentCoding`  in the Forms. 
@ektrah or @mkovatsc can you make a PR?
