### ISSUE TITLE
TD has no support for describing methods

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#558]
Currently, the required request method is only mentioned in examples for extension context. Otherwise, there is no mention that forms MUST have a request method field.

Furthermore, none of the assumptions are documented: GET when `readproperty`, PUT when `writeproperty` etc.

It does make sense when the request method field for forms comes from the protocol-specific vocabulary and not the TD vocabulary, e.g., `htv:methodName`.

However, there must be a normative assertion that such a protocol-specific field has to inserted into the form to have a valid form (the request method is mandatory), either explicit in the TD, or through a default value that is derived from affordance/op-type/protocol.

Since the TD spec currently only makes HTTP examples and only has the HTTP in RDF vocabulary, it would suffice to specify the default values for HTTP only so far. Once with have the CoAP or MQTT extension (with its vocabulary), we can write an updating spec that defines the defaults for that protocol.

**Comment by sebastiankb** [comment]
In today's TD web meeting we decided to have separate (normative) chapter that explained the protocol handling for http only. It will also point out that other protocol handling is possible by separate (normative) documents in the future. Future explanations is given by the protocol binding template document.

**Comment by vcharpenay** [comment]
See [Section 7.3 Protocol Constraints](https://w3c.github.io/wot-thing-description/#protocol-constraints), added today to the editor's draft.

**Comment by mkovatsc** [comment]
I do not understand why suddenly a concept of explicit and implicit is introduced, when elsewhere TD has a working mechanism with default values. Is it necessary to make it more complex than it is?

**Comment by vcharpenay** [comment]
Ok, here is another attempt: f6b53f0 (same link as above).

Let me know what you think.
