### ISSUE TITLE
Is WoT ontology normative or not

### ISSUE THREAD

**Issue by takuki** [w3c/wot-thing-description#56]
During the last LD call, a question was raised to ask whether WoT core ontology files are intended to be normative or not. When other ontology such as SSN wants to integrate into WoT by ontology alignment, it would be better if WoT ontology is also a standard.

**Comment by sebastiankb** [comment]
In Prague f2f I will put this on the agenda.

**Comment by sebastiankb** [comment]
The TD spec does not claim a TD ontology and should be not normative. We used a ontology as a  _tool_ to setup the TD model. However, the URL namespace https://www.w3.org/ns/td is normative. Behind the URL the TD ontology can be provided.
