### ISSUE TITLE
Make a request for TD media type registration at IANA

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#560]
We have to start the process to register `application/td+json` at IANA. This has to be announced in the TD specification.

**Comment by sebastiankb** [comment]
@ashimura will talk with Ralph about this

**Comment by ektrah** [comment]
FWIW, from the IETF side, this should be as easy as filling out this form: https://www.iana.org/form/media-types.

[RFC 6838](https://tools.ietf.org/html/rfc6838#section-3.1):

> Standards-tree registrations from recognized standards-related organizations are submitted directly to the IANA, where they will undergo Expert Review prior to approval.

**Comment by mkovatsc** [comment]
The e-mail to media-types@iana.org for the Preliminary Community Review is out. Track on https://mailarchive.ietf.org/arch/browse/media-types/

**Comment by mkovatsc** [comment]
@ektrah Is there something similar for CoAP Content-Fortmat IDs? I included that information in the mail to IANA. We want to go for the 2-byte range in 256-1000, since TDs are usually quite large anyway.

**Comment by ektrah** [comment]
@mkovatsc I assume you mean the media-types@ietf.org mailing list for community review; or have you contacted IANA already directly? You could send the content format registration request also to the core-parameters@ietf.org mailing list for community review. But since there's not much to review in a content format registration (the meat is in the media type registration), you could simply include this when sending the request to IANA.

**Comment by mkovatsc** [comment]
https://tools.ietf.org/html/bcp13#section-5.1 lists "@iana.org", but I guess it is the same mailing list.

I included the intent for Content-Format there, so I will do both in the IANA request.

**Comment by mkovatsc** [comment]
Update:

Besides the mail from Mark on the [mailing list](https://mailarchive.ietf.org/arch/browse/media-types/), I received a comment about "clipboard flavor names". They help in operating systems to preserve the format when copying & pasting between applications. The commentator has been busy, so I am still waiting for some consensus on that.

**Comment by mkovatsc** [comment]
I just checked [IANA](https://www.iana.org/assignments/media-types/media-types.xhtml) and in many cases the reference points to the CR document.

Unfortunately, the reference in the IANA section of the TD CR was not updated.
@ashimura Can we fix this? Or ideally, we should give the updating https://www.w3.org/TR/wot-thing-description/ as reference for IANA, no?

**Comment by mkovatsc** [comment]
Unclear what "Reference" IANA expects:

* https://www.iana.org/assignments/media-types/media-types.xhtml should probably be [W3C][Kazuyuki_Ashimura]
* https://www.iana.org/assignments/core-parameters/core-parameters.xhtml would however be ["Web of Things (WoT) Thing Description", June 2019] -- or July 2019...
* Is this related to the "Published specification" field in the registration request / IANA section?

**Comment by mkovatsc** [comment]
There was a comment about "clipboard flavor names" that help copy-pasting in OSes. However, I could not find anything related at IANA and there seem to be only the Apple and Microsoft flavors:

https://github.com/w3c/html/issues/227

**Comment by sebastiankb** [comment]
@mkovatsc what is the status here?

**Comment by takuki** [comment]
Here is a link to a guideline called [Register an Internet Media Type for a W3C Spec](https://www.w3.org/2002/06/registering-mediatype2014.html).

**Comment by takuki** [comment]
[Here](https://mailarchive.ietf.org/arch/browse/media-types/?q=wot) is the email thread that is discussing media type registration in the IANA media-types mailing list.

**Comment by takuki** [comment]
I propose to send to the following message to the IANA [media-types mailing list](https://mailarchive.ietf.org/arch/browse/media-types/). 

> Dear IANA
> 
> In May this year, representing the Web of Things WG at W3C, Matthias Kovatsch 
> asked a Preliminary Community Review for the intent to register both a media type
> "application/td+json" and a CoAP Content-Format ID for WoT Thing Description (TD).
> (Please see https://mailarchive.ietf.org/arch/msg/media-types/2YAycXGB9a_HGteOsZ70EyeJSqE)
> 
> We received two comments for the review request. 
> 
> One was a question about the need for registering a media type for WoT TD given 
> that there is already a media type registered for JSON-LD. It was adressed in 
> a response message https://mailarchive.ietf.org/arch/msg/media-types/7kT3dXdqY9OZUT7gKIrtWRwTLbE .
> 
> The other comment was recommending to define clipboard identifiers for WoT TD.
> We suggested to leave it out for the current version of the WoT TD spec, and
> re-visit the issue for WoT TD version 1,1. Note there are no clipboard 
> identifiers defined for JSON-LD or JSON at this moment. The WoT WG should 
> consult with JSON-LD WG in the meantime. This will provide enough input to 
> choose the right level of specificity before the next version becomes ready 
> for review. Please see
> https://mailarchive.ietf.org/arch/msg/media-types/-ETsTQJU6GMdjlp5bUErl4lHZB4 .
> 
> Since there has been no more comments or further discussions, we would like to
> ask you to consider the preliminary community review complete and permit us to proceed.

**Comment by sebastiankb** [comment]
@kaz @plehegar I think we need support from you. It seems we cannot go to PR transition without the registration the TD media type application/td+json.

**Comment by plehegar** [comment]
The form at https://www.iana.org/form/media-types needs to be completed. Who would be best to do that? It doesn't have to be someone from the W3C staff (they'll check with me in any case before sending it to the review expert).

**Comment by ektrah** [comment]
Done. The reference number assigned by IANA to the registration request is 1158000.

**Comment by plehegar** [comment]
Confirmed the request to IANA. They will list it as Provisional until they get expert review.

**Comment by mmccool** [comment]
Our conclusion is that being provisional, this is not a blocker for a PR transition request.

**Comment by sebastiankb** [comment]
for record #874

**Comment by sebastiankb** [comment]
I recommend that the issue can be closed as PR #880 was merged and no further action is required.

**Comment by sebastiankb** [comment]
discuss this in today's TD call that is ok to close this issue
