### ISSUE TITLE
Reading and  writing Properties are not consistent

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#563]
In 5.2.2.1 PropertyAffordance, we are talking about retrieving, setting instead of reading and modifying, setting instead of writing. This should be consistent with op values.

A discussion to use the architecture document definitions is in place

**Comment by sebastiankb** [comment]
this should be synchronized with the WoT Architecture document. Will be discussed on Friday

**Comment by sebastiankb** [comment]
based on the feedback from @mkovatsc we can simple take the definitions from the Architecture document since it is stable there

**Comment by mkovatsc** [comment]
The WoT Arch definitions include explanation text. To gain consistency in TD, the terms read and write should be used, as used in the corresponding op types and stated by @egekorkan .

**Comment by sebastiankb** [comment]
the latest polished TD version should be in sync with Arch and have no words used such as retrieving

**Comment by egekorkan** [comment]
The word retrieving is still there as of 06.05 11:16 am at 5.3.1.3 PropertyAffordance:
> An Interaction Affordance that exposes state of the Thing. This state can then be retrieved (read) and optionally updated (write).

**Comment by sebastiankb** [comment]
you are right, however, this is aligned with the Architecture document (see https://w3c.github.io/wot-architecture/#terminology)
