### ISSUE TITLE
Semantics of Forms.op "writeallproperties" is unclear

### ISSUE THREAD

**Issue by zolkis** [w3c/wot-thing-description#568]
The ```writeallproperties``` op has not much use in Scripting, since ```writemultipleproperties``` can cover the same use case, and ```writeallproperties``` has issues:
- we still have to specify all the values, in that case not different from ```writemultipleproperties``` unless all the values are of the same type (to be clarified if that is the use case)
-  we must guarantee we write _all_ properties, so does that mean the properties not specified to ```writeallproperties``` call should be removed from the target Thing? That would result in changing its TD and I am pretty sure that's not the desired outcome (to be clarified).

**Comment by sebastiankb** [comment]
there doesn't seem to be a problem for the TD specification itself, but rather for the scripting API. Or do I misunderstand something?
