### ISSUE TITLE
Support of Scripts in ThingDescription

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#57]
During a Scripting call the discussion was raised whether

1. Scripting might or could be a first class citizen in the core ThingDescription comparable to Scripting in HTML or wether we should target a
2. completely layered approach.

While we are aware of certain downsides of 1. we would like to start collecting pros and cons with that regard in this issue.

HTML offers a scripting "placeholder" with the possibility of also identifying the scripting language but without specifying the actual content.

Example:
`<script language="JavaScript"> /* ... */ </script>`

A similar approach could be used for ThingDescription scripts. One example could be that a simple WoT Counter can be easily serialized as a single TD file containing the interaction but also the scripting logic of incrementing the counter et cetera.

Without the possibility of "storing" scripts as part of a TD this would be more complex having external resources that would need to be referenced properly.

Storing scripts as part of TD is a possibility that may help in some cases and may not be sensible in other use-cases. This is very much in line with HTML and scripts.

The scripting task force looks forward to your input/comment/feedback...

**Comment by zolkis** [comment]
Of course scripting support would be optional in the TD and WoT runtimes that don't support scripting can reject or ignore scripts, depending on the context.

The symmetrical approach would be something like Polymer, i.e. the possibility to use (reusable) TD components in scripts, a mix of declarative, functional and event-driven programming.

**Comment by mkovatsc** [comment]
Scripts in HTML are for code-on-demand, i.e., to ship new client code to clients. This proposal was build on the idea of including server code in the TD.

On the way to the and Working Draft of the WoT Scripting API, the working assumptions returned to a clean split between code and metadata/TD.
