### ISSUE TITLE
Clarify assertions in Section 5 & 6

### ISSUE THREAD

**Issue by vcharpenay** [w3c/wot-thing-description#575]
Several issues:
 - the wording differs in both sections: assertions refer interchangeably to "TD definitions", "Vocabulary terms" and "term members"
 - there are (redundant) assertions in both sections on default values

## Proposal

I opened PR #574 with a few definitions in the terminology section to try to clarify:
 - the **TD information model** is a set of constraints (all in Section 5, either implicitly in the tables or as assertions in each sub-section, e.g. on `op`) and equivalence relations (between TDs with and without default values).
 - a **TD processor** can serialize and deserialize a TD, and "interpret" the information model: it checks that constraints are met and computes equivalences.

Assertions can then be reformulated either as constraint checking or equivalence computation.

**Comment by vcharpenay** [comment]
It seems there is an important decision to make before editing further (follows a discussion with @mkovatsc ).

Question to the group: Is a TD a **data structure**, that can then be serialized in JSON, or is the TD the exchanged **JSON document** itself?

**Comment by egekorkan** [comment]
I have always *thought* it as your first proposal, a data structure that can then be serialized in JSON

**Comment by vcharpenay** [comment]
We discussed the issue today in the TD call. The general comment was that the TD should be the data structure but it is OK to call a 'TD serialization' a TD in the vernacular. There were some suggested rewording, which I implemented (among others to add a def for 'TD Serialization').
