### ISSUE TITLE
Typo - htv / http in Example 2

### ISSUE THREAD

**Issue by azaroth42** [w3c/wot-thing-description#577]
Reading example 2, it seems like there's a typo in the second `methodName` property in `actions`. It is given as `http:methodName` rather than `htv:methodName`.

Or is `http` defined in the context? This is hard to tell as https://www.w3.org/2019/wot/td/v1 does not resolve. Is the context available somewhere else in the mean time?

**Comment by vcharpenay** [comment]
It is indeed a typo, thanks for your review!

The context is available [here](https://w3c.github.io/wot-thing-description/context/td-context-1.1.jsonld).

**Comment by sebastiankb** [comment]
the latest TD version has removed the methodName in example 2 and uses SAREF as context extension example https://w3c.github.io/wot-thing-description/#thing-description-full-serialization

**Comment by azaroth42** [comment]
@vcharpenay @sebastiankb Thanks both! Should external review be against the github.io version, or against https://cdn.staticaly.com/gh/w3c/wot-thing-description/TD-TAG-review/index.html?env=dev ?

**Comment by sebastiankb** [comment]
@azaroth42 Many thanks for doing a review.

I would suggest going for github.io version as it is a more polished version and contains already some achievements from some new resolved issues.
