### ISSUE TITLE
i18n checklist for Working with numbers

### ISSUE THREAD

**Issue by takuki** [w3c/wot-thing-description#579]
### Working with numbers
1. [x] <a class="self" href="#loc_numbers_shape_parse">​</a>When parsing user input of numeric values, allow for digit shaping (non-ASCII digits).

    One of the usage of TD is to create user interfaces for humans to interact with Things based on TDs.
    - For payload, TD uses a type system compatible with JSON Schema.  
        - Therefore, number values in the payload are ASCII digits as required by JSON Schema.
    - However, the software generating user interfaces are free to apply number shaping to interact with users, depending on the user's preferences.
　

2. [x] <a class="self" href="#loc_numbers_shape_display">​</a>When formatting numeric values for display, allow for culturally sensitive display, including the use of non-ASCII digits (digit shaping).

    Similar to the above, a software can process TDs to generate user interfaces.
    - Numeric items (such as minimum and maximum) in the TD Information Model (section 5) are defined in terms of value spaces (instead of lexical spaces) by referencing XML Schema 1.1 datatypes. 
    - The software generating user interfaces are free to apply number shaping to display culturally sensitive numbers, depending on the user's preferences.

**Comment by mkovatsc** [comment]
All items checked. Closing.
