### ISSUE TITLE
i18n check item: TD spec describes a format or data that is likely to need localization

### ISSUE THREAD

**Issue by takuki** [w3c/wot-thing-description#583]
Short i18n review [checklist](http://w3c.github.io/i18n-activity/reviews/shortchecklist) says:

> If the spec (or its implementation) describes a format or data that is likely to need localization, then ensure that there’s an approach in place which allows effective storage and labelling of, and access to localised alternatives for strings, text, images, etc.

@mmccool , can you take care of this item?

**Comment by mmccool** [comment]
I think this item is quite clearly covered by the current spec, given that we allow Multilanguage objects in all places where there are strings that might be made part of a user interface.   So this checkbox should simply be checked "yes".

**Comment by mmccool** [comment]
Resolved, with an update to the checklist.
