### ISSUE TITLE
Clarify on the timezone of DateTime serialization in TD

### ISSUE THREAD

**Issue by takuki** [w3c/wot-thing-description#586]
With regards to the following statement in section 6.1.1 Mapping to JSON Types:

> Vocabulary terms that use simple type dateTime MUST be serialized as JSON string and have the lexical form YYYY-MM-DDThh:mm:ssZ.

@vcharpenay suggested to clarify T and Z in the format are literals, not variables, and that therefore times are always in UTC.

**Comment by sebastiankb** [comment]
@vcharpenay takes care on it

**Comment by vcharpenay** [comment]
just implemented. See [my changes in Section 6.1.1](https://w3c.github.io/wot-thing-description/#td-basic-types-mapping).

**Comment by mkovatsc** [comment]
Is enforcing UTC only really necessary when there is timezone support in the format? Does not feel user-friendly...

**Comment by mkovatsc** [comment]
See also https://github.com/w3c/wot-thing-description/issues/641

**Comment by mkovatsc** [comment]
> While this is correct, a better reference to this specific format would be [RFC3339]'s date-time. This is exactly this format.

> Also, the pattern given includes Z, which, when it appears as the literal string Z means "UTC". But it can also mean that offsets such as -03:00 or +08:00 are also permitted. Please clarify what is intended here and note that UTC is recommended, even if offsets are permitted.

**Comment by vcharpenay** [comment]
my rationale was, because these terms are for annotation purposes (not functional), I wanted to simplify the mapping such that there a single lexical form for each possible value. If necessary, I can relax the assertion to allow other time zones.

**Comment by mkovatsc** [comment]
The issue is that I think it is highly likely that other forms than Zulu time will end up in there. Should they be invalid then? I would say no.

**Comment by jmcanterafonseca** [comment]
Opting for only allowing 'Z' terminated strings is a good thing in terms of simplicity. Also can help future API designs around the TD, for instance discovery APIs, "give the TDs modified before <date>

on a side note ajv JSON Schema validator only accepts `date-time` format strings 'Z' terminated ...

**Comment by mkovatsc** [comment]
Maybe do a "SHOULD" assertion, so that other forms are not considered an Error.

**Comment by vcharpenay** [comment]
it's a good trade-off, indeed. That's what I did in 2086f076f168408a7098d151b298a0bd2efd941f.

**Comment by sebastiankb** [comment]
>In particular, Z is mandatory and must be interpreted as the UTC+00 time zone. This lexical form represents a subset of the XSD built-in dateTime datatype , itself inspired by [RFC3339] for timestamps.

musbt be fixed @vcharpenay taking care of it

**Comment by vcharpenay** [comment]
PR was closed
