### ISSUE TITLE
@context below document level for parts of TD

### ISSUE THREAD

**Issue by takuki** [w3c/wot-thing-description#587]
@context, when it is found below document level, can redefine a default @language.

Do we allow it?
We should be clear about that in the TD spec.

- This is related to the media type discussion.
    - If we go for a JSON-LD profile instead of a TD media type,  we wouldn't be able to make constraints.
        - During 4/30 telecon dedicated to Media Type and Namespaces issues, it was suggested to register both a IANA media type and a JSON-LD profile for TD.
- If we allow it, it makes client processing more complicated.
    - If clients can't process nested contexts, can they ignore them?

**Comment by takuki** [comment]
According to the definition of "profile" parameter in JSON-LD at [here](https://w3c.github.io/json-ld-syntax/#iana-considerations):

> A profile does not change the semantics of the resource representation when processed without profile knowledge, so that clients both with and without knowledge of a profiled resource can safely use the same representation.

Also, [RFC6906](https://tools.ietf.org/html/rfc6906) says:

> The concept of a profile has no strict definition on the Internet or on the web.  For the purpose of this specification, a profile can be described as additional semantics that can be used to process a resource representation, such as constraints, conventions, extensions, or any other aspects that do not alter the basic media type semantics.  A profile MUST NOT change the semantics of the resource representation when processed without profile knowledge, so that clients both with and without knowledge of a profiled resource can safely use the same representation.  While this specification associates profiles with resource representations, creators and users of profiles MAY define and manage them in a way that allows them to be used across media types; thus, they could be associated with a resource, independent of their representations (i.e., using the same profile URI for different media types).  However, such a design is outside of the scope of this specification, and clients SHOULD treat profiles as being associated with a resource representation.

Based on those definitions, I think we can still constrain @context so that it only appear at the top level if we so wish.

**Comment by takuki** [comment]
During May 3 TD telecon, it was suggested not to prohibit @context at lower-levels.

The complexity it will add to detect @language and switch languages were found minimal.

**Comment by mkovatsc** [comment]
Section 5 defines `@context` only within the `Thing` class. To me, this means TDs do not allow embedded contexts and raw JSON processors would not be prepared for it.

The current text also says that only one default language can be encoded in the top-level `context`.

To me, this is a good and simple solution. I propose closing.

**Comment by sebastiankb** [comment]
agreed with @takuki we can close this issue.
