### ISSUE TITLE
Proper IANA Considerations section

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#588]
We need a proper top-level section for the IANA registration, following their template:

https://tools.ietf.org/html/bcp13#section-5.6

JSON-LD 1.1 has a good example:

https://w3c.github.io/json-ld-syntax/#iana-considerations

**Comment by mkovatsc** [comment]
Once done, I also need to send the e-mail to media-types@iana.org following https://tools.ietf.org/html/bcp13#section-5.1

**Comment by mkovatsc** [comment]
Done: https://mailarchive.ietf.org/arch/browse/media-types/

**Comment by takuki** [comment]
@mkovatsc , we need to update IANA with the CR version URL.

**Comment by mkovatsc** [comment]
So far, I only sent out the Preliminary Community Review, for which the Editor Draft still is technically up to date.

It is a pitty that the Link under IANA Considerations was not updated in the CR version... We have to make sure we reference the right document when sending the actual registration request to IANA.

See #560 for IANA progress.
