### ISSUE TITLE
Alignment with Generic Sensor spec

### ISSUE THREAD

**Issue by zolkis** [w3c/wot-thing-description#59]
For data/type representation issues, make sure WoT TD is aligned with [W3C Generic Sensor](https://www.w3.org/TR/generic-sensor/) spec.

The question: is it possible to model the Generic Sensor with WoT TD? 
If yes, make that TD public. 
If no, identify and address the gaps.

**Comment by sebastiankb** [comment]
Are there already some efforts on that? It seems to be also a relevant for the WoT API, right?

**Comment by zolkis** [comment]
What concerns the scripting API, we have investigated the opportunities.

In this issue, the first question was whether and how a TD can describe Generic Sensors. We need to create examples how to do it. This is increasingly relevant, as more and more solutions pick up Generic Sensors.

Then, the next question is whether can the TD profit from the data representation in Generic Sensor specifications.

**Comment by sebastiankb** [comment]
I have still difficulties understand the impact of this API to the TD. Maybe, when you create examples this could make the situation more clearer for us.

**Comment by sebastiankb** [comment]
Is this issue is still relevant, please open it again.
