### ISSUE TITLE
Update at-risk and minimize spurious highlighting

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#597]
- Remove at-risk highlights that are simply missing tests but are clearly supported
    - eg the assertions that basically say "this is a JSON file"
- Re-interpret features used in several places, eg "description", as being implemented even if they do not appear in every single context
- Update "scheme" to take into account new definition as simply "string", so don't need every single scheme
- Update manual assertions to cover all new assertions
    - And ping implementators to gather final manual assertions

NOTE: I will try to get this done by Saturday night, so implementors should try to update manual assertion reports by Monday.   I will regenerate the highlighting Saturday night and Tuesday (the latter to include any manual assertion updates).

**Comment by mmccool** [comment]
See PR https://github.com/w3c/wot-thing-description/pull/651

**Comment by mmccool** [comment]
Note: it should be possible to merge this PR even if the base document changes significantly, since most changes were to testing/inputs/atrisk.csv.   However, there were a few small changes to index.template.html to clean up the at-risk highlighting explanation at the very start of the document.  Diffs in index.html and in other places are "render noise" and can be ignored.

**Comment by sebastiankb** [comment]
please check the default value table https://w3c.github.io/wot-thing-description/#sec-default-values
