### ISSUE TITLE
Add text direction definition

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#598]
State that default text direction is to be inferred from the default language but that this places some restrictions on strings (they should not start with text, such as numbers, that are not in the same direction as the default language).

Please comment if you find a suitable citation or text in a similar specification that we can reuse.

**Comment by mkovatsc** [comment]
I think we should pick this solution: https://www.w3.org/TR/string-meta/#script_subtag

* We are based on JSON-LD, which "prevent the use of metadata" for direction metadata
* Default is LTR
* Langauge tags in `MultiLanguage` names MAY indicate RTL
* We must state that the `MultiLanguage` names MUST provide the [script subtag](https://tools.ietf.org/html/bcp47#section-2.2.3) when it changes the direction

**Comment by mkovatsc** [comment]
Also make a note that this puts constraints on strings such as a RTL string cannot start with a multi-digit number. Here we might want to ask for help to be correct.

**Comment by mmccool** [comment]
So, after reading over the section noted in string-meta, I think the "don't start with a number" issue is not actually a problem if we state that the base direction is ALWAYS inferred from the script sub-tag.  There are cases however where numbers with embedded spaces are displayed in the wrong order but this seems to be a problem with all encodings.  However, I noticed an additional problem: we have to limit the strings to which this is applied to the human-readable entries, i.e. title, description, etc.  For example, we would not want to apply it to "scheme", even though it is a "string".  

One troublesome field though is "support".  This is a "string", but is "free-form": it could be a URL, or it could be human-readable text, or it could be a phone number (which could run into the embedded spaces issue...).   Solutions include:
- Saying it must always be a URI
- Removing it
- Saying it must always be human readable
- Saying the strong-first algorithm must be used on it instead of the default base direction

I personally am in favor of the first option.   There is also no "supports" which would be weird anyway.  But if we give a URI then what it points at can do the heavy lifting.

**Comment by mmccool** [comment]
The Thing "name" is also troublesome.  I assume this is meant to be human-readable text, eg for display on web dashboards, and is not meant to be unique (we have the id for that).   So I'm assuming that we should apply the base direction to it.

However, there is no "names".   As a separate issue (which I will file), I think there should be, so that when language negotiation is used a name in an appropriate target language can be provided.

**Comment by mmccool** [comment]
Also, Matthias, you are saying the default base direction should be RTL.   I think this should be the default only if no `@language@ tag is present in the enclosing context.   If it is, then the base direction should be inferred from the script subtag used in `@language` (which may inferred in the case of languages with only one script).
 
I'd LIKE to specify the default language if no `@language` tag is given but this might be politically incorrect.

**Comment by mmccool** [comment]
Apparently there was a "names", but it was taken out recently: https://github.com/w3c/wot-thing-description/issues/464.  The justification was there didn't really seem to be a need for it.   Well... I will just reopen that issue and cite this one.

**Comment by mmccool** [comment]
See PR https://github.com/w3c/wot-thing-description/pull/620.

**Comment by mkovatsc** [comment]
> Also, Matthias, you are saying the default base direction should be RTL

I wrote LTR -- left-to-right -- as default default, maybe you meant that as well.

> I'd LIKE to specify the default language

We do not have to do this. We only define the default direction to LTR when no `@language` or out-of-band information is available.

> the base direction should be inferred from the script subtag 

I understand https://www.w3.org/TR/string-meta/#script_subtag as follows:

1. Start with default direction (LTR for us)
2. Infer direction from the language tag if provided (the language tag alone can already inform about the direction; script subtag can be computed)
3. Infer direction further from the script subtag if provided (as the script subtag might change the direction; must be provided if it does so)

**Comment by mkovatsc** [comment]
> However, there is no MultiLanguage "names" object

The `name` is an identifier that needn't be unique across Things. However, there should be only one name for a Thing. Thus no `names`. I assume that the name can usually be changed by the user. It underlies the default language.

**Comment by mmccool** [comment]
OK regarding names.   My concern is that if the default language is changed, for example as part of HTTP negotiation returning text for title and description using an alternative language, then the interpretation of these will get broken.   I still think "support" is an issue but for now I have lumped it in with "name" (by adding it to the list of human-readable metadata in Section 6) in that it should be interpreted using the default language (since it might, for example, contain a person's name).

**Comment by mmccool** [comment]
Perhaps in a future TD version we can have an alternative mechanism for specifying a language explictly for "name" and "support" that overrides the default language.   That would be the right way to fix this, I think.

**Comment by mmccool** [comment]
Sigh.   Well, let me make an issue for "supportLanguage".   Maybe we can get it in.

**Comment by mmccool** [comment]
I created a modification of my text-direction PR to define "supportLanguage": https://github.com/mmccool/wot-thing-description/pull/8
This is actually a PR against the branch used to create PR https://github.com/w3c/wot-thing-description/pull/620.   So if we decide to do this, I should merge the PR for supportLanguage first in my own repo, then merge PR620.

**Comment by mkovatsc** [comment]
We somehow have a lot of issues related to this... I would like to simplify for this version of WoT TD. We can do so by defining `support` as anyURI; it can still identify a person by their e-mail address (mailto URI), which is even better than "John Smith" strings. Furthermore, supportLanguage, in me, raises the notion of being able to provide support (in the bigger sense) only in one language...

**Comment by mmccool** [comment]
To wrap this up, I think this is now covered by many other issues and solutions have been merged into the specification.   In summary, we have decided to require "support" to be an URI/IRI and so "supportLanguage" is no longer needed.   Text direction is now addressed in the spec via inference from language/script tags.  I therefore propose we close this issue.

**Comment by mkovatsc** [comment]
Agree
