### ISSUE TITLE
Example 2 title could be improved

### ISSUE THREAD

**Issue by jmcanterafonseca** [w3c/wot-thing-description#599]
Current figure title:

EXAMPLE 2: Thing Description with context extension

Suggested: 

EXAMPLE 2: Thing Description with semantic annotations using the SAREF ontology (@context extension)

**Comment by sebastiankb** [comment]
The examples should just show that there is this context extension feature in the TD. I think the title is enough for that. Further details are described in the paragraph above.

**Comment by jmcanterafonseca** [comment]
could it be "Thing Description with context extension using SAREF" ?

**Comment by mkovatsc** [comment]
@jmcanterafonseca , are there hard feeling for this? (e.g., for marketing SAREF :P )
Otherwise I would close.

**Comment by jmcanterafonseca** [comment]
@mkovatsc intention was not to promote SAREF specifically :), but to promote semantic annotation as a way of showing the potential of TDs ... having said that you can close or add somehow the "semantic annotation" slogan to the example title :) 

thx!

**Comment by mkovatsc** [comment]
Hmm, valid point -- we have been working too hard on hiding this for those who do not like RDF semantics..
Maybe "Thing Description with context extension for semantic annotations" would do something positive :)

**Comment by mkovatsc** [comment]
See #646

**Comment by jmcanterafonseca** [comment]
@mkovatsc thanks! LGTM in #646, once that lands I think we can close this.
