### ISSUE TITLE
Annex B : ThingTemplate : Is it normative? 

### ISSUE THREAD

**Issue by jmcanterafonseca** [w3c/wot-thing-description#600]
ThingTemplate is indeed a good idea, but is it mature enough? is it going to be normative in the TD 1.0? 

On a side note, there can be other, mechanisms, for instance, https://tools.ietf.org/html/rfc6570 to allow to define templates, also it should not be difficult for IoT platform providers to define their own mechanisms for templating Thing Descriptions

**Comment by mkovatsc** [comment]
It shouldn't. As you say, it is not mature enough, in particular the indicated mechanisms. In today's call (3 May 2019) we decided to remove B.1.3.

We also need to mark them non-normative.

**Comment by mkovatsc** [comment]
@sebastiankb marked the section "non-normative". We can close this.
