### ISSUE TITLE
Incomplete change to Affordances

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#607]
Section 6 refers to Property, Action, and Event classes with a broken link.

This is because they are now PropertyAffordance, ActionAffordance, and EventAffordance classes...

**Comment by vcharpenay** [comment]
just fixed them.

**Comment by mkovatsc** [comment]
Still found two issues in Recent Specification Changes

**Comment by mkovatsc** [comment]
Not sure how to deal with this. Shouldn't we include a the class name change in the changelog?

**Comment by mkovatsc** [comment]
Fixer by #610
