### ISSUE TITLE
Usage of the term Vocabulary Term

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#608]
I repeatedly stumble other statements that Vocabulary Terms have values, default values, types, etc.

Technically, a Vocabulary Term is used to identify something, which then can have values, types, etc.

How about we talk about Vocabulary Items and keep Vocabulary Term as the identifier as, for instance, correctly used in the class tables?

**Comment by vcharpenay** [comment]
I am doing changes in that direction, based on [Section 5.1 Overview](https://w3c.github.io/wot-thing-description/#overview): terms *denote* objects or classes of objects. I was planning on scanning section 5/6 over the weekend and applying this wording wherever the text isn't currently consistent.

I don't think another notion like "vocabulary item" is needed, the notion of "object" suffices to me.

**Comment by mkovatsc** [comment]
"Object" is conflicting, as we use JSON objects, and just before the definitions in 5.1, you talk about "physical world objects".

**Comment by mkovatsc** [comment]
Vocabulary Term is defined to also be "a property value (like readproperty)."

This conflicts with all the statements that Vocabulary Terms are serialized to JSON members.

This again tells me, that we need a properly defined term that denotes these class/table entries, and which is different from property value definitions.

**Comment by mkovatsc** [comment]
After @vcharpenay 's revision, it is now a "name-value pair" that is serialized as JSON member. This much better than the mismatched term "vocabulary term" and it avoids the conflict of "property".

Addressed my issue.
