### ISSUE TITLE
TPAC resolution: Observable Properties and Events

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#61]
There have been two main motivations for Observable Properties: more concise TDs (no need for Property + related Event) and good match with CoAP Observe and PubSub-based Protocol Bindings.

Observable Properties are a shortcut for Change-of-Value Notifications. They have the notion of eventual consistency, i.e., individual notifications might be lost without critical impact on the application.

Events are different in two aspects: they can carry information that is not exposed through Properties and Event instances (i.e., Event notifications) are more stand-alone and loss might have a critical impact. Hence they should also be transferred more reliable (custody transfer...). Events are also still understood as to be able to provide a stream of data.

We agreed that we will follow the concept of Observable Properties and Events. We need more practical Protocol Bindings (CoAP Observe, Panasonic proposal, MQTT, etc.).

Events will also be explored to be "transient Things": being described with Properties, Actions, Events, but not being a Thing. Only the TD mechanisms are reused to describe how to interact with an Event, e.g., to confirm reception of an Alert Event, montoring it, resolving it (cf. Action Tasks that need to be monitored, canceled, notified about completion).

**Comment by zolkis** [comment]
I agree on the observable properties idea.

However, not for the reason that these notifications can be lost and events cannot. This is an arbitrary convention. Events (notifications, packets, messages) themselves can be of multiple categories:
- non-critical, can be lost, delivery is not guaranteed and not necessarily in order (like UDP)
- critical, should not be lost and should be delivered in order (like TCP)
- stream, i.e. samples can be lost, but should not be late (like RTP).
If we want to argue about the notification type, it should be exposed on the definition of the WoT Event interaction.

Then we could say that non-critical events are used for value-change notifications. It's more consistent.

> Events will also be explored to be "transient Things": being described with Properties, Actions, Events, but not being a Thing. 

This is another arbitrary convention. It would be simpler and more consistent to model that event data with a Thing, without redefining Events.

**Comment by mkovatsc** [comment]
The main point above was that
- Observable Properties are related to modeled state just like Properties
- Events are related to state transitions (click, keydown, buttonpress) -- in these classic cases, if not observed, the current state is unknown

**Comment by sebastiankb** [comment]
@mkovatsc There was the plan to have a concrete definetion in the architecture document. Also check my comment here https://github.com/w3c/wot-architecture/issues/51

**Comment by mkovatsc** [comment]
I will try to remember to close this after Arch was updated.

**Comment by sebastiankb** [comment]
latest Arch version covers now a good definition
