### ISSUE TITLE
Default value of "contentType" in "response"

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#611]
Currently, the contentType of possible responses defaults to "application/json".

I think it would be better if it defaults to the contentType of the containing form.

If there is agreement, we would need an additional row in the table in 5.2 for `contentType` in Context `ExpectedResponse`.

**Comment by sebastiankb** [comment]
I would propose to have such an entry in the table + a separate assertion explaining that the default value of the response contentType is always the same as that specified by the contentType in the Form class.

**Comment by mkovatsc** [comment]
The current solution has the following problem:
There is a (fixed) Default Value for `contentType` in `reponse`. However, in the absence of `response`, we expect `contentType` in `reponse` to equal `contentType` in the Form object. This Default Value for `response` is not defined, as it is also dynamic...

I the following path:
1 Define the Default Value for `contentType` in `reponse` dynamically based on `contentType` in the Form object (i.e., dynamic). However, `reponse` in the Form object would still be undefined, so is there actually a value for `contentType` in `reponse`?
2. Define a Default Value for `reponse` in `Form`, which is also dynamic based on `contentType` in the Form object. However, it would be a complex type, a Class instance -- is that valid?

**Comment by mkovatsc** [comment]
Good:
* Remove ExpectedResponse contentType from the (static) default value table
* make a simple assertion that in the absence of `repsonse` the expected response content type will be equal to the form content type

**Comment by mkovatsc** [comment]
How could I move the comment back in time before yours?!

**Comment by mkovatsc** [comment]
![image](https://user-images.githubusercontent.com/664090/57412457-023b2b80-71f1-11e9-8315-59e3570f1ba3.png)

Time traveling was also resolved. Closing.
