### ISSUE TITLE
Misleading assertions for security

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#612]
I just stumbled over the following:

> Security schemes MAY also be specified at the form level.
> In this case, definitions at the form level override (completely replace)
> all definitions given at the top level.

I think this is outdated, as we have “securityDefinitions” at the top level and only activate through “security” at lower levels.

Please confirm, I will then fix this in my PR #610

**Comment by mkovatsc** [comment]
I now think this is an editorial issue because the word "definitions" is used to actually mean the `security` activation set. I will fix this in #610.

**Comment by mkovatsc** [comment]
New text:
<p>
  Security configuration in the TD is mandatory.
  <span class="rfc2119-assertion" id="td-security-overrides">
  Security definitions MAY also be activated at the form level by including a
  <code>security</code> member in the form object,
  which overrides (i.e., completely replace) all definitions activated at the Thing level.
  </span>
  <span class="rfc2119-assertion" id="td-security-mandatory">
  At least one security definition MUST be activated through the
  <code>security</code> array, either at Thing level (i.e., in the TD root object)
  or at form level (i.e., in each form object).
  </span>
  </p>

**Comment by mkovatsc** [comment]
@mmccool Please check if the new assertions of PR #610 match your expectation for the security configuration.

**Comment by mmccool** [comment]
Yes, I agree with this update.  "Activation" is a better term here than "definition".

**Comment by mkovatsc** [comment]
Good, since two editors agree, we should move on and merge #610. We still have work to do :)
