### ISSUE TITLE
Make security scheme identifiers more visible

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#613]
Security schemes are defined by a vocabulary term the is quite hidden in the introduction text for each scheme:

> Basic authentication security configuration ("scheme": "basic"), using an 

As this is such an important part, please make it more visible and more prominent than in parentheses:

> Basic authentication security configuration is identified by the vocabulary term `basic` (i.e., "scheme": "basic") and using an ...

**Comment by egekorkan** [comment]
I agree with this proposal and will implement it in #634

**Comment by egekorkan** [comment]
I have implemented your proposal in #634 and specifically in commit [9f5ed5b0c1efbba6fb8a08c06f731050ce782fdf at link](https://github.com/w3c/wot-thing-description/blob/9f5ed5b0c1efbba6fb8a08c06f731050ce782fdf/ontology/wot-security.ttl)

@vcharpenay is it ok to put html tags in rdf:comment, this works but I am not sure if it is best practice.

**Comment by mmccool** [comment]
Lots of HTML markup in RDF comments at this point, not sure it's a good time to change right now ;).

**Comment by mmccool** [comment]
I have marked this as WIP.   Ege, I also need to make some changes to the security sections to deal with the format thing, so I will watch your PR and do a review as soon as it seems to be done, then we can discuss it in the editors's call.   We do need to wrap this up in the next few hours so it can be merged in time for the CR transition version.

**Comment by vcharpenay** [comment]
> @vcharpenay is it ok to put html tags in rdf:comment, this works but I am not sure if it is best practice.

yes, it is. You can even indicate it is an HTML snippet by adding `^^rdf:HTML` at the end of the string.
