### ISSUE TITLE
Allow array for response in From class?

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#617]
Originally, I expected that all possible responses can be described through the `response`(s) vocabulary term.

A use case is where the input of an Action might select the representation format (e.g., RAW vs JPEG vs PNG), and hence multiple responses are possible.

Furthermore, it might be an extension point to also describe expected error responses out-of-band in the future (i.e., to retrofit hypermedia behavior to devices that would only respond with an error code).

**Comment by sebastiankb** [comment]
Theoretically, it is possible to set up different form instances with different combinations of _input_ contentType and _response_ contentType.
I know, this may lead to complex TDs.
I do not have a hard opinion on that.

**Comment by mkovatsc** [comment]
I would change the Form class definition, so that the Type for `response` says "ExpectedResponse" or array of "ExpectedResponse".

Otherwise, it only supports a subset of the targeted use cases.

**Comment by mkovatsc** [comment]
A test is easily done through the takeSnapshot Action, where input can also specify the output format / media type.

**Comment by mkovatsc** [comment]
Giving multiple possible responses would on the other hand rely on content metadata. Good protocols have that, MQTT does not...

Let's defer.

**Comment by farshidtz** [comment]
Array of responses in [Form](https://www.w3.org/TR/wot-thing-description/#form) may also be used to describe various response codes.

Describing a PUT method (based on https://tools.ietf.org/html/rfc7231#section-4.3.4):
```json
{
    "href": "/resources/{id}",
    "htv:methodName": "PUT",
    "contentType": "application/json",
    "response": [
        {
            "description": "Created new resource",
            "htv:statusCodeValue": 201
        },
        {
            "description": "Updated existing resource",
            "htv:statusCodeValue": 204
        }
    ]
}
```

Response errors (relevant to https://github.com/w3c/wot-thing-description/issues/303):
```json
{
    "href": "/resources/{id}",
    "htv:methodName": "GET",
    "response": [
        {
            "description": "Success response",
            "contentType": "application/json",
            "htv:statusCodeValue": 200
        },
        {
            "description": "Resource not found",
            "htv:statusCodeValue": 404
        }
    ]
}
```

Headers on success response (based on https://tools.ietf.org/html/rfc7231#section-4.3.3):
```json
{
    "href": "/resources",
    "htv:methodName": "POST",
    "contentType": "application/json",
    "response": [
        {
            "description": "Success response",
            "htv:headers": [
                {
                    "description": "Resource identifier",
                    "htv:fieldName": "Location"
                }
            ],
            "htv:statusCodeValue": 201
        },
        {
            "description": "Invalid input",
            "htv:statusCodeValue": 400
        }
    ]
}
```

NOTE: the above examples may not be valid TD forms.

**Comment by egekorkan** [comment]
From @farshidtz comments above, this issue in the scripting api is also relevant: https://github.com/w3c/wot-scripting-api/issues/200

**Comment by mmccool** [comment]
Adding an array in responses would break backward compatibility, and also if multiple responses are possible the TD NEEDS a way to distinguish the various response (eg a header field).   So I'm thinking something like using the current "response" field as the "default" response, and a NEW field, which has an array of responses, each of which include a header to distinguish then.   This could be called something like "alternateResponses" although we could argue about better names (eg just "alternates") if you would like...

**Comment by takuki** [comment]
> Adding an array in responses would break backward compatibility, and also if multiple responses are possible the TD NEEDS a way to distinguish the various response (eg a header field). So I'm thinking something like using the current "response" field as the "default" response, and a NEW field, which has an array of responses, each of which include a header to distinguish then. This could be called something like "alternateResponses" although we could argue about better names (eg just "alternates") if you would like...

If the Thing with an alternateResponses field does not know the consumer can handle v1.1, the consumer would be surprised to receive a response that is different from what it expects.

I think although it does not break interoperability when parsing a TD, but it may break interoperability at run-time this way.

**Comment by sebastiankb** [comment]
From today's TD call:
- as @takuki mentioned supporting `response` as an array we will have backwards compatible issue
- we should clarify with the Discovery TF (@farshidtz @mmccool) how essential this feature is and may decide to do an exception

**Comment by egekorkan** [comment]
I wasn't there in the call but what's the relation to the Discovery TF?

**Comment by sebastiankb** [comment]
>I wasn't there in the call but what's the relation to the Discovery TF?

https://github.com/w3c/wot-discovery/issues/54

**Comment by sebastiankb** [comment]
From today's TD call:
- we introduce a new term `additionalResponses` as array in `forms`
- this keeps backwards compatibility to 1.1
- we have to evaluate the definition about different data schema that can be assigned to different responses
- first idea is to use `anyOf` at data schema level to provide different schema definitions
- within the response entries there can be a JSON pointer to a schema definition 
- there needs a default assumption for the pointer
- @mmccool will discuss some use cases during the discovery TF
- @mmccool will also provide a PR to integrate this new feature if there is consensus

**Comment by mjkoster** [comment]
Entry point for the discussion on "anyOf" in SDF: https://github.com/ietf-wg-asdf/SDF/pull/8

We should write up a FAQ entry for this

**Comment by sebastiankb** [comment]
issue is addressed by the latest draft
