### ISSUE TITLE
Links becoming Web Forms 

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#62]
See https://github.com/w3c/wot-binding-templates/issues/12 for context.

TDs need a way to express the relations of one Thing to other Things (e.g., a room Thing containing device Things, A pump Thing connected to a valve Thing). Unfortunately, the `link` keyword is already taken. However, with the issue above, it would make sense to rename the current `link` voacbulary to `from` and use `link` at the top level of a TD to express the Web links from this Thing to other Things.

**Comment by sebastiankb** [comment]
close the issue since link is renamed to form in new [TD version for Prague](https://rawgit.com/w3c/wot-thing-description/TD4Prague/index.html) (not merged with master yet)
