### ISSUE TITLE
change the order of the terms in the Form class table

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#621]
`op` is only defined as string, but must be string or array of string.

BTW: can you change the order of the terms in the table? Would be nice to align with https://w3c.github.io/wot-architecture/#sec-hypermedia-forms and have:

* op
* href
* contentType
* contentCoding
* subprotocol
* security
* scopes
* response

**Comment by sebastiankb** [comment]
bug is fixed. Order is still open @vcharpenay are you taken care of it?

**Comment by vcharpenay** [comment]
done (5ee8d4126fb2c7b0e582dcc0a4945bb6836be2f2).
