### ISSUE TITLE
`ThingDescription` term shall be defined in the @context and be the @type of TDs?

### ISSUE THREAD

**Issue by jmcanterafonseca** [w3c/wot-thing-description#627]
We need in the `@context` the term `ThingDescription` so that we can label Thing Descriptions JSON-LD documents with the proper `@type`

BTW, I'm wondering whether the type of Device the Thing Description is describing should be defined in the root "@type" as suggested by example 2 (https://w3c.github.io/wot-thing-description/#thing-description-full-serialization) or should it be conveyed using other semantic annotation coming from SAREF. All in all the ThingDescription is describing the service a Device is providing but not the Device itself ... 

That's why I'm making the following suggestion, using the `saref:isAbout` Object Property. 

```json
{
    "@context": [
        "https://www.w3.org/2019/td/v1",
        {
            "saref": "https://w3id.org/saref#"
        }
    ],
    "id": "urn:dev:ops:32473-WoTLamp-1234",
    "name": "MyLampThing",
    "@type":  "ThingDescription",
    "saref:isAbout": "saref:LightingDevice",
....
}
```

**Comment by mkovatsc** [comment]
No, Thing Descriptions are representations of Things, hence they have the `@type` `Thing`, which exists in the TD code vocabulary.

**Comment by jmcanterafonseca** [comment]
ok, but ... 

is example 2, https://w3c.github.io/wot-thing-description/#thing-description-full-serialization, then correct? are you assuming that anything in SAREF is a subclass of wot:Thing?

**Comment by mkovatsc** [comment]
Makes sense to me, as you need "saref:isAbout" to point from a ThingDescription to "saref:LightingDevice". Since TDs directly represent Things, there should be no conflicts for classes that define SAREF Devices. Anything in SAREF goes to far, I would say.

@vcharpenay made a proper analysis.

**Comment by mkovatsc** [comment]
@vcharpenay can you quickly comment on the compatibility of the Thing class with SAREF Device classes? If that is given, I propose to close this issue.

**Comment by vcharpenay** [comment]
Example 2 does not make any *general* assumption about SAREF but there is an overlap between `td:Thing` and `saref:Device`, indeed. It could event be formalized as follows: `(Device and hasInteractionAffordance some InteractionAffordance) subClassOf Thing`.

As for adding `td:ThingDescription`, it is analogous to having every JSON-LD document contain an RDF node with type `JsonLdDocument`. I don't see the benefit. Moreover, a TD is not about all possible `saref:LightingDevice` but the one that offers very specific affordances and that is identified on the Web as `urn:dev:ops:32473-WoTLamp-1234`. In SemWeb terms, it is a *semantic* resource that is described by some *information* resource (the TD document) whose IRI is not given in the example. The two are distinct.

**Comment by jmcanterafonseca** [comment]
@vcharpenay thanks for the explanation!, very useful
