### ISSUE TITLE
Inconsistency on accepted values for @context

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#628]
In the spec, there are multiple values for the `@context`. Below are the different ones:
* 5.3.1.1 Thing, below the table; Example 5: The mandatory context definition of the string "https://www.w3.org/2019/wot/td/v1" MUST be the first item in the @context array. ( I think that this is a bug, there shouldn't be a `wot`)
* Example 1 and 2 and pretty much everywhere: "@context": "https://www.w3.org/2019/td/v1" ( I think this is the correct one)
* Validation schema: 
```
                {
                    "type": "string",
                    "pattern": "^https?://(www\\.)?w3\\.org/2019/td/v1$"
                }
```

( This is a flexible version of the second one)
* In the comments of PR #603 @mkovatsc said that we have only the value with www which contradicts the previous point.

In the end, I think it should be clear if `@context` can be flexible/redirectable or not. Some questions I have:
* http or https
* www or not
* with year or not: *3.2 Alternative Namespaces* says that the namespace will redirect but is it OK to have a TD without the year that redirects to the latest version upon JSON-LD processing.

**Comment by mkovatsc** [comment]
> In the comments of PR #603 @mkovatsc said that we have only the value with www which contradicts the previous point.

It rather says the JSON Schema needs to be made more restrictive

* the URI is used as an identifier of the format version, hence no flexibility
* with www
* with year (Alternative Namespaces are for the Vocabularies, not the context file)
* http vs https is still open for the Namespace IRIs, as we saw both practices (SSN with http, verifiable credentials with https)
* for the context file, it should probably be `https` -- other comments?

**Comment by sebastiankb** [comment]
Regarding https vs http and www & without www I just tested the existing `w3.org/ns/td` with postman and all variations returned the same document:

- http://w3.org/ns/td
- https://w3.org/ns/td
- https://www.w3.org/ns/td
- http://www.w3.org/ns/td

**Comment by egekorkan** [comment]
> We need firstly the unique identifier aspect. 

I agree with this, whether they return the same document can depend on the configuration of the Web server/DNS

**Comment by sebastiankb** [comment]
I would simple go for https://www.w3.org/2019/td/v1 as announced in the TD spec and define this in the JSON Schema.

**Comment by sebastiankb** [comment]
I fixed the namespaces errors (https://www.w3.org/2019/wot/td/v1 --> https://www.w3.org/2019/td/v1) in the spec

**Comment by egekorkan** [comment]
In that case if there are not objections, I am constraining the schema to accept only ` https://www.w3.org/2019/td/v1 `

**Comment by egekorkan** [comment]
If the PR#632 is merged this issue can be closed given that @sebastiankb has also fixed the inconsistency with having `wot` in the uri or not
