### ISSUE TITLE
Alignment with Mozilla/Evrthng proposal

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#63]
At TPAC, the preference for SIMPLE solutions was expressed again. The Mozilla/Evrthng proposal (https://benfrancis.github.io/wot/proposals/json-td/) is a good example for that.

To go toward aligning this work, a step that should be taken by the W3C WoT Thing Description is to simplify the TD by relying more on defaults and omitting the extension points in serializations. For instance, the `writable` flag for Properties can default to `false` and node-wot already can successfully parse TDs that do not include it. Similarly, `mediaType` might be omitted when defaulting to `application/json`. We should create such minimal versions and compare those to the Mozilla/Evrthng proposal.

For the Mozilla/Evrthng proposal, I would like to see a bit more details about complex data types (`"type": "object"`), Action paramters, etc.  Once we get a complete example, I have the hope it will be quite similar to our minimal version.

**Comment by poussa** [comment]
+1

I think this is a step to right direction.

**Comment by mmccool** [comment]
I think it would be worthwhile to break this down into a number of smaller issues that we can discuss one by one that can bring us into closer alignment, without necessarily adopting everything in the Mozilla proposal.  I agree generally with the idea of providing default values for fields and then allowing fields to be omitted, but we may have to reorganize somethings to make this work better.

**Comment by mkovatsc** [comment]
A first step was done in Dec 2017 with this [proposal](https://rawgit.com/w3c/wot-thing-description/master/proposals/simplified-json-ld/index.html).

More detailed issues are now in:
https://github.com/w3c/wot-thing-description/issues/84
https://github.com/w3c/wot-thing-description/issues/85
https://github.com/w3c/wot-thing-description/issues/86
https://github.com/w3c/wot-thing-description/issues/87
https://github.com/w3c/wot-thing-description/issues/88
https://github.com/w3c/wot-thing-description/issues/90
