### ISSUE TITLE
Human-readable "name" has i18n problem - rely on "title"/"titles" in Thing instead?

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#630]
If the default language is changed, for example as part of HTTP negotiation returning text for title and description using an alternative language, then the interpretation (and potentially display, eg in a web dashboard) of "name" and "support" (in case the value of "support" is a person's name, for example) will get broken if "name" and "support" are written using a language with a text direction opposite to that of the (new) default language.

I think we need an alternative mechanism for specifying a language explicitly for "name" and "support" that overrides the default language, since the idea is that these strings are immutable and should always be displayed the same way, including language and text direction.

I  suggest adding an optional "supportLanguage" name/value to the Thing object.  This would would have a BCP47 language tag as a value (potentially with a script subtag, as needed to specify the direction unambiguously) to specify the language for "name" and "support".  This would override any default language specified by any other means for those two strings only, whether the default language was specified using `@language` or through protocol negotiation.

It would be optional, however, and if not present the values of "name" and "support" would be interpreted according to the default language.

In the interest of time, I will prepare a PR based on top of my text direction PR, then we can discuss.

**Comment by mmccool** [comment]
Another way to deal with this (which might be more JSON-LD-ish) would be to allow a nested context for "name" and "support".   However this is tricky since there is no convenient object scope to add it to.

Yet another way to do this would be allow the values of "name" and "support" to be either strings OR MultiLanguage objects with explicit language tags, eg.
```
"name": { "en": "My Thing" }
```
but this has the problem that there implies there could be more than one entry (technically, we would need something like SingleLanguage that is like MultiLanguage but with a cardinality of exactly 1).

I'll create a PR for now based on adding "supportLanguage" but we can discuss these other options here.

**Comment by mmccool** [comment]
PR available: https://github.com/mmccool/wot-thing-description/pull/8.
This is currently set up as a modification of PR https://github.com/w3c/wot-thing-description/pull/620.

**Comment by sebastiankb** [comment]
name should be kind of identifier and there should be no language variations. 
I understand the purpose to provide language information for the support term. We should rethink to type the support term as anyURL again and use scheme like [mailto](https://tools.ietf.org/html/rfc6068). What do you think?

**Comment by mkovatsc** [comment]
This feels like classic overengineering to me.

I would define the "name" field as a (non-unique) identifier in the default language.
Restricting supprot to anyURI is also good, as people can still be given as mailto URI.

**Comment by mmccool** [comment]
Yes, but the point is the default language can *change* due to content negotiation, which will screw up rendering.   Anyhow, I've just prepared a PR and we can decide to use it or not.   But it's a potential problem that could easily arise in multilanguage contexts.   And we can fix it.   Or not.

**Comment by mkovatsc** [comment]
Oh darn, got it! When dynamically generating a TD for a certain language, that language might be different from the name chosen...

**Comment by sebastiankb** [comment]
we should drop `name` and introduce `title` (mandatory) and `titles`

I know it is big change

**Comment by mkovatsc** [comment]
> we should drop name and introduce title (mandatory) and titles

Yes, a big chance at this point, but I also think we need to, as it is basically an i18n issue.

We stuck to `name` because we thought it is just a "simple string" that can be used as informal identifier. Yet we also have the strong expectation, that this name will be used in UIs. This has a clear i18n requirement. `title` and `titles` address this this requirement.

Introducing `names` does not make sense to me, as `name` loses its informal identifier aspect (there being only one string). Hence lets use `title`/`titles`.

Making `title` mandatory solves the issue that there must always be a string for the Thing to use in UIs.

Having `titles` enables dynamic TD generators to serialize a correct `title` string for the negotiated default language.

**Comment by mkovatsc** [comment]
@mmccool , can we agree on dropping the supportLanguage feature and rename this issue to reflect the issue with a non-internationalized name?

**Comment by mmccool** [comment]
Sure, can drop supportLanguage; using title/titles seems like a good solution to me, as well as making "support" an anyURI.   I can include both those changes in my PR, but I'll have to do it tomorrow (it's very late in the evening here and I'll screw it up if I do it now).

I will update the title of this issue.

**Comment by mmccool** [comment]
Title changed.   Sorry it's so long, I'm out of brain cells right now.

**Comment by mmccool** [comment]
Created this, too: https://github.com/w3c/wot-thing-description/issues/633

**Comment by mkovatsc** [comment]
Can we collect +1s for going for `title` and `titles` in Thing?

I am in favor (see https://github.com/w3c/wot-thing-description/issues/630#issuecomment-490073919)

**Comment by mmccool** [comment]
Re title/titles in Thing: +1, in favor.

**Comment by egekorkan** [comment]
title/titles in Thing: +1

**Comment by takuki** [comment]
+1 regarding renaming "name" to "title" plus "titles", and also +1 for changing type of "support" to anyURI.

**Comment by mkovatsc** [comment]
FYI: We are not renaming, we are kicking `name` with its identifier definition and allow `title` and `titles` as they exist already now also in Thing.

**Comment by takuki** [comment]
I just made changes so that "titles" is now optional while "title" stays mandatory.
Please take a look at [here](https://cdn.staticaly.com/gh/w3c/wot-thing-description/1a1bc264f3051186f544debf6ea6f6da58356d9e/index.html#thing).

**Comment by mkovatsc** [comment]
We had this one open as long as possible for the group to review and comment. Since no concerns were raised, I am closing this issue now.

Note that this is not an issue opened by the I18N WG.
