### ISSUE TITLE
Make value of "support" an anyURI

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#633]
This avoids some annoying i18n issues upon language renegotiation.   Specifically, if "support" can be in any language, but the default language is changed due to content negotiation, then the wrong text direction might end up getting used when it is displayed.

If we make this a URI then not only is it clearer what to do with it, the endpoint of the link can deal with content negotiation issues.   This makes a lot more sense than trying to pack all the information into the TD.   It also enhances privacy since rather than put a person's name and phone number (say) into a TD, the URI can direct to a web site that requires authentication information.

**Comment by mkovatsc** [comment]
FYI, people and phone numbers can still be indicated using `mailto:` and `tel:` URIs.

**Comment by mmccool** [comment]
Sure.   I'm just saying they don't HAVE to.   Anyhow, a URI is cleaner.
Let's resolve that I will add this to PR https://github.com/w3c/wot-thing-description/pull/620.   First thing tomorrow (well before the editor's call, though).

**Comment by mkovatsc** [comment]
I think @sebastiankb or @vcharpenay can take over the anyURI part.
Can you focus on finishing the PR?

**Comment by mmccool** [comment]
Actually, PR https://github.com/w3c/wot-thing-description/pull/620 is done and can be merged as far as I am concerned.   It does not have any mention of "supportLanguage" since I have not merged the sub-PR.
So... why don't you merge it, then take over making these changes?   I am happy to give you the pen at this point.

**Comment by mkovatsc** [comment]
Sorry, last question in #620 ! Please see there.

**Comment by mmccool** [comment]
OK, I think I answered the last pending question and resolved the last review comment (well, marked it resolved; it was actually about THIS issue)

**Comment by mkovatsc** [comment]
Looks good.
@egekorkan Maybe you want to update the JSON Schema for "support" in Thing

**Comment by egekorkan** [comment]
It is done at #632

**Comment by sebastiankb** [comment]
ok thanks.
