### ISSUE TITLE
(editorial) content type examples may be misleading

### ISSUE THREAD

**Issue by aphillips** [w3c/wot-thing-description#636]
5.2.3 Form
https://cdn.staticaly.com/gh/w3c/wot-thing-description/TD-TAG-review/index.html?env=dev#form

> Assign a content type based on a media type [IANA-MEDIA-TYPES] (e.g., 'application/json) and (optional) parameters (e.g., 'charset=utf-8').

The type `application/json` does not take a `charset` parameter. I realize that it is just an example and we do want to encourage UTF-8 for media types that require a charset, so perhaps no change should be made.

**Comment by mkovatsc** [comment]
Should be `text/plain`. Thanks!

**Comment by vcharpenay** [comment]
addressed by 3c3c7f745aef7731b8af6b201dc2375c4fcf3eac. Thanks.
