### ISSUE TITLE
Multilanguage section clarity [I18N]

### ISSUE THREAD

**Issue by aphillips** [w3c/wot-thing-description#637]
5.2.6 Multilanguage
https://cdn.staticaly.com/gh/w3c/wot-thing-description/TD-TAG-review/index.html?env=dev#multilanguage

> Container to provide human-readable text in different languages using language tags described in [BCP47]. Each used language tags code MUST be decleared as vocabulary term member of this container (e.g., en, de, ja, zh-Hans, zh-Hant). See § 6.2.10 titles and descriptions for example usages of this container in a Thing Description instance.

Two editorial notes:

* `declared` is misspelled

* The text _Each used language tags code MUST be decleared as vocabulary term member of this container (e.g., en, de, ja, zh-Hans, zh-Hant)_ is somewhat unclear. I would suggest:

> Each language tag used in a `Multilanguage` MUST be declared as a vocabulary term member of this this container.

By the way, thank you for showing an example language tag that is not just two-letters long.

**Comment by mkovatsc** [comment]
Thank you! We have already been working hard and have this assertion in the [Editors' Draft](https://w3c.github.io/wot-thing-description/#multilanguage):

> Each name of the MultiLanguage Map MUST be a language tag, potentially including a script subtag, as defined in [BCP47] (e.g., en, de, ja, zh-Hans, zh-Hant, az-Latn, az-Arab).

**Comment by mmccool** [comment]
Note I added the az-Latn and az-Arab tags since the version originally sent in for review.   I used these as examples of where a script subtag is needed to determine the base text direction.

**Comment by takuki** [comment]
Just a note. One difference between zh-Hans and zh-Hant in the examples is that the translation of the word "information" should be different. Not only the glyphs are different, actual words are different for the word "information" between mainland China (using zh-Hans) and Taiwan/HK (using zh-Hant).

**Comment by mkovatsc** [comment]
@takuki Could you please check the translations for `titles` in https://w3c.github.io/wot-thing-description/#example-7 and https://w3c.github.io/wot-thing-description/#example-8 ?

**Comment by takuki** [comment]
@mkovatsc , the translations in Asian languages looks good. Thank you.

**Comment by sebastiankb** [comment]
@aphillips I think, this is issue is addressed with an improved description in https://w3c.github.io/wot-thing-description/#multilanguage and https://w3c.github.io/wot-thing-description/#thing

Proposal to close this issue

**Comment by aphillips** [comment]
LGTM. I18N is satisfied. Thanks!

**Comment by sebastiankb** [comment]
thank you for your feedback. I will close this issue.
