### ISSUE TITLE
Clarify about language negotiation [I18N]

### ISSUE THREAD

**Issue by aphillips** [w3c/wot-thing-description#638]
5.2.6 Multilanguage
https://cdn.staticaly.com/gh/w3c/wot-thing-description/TD-TAG-review/index.html?env=dev#multilanguage

> Note that in protocols such as HTTP that have an ability to negotiate content based on languages, those terms (e.g. description and title) intended for carrying texts in a default language SHOULD be used instead of MultiLanguage container when the texts are served as a result such negotiation. 

It's not clear to me what this text intends should happen. While HTTP provides the `Accept-Language` header to assist with language negotiation and indeed some systems do use this header to perform language negotiation, there is no specific standard here. I think the intention is that _if_ a service or thing has successfully negotiated language with the requesting party, _then_ the `description` or `title` (or other natural language text bearing fields) should use that language/locale for the response. It's not clear to me that returning a `Multilanguage` would be an error, which is what this normative language suggests.

Note this paragraph is marked "at risk".

**Comment by mkovatsc** [comment]
Thank you! We have already been working hard and have this text in the [Editors' Draft](https://w3c.github.io/wot-thing-description/#multilanguage):

> Another possibility is to set the default language with a language negotiation mechanism, such as the Accept-Language header field of HTTP. In protocols such as HTTP that have an ability to negotiate content based on languages, terms (e.g. description and title) intended for carrying texts in the default language SHOULD be used instead of MultiLanguage container when the texts are served as a result of such negotiation. In contexts where the default language has been negotiated, TD documents SHOULD NOT include any MultiLanguage objects. In contexts where the default language has been negotiated, a @language definition, if present, MUST be consistent with the negotiated default language. Note however that constrained devices may choose to not support dynamically-generated TDs and do not need to support language negotiation.

We will mark it "at risk".

**Comment by mkovatsc** [comment]
> It's not clear to me that returning a Multilanguage would be an error, which is what this normative language suggests.

It is not considered an error, hence "SHOULD". The reasoning behind this is that when a concrete language is requested by a client, then the response should not include all supported languages, but only the result of the content negotiation.

**Comment by aphillips** [comment]
> In contexts where the default language has been negotiated, TD documents SHOULD NOT include any MultiLanguage objects. In contexts where the default language has been negotiated, a @language definition, if present, MUST be consistent with the negotiated default language. Note however that constrained devices may choose to not support dynamically-generated TDs and do not need to support language negotiation.

A few comments on this:

- "constrained devices may" -> "constrained devices MAY" ?
- "TD documents SHOULD NOT include any MultiLanguage objects" is too restrictive and doesn't perhaps describe what the desired result is. In particular, the fact that a negotiation has taken place does not mean that an exact match has been found or that specific resources were subject to that negotiation. I'd suggest something like:

> In contexts where the default language has been negotiated, TD documents SHOULD return the appropriate matching language term (such as `title` or `description`) in preference to a MultiLanguage object.

- I'm not sure about this text:

> In contexts where the default language has been negotiated, a @language definition, if present, MUST be consistent with the negotiated default language. 

The `@language` should be consistent with the language of the item being returned. Perhaps what you would want is more like:

> In contexts where the default language has been negotiated, an `@language` definition, if present, indicates the result of the negotiation and the corresponding language of the returned content.

- The phrase  "[i]n contexts that have been negotiated" is a bit repetitive

**Comment by mkovatsc** [comment]
Thanks, some more tweaks:

Preamble:

> Another possibility is to set the default language with a language negotiation mechanism, such as the `Accept-Language` header field of HTTP.

Then first ensure that the outcome of the negotiation is marked in the document in case it is transferred further:

> In cases where the default language has been negotiated, an `@language` member MUST be present to indicate the result of the negotiation and the corresponding default language of the returned content.

Ten your nicer statement about the MultiLanguage objects:

> When the default language has been negotiated successfully, TD documents SHOULD include the appropriate matching values for the members `title` and `description` in preference to `MultiLanguage` objects in `titles` and `descriptions` members.

And all marked as "at risk".

**Comment by aphillips** [comment]
@mkovatsc Just curious: why is this at risk? Are you concerned that you won't have implementations?

**Comment by mkovatsc** [comment]
Oh, good that you ask because after so many issues up to now, I read "Note this paragraph *a*s marked "at risk", assuming you want it to be marked at risk.

It currently is marked in yellow, because we do not have positive test results yet -- the markup is automatic based on the test cases, which we already started to implement.

**Comment by aphillips** [comment]
@mkovatsc Argh. Sorry. That was a note to the I18N group when reviewing the comment. I should have removed it.

**Comment by mkovatsc** [comment]
No worries! :)

**Comment by mkovatsc** [comment]
See #646

**Comment by mmccool** [comment]
Regarding the updates, these all look good; sorry I was not engaged for them (I need to sleep sometime).   

We need to ensure the language in the spec allows protocols OTHER than HTTP to have language negotiation.   I do think the current language allows for this (via the phrase "such as").  We have to make sure we don't lose that in a last-minute edit...

Regarding the at-risk markup, I expect to update that markup for the CR transition to reflect what we don't THINK we will have implementations for rather than what we don't have a TEST for right now (which is not actually a CR requirement...).   Right now it's a lot more conservative than it should be.

**Comment by mkovatsc** [comment]
Latest text in [6.3.2 Human-Readable Metadata](https://w3c.github.io/wot-thing-description/#titles-descriptions-serialization-json):

> Another possibility to set the default language is through a language negotiation mechanism, such as the Accept-Language header field of HTTP. In cases where the default language has been negotiated, an `@language` member MUST be present to indicate the result of the negotiation and the corresponding default language of the returned content. When the default language has been negotiated successfully, TD documents SHOULD include the appropriate matching values for the members title and description in preference to MultiLanguage objects in titles and descriptions members. Note however that Things MAY choose to not support such dynamically-generated TDs nor to support language negotiation (e.g., because of resource constraints).

**Comment by sebastiankb** [comment]
@aphillips please check if the new text is also ok for you. 

@mmccool http is just mention as example. There can be other protocols and the `@language` terms is protocol independent anyway.

I propose we close this issue.

**Comment by aphillips** [comment]
LGTM. I18N is satisfied. Thanks!

**Comment by sebastiankb** [comment]
thank you for your feedback. I will close this issue.
