### ISSUE TITLE
DataSchema format field and patterns [I18N]

### ISSUE THREAD

**Issue by aphillips** [w3c/wot-thing-description#639]
5.3.1 DataSchema
https://cdn.staticaly.com/gh/w3c/wot-thing-description/TD-TAG-review/index.html?env=dev#dataschema

> Defines  format pattern validation on certain kinds of string values. It is open  to use pattern values that may originate from JSON schema presets  (e.g., date/time, email, URL) or other (custom-based) definitions.

The field `format` has the above description. This spec doesn't particularly define what kind of pattern can go into it, but it should be noted that some of these (including `date/time`) have I18N implications. I'm raising this issue here, even though I don't propose making any spec changes at this time.

**Comment by mkovatsc** [comment]
The `format` actually takes terms from a defined set of identifier strings. I would say, the field does not have the I18N implications, but implementations using this information (e.g., schema validators) might.

http://json-schema.org/latest/json-schema-validation.html#rfc.section.7.3 defines the set of well-known identifier strings.

We should clarify this, but also mark the `format` name-value pari as "at risk".

**Comment by takuki** [comment]
Clarified format field definition.
Please see the updated draft [here](https://cdn.staticaly.com/gh/w3c/wot-thing-description/f87127b9a195758013e67c649769e33530c26ff0/index.html).

**Comment by mmccool** [comment]
I'm working on the at-risk markup right now.   Should I still mark "format" as at-risk?

**Comment by takuki** [comment]
@mmccool , yes, I think so because there will be a possibility that we may need to consider withdrawing the feature depending on the eventual status of the feature.

**Comment by sebastiankb** [comment]
@aphillips I think, this is issue is addressed. As @mkovatsc mentioned above the JSON Schema based `format` term comes with a well-known list of string identifier. @takuki made this point clearer in the specification. 

Proposal to close this issue

**Comment by aphillips** [comment]
The original comment was in case non-locale-neutral formats were encouraged/allowed/etc. With the clarifications added, I'm satisfied. Thanks!

**Comment by sebastiankb** [comment]
thank you for your feedback. Close this issue.
