### ISSUE TITLE
Thing Description Serialization and BOM [I18N]

### ISSUE THREAD

**Issue by aphillips** [w3c/wot-thing-description#640]
6. Thing Description Serialization
https://cdn.staticaly.com/gh/w3c/wot-thing-description/TD-TAG-review/index.html?env=dev#sec-td-serialization

> Implementations that parse TDs MAY ignore the presence of a byte order mark rather than treating it as an error.

This section requires (`MUST`) that the serialized form use UTF-8 (yay!) and requires (`MUST`) that the file not start with a Byte Order Mark (U+FEFF BOM) (which is reasonable). It then goes on to permit ignoring BOM. Should this be increased to SHOULD?

**Comment by mkovatsc** [comment]
The statements are actually taken from [RFC 8259](https://www.rfc-editor.org/rfc/rfc8259.txt) and presented here for convenience. The RFC says

> In the interests of interoperability, implementations that parse JSON texts MAY ignore the presence of a byte order mark rather than treating it as an error.

with a MAY.

(At this very moment, tools.ietf.org is down, hence the link to the plaintext version...)

**Comment by mkovatsc** [comment]
I think we can leave this; no PR needed.

**Comment by mmccool** [comment]
I agree, the i18n comment was just a suggestion, but being consistent with RFC8259 makes more sense.

**Comment by sebastiankb** [comment]
@aphillips Please let us know if this [explanation](https://github.com/w3c/wot-thing-description/issues/640#issuecomment-490162832) is ok for you. 

Proposal to close this issue.

**Comment by sebastiankb** [comment]
since @aphillips already provide us a detailed positive feedback about our I18N changes I think this issue should be also ok. 

@aphillips please reopen, if it is not the case.
