### ISSUE TITLE
Acknowledge all contributors

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#649]
We should acknowledge all contributors to the thing-description spec.
See: https://github.com/w3c/wot-architecture/pull/330

**Comment by mmccool** [comment]
Probably not something we have to do before the CR transition, though.

**Comment by takuki** [comment]
Some of the people who I think made contribution after the last publication includes:

@egekorkan (Ege), @msporny (Manu Sporny), @aphillips (Addison Phillips) , @ektrah (Klaus Hartke)

Any thoughts?

**Comment by sebastiankb** [comment]
I would also mention @jmcanterafonseca

**Comment by zolkis** [comment]
In specifications where there are a lot of contributors, it's very rare that all contributors are explicitly acknowledged, but a general acknowledgement is made to all contributors and a link to github contributors is given.

There are even more concise ways, for instance the Web Bluetooth group has done it: there is no acknowledgements section, they don't even name editors, but says to check contributors in the github repository. Which is always up to date and don't have to update names (leading to possible misunderstandings). Also, it gives incentive to people to actually make commits :).
See:
https://github.com/WebBluetoothCG/web-bluetooth/graphs/contributors 
https://webbluetoothcg.github.io/web-bluetooth/

**Comment by mlagally** [comment]
There are different styles ...

In the architecture spec I took the approach of adding everybody who did commits to the3 spec on github. This honours all contributions.

**Comment by jmcanterafonseca** [comment]
issue with mentioning only GH Contributors, is that there can be useful contributions in terms of issue raising, alternative proposals etc. that could be acknowledged

 In addition, as pointed out by @ashimura the IPR Policy essentially does not recommend to land PullRs from people, like me, who did not previously sign the IPR commitment (even if we state that we do not pretend to claim any IPR as a non for profit org). 

...

**Comment by takuki** [comment]
Made changes to Acknowledgments section.
See PR #661 and #662.

**Comment by jmcanterafonseca** [comment]
@takuki thanks! and count on me for further reviews of the WoT TD Spec and related!

**Comment by takuki** [comment]
I suggest to also name @chachamimm as a contributor as he contributed by helping us to investigate one of the i18n issues. See issue [#580](https://github.com/w3c/wot-thing-description/issues/580).

**Comment by takuki** [comment]
I added a special thanks sentence for Joerg Heuer.

I also added Soumya Kanti Datta and Benjamin Klotz because I think their efforts on WoT and involvement with the group was not small.
