### ISSUE TITLE
Do we need an "observeData" field?

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#65]
Currently we have "outputData" and "inputData", corresponding to payloads for read and write operations or inputs and outputs from Actions, or output data from Events.

However, if we add an "observe" capability to Properties, then there is no guarantee that a given protocol will use the same payload format as a read.   As an example, the Mozilla proposal wraps the payload for an observe message in an additional JSON object that includes a timestamp, so the structure (not just the fields) are different from that returned from a GET.   This example shows that we can't necessarily just ignore fields to deal with differences, as the structure itself might be different.

So, we need a separate way to give payloads for observe events.   One suggestion that generalizes inputData and outputData to multiple roles is given in issue https://github.com/w3c/wot-thing-description/issues/66.  Of course we could also just add an "observeData" tag.

**Comment by mkovatsc** [comment]
If the "observe data" is different from the Property data, I don't see any point in forcing this into the same Property. It is simply an Event that sends data that is different from the Property.
