### ISSUE TITLE
Alternative Namespaces (www.w3.org/ns/...)

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#652]
Ralph's feedback for the year-based namespace, where we have to add "wot", does not match with the Alternative Namespaces, which we were encouraged to continue using.

This feels odd to me, in particular ns/json-schema considering the arguments for the year-based namespaces.

**Comment by sebastiankb** [comment]
I also +1 this since 4.2 is not very useful and may confuse developer.....

**Comment by ashimura** [comment]
I talked with Ralph again about this, and confirmed that if the definition has changed enough that the old name(s) should not really redirect to the new name(s) that is fine.

So we can remove section 4.2.

**Comment by mkovatsc** [comment]
We applied this clean-up before the CR transition request. Closing.
