### ISSUE TITLE
Namespace clarifications by Ralph

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#654]
Ralph provided clarifications on the namespaces we target:
https://lists.w3.org/Archives/Member/member-wot-wg/2019May/0018.html

In the call on 8 May 2019 we decided to go for option B with subdirectories:

1. Core https://www.w3.org/2019/wot/td#
2. Data Schema https://www.w3.org/2019/wot/json-schema#
3. Security https://www.w3.org/2019/wot/security#
4. Web Linking https://www.w3.org/2019/wot/web-linking#

As web-linking also includes forms, we should use this change to align the namespace to:

4. Hypermedia https://www.w3.org/2019/wot/hypermedia#

Note that this also includes changes to the headings in the TD spec.

**Comment by vcharpenay** [comment]
PR #656 addressed the issue and was merged.
