### ISSUE TITLE
Generalize inputData, outputData to "payload"

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#66]
We may want to reconsider the syntax for inputData/outputData, as I personally get constantly confused as to whether "input" and "output" are with respect to the Thing or the user of the Thing.   There is a related issue that often inputData and outputData are copies of each other, leading to verbosity (and potential for error).   This arises because we are re-using "input" and "output" for Property get/set (where input and output are just copies of the state) and Actions (where input and output are basically parameters and return values from procedure calls).  Finally, we may need additional fields for observable payloads.

So maybe a generic "payload" array with a list of objects, each object listed by what kinds of payloads it is for, would be a better structure.   Something like:

    "payload" : [
         { "role": ["readProperty","writeProperty"],
           "@type": ...
           "type": ...
           "fields": ...
         },
         { "role": ["observe"],
            ...
         }
    ]

As a related issue, I think "readProperty" should just be "read", "writeProperty" should just be "write", "invokeAction" should just be "invoke", etc. to be consistent with "observe" (also in the Scripting API...). 
We may also want to use "input" and "output" for Actions for these payload roles to differentiate these roles (invoke does not make sense, since it does not differentiate the input and output roles; but I think it still makes sense to have "read" and "write" for Properties for semantic clarity).   Note also that if we adopt the suggestion in issue https://github.com/w3c/wot-thing-description/issues/64, the payloads for "read", "write", and "observe" roles would be given appropriate defaults for a given type definition on Properties.

**Comment by vcharpenay** [comment]
Regarding verbosity, there is one thing where JSON-LD could help:

```
{
  "name": "someTemperatureSensor",
  "inputData": {
    "@id": "_:TemperatureValue",
    "@type": "Number" (or "type": "number"),
    "minimum": 0 
  },
  "outputData": "_:TemperatureValue",
  ...
}
```

Here, I gave a local ID to the definition (prefixed with `_:`), in order to refer to it later in the document.

You could even externalize this definition in some model registry and simply reference it as follows:
```
{
  "name": "someTemperatureSensor",
  "inputData": "http://schema.intel.com/TemperatureValue",
  "outputData": "http://schema.intel.com/TemperatureValue",
  ...
}
```
But regardless of whether we want to leverage Linked Data here, your proposal looks very much like the Open API Specification/Swagger format (used by OCF). In the Swagger terminology, this payload object you are describing is simply referred to as a 'schema'. I find this term more accurate.

**Comment by benfrancis** [comment]
The JSON-TD proposal uses `data`. I agree that `inputData` and `outputData` is confusing as it may depend on which perspective you are thinking about it from.

**Comment by benfrancis** [comment]
The JSON-TD proposal also defines a Value object which can be re-used as a Property definition, one of multiple arguments to an action and one of multiple data items in an event payload:

```
"properties": {
  "brightness" : {
    "name": "Brightness",
    "type": "number",
    "description": "The level of light from 0-100",
    "min" : 0,
    "max" : 100,
    "href": "/things/lamp/properties/brightness"
  }
},
"actions": {
  "fade" : {
    "name": "Fade",
    "description": "Fade from one brightness to another",
    "data": {
      "from": {
        "type": "number",
        "min": 0,
        "max": 100
      },
      "to": {
        "type: number",
        "min": 0,
        "max": 100
      },
      "duration": {
        "type": "number",
        "unit": "milliseconds",
      }
    },
    "href": "/things/lamp/actions/fade"
  },
"events": {
  "overheated": {
    "name": "Overheated",
    "description": "The device exceeded its maximum safe operating temperature",
    "data": {
      "temperature": {
        "type": "number",
        "unit": "celcius"
      }
    }
  }
}
}

```

**Comment by draggett** [comment]
> > The JSON-TD example could be simplified further by stripping out the "data" object so that "from", "to" etc. are peers of "name" and "description". In my implementation, I chose to use "request" and "response" rather than "from" and "to" as I believe that request and response are unambiguous and as such easier to understand.

> I don't understand what you mean by request and response here. from, to and duration are intended as arguments to submit with the fade action request. For example to tell a light to "Fade from 100% to 50% over 200 milliseconds".

Ah, I misunderstood, in my proposal, I use "request" in place of "data" for the data to send with the action request. I also allow for data to be passed in the action "response".

**Comment by mkovatsc** [comment]
I See a lot oft confusion in this issue...

### Generalization to payload

The current status in the WG is:
- input and output are with respect to the Thing, as a TD describes the Thing. `inputData` is input for the Thing, `outputData` is output by the Thing.
- Properties only have one data definition. We picked `outputData` is the default assumption is read-only Properties.
- Observing a Property must return the same data type is reading, is it just an optimization of polling. Why would I use the same Property for different data in the first place?

While generalization to payload does not make sense as proposed, a renaming of inputData and outputData might help clarity. `request` and `response` probably would confuse MQTT folks. Different terms for the different Interactions might help, as the single schema element in Properties serves a different purpose than each of the two in Actions and even the one in Events, which defines not state but transitions or alerts.

### JSON-TD Proposal

In the JSON-TD example I cannot understand why complex data for an Action would be modeled as three Property-like parameters while it was said to be JSON Schema. Complex properties would need to be modeled differently, causing an inconsistent model. In the Web and when sing href one also usually thinks message-oriented, meaning there is a payload and not distinctive parameters like in programming.

JSON-TD should be fixed to use proper JSON Schema. Having a `data` field within the properties would make the model more consisted. A renaming of this field to `schema` might be clearer.

**Comment by benfrancis** [comment]
@mkovatsc wrote:
> In the JSON-TD example I cannot understand why complex data for an Action would be modeled as three Property-like parameters while it was said to be JSON Schema. Complex properties would need to be modeled differently, causing an inconsistent model. In the Web and when sing href one also usually thinks message-oriented, meaning there is a payload and not distinctive parameters like in programming.
> 
> JSON-TD should be fixed to use proper JSON Schema. Having a data field within the properties would make the model more consisted. A renaming of this field to schema might be clearer.

To explain this rationale with an analogy to JavaScript:
- Properties are like properties of an object which each have their own type
- Members of action "data" are like arguments to methods, of which there can be several, each with its own type
- Event "data" is like the detail property of an Event object, i.e. the event payload

This should all hopefully feel quite natural to web developers (although admittedly JavaScript itself isn't strongly typed).

Action data could be called "arguments" and Event data could be called "detail" or "payload" but that might be a bit too coupled with JavaScript and procedural programming concepts. We went with "data" for consistency (like the "payload" proposal above).

One thing which might be missing from JSON-TD which is included in JSONLD-TD is a return type for an action. In Mozilla's current [REST API](https://iot.mozilla.org/wot/#web-thing-rest-api) and [WebSocket API](https://iot.mozilla.org/wot/#web-thing-websocket-api) implementation an action is something you request and can either get the status of (with an `HTTP GET` request) or be notified of a status change with an `actionStatus` message respectively.

Perhaps there are use cases for having a return type for an action?

These data specifications don't conform to JSON Schema syntax, they just re-use the data types. But I thought that was the case with JSONLD-TD too, as there was a naming conflict with "properties"?

@mkovatsc wrote:
> Properties only have one data definition. We picked outputData is the default assumption is read-only Properties.

This is a bit confusing in the use case of setting a property. For example, in our implementation a [multiLevelSwitch](https://iot.mozilla.org/wot/#multilevelswitch-type) has a "level" property which you can set with an `HTTP PUT` or a `setProperty` WebSocket message. It would seem strange to "set" the "outputData" of a switch to modify its state.

Perhaps your implementation implements setting properties differently?

**Comment by mkovatsc** [comment]
> Members of action "data" are like arguments to methods, of which there can be several, each with its own type

How do you ensure the order of the Action üarguments? Answer is you don't, you always pass a single surrounding object. So why not simply describe that? It also fits the JavaScript trend pass an object with named members instead of individual arguments. Having a mixture of your data object and JSON Schema object definitions is also confusing.

> outputData -- This is a bit confusing in the use case of setting a property

Yes, it was somewhat a laziness decision that happened back then and needed fixing. We already discussed this today in the binding call and could agree to simply call it `schema` for Properties. To produce sensible triples and be able to reuse schema definitions, we need this `schema` predicate and cannot put `type` etc. directly under the Property. Let us share this once its stable.

**Comment by mkovatsc** [comment]
`data`, `arguments`, and `return` definitely improves along the input/output confusion dimension. It is still a bit off in the data vs data schema department...

`dataSchema`, `argumentSchema`, and `returnSchema` are a bit more correct, but clumsy.

Let's keep looking.

**Comment by zolkis** [comment]
Looks like there are similar ideas in the [Bindings issue 13](https://github.com/w3c/wot-binding-templates/issues/13).

**Comment by mkovatsc** [comment]
It is in fact related, as we want to apply the same pattern at both levels.

**Comment by mkovatsc** [comment]
Issue is addressed by https://github.com/w3c/wot-binding-templates/issues/13

The concrete naming for Action request and response payload schemas remains. Go to https://github.com/w3c/wot-binding-templates/issues/13 for discussion on the naming.
