### ISSUE TITLE
JSON-LD context file 

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#665]
The JSON-LD context file, which is referenced in the normative section 4 cannot be found.

**Comment by mkovatsc** [comment]
Wenn know that see issue for Kaz.
Ist okay

**Comment by mmccool** [comment]
I assume by "cannot be found" is "URL cannot be dereferenced".   We discussed this, and Kaz will deal with it (eg override any errors it raises) during the publication process.   We probably should try to set it up as soon as we can, but I don't think it gates our CR transition.

**Comment by mkovatsc** [comment]
See #432
