### ISSUE TITLE
Semantically equivalence and semantic validity of TD‘s is undefined

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#666]
Used  in the terminology section

**Comment by vcharpenay** [comment]
Thanks for the comment. Here is the proposed change:

- remove the notion of equivalence but keep a note on canonical forms, referring exclusively to default values
- replace semantic validity by the notion of satisfying instantiation constraints on objects

If I have no objection before the CR transition meeting, @mlagally, I'll implement that in the spec.

**Comment by vcharpenay** [comment]
See 5fca6f84017db3cc5bccbcbada68211bb98247e9.
