### ISSUE TITLE
Section 5: The instance relationship for simple types is unclear

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#667]
> According to the definition above, an Object is an instance of every Simple Type, regardless of its structure. Instead, another definition for instantiation is introduced for Simple Types:

> An Object is an instance of a Simple Type if it is a Term with a given lexical form (e.g. true, false for the boolean type, 1, 2, 3, ... for the unsignedInt type, etc)

Which simple types are permitted? Where are they defined?
Can a value be an instance of two simple types, e.g., 1 could be an instance of both unignedInt and Int?

**Comment by mkovatsc** [comment]
Can copy list from 6.1.

**Comment by vcharpenay** [comment]
> Which simple types are permitted? Where are they defined?

I'll add a list. 

> Can a value be an instance of two simple types, e.g., 1 could be an instance of both unignedInt and Int?

The answer should follow from the definition: yes.

**Comment by mkovatsc** [comment]
Add the list for CR

**Comment by mkovatsc** [comment]
Include "float", "signedInt" from XSD to be future proof...
Maybe we can say something like "for a full list see ..."

**Comment by mkovatsc** [comment]
Otherwise, we have to extend Section 6.1 as well..
