### ISSUE TITLE
Improve definitions of type and assignment functions

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#668]
> The Signature of a Class allows to construct two functions that further define Classes: an Assignment Function and a Type Function. The Assignment Function of a Class takes a Vocabulary Term as input and returns either true or false as output. The Type Function of a Class also takes a Vocabulary Term as input and returns another Class as output. These functions are partial: their domain is limited to the Signature of the Class being 

Language should be simplified for clarity: since these functions take only a Signature of the Class as a valid argument, replace ‚Vocabulary Term‘ with ‚Signature of the Class‘
Drop sentence on ‚partial‘

**Comment by mkovatsc** [comment]
A Term and a set of Terms (Signature) are significantly different. They only take a Term.
Hence correct.

Partial ... can be dropped. Agree

**Comment by vcharpenay** [comment]
Note that I added 'partial' after your own review, @mkovatsc, since it is be otherwise ambiguous: another way to read the definition is that these functions are defined on all terms, in which case it is unclear what it should return for other terms.

**Comment by mkovatsc** [comment]
Maybe this is clearer:
* The Assignment Function of a Class takes a Vocabulary Term **of the Signature of its Class** as input and returns either true or false as output.
* The Type Function of a Class also takes a Vocabulary Term **of the Signature of its Class** as input and returns another Class as output.

**Comment by vcharpenay** [comment]
To me, it is a paraphrase of the following sentence: "These functions are partial: their domain is limited to the Signature of the Class being defined." but... if time allows it, I'll change that.

**Comment by mkovatsc** [comment]
Yes, it is only for "Language should be simplified for clarity"

**Comment by vcharpenay** [comment]
see #680.
