### ISSUE TITLE
Section 5: assignment function is underspecified

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#669]
> The Assignment Function of a Class takes a Vocabulary Term as input and returns either true or false as output.

What is the condition for returning true or false?
I believe we want to define duck typing, however this needs a clear definition, like:

... returns true, if it contains all mandatory vocabulary terms

**Comment by mkovatsc** [comment]
Appears okay when seeing this as a tuple definition. We define those functions basically in the tables by giving assignment and type.

**Comment by mkovatsc** [comment]
@vcharpenay please look into this and only then decide if PR needed.

**Comment by vcharpenay** [comment]
indeed, as @mkovatsc mentioned, the assignment function *is used* to define mandatory terms (as opposed to being defined from them). The following sentence in the def expresses this: "In other words, the Assignment Function indicates whether a Vocabulary Term in the Signature of the Class is mandatory.".

To me, there is no change needed.

**Comment by mlagally** [comment]
As proposed by @mkovatsc, we could add text that gives a reference to the Assignment column 
in the tables and explains, that the assignment function returns 'true', if the value of the corresponding table column is "mandatory", 'false' otherwise.

**Comment by vcharpenay** [comment]
see #680.
