### ISSUE TITLE
@context for TD trailing '/' ?

### ISSUE THREAD

**Issue by jmcanterafonseca** [w3c/wot-thing-description#673]
```
"@context": [
        "https://www.w3.org/2019/wot/td/v1"
]
````

shouldn't it be 

```"https://www.w3.org/2019/wot/td/v1/"```

or are both allowed? or only v1 allowed? in that case `v1` would be just an alias of `td-context.jsonld` ?

IMHO, it is more correct with the trailing '/' as in that case `td-context.jsonld` would be just the index file of that folder ...

**Comment by vcharpenay** [comment]
That would not be exactly compliant with W3C style guidelines (see [Cool URIs don't change](https://www.w3.org/Provider/Style/URI)). A URI should not expose the internal server mechanisms to serve data, especially not its directory structure.

If the w3.org server redirects with 303 to `https://www.w3.org/2019/wot/td/v1/`, it is fine but there is no guarantee that it will not change its behavior in the future.
