### ISSUE TITLE
Need a $id for the JSON Schema

### ISSUE THREAD

**Issue by jmcanterafonseca** [w3c/wot-thing-description#674]
I think it is needed a `$id` for the TD JSON Schema. I'm wondering where at W3C the schema is going to be hosted and that could be equal to the `$id` maybe it could be 

"$id": "https://www.w3.org/2019/wot/td/v1" and serve the schema under content negotiation (`application/schema+json`), not sure if that could be a good idea ... or just 

"$id": "https://www.w3.org/2019/wot/td/v1/schema.json"

**Comment by vcharpenay** [comment]
A good point, to include to the discussion on #432.

**Comment by sebastiankb** [comment]
this is not part of the subset that we want to support at the moment. Can be consider in the future

**Comment by mkovatsc** [comment]
Our alignment with JSON-LD favors the Linked Data inclusion mechanism. The subset still ensures compatibility with JSON Schema.

A future version might look further into a combined solution (we had discussions and unsatisfactory proposals for this already and decided to defer).

**Comment by fennibay** [comment]
Hello, maybe a silly question, is there an official URL for the JSON schema that I can reference in my thing descriptions? Simply to see if my thing description is schema-conform.

My current solution is to copy the text from the Thing Description specification into a local file and reference it. Doesn't make much sense to me 😃 .

**Comment by vcharpenay** [comment]
You can use the following URI: https://w3c.github.io/wot-thing-description/validation/td-json-schema-validation.json. It's not canonical, though.

**Comment by sebastiankb** [comment]
also see https://www.w3.org/TR/wot-thing-description/#json-schema-for-validation and http://plugfest.thingweb.io/playground/

**Comment by fennibay** [comment]
Thank you very much!

**Comment by sebastiankb** [comment]
@egekorkan what do you think?

**Comment by egekorkan** [comment]
Call of 15.12.2021: we will use the github url as $id for editor drafts and provide static $id for publication. (this will be done in TM Schema as well)

**Comment by egekorkan** [comment]
@egekorkan will also add an editor's note so that the change of $id to a static one is not forgotten before publication
