### ISSUE TITLE
Figure 1: Ensure Subclass relation between PropertyAffordance and DataSchema is visible

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#678]
Figure 1 has many arrows pointing to DataSchema. The only Subclass relation arrow is from PropertyAffordance and is easily missed because the white arrow head is hidden under the black ones.

Victor, when manually finalizing the generated figures, please take care of this.

**Comment by mmccool** [comment]
Do we need this by CR transition?   It seems like an editorial fix (graphical fix) to me.   Trying to get this done now, and... let's use the "by CR transition" label only for things that ABSOLUTELY need it.

**Comment by mkovatsc** [comment]
okay, with the new i18n stuff, let's relax it...

**Comment by vcharpenay** [comment]
see #687.
