### ISSUE TITLE
Editorial and other minor comments

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#679]
Please find below some editorial comments according to the section.

# 5.3.1.4 ActionAffordance

"dimm a lamp" --> "dim a lamp"

# 5.3.1.5 EventAffordance

"Provides a version identicator" --> "Provides a version indicator"

# 5.3.2.1 DataSchema

"Section 7.3 Defined Formats in particluar" --> "Section 7.3 Defined Formats in particular"

# 5.3.3 Security Vocabulary Definitions

"eligable" --> "eligible"

# 5.3.4.2 Form

"metdata" --> "metdata"
"reponse" --> "response"
"servients ." --> "servients."

# 6.3.2 Human-Readable Metadata

"The the language" --> "The language"

# 6.3.6 actions

"They rely on the the" --> "They rely on the"

# 7. TD Context Extensions

"addind" --> "adding"

# 7.2 Adding Protocol Bindings

"accessable" --> "accessible"

# 9.1 Context Dereferencing Privacy Risk

Not sure about "Deferencing", "deferences" etc.. --> "Dereferencing" ??

"derefenced" --> "dereferenced" ?

**Comment by sebastiankb** [comment]
thanks @danielpeintner

**Comment by sebastiankb** [comment]
Editor's note have to be removed in Chapter 5
