### ISSUE TITLE
Examples in TD Deliverable do not use right context url

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#68]
Examples (e.g., Example 1) point to a wrong context uri (http://w3c.github.io/wot/w3c-wot-td-context.jsonld). The right uri should be https://www.w3.org/ns/td/w3c-wot-td-context.jsonld

**Comment by mkovatsc** [comment]
@vcharpenay told me that there is still something broken with the w3.org ns server (content negotiation). To not break reasoning, we shall wait.

**Comment by sebastiankb** [comment]
I would propose that the github.io draft version should always point to the http://w3c.github.io/wot/w3c-wot-td-context.jsonld file. The official draft release for W3C should have https://www.w3.org/ns/td/w3c-wot-td-context.jsonld file link.

**Comment by sebastiankb** [comment]
the lastest TD deliverable version on github contains stringent in each TD sample the context of  https://w3c.github.io/wot/w3c-wot-td-context.jsonld
