### ISSUE TITLE
Examples 27 and 28 of the document missing context

### ISSUE THREAD

**Issue by onovo1** [w3c/wot-thing-description#69]
Examples 27 and 28 use the vocabulary 'unit' and 'celsius' but such vocabulary is not defined in the context. The w3c-wot-common.context does not define that vocabulary.

**Comment by sebastiankb** [comment]
Thanks for the hint.
@vcharpenay I think, it make sense to introduce iot.schema.org here for unit and celsius. What do you think?

**Comment by onovo1** [comment]
Is it iot.schema.org defining "unit" and "celsius"? I couldn't find those definitions in iot.schema.org.

**Comment by sebastiankb** [comment]
Should be the plan: [link](https://github.com/iot-schema-collab/iotschema/blob/master/unit.jsonld)

**Comment by onovo1** [comment]
All right. Then, I think it is a good idea.

**Comment by sebastiankb** [comment]
for now, we removed the unit field in the samples. In future TD updates we may introduce it again when the context file is updated and include all needed definitions for the samples.
