### ISSUE TITLE
Leftover change - "name" to "title"

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#696]
[Example 2](https://w3c.github.io/wot-thing-description/#thing-description-full-serialization) still contains `name` instead of `title` on thing level....

**Comment by danielpeintner** [comment]
One more minor comment. This "name to title" change is not listed under [Recent Specification Changes](https://w3c.github.io/wot-thing-description/#changes). I think it would be good to add it given this is a rather important point. Thanks!

**Comment by mmccool** [comment]
I think these can both be considered editorial changes.

**Comment by sebastiankb** [comment]
I will take of it

**Comment by danielpeintner** [comment]
@takuki @sebastiankb the *rendered* version of the changes section still not contains any mentioning about

"Renamed name to title" for Thing

I think this change should be listed and hence I re-opened the issue. Feel free to close it again if you feel differently.

**Comment by takuki** [comment]
I created another issue for this.
Please see issue #769
