### ISSUE TITLE
Unit definition in TD

### ISSUE THREAD

**Issue by vcharpenay** [w3c/wot-thing-description#70]
In [example 27](https://w3c.github.io/wot-thing-description/#temperature-sensor), `unit` is used in the TD but not included in any context. In [example 11](https://w3c.github.io/wot-thing-description/#type-system), a unit is declared with `actuator:unit`. This should probably be unified throughout the document.

Moreover, in the first case, the unit is defined at the interaction level, while it is defined inside input/output data definitions in the second case. The spec should provide a guideline on this.

*(Comment from @mkovatsc)* *(relates to #69)*

**Comment by vcharpenay** [comment]
I don't think that a definition at the interaction level is necessary. For instance, the following definitions are equivalent: 

```json
{
  "interaction": [{
    "@type": "Property",
    "unit": "celsius",
    "outputData": {
      "type": "integer"
    }
  }]
}
````

```json
{
  "interaction": [{
    "@type": "Property",
    "outputData": {
      "type": "integer",
      "unit": "celsius"
    }
  }]
}
````

`"unit": "celsius"` was just shifted from the interaction to the output data definition.

**Comment by sebastiankb** [comment]
ok, I will move the unit and I will point out this is defined in the TD common vocabulary.

**Comment by sebastiankb** [comment]
short question. This example also shows the usage of      
    `"property": "temp"`
Which does not exist in the mentioned context. If ok, I would remove it.

**Comment by vcharpenay** [comment]
Same for `"reference": "threshold"`. Yet, these two properties probably make sense, it is important to express interdependence between WoT resources in a single TD. Could we leave an Editor note saying that this question is still pending (like the one already there for `associations`)?

**Comment by sebastiankb** [comment]
for the sake of convenience I would remove it for now. There is no definition within the context as well as a clear description of it. Instead, a new issue would make sense for future discussion on it. 

BTW: 'unit' is not defined in the common context. That mean we should introduce a concrete context such as iot.schema.org for it. What do you think?

**Comment by mkovatsc** [comment]
Should maybe go into the semantic annotations within the data schema part.

**Comment by sebastiankb** [comment]
merge this issue with https://github.com/w3c/wot-thing-description/issues/69

TD examples have to be updated in section 6.7
