### ISSUE TITLE
[Testing] td-default-idempotent is used for writeOnly

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#701]
The assertion with id `td-default-idempotent` that is `td-default-idempotent-1` in the implementation report should not be called this but `td-default-writeOnly` since it's description is 
> The value associated with member "DataSchema" if not given MUST be assumed to have the default value " writeOnly ".

Applying this will remove the duplicate id as well

**Comment by mmccool** [comment]
Fixed in PR https://github.com/w3c/wot-thing-description/pull/707

**Comment by mmccool** [comment]
Looks like this was fixed already in the CR version, too, by @ashimura

**Comment by mkovatsc** [comment]
Implementation report looks correct.
Closing.
