### ISSUE TITLE
[Testing] Wrong default value in assertion descriptions of td-default-X

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#702]
The issue applies to the following assertions so I think it is a code bug that introduces this bug:

td-default-alg
td-default-alg-pop
td-default-contentType
td-default-flow
td-default-format
td-default-format-pop
td-default-in-apikey
td-default-in-basic
td-default-in-bearer
td-default-in-digest
td-default-in-pop
td-default-op-actions
td-default-op-events
td-default-op-properties
td-default-qop
td-default-readOnly
td-default-safe

In all of them the description is like:
> The value associated with member " BasicSecurityScheme " if not given MUST be assumed to have the default value " in ".

It should be:
> The value associated with member " BasicSecurityScheme " if not given MUST be assumed to have the default value "header".

**Comment by mmccool** [comment]
OK, let me take a look; looks like a bug in assertions.js.

**Comment by mmccool** [comment]
I put a fix into PR https://github.com/w3c/wot-thing-description/pull/707.   I was pulling the columns out of the table in the wrong order...

**Comment by mkovatsc** [comment]
Was merged and implementation report looks fine now.
Closing.
