### ISSUE TITLE
[Testing] td-data-schema-objects_items is still present

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#703]
The report produces the following text

> The value of the member items MUST be serialized as a JSON object with a DataSchema object. 

This is no more valid and the following line covers it:
> td-data-schema-objects-arrays | The value assigned to items in an instance of ArraySchema MUST be serialized as a JSON object or a JSON array containing JSON objects.

**Comment by mmccool** [comment]
Update to extra-assertions in PR resolves this issue.
