### ISSUE TITLE
No link to A.2 in toc

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#706]
When I click in the table of content "A.2 MyLightSensor Example with MQTT Protocol Binding" it jumps me to A.1

**Comment by k-toumura** [comment]
due to duplicated id `myLampThing-example-serialization`.
https://github.com/w3c/wot-thing-description/blob/fd89b0c40330bb3266edf08854d22a943c36ae6e/index.template.html#L3703
https://github.com/w3c/wot-thing-description/blob/fd89b0c40330bb3266edf08854d22a943c36ae6e/index.template.html#L3764
