### ISSUE TITLE
Ontology HTML files are not yet WG Notes

### ISSUE THREAD

**Issue by takuki** [w3c/wot-thing-description#708]
They are Working Group Editor's Draft for now.

http://w3c.github.io/wot-thing-description/ontology/td.html
http://w3c.github.io/wot-thing-description/ontology/jsonschema.html
http://w3c.github.io/wot-thing-description/ontology/wotsec.html
http://w3c.github.io/wot-thing-description/ontology/hyperm.html

Please see @ashimura 's [comment](https://github.com/w3c/wot-thing-description/issues/432#issuecomment-493326214) in Issue #432.

**Comment by mkovatsc** [comment]
See https://github.com/w3c/wot-thing-description/issues/770

**Comment by takuki** [comment]
I saw #770 . 
So it means they can stay as Working Drafts.
Thank you for clarification.

**Comment by mkovatsc** [comment]
> So it means they can stay as Working Drafts

EDITORS' Drafts -- Working Drafts are for REC track documents...

**Comment by ashimura** [comment]
On Fri, Jul 5, 2019 at 8:57 PM Matthias Kovatsch <notifications@github.com>
wrote:

> So it means they can stay as Working Drafts
>
> EDITORS' Drafts -- Working Drafts are for REC track documents...
>

Right. Editor's Drafts for a while and Group Notes at some point :)

Kazuyuki
