### ISSUE TITLE
Describe automated testing in TD Implementation Report

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#710]
To satisfy the "Test Cases" deliverable in the charter, add a description of the ThingWeb Playground and AssertionTester to the TD Implementation Report.   Break the results table into "Automatically Tested" and "Manually Asserted" results.

**Comment by mmccool** [comment]
Since we resolved in the last meeting not to have Test Cases as a deliverable this is not really an issue anymore, although I plan in PR https://github.com/w3c/wot-thing-description/pull/707 to mention our automatic testing tools.

**Comment by mkovatsc** [comment]
During the F2F we concluded to skip this.
