### ISSUE TITLE
Lingual correction in 5.3.1.3 PropertyAffordance

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#711]
The assertion currently says

> When a Form instance is within a PropertyAffordance Class, ...

It should say the following, similar to Action- and EventAffordance:

> When a Form instance is within an instance of the PropertyAffordance Class, ...

Or even better, to simplify all three to:

> When a `Form` instance is within a(n) `_____Affordance` instance, ...

**Comment by sebastiankb** [comment]
ok, I will take care of it

**Comment by sebastiankb** [comment]
done
