### ISSUE TITLE
Multiple methodName's ?

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#712]
[8.3.1 HTTP Protocol Binding](https://w3c.github.io/wot-thing-description/#http-binding-assertions) states that a TD can include a term indicating the method, i.e., `htv:methodName`.

For HTTP e.g.;
* `op: "readproperty"` maps to `GET`
* `op: "writeproperty"` maps to `PUT`
* ...

However this is somewhat limited given that `op` may be of type array.
Hence it is not possible to provide a *correct* htv:methodName for `op : ["readproperty", "writeproperty"]`.

**Comment by mkovatsc** [comment]
It is important to understand how the declaration of forms works. It works just like Web links, where a link element having multiple `rel` attributes actually represents multiple links, one for each `rel`attribute!

This means that this optimization with multiple `op` attributes only works for default values of other attributes. If the attributes do not apply to all forms combined through an `op` array, the forms have to be split out into their own element.

```
"forms": [{
    "op": [
        "readproperty",
        "writeproperty"
    ],
    "href": "https://mylamp.example.com/status",
    "contentType": "application/json"
}]
```
expands to
```
"forms": [{
    "op": "readproperty",
    "href": "https://mylamp.example.com/status",
    "contentType": "application/json"
}, {
    "op": "writeproperty",
    "href": "https://mylamp.example.com/status",
    "contentType": "application/json"
}]
```
[Example 32](https://w3c.github.io/wot-thing-description/#example-32) is correct. However, I now noticed that [Example 33](https://w3c.github.io/wot-thing-description/#example-33-mylampthing-with-coap-protocol-binding) is faulty, as it uses `cov:methodName` without `op`. Technically, that form means that both `readproperty` and `writeproperty` (from the default value for Properties) would use `GET`, which obviously makes no sense.

**Comment by mkovatsc** [comment]
Oh, `"op": "subscribeevent"` is missing in Example 32 when displaying default values.

I am also wondering why the examples in Appendix A do not have this nice default values feature... shouldn't we add this (again)?

**Comment by takuki** [comment]
In addition, is it ok **not** to specify default method name for subscribeevent in section [8.3.1](https://w3c.github.io/wot-thing-description/#http-binding-assertions) ?

**Comment by mkovatsc** [comment]
> In addition, is it ok not to specify default method name for subscribeevent in section 8.3.1 ?

We probably need more explanation around the values for `subprotocol`. In the case of 8.3.1, I see the method as part of the `longpoll` definition -- like `observe` for CoAP means a GET request with Observe option.

**Comment by mkovatsc** [comment]
This is actually a good comment that only came up during CR period.

**Comment by mkovatsc** [comment]
In the call on 19 June 2019 we had enough feedback that this is clear enough to enough implementers, so no need to rush this. We can provide further tutorials etc. later.

**Comment by danielpeintner** [comment]
As discussed in the call on 24th of January I looked into the issue again.

The "issue" still exists but I think we can work around it like @mkovatsc  sketched by splitting forms (see https://github.com/w3c/wot-thing-description/issues/712#issuecomment-496149253 above).

However, the original cause of the issue is that `op` can be of type string ***or array*** while a possible `htv:methodName` can be of type string only.

Let's assume we start with a simple form like the following

```
"forms": [{
     "op": ["readproperty", "writeproperty"],
    "href": "https://mylamp.example.com/status"
}]
```

and would like to add HTTP vocabulary like `htv:methodName` fails (Note: this popped up in the node-wot implementation). 

```
"forms": [{
     "op": ["readproperty", "writeproperty"],
     "href": "https://mylamp.example.com/status",
     "htv:methodName": ["GET", "PUT"] // invalid, type string only
}]
```

Instead we have to split it to

```
"forms": [{
     "op": "readproperty",
     "href": "https://mylamp.example.com/status",
     "htv:methodName": "GET"
 },
{
     "op": "writeproperty",
      "href": "https://mylamp.example.com/status",
     "htv:methodName": "PUT"
} ]
```

which makes it more verbose.

**Comment by zolkis** [comment]
> which makes it more verbose

At least I find the split description more clear.

**Comment by sebastiankb** [comment]
From TD's call:
- the TD spec should be clear that this presentation 

```
"forms": [{
     "op": ["readproperty", "writeproperty"],
    "href": "https://mylamp.example.com/status"
}]
```

will be transformed to 

```
"forms": [{
     "op": "readproperty",
     "href": "https://mylamp.example.com/status",
     "htv:methodName": "GET"
 },
{
     "op": "writeproperty",
      "href": "https://mylamp.example.com/status",
     "htv:methodName": "PUT"
} ]
```
- there should be also procedure description how the transformation to the default representation works in respect to specific protocol bindings (e.g., [http table](https://www.w3.org/TR/wot-thing-description/#http-binding-assertions) and the [generic default table](https://www.w3.org/TR/wot-thing-description/#sec-default-values)
- @sebastiankb will provide a PR for it

**Comment by sebastiankb** [comment]
latest draft addresses this issue.
