### ISSUE TITLE
Example 33 is missing op for status Property

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#714]
The default value of `op` for Properties is `["readproperty", "writeproperty"]`. In the example, however, a request method is assigned, which now sets it to GET for both operations. This does not make sense...

Basically, only `"op": "readproperty"` is missing.

However, I would improve the example by showing behavior of OCF devices, which use POST for `writeproperty`. Hence, I would split the form into two, one for `readproperty` with GET and one for `writeproperty` with POST.

**Comment by sebastiankb** [comment]
ok, make sense. 
Since I dont't know how the latest OCF spec looks like, I would simple fix the bug by adding  "op": "readproperty"

**Comment by sebastiankb** [comment]
done, PR available
