### ISSUE TITLE
No "with default values" checkbox for Appendix A examples

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#715]
I think the "with default values" checkbox is a valuable feature. We should add it to the examples in Appendix A.

**Comment by mkovatsc** [comment]
All full examples should have that.

**Comment by mkovatsc** [comment]
Given the limited time, it seems to be a risk to introduce errors.

**Comment by sebastiankb** [comment]
yes, nice to have feature that we should consider for the next version from the beginning.
