### ISSUE TITLE
[Testing] Additional implementation needed for Action features

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#717]
The following Action features need additional implementations:
- [x] ~~1 more example of use of titles and descriptions (td-action-names_titles and td-action-names_descriptions)~~
- [x] ~~1 more example of use of output object (td-action-names_output, td-action-objects_output)~~
- [x] ~~1 more example of use of uriVariables (td-action-names_uriVariables)~~ TESTING PROBLEM

The Form also needs 1 additional implementation of the following, which can be considered an Action feature since it is only used there (when the return contentType is not the same as the request type):
- [x] 1 additional implementation of a response object in a Form (td-forms-response)

**Comment by mmccool** [comment]
- updated intel-camera to have action titles and descriptions resolving td-action-names_titles and td-action-names_descriptions
- added intel-inference.jsonld which uses an "output" data schema on an action, resolving td-action-names_output and td-action-objects_output.
Description has been updated.

**Comment by mmccool** [comment]
Intel has also created the other uriVariables

**Comment by mkovatsc** [comment]
Implementation report shows enough positive results.
Closing.
