### ISSUE TITLE
[Testing] Additional Implementations needed for DataSchema features

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#718]
In order to complete the PR testing requirements, additional examples are needed for DataSchema features:
- [x] 1 additional examples for the use of oneOf in an array (td-data-schema-arrays_oneOf, td-data-schema_oneOf)
- [x] ~~1 additional example for the use of descriptions and titles (td-data-schema_descriptions, td_data-schema_titles)~~
- [x] 1 additional example for the use of format (td-data-schema_format)
- [x] ~~1 additional example for the use of minItems  in an array (td-data-schema_minItems)~~
- [x] 1 additional examples for the use of maxItems in an array (td-data-schema-maxItems)
- [x] ~~1 additional example for the use of unit (td-data-schema_unit)~~ - but testing problem
- [x] 1 additional examples for the use of a null type (td-vocab-type--DataSchema_null)

**Comment by mmccool** [comment]
- Added some titles and descriptions to some data schemas in Intel TDs, resolving the issue with td_data_schema_descriptions and td_data_schema_titles

The description has been updated to strike these out.

**Comment by mmccool** [comment]
I also added an additional example of minItems in an array

**Comment by egekorkan** [comment]
It seems that there is a problem with `td-data-schema-maxItems` since the output of [this](https://github.com/w3c/wot/blob/master/testing/tests/2019-05/outputs/Siemens/siemens-node-wot/dataSchemaTest-siemens.csv) shows that it is implemented.

**Comment by egekorkan** [comment]
Same for `_oneOf`

**Comment by mmccool** [comment]
Intel will generate an example for each of _oneOf and _maxItems

**Comment by mmccool** [comment]
Siemens will take care of format

**Comment by mmccool** [comment]
maxItems apparently has one implementation which is not showing up (from Siemens) but a second one is needed.   I already said above that I would add an implementation (and fix the report generator).

**Comment by mmccool** [comment]
Apparently minItems has two implementations but only one is showing up.  Fix report generator.

**Comment by mmccool** [comment]
Unit also has (at least) two implementations, one from Siemens, and one Panasonic.  Fix report generator.

**Comment by sebastiankb** [comment]
> 
> 
> Siemens will take care of format

done https://github.com/w3c/wot/commit/ee9c507e88e548bdc52c75d421ec7ab74ce249bf

**Comment by mmccool** [comment]
Intel took care of maxItems, oneOf, and null.   These are all satisfied now and I am closing the issue.
