### ISSUE TITLE
[Testing] Additional implementations needed for HTTP method defaults

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#719]
Additional implementations are needed for HTTP method defaults.   Or rather, additional implementations need to record these using manual assertions, as default values cannot be tested since they do not appear in the TD, but are statements about the behavior of a Consumer.

- [x] additional assertion for td-default-http-method_get (for op = readproperty)
- [x] additional assertion for td-default-http-method_put (for op = writeproperty)
- [x] additional assertion for td-default-http-method_post (for op = invokeaction)

There is a dependent assertion td-default-http-method that is the min-max of the above, but it should not be asserted directly.

**Comment by mkovatsc** [comment]
node-wot can handle any method as HTTP or CoAP client.

For the server part, a corresponding TD backed by a simple PHP script or whatever would hold.

**Comment by mmccool** [comment]
The existing assertions are from Hitachi, but node-wot also implements these and should assert them.  Matthias @mkovatsc has confirmed that node-wot implements these defaults and we have updated https://github.com/w3c/wot/blob/master/testing/tests/2019-05/inputs/Siemens/siemens-node-wot.csv.
See https://github.com/eclipse/thingweb.node-wot/blob/master/packages/binding-http/src/http-client.ts

**Comment by mmccool** [comment]
We did a code check and node-wot implements defaults for apikey, bearer, and basic, but does not explicitly mention digest.   We have updated the manual assertions accordingly, but digest still needs to be checked.  @danielpeintner and @mkovatsc can you please sort that out?

**Comment by mkovatsc** [comment]
We now have 3..4 positive results for each.
Closing.
