### ISSUE TITLE
[Testing] Additional implementations are needed for Event features

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#720]
Additional implementations are needed for the following Event features:
- [ ] 1 additional implementation of titles and descriptions (td-event-names_titles, td-event-names_descriptions)
- [ ] 1 additional implementation of uriVariables (td-event-names_uriVariables)

**Comment by mkovatsc** [comment]
I still doubt we need the titles/descriptions mechanism in all possible contexts. It is overall the same mechanism and a single entry in the report should suffice.

uriVariables works slightly different in Actions (only input) than Events (subscription and cancellation). I think we need a TD that declares different URI variables for subscription and cancellation.

**Comment by mmccool** [comment]
Siemens will add implementation of titles and descriptions in events.

**Comment by sebastiankb** [comment]
> 
> 
> Siemens will add implementation of titles and descriptions in events.

done https://github.com/w3c/wot/commit/3d490bb5381541f99a1313446bfc61d63faae1b4

**Comment by mkovatsc** [comment]
Here the test case was actually wrong: all fields are defined for `InteractionAffordance`, hence, they can be tested on any instance of that class (i.e., any Property, Action, or Event).

The report actually follows the fixed test case. Closing.
