### ISSUE TITLE
[Testing] Additional assertions needed for JSON open ecosystem requirements

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#721]
Some assertions are needed to confirm that implementations conform with the "open ecosystem" requirements for JSON:

- [x] 2 additional assertions for td-json-open

**Comment by egekorkan** [comment]
This is already tested but the online results show null. Are you sure that you have taken the latest version of manual assertions?

**Comment by mmccool** [comment]
There are some sub-assertions for td-json-open having to do with byte order.  However, acceptance is a "MAY".   We only need one implementation to do a MAY.   It turns out node-wot uses node.js JSON.parse that throws an error if it sees this... but there is an option to let it accept these.  Node-wot will be updated to use this option (@sebastiankb and @danielpeintner is assigned)

**Comment by takuki** [comment]
> TD Processors MAY ignore the presence of a byte order mark rather than treating it as an error.

I do not think this assertion belongs to TD specification. TD is in JSON format which is defined by RFC 8259. This assertion belongs to RFC 8259.

We are not testing RFC 8259. Therefore, I suggest to demote this assertion to a statement without an asserting qualification.

**Comment by danielpeintner** [comment]
I agree with Taki that this does not really belong to the TD. 

Anyhow, I added a quick check to node-wot that removes a potential Byte Order Mark (BOM), see https://github.com/eclipse/thingweb.node-wot/commit/c2278c7fabd80dd0eb3c54d072020814781513e6

**Comment by mkovatsc** [comment]
I agree that this is redundant, as we clearly build on top of RFC 8259. So even if we remove this, it still applies...

**Comment by mkovatsc** [comment]
Anyhow, we cannot just remove assertions. And we have enough implementation results now.
Closing.
