### ISSUE TITLE
[Testing] Additional implementations are needed for Property features

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#723]
Additional implementations are needed for the following property features:
- [x] ~~2 additional implementations of td-property-names_const~~
- [x] ~~1 additional implementation of td-property-names_titles and td-property-name_descriptions~~
- [x] ~~1 additional implementation of td-property-names_format~~
- [x] ~~1 additional implementation of td-property-names_items~~
- [x] ~~2 additional implementations of td-property-names_minItems and td-property-names_maxItems~~
- [x] ~~2 additional implemenations of td-property-names_oneOf~~ (but: see comment below!)
- [x] ~~1 additional implementation of td-property-names_unit~~
- [x] ~~1 additional implementation of td-property-names_uriVariables~~

**Comment by mmccool** [comment]
I added property titles and descriptions to an Intel implementation and resolved the problem with td-property-names_titles and td-property-name_descriptions.   Issue description has been updated.

**Comment by egekorkan** [comment]
oneOf is actually implemented in [this](https://github.com/w3c/wot/blob/master/testing/tests/2019-05/outputs/Siemens/siemens-node-wot/dataSchemaTest-siemens.csv) but does not appear in the report.

**Comment by egekorkan** [comment]
maxItems is actually implemented in a data schema in [here](https://github.com/w3c/wot/blob/master/testing/tests/2019-05/inputs/Siemens/siemens-node-wot/dataSchemaTest-siemens.json) but it is not in the property level. 
@sebastiankb or @danielpeintner can you provide a TD that has maxItems in the property level?

**Comment by mmccool** [comment]
resolved by suppressing assertions in property that are inherited from DataSchema; what we really care about is whether these are taken care of in some DataSchema.
