### ISSUE TITLE
[Testing] Additional implementations are needed for Link features

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#724]
Additional implementations are needed for the following Link features:
- [x] 2 additional implementations of the anchor feature (see td-vocab-anchor--Link)

**Comment by mmccool** [comment]
@mkovatsc and @mmccool will create implementations.   Basically this is used to declare a relationship between two other entities given by URLs.

**Comment by mkovatsc** [comment]
I can provide a TD + implementation for a Thing (Room) that has two sub-Things and the knowledge that the (LightBulb) is related to the (LightSwitch), which is expressed through a link with anchor (LightBulb) and target (LightSwitch).

**Comment by mkovatsc** [comment]
@mmccool can make a link statement with Web resources, e.g., a relation between a documentation (https://...) and a support contact (mailto:...)

**Comment by mmccool** [comment]
So, there is one implementation and since this is an optional feature that is sufficient.   We can consider closing this, although I could probably add some examples still if it made sense.

**Comment by mmccool** [comment]
Since we have enough implementations of this to satisfy PR requirements I am going to close.
