### ISSUE TITLE
[Testing] Test results for op in Form seem to be incorrect

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#726]
Test results for op in Form are coming back as "not implemented" from AssertionTester although they exist.  The test should be for at least one valid value; it is not necessary to check for all possible valid values.

**Comment by egekorkan** [comment]
This is due to child assertions

**Comment by egekorkan** [comment]
It can be closed now?

**Comment by mmccool** [comment]
The results are now correct; closing this.
