### ISSUE TITLE
[Testing] Test results for type in DataSchema seem to be incorrect

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#728]
The results from AssertionTester currently show no passes but clearly this feature is being used.   It is possible that not all possible values for this parameter are being used, but it should be acceptable to accept use of type with a single valid value in any given TD.  Note also that support for the various possible types is tested separately.

**Comment by egekorkan** [comment]
this is happening due to child assertions

**Comment by mmccool** [comment]
fixed, I think.
