### ISSUE TITLE
[At-Risk] Implementations of proxy feature in SecurityScheme needed

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#729]
The "proxy" feature in SecurityScheme is at risk.
- 2 additional implementations are needed, in any SecurityScheme

**Comment by mmccool** [comment]
Apparently node-wot implements this, so we need a producer (not implemented via node-wot) that goes through a proxy and is accessed by node-wot.
@danielpeintner and @mmccool and @sebastiankb to collaborate on this.  @mmccool can create a target implementation and a proxy, node-wot can talk to it.

**Comment by mkovatsc** [comment]
Done wit my Meta-Interaction impl and tested with (updated) node-wot.
