### ISSUE TITLE
[At-Risk] Implementations of CertSecurityScheme needed

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#732]
The CertSecurityScheme is currently at risk
- 2 implementations are needed with all sub-features

**Comment by mkovatsc** [comment]
I am happy to defer this to the next version, as there is not enough information provided for this scheme. It is for client certificates, which are rarely used for HTTP.

Let's do this properly when tackling CoAP(S), where it is mainly needed.
