### ISSUE TITLE
[At-Risk] Implementations of PSKSecurityScheme needed

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#733]
The PSKSecurityScheme is currently at risk.
- [x] 1 additional implementation is needed

**Comment by mmccool** [comment]
There is currently one implementation, so what we have to decide is whether since this is an optional feature (sort of, since you don't HAVE to use the PSK scheme, or any other scheme for that matter) one implementation is sufficient.

**Comment by mkovatsc** [comment]
We have two implementations, one by SmartThings (IKEA Tradfri wrapper), one by myself (Californium-based). Actually, it should be three, as I implemented this in node-wot, but there is no manual validation ID for this.

However, detailed fields for the metadata are also missing, e.g., named curve or ciphersuite. Thus, I am happy to defer this and provide it, for instance together with the CoAP binding vocabulary. Let's fix this together with CoAPS experts.
