### ISSUE TITLE
[At-Risk] Implementations of APIKeySecurityScheme needed

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#736]
The APIKeySecurityScheme is currently at risk
- 2 additional implementations are needed

**Comment by yamagile** [comment]
@mmccool , I created the [PR](https://github.com/w3c/wot/pull/819) on this issue. It makes some assertions passed like below:

---

pass: 0->2

* td-vocab-in--APIKeySecurityScheme
* td-vocab-name--APIKeySecurityScheme
* td-vocab-scheme--SecurityScheme_apikey

**Comment by mkovatsc** [comment]
Thanks @yamagile for providing APIKeySecurityScheme implementations!
Closing.
