### ISSUE TITLE
[Testing] Additional Manual Validation Needed for Text Direction Assertions

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#738]
Text-direction assertions are constraints on the rendering of strings found in TDs and so must be validated in Consumers with multilanguage text display capabilities.

Additional manual validation is needed for the following assertions, which have to do with selection of the base text direction:
- [x] td-context-default-language-direction-heuristic	
- [x] td-context-default-language-direction-independence
- [x] td-context-default-language-direction-inference	
- [x] td-context-default-language-direction-script
- [x] td-context-ns-multilanguage-text-direction-infer

The "direction-script" assertion requires some peculiar test cases as there are only a few languages that can be written in two different scripts with different base directions.  One is Azeri, which can be written in Latin script (az-Latn) or Arabic script (az-Arab).   So we also need a TD with Azeri descriptions to test against as well as two Consumers that can render Azeri... or at least can output a base text direction inference.

**Comment by mmccool** [comment]
So it's going to be harder to come up with test cases for direction-script than I thought.   My original idea was to generate some simple test cases (say, for a Light) using online translators but apparently az-Arab is only used in Iran, and all the online dictionaries, wikipedia, and google translate seem to only support az-Latn.  If anyone knows of a translator that can output az-Arab that would be great (even from az-Latn, which I can get; az-Arab is also not really a Latin script, BTW, it is just based on it but has a bunch of special characters, like the schwa).   I haven't seen any other mention of a language written today using both an RTL and LTR script.   There are some other languages like Javanese that historically used Arabic script but most have converted to Latin script.

**Comment by mmccool** [comment]
So... I found the following OSS tool to convert Azeri scripts: http://azconvert.sourceforge.net.  It only runs on Windows though, and I'm not entirely confident about installing this on my work Windows machine, for security reasons.   I do have a sandboxed/sacrificial Windows machine I could use for this purpose, though; once I generate a few text examples I will share them here.

**Comment by mmccool** [comment]
See new intel-camera TD.   Test results updated, which addressed some of the multilanguage testing gaps and provides a test case for the consumers needed for the above assertions.

**Comment by k-toumura** [comment]
@mmccool @mkovatsc This is screenshot of bidirectional support in Node Generator.
<img width="968" alt="Screen Shot 2019-06-07 at 1 11 15" src="https://user-images.githubusercontent.com/30313213/59072001-345bae00-88c1-11e9-9cd3-69a56734f1af.png">
To support it, Node Generator adds `dir="auto"`(not `rtl`) attribute for each element.
Is this your expected result?

**Comment by mmccool** [comment]
The td-context-default-language-direction-script can be tested automatically since it is a property that the TD must satisfy.   For now, I can manually assert it (and Intel has two separate implementations).
The above Node-RED implementation satisfies the td-context-default-language-direction-heuristic.   @k-toumura can update the Node-RED implementation to also have an inference from the language and explicitly set rtl or ltr instead of auto.   Intel can update the proxy to render an HTML landing page for all supported TD endpoints and the renderings of the titles can use HTML tags generated in such a way as to satisfy the above two assertions as well.

**Comment by mmccool** [comment]
See https://www.w3.org/International/questions/qa-html-dir; IMO doing the inference of the direction satisfies our objectives here, although ideally we also convince the browser to render the strings correctly.

**Comment by takuki** [comment]
This [page](http://guide.icherisheher.az/az) (supposed to be created by UNESCO) appears to provide translations between latin and arabic scripts. 

For example. "görməli yerlər" (latin) and "معالم" (arabic) are both milestones in English, and so forth.

**Comment by k-toumura** [comment]
"görməli yerlər" is Azerbaijani in Latin(az-latn) script, but "معالم" is Arabic(ar), not Azerbaijani in Arabic script(az-arab).
Anyway, if an implementation can infer and add 'dir=rtl' when '@language' is 'az-arab', and 'dir=ltr' when 'az-latn', it satisfies the td-context-default-language-direction-script, I think.

**Comment by takuki** [comment]
As for td-context-default-language-direction-independence assertion, I do not think the assertion belongs to TD specification.

TD is in JSON-LD format, and this constraint should be universal to all JSON-LD implementations whether it is TD or not.

Therefore, I suggest to demote this assertion to a plain statement without asserting qualification.

**Comment by takuki** [comment]
As for td-context-default-language-direction-script assertion, the current test report shows we need one more implementation.

I think the other implementation can be a simple flowchart and manual generation of a HTML snippet according to the flowchart. This makes the number of implementations 2.

**Comment by mkovatsc** [comment]
To my understanding, string-meta provides i18n guidance for basically all W3C specs. It is an i18n feature of TD to enforce independent treatment by implementations that display the human-readable text. We also have sufficient implementation coverage, so is this a needed -- or even valid -- change?

**Comment by takuki** [comment]
As long as we can successfully test this string-meta level requirement in time, everything is fine.
Please remember we are testing interoperability of TD specification, by testing assertions in TD spec.
I am *not* pushing this.
Just suggesting this test item is not in our critical path if we do not have enough time.

**Comment by mkovatsc** [comment]
Thanks to @k-toumura and @danielpeintner for providing implementations through their WoT UI projects!
Closing.
