### ISSUE TITLE
[Testing] Implementations of Digest QoP sub-feature needed

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#739]
Default values depend on the behavior of a Consumer and can't be checked by inspecting TDs.

The following default value assertions need additional manual validations:
- [x] td-default-idempotent 
- [x] td-default-in-basic
- [x] td-default-in-digest
- [x] td-default-op-actions
- [x] td-default-op-events
- [x] td-default-op-properties

The following also need manual assertion but are associated with at-risk features (and so are actually lower priority than the above):
- [ ] td-default-alg-pop
- [x] td-default-flow
- [ ] td-default-format-pop
- [x] td-default-in-apikey
- [ ] td-default-in-pop
- [x] td-default-qop

Note that these could all be satisfied by building an additional TD processor, perhaps in a proxy, that filled in all missing default values, and then using a sufficient set of TD inputs requiring those defaults.

**Comment by mmccool** [comment]
We did a code check and node-wot implements defaults for td-default-(name,in)-(apikey, bearer, basic), but does not explicitly mention digest. We have updated the manual assertions accordingly, but digest still needs to be checked. @danielpeintner and @mkovatsc can you please sort that out?

**Comment by mmccool** [comment]
Still some outstanding tests needed, but the only one that is not at-risk is in-digest.

**Comment by yamagile** [comment]
@mmccool , I created the [PR](https://github.com/w3c/wot/pull/819) on this issue. It makes td-default-flow passed.

**Comment by mkovatsc** [comment]
My [Meta-Interaction Thing](http://18.197.93.117/) implements Digest.

**Comment by mkovatsc** [comment]
The open issues are now limited to the PoP Token feature, which is at-risk.

**Comment by mkovatsc** [comment]
I am removing the "by PR transition" label, as these at-risk features will be dropped given the implementation report.

**Comment by mkovatsc** [comment]
The PoPSecurityScheme part is actually a duplicate of https://github.com/w3c/wot-thing-description/issues/731. Adjusting title for better at-risk tracking (QoP only).

**Comment by mkovatsc** [comment]
Having the `qop` term together with the obvious default value `auth` does not hurt and provides an "just-in-case" extension point. Hence, we should leave it in.

**Comment by mmccool** [comment]
the QoP feature now has sufficient implementations... so closing this issue.
