### ISSUE TITLE
Pragmatic TD validation

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#74]
Validating TDs is mentioned as an open issue in section 4 of the spec:

> ISSUE 1
> We need to be more precise here: How to validate a TD? E.g., structure validation and/or RDF validation? Comments are welcome.

Since all recent discussions and plug fest examples currently are using JSON-LD, a way to perform a formal validation of a TD in JSON-LD would be beneficial.

A starting point could be a definition of the TD syntax as JSON-Schema , which could be validated by 
https://jsonschemalint.com

To increase the level of validation, a dedicated JSON-LD validator (e.g. https://json-ld.org/playground/) could be used.

**Comment by sebastiankb** [comment]
There is a [TD Playground](http://plugfest.thingweb.io/) which combines JSON Schema and JSON-LD validation in one tool. Currently, this tool is under development and thus offline. The plan is to have it active again for the next plugfest.

**Comment by mkovatsc** [comment]
From an LD perspective, [SHACL](https://www.w3.org/TR/shacl/) is another way.

**Comment by mlagally** [comment]
Is the TD playground now available?

**Comment by sebastiankb** [comment]
We can also use the playground again for validation: http://plugfest.thingweb.io/playground/
