### ISSUE TITLE
[Testing] Manual Validation is needed for Multilanguage Assertions

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#741]
The following need additional validation:
- [x] td-multi-languages-consistent 
- [x] td-multilanguage-language-tag 
- [x] td-titles-descriptions
- [x] td-ns-multilanguage-content-negotiation 
- [x] td-ns-multilanguage-content-negotiation-no-multi

Note however that there is an ambiguity in td-titles-descriptions which is why there are some "failures" in the test results.   A PR to resolve this ambiguity (using some informative explanatory text) would be useful, and a future spec may want to more carefully word this assertion.

**Comment by mmccool** [comment]
I @mmccool can take care of content negotiation as part of my proxy implementation.
Also node-wot can be updated to do this: @danielpeintner and @mkovatsc 
It might also be possible for @k-toumura to do it in Node-RED (consumer side).

**Comment by takuki** [comment]
If there is an ambiguity, and there was a failure because of that, we need to clarify that in the spec before PR.

@mmccool , can you describe the nature of the ambiguity?

**Comment by mkovatsc** [comment]
@danielpeintner added language negotiation to node-wot.

To second this, I implemented the [Meta-Interaction Thing](http://18.197.93.117/), which also supports language negotiation (en and de).

@k-toumura could you maybe do another end-to-end test with your negotiating TD Consumer?

**Comment by k-toumura** [comment]
@mkovatsc End-to-end test with Meta-Interaction Thing and nodegen is passed.
For example, following command generates a German localized node.
`% ./node-red-nodegen.js http://18.197.93.117/ --name meta-de --wottd --lang de`

Sample screenshot is below:
![Screen Shot 2019-06-16 at 12 50 45](https://user-images.githubusercontent.com/30313213/59558797-73160480-9035-11e9-80f5-ff84ab7c04a8.png)
Nodes in left are generated nodes(no negotiation, en and de), and localized help is shown in right pane.

**Comment by mkovatsc** [comment]
@k-toumura Great, thank you very much!
Closing.
