### ISSUE TITLE
[Testing] Manual Validation is Needed for Security Assertions

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#742]
The following needs additional validations:
- [x] td-security-bearer-format-extensions

The following also need validation but are associated with at-risk features (and so are a lower priority than the above):
- [x] td-security-oauth2-code-flow 
- [ ] td-security-oauth2-implicit-flow 
- [ ] td-security-oauth2-password-client-flow

**Comment by mmccool** [comment]
We need to invent a new bearer format, maybe an "eatme" format with the string "Eat Me" in a file as the token, and a corresponding vocabulary extension.

**Comment by mkovatsc** [comment]
We do not only need a custom `format`, but also `alg`. It can follow the same dummy approach as above to mock any potential future use.

**Comment by mmccool** [comment]
I want to emphasize again that the actual implementation can be an existing format and alg, just as jwt (or whatever is already implemented).   All we really need is a test of the extension mechanism, and do that we can just "rename" an existing format and alg to mock up an extension.

**Comment by takuki** [comment]
I think the minimum bar for the testing is to let producer generate a TD using an extension (i.e. not one of the predefined values, and make sure a Consumer recognizes that as an extension.

**Comment by yamagile** [comment]
@mmccool , I created the [PR](https://github.com/w3c/wot/pull/819) on this issue. It can add 2 passes to result of td-security-oauth2-code-flow.

**Comment by vcharpenay** [comment]
Regarding the assertion on custom bearer tokens, is something like that what you expected?

```json
{
  "@context": [
    "https://www.w3.org/wot/td/v1",
    {
      "cred": "https://www.w3.org/2018/credentials#",
      "sec": "https://w3id.org/security#"
    }
  ],
  "securityDefinitions": {
    "extendedBearer": {
      "scheme": "bearer",
      "format": "cred:VerifiablePresentation",
      "alg": "sec:RsaSignature2018"
    }
  }
}
```

As far as I understand, JWT can be substituted by JSON-LD [Verifiable Claims](https://www.w3.org/TR/verifiable-claims-data-model/). I looked at VC examples for the definition above.

**Comment by mkovatsc** [comment]
@vcharpenay This sounds great -- @msporny can you maybe clarify if Verifiable Credentials can be applied to the HTTP Auhorization header field?

To be safe, I implemented the [Meta-Interaction Thing](http://18.197.93.117/), which also secures one Property with a fictional [Useless Web Token](http://18.197.93.117/useless-web-token#). @vcharpenay could you maybe check if my TD Context Extension is modeled correctly?

**Comment by mkovatsc** [comment]
Implementation report has 2 `pass` for td-security-oauth2-code-flow

**Comment by mkovatsc** [comment]
td-security-oauth2-implicit-flow and td-security-oauth2-password-client-flow are not implemented, but at-risk features.

**Comment by mkovatsc** [comment]
This is now a duplicate of https://github.com/w3c/wot-thing-description/issues/730

Closing.
