### ISSUE TITLE
[Testing] Automated Tests Needed for Some "Manual" Assertions

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#743]
The following assertions are currently listed as a manual assertions but could be tested automatically.   In a pinch we could handle these as a manual assertions, however.

The following are also mentioned in Issue https://github.com/w3c/wot-thing-description/issues/741:
- [x] td-multi-languages-consistent
- [x] td-multilanguage-language-tag
- [x] td-titles-descriptions

The following are also mentioned in Issue https://github.com/w3c/wot-thing-description/issues/742:
- [x] td-security-bearer-format-extensions
- [x] td-security-oauth2-code-flow
- [x] td-security-oauth2-implicit-flow
- [x] td-security-oauth2-password-client-flow

**Comment by egekorkan** [comment]
> The following are also mentioned in Issue #741:

    td-multi-languages-consistent
    td-multilanguage-language-tag
    td-titles-descriptions

These are not _that_ easy to check since they cannot be checked with an assertion schema. I will need to write a javascript code that can check them. Not difficult but not in a pinch either

**Comment by egekorkan** [comment]
td-multi-languages-consistent has been added
it was not mentioned here but td-security-scheme-name was also not being tested

**Comment by egekorkan** [comment]
`td-multilanguage-language-tag` is added as well

**Comment by egekorkan** [comment]
td-titles-descriptions are also added now

**Comment by egekorkan** [comment]
All the assertions mentioned are now tested automatically

**Comment by mmccool** [comment]
Not sure test for td-titles-descriptions is correct.   I am seeing failures in intel-inference.json, but I am pretty sure it is correct.  All other TDs are failing, too.
