### ISSUE TITLE
[Testing] Additional Implementations need to cover the op values

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#747]
Currently the following op values need additional implementations:
* [x] readmultipleproperties
* [x] writemultipleproperties
* [x] writeallproperties
* [x] unobserveproperty

**Comment by mmccool** [comment]
These seem to be included in TestThing for node-wot but are not being picked up somehow.   I will investigate.

**Comment by egekorkan** [comment]
But TestThing is not in the inputs

**Comment by mmccool** [comment]
It looks like even so we need additional implementations for readmultipleproperties, write(all,multiple)properties and (the hard one) unobserveproperties

**Comment by mmccool** [comment]
@mkovatsc will look at a producer to connect with node-wot, which is able to consume TDs with such features.  Will address td-vocab-op--Form_writemultipleproperties, td-vocab-op--Form_readmultipleproperties, td-vocab-op--Form_writeallproperties

**Comment by mmccool** [comment]
@danielpeintner will address td-vocab-op--Form_unobserveproperty

**Comment by mkovatsc** [comment]
I implemented the [Meta-Interaction Thing](http://18.197.93.117/), which provides all meta interactions.

**Comment by mkovatsc** [comment]
Thanks, @egekorkan, for the additional unobserve Thing!
