### ISSUE TITLE
[Testing] Additional Implementations needed for Form features

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#748]
td-vocab-contentCoding--Form needs another implementation than node-wot.
The results in [here](https://github.com/w3c/wot/blob/master/testing/tests/2019-05/outputs/Siemens/siemens-node-wot/fullInteractionsTest-siemens.csv) say that it is implemented but doesn't appear in the report

**Comment by mmccool** [comment]
appears in the report now.  all node-wot results were getting dropped due to a malformed manual csv file, which I fixed.

**Comment by egekorkan** [comment]
Now there is 1 implementation for a MAY assertion. Can be closed
