### ISSUE TITLE
[Testing] Additional implementations required for BearerSec

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#749]
None of the implementations with Bearer Security Scheme do not have an `in` key. This results in td-vocab-in--BearerSecurityScheme having 0 implementations. I see that Panasonic have a lot of TDs with bearer but do not specify 'in' key. Could you add these @ToruKawaguchi or @yamagile ?

**Comment by yamagile** [comment]
@egekorkan Sure. I can add `in` key to some TDs in the next coffee break.

**Comment by yamagile** [comment]
@egekorkan done! see w3c/wot#809 .

**Comment by mkovatsc** [comment]
Implementation report reflects this now, closing.
