### ISSUE TITLE
Section "5.2.6 DataSchema" should be independent from the serialisation format

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#75]
Section 5.2 defines a conceptual data model of the entities in the WoT context.

These conceptual entities are **independent from a specific serialisation**, and most of the classes in Section 5.2. are described in that way.  

However in section "5.2.6 DataSchema" there is a requirement for a **specific declaration as JSON Schema**. 
This may cause problems in resource constrained devices and in binary serialisations, which, according to the current spec - would have to include a textual block encoded in UTF (8,16 or 32).
See the requirements in https://tools.ietf.org/html/draft-handrews-json-schema-00 and section 8.1 of 
https://tools.ietf.org/html/rfc7159#page-9 for details.

Proposal:
The requirement of a JSON Schema representation of the DataSchema should be moved to chapter 6 and chapter 5.2.6 should define a serialisation-independent way of describing data structures.

**Comment by mkovatsc** [comment]
This is related to https://github.com/w3c/wot-binding-templates/issues/23

Note that there is currently an overlap between Binding Templates and TD, as the BT Task Force is looking at concrete requirements from protocols to formulate a concrete proposal to be included in TD.

**Comment by sebastiankb** [comment]
The new updated TD draft includes a more concrete plan for the future of the [DataSchema section](https://w3c.github.io/wot-thing-description/#dataschema). We will rely only on the JSON Schema terms that will be mapped to Linked Data.
