### ISSUE TITLE
[Testing] Additional Implementations required for Basic Sec

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#750]
None of the provided implementations that already have basic security scheme provide the name for the parameter. This results in td-vocab-name--BasicSecurityScheme having 0 implementations.

Intel @mmccool , Fujitsu @mryuichi , Siemens @sebastiankb @danielpeintner and Oracle @mlagally  can provide this by simply adding a name in the security scheme

**Comment by mkovatsc** [comment]
@yamagile will add `"name": "Bearer"` to the Bearer Token TD(s) where they already have `"in": "header"`.

**Comment by mkovatsc** [comment]
@mmccool will add similar entries for digest and basic.

**Comment by yamagile** [comment]
@mkovatsc my [TD](https://github.com/w3c/wot/blob/master/testing/tests/2019-05/inputs/Panasonic/panasonic-server-real/cleaner_p1.jsonld) has `"name": "Authorization"`. Is it incorrect? (What document should I refer?)

**Comment by yamagile** [comment]
My [TDs](https://github.com/w3c/wot/blob/master/testing/tests/2019-05/inputs/Panasonic/panasonic-server-real) has `"name": "Authorization"` and `"in": "header"`. 👍

**Comment by mmccool** [comment]
I also added these for basic and digest, so these all pass now.  However, we should discuss whether the correct value is "Authorization", "Authorization: Basic" or "Basic".
