### ISSUE TITLE
DISCUSS: Can we Relax Implementation Requirements for Extensions?

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#752]
It is hard to have implementations for extension points, e.g. support for future bearer token formats and algorithms.

**Comment by sebastiankb** [comment]
can you be more clear about this? is this more implementation or TD issue?

**Comment by mmccool** [comment]
This specifically relates to assertions like td-security-bearer-format-extensions, which require that the TD support extensions.   However, to test this, we need to implement an extension.   But extensions are intended for future features, so we can only test it with a "made-up" extension.   See https://github.com/w3c/wot-thing-description/issues/742.

What we decided in the meeting however (probably when you were not there...) was that we should aim to test this particular assertion with a specialized test, and we assigned @vcharpenay to work on it.  Basically, he needs to implement a "fake" extension that can however be implemented using a currently implemented security scheme, that is, the test only has to test the extension mechanism itself, not provide an actual new security scheme.

**Comment by mmccool** [comment]
We can probably close this issue since we decided in this particular case that we can provide a test.   But the point was testing a feature intended to support FUTURE features is a little challenging.

**Comment by mmccool** [comment]
As to whether this is a TD or an implementation issue, it is both; or rather, it is a testing issue; it relates to a TD feature that needs an implementation for testing.

**Comment by takuki** [comment]
I think the minimum bar for the extension-point testing is to let producer generate a TD using an extension (i.e. not one of the predefined values), and make sure a Consumer properly recognizes that as something it does not understand.

**Comment by mmccool** [comment]
Right, we just have to verify the extension *mechanism* works...

**Comment by mkovatsc** [comment]
My [Meta-Interaction Thing](http://18.197.93.117/) demonstrates a fictional future extension for a custom bearer token format and algorithm. With thatm the extension point was tested.

I propose to close this issue.

**Comment by mkovatsc** [comment]
Closing, as this is no a non-issue.
