### ISSUE TITLE
Update Recent Changes section for Proposed REC

### ISSUE THREAD

**Issue by takuki** [w3c/wot-thing-description#769]
The recent changes section need to describe the following items.

- [x] https://github.com/w3c/wot-thing-description/issues/696 - @sebastiankb 
- [x] https://github.com/w3c/wot-thing-description/issues/714 - @sebastiankb 
- [ ] [fixed mistakes in TD vocabulary UML diagram](https://github.com/w3c/wot-thing-description/commit/df824840dec5bda76b2c3310a696c7b4011f5a63#diff-2b300fa6d666e42846435e06c8459af6) - @vcharpenay 
- [x] Updated [Example 28](https://cdn.staticaly.com/gh/w3c/wot-thing-description/extension-refactor/index.html?env=dev#example-28). - @vcharpenay
- [x] Added [Example 40](https://cdn.staticaly.com/gh/w3c/wot-thing-description/extension-refactor/index.html?env=dev#example-40). - @vcharpenay
- [x] https://github.com/w3c/wot-thing-description/pull/744

**Comment by mkovatsc** [comment]
> fixed mistakes in TD vocabulary UML diagram

This was for appropriate use of the `@type` annotation for Thing and Property.

**Comment by mkovatsc** [comment]
All and changes beyond addressed in #784
