### ISSUE TITLE
Status of Ontology Documents

### ISSUE THREAD

**Issue by vcharpenay** [w3c/wot-thing-description#770]
Currently, the vocabulary namespaces mentioned in the TD spec host files that have the **Working Group Note** status. E.g.: https://www.w3.org/2019/wot/td.

Issues:
- a working group note requires the approval of both the WoT WG and the W3C, we can't get both before PR transition.
- future changes to the ontology documents will likely have impact on [Appendix D](https://w3c.github.io/wot-thing-description/#note-jsonld11-processing), which shows a full RDF example. On the other hand, these changes must be conducted for the ontologies to be usable in practice.

Proposed solution:
- split PR #744 in two parts: one to be done before PR transition, another that can be dealt with within the future IG or WG (after rechartering)
  - the first part will only include status change (to plain document) and a warning in Appendix D?
  - the second part will include various examples on how to use the ontology and a `v1.1` JSON-LD context (already included in PR #744)

A decision should be made on what status ontology documents should have eventually (IG note, WG note, none).

**Comment by mkovatsc** [comment]
@ashimura can you please advise how to populate the namespace under https://www.w3.org/2019/wot/ ? Maybe you have to check with Ralph.

We have .ttl ontology files accompanying the TD spec. The idea was to release their HTML documentations as WG Notes. However, we could just put them as HTML documentation documents under the namespace URIs.

**Comment by takuki** [comment]
During 6/14 telecon, the TD TF discussed this issues that resulted in creating this issue.

* Ontology files are now editor’s draft as suggested by @ashimura 
* TD TF suggests to publish ontology documentation after TD PR publication.
  * Question is when? and how? (WG Note? IG Note? or even CG Note?)

**Comment by takuki** [comment]
@vcharpenay , can you split #744 into two, one of which will not be affected by future ontology file changes? How soon do you think you can make it?

**Comment by mkovatsc** [comment]
@ashimura confirmed during the chairs call on 19 June 2019 that we can populate the namespaces with the ontology files and use an "Editors' Draft" stylesheet for the HTML documentation files.

@vcharpenay Can you please adapt the files accordingly?

**Comment by mkovatsc** [comment]
#782 was merged and ontology documentation updated through #783
