### ISSUE TITLE
Move Transformation to RDF (now removed from TD) to TD ontology document

### ISSUE THREAD

**Issue by takuki** [w3c/wot-thing-description#787]
The Introduction states:
> Hence, a TD instance can be also processed as an RDF document (for details about semantic processing, please refer to the documentation under the namespace IRIs, e.g., https://www.w3.org/2019/wot/td). 

We should reinstate the used-to-be-Appendix D (Transformation to RDF) section in the [TD ontology document](https://www.w3.org/2019/wot/td) because otherwise the quoted text above in the introduction is not very accurate.

Note the appendix section was removed recently as agreed in the main call on June 19.
Please see [here](https://github.com/w3c/wot-thing-description/commit/1607e32ec5e434f5bf392b04e164002ea487b9a1#diff-eacf331f0ffc35d4b482f1d15a887d3b) for the change log.

**Comment by takuki** [comment]
Also, section [5.3.2 Data Schema Vocabulary Definitions](https://w3c.github.io/wot-thing-description/#sec-data-schema-vocabulary-definition) states:

> for details about semantic processing, please refer to the documentation under the namespace IRIs, e.g., https://www.w3.org/2019/wot/td

**Comment by vcharpenay** [comment]
The issue can be closed, in my opinion. The branch `onto-examples` includes changes on the onto documentation that describe RDF transformation.

See https://cdn.staticaly.com/gh/w3c/wot-thing-description/onto-examples/ontology/td.html?env=dev#thing-description-json-ld-1-1-instance-to-rdf-dataset

**Comment by takuki** [comment]
Thank you @vcharpenay . It makes sense to me as well. Let's close this issue.
