### ISSUE TITLE
Handle at risk features before publishing as proposed rec

### ISSUE THREAD

**Issue by kenchris** [w3c/wot-thing-description#789]
A comment in the https://github.com/w3ctag/design-reviews/issues/357 says that you plan to publish the spec as a Proposed Recommendations on June 27th, but the spec itself is full of features at risk.

We believe that it would be good to resolve these at risk features before doing so

**Comment by takuki** [comment]
The WoT Thing Description TF discussed this issue during 7/12 telecon.
Minutes is available [here](https://www.w3.org/2019/07/12-wot-td-minutes.html#item012).

Excerpt from minutes:
> TD Issue 789
>   Sebastian: at risk features
>   Taki: We have addressed most of those (at-risk features).
>    Sebastian: We also have time with the (charter) extension

**Comment by mmccool** [comment]
The IR is being updated for a planned second CR, and the number of features at risk have been greatly reduced.  The main category of such features are unimplemented security schemes, which we will remove before PR if we still do not have implementations for them by then... but can still be used via an extension mechanism if necessary.   One sub-category is that we only are using a subset of all the possible flows for OAuth2.   In that case, we will have to "trim" the specification before PR to only mention the OAuth2 flows that we have two or more implementations for.

**Comment by sebastiankb** [comment]
we are currently on the way to CR2. At risk features can be handled until PR transition that will be December 10th

**Comment by sebastiankb** [comment]
@mmccool please provide the 'PR available' label when you are ready

**Comment by sebastiankb** [comment]
all at-risk features are removed from the spec. I will close this issue
