### ISSUE TITLE
Retrieve raw JSON data for context namespaces 

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#790]
FYI: Issue https://github.com/w3c/wot-architecture/issues/374 seems related to the thing description.

How to obtain JSON-LD context files other than `https://www.w3.org/2019/wot/td/v1` ?

**Comment by takuki** [comment]
I think this is not a comment from TAG.

**Comment by takuki** [comment]
It appears that https://www.w3.org/2019/wot/td/v1 has also contains other stuff beyond the core vocabulary.

**Comment by sebastiankb** [comment]
we should wait for @vcharpenay. He is currently on vacation and will be back next week Wednesday.

**Comment by sebastiankb** [comment]
In today's TD call, we decided that we should add a better explanation of the relationship between the JSON-LD TD context file and all turtle-based namespaces such as https://www.w3.org/2019/wot/security#, https://www.w3.org/2019/wot/td# ...

@vcharpenay will take care of it

**Comment by vcharpenay** [comment]
See PR #811.

**Comment by vcharpenay** [comment]
(and 474df1e for a minor edit related to that PR.)
