### ISSUE TITLE
Name vs title in TD examples

### ISSUE THREAD

**Issue by akeranen** [w3c/wot-thing-description#793]
Some example TDs don't pass validation because of missing mandatory "title" member and Example 2 is still using "name".

**Comment by sebastiankb** [comment]
This issue was already addressed and is already compiled in the latest [editor draft](https://w3c.github.io/wot-thing-description/) for the PR submit.

**Comment by sebastiankb** [comment]
also see https://github.com/w3c/wot-thing-description/issues/696
