### ISSUE TITLE
Missing references for WebSub and Server-Sent Events

### ISSUE THREAD

**Issue by takuki** [w3c/wot-thing-description#795]
Section on [Form](https://w3c.github.io/wot-thing-description/#form) mentions WebSub and Server-Sent Events with direct links to the respective specifications.

They should be listed as normative references.

Note: This is related to Issue #380.

**Comment by takuki** [comment]
Please see PR #796.

**Comment by sebastiankb** [comment]
isseu  solved by PR #796
