### ISSUE TITLE
WoT TD ontology HTML document can describe how to retrieve turtle representation

### ISSUE THREAD

**Issue by takuki** [w3c/wot-thing-description#797]
The [WoT TD Ontology](https://www.w3.org/2019/wot/td) should describe how people can obtain its turtle representation.

Please see this [issue](https://github.com/w3c/wot-architecture/issues/374#issuecomment-512583412) in architecture repo.

The same is true for other WoT ontologies ([JSON Schema Ontology](http://w3c.github.io/wot-thing-description/ontology/jsonschema.html), [Security Ontology](http://w3c.github.io/wot-thing-description/ontology/wotsec.html) and [Hypermedia Controls Ontology](http://w3c.github.io/wot-thing-description/ontology/hyperm.html)).

Also, see the [redirection configuration](https://github.com/w3c/wot-thing-description/issues/432#issuecomment-493326214) created by @ashimura .

**Comment by sebastiankb** [comment]
maybe we can merge this issue to this one https://github.com/w3c/wot-thing-description/issues/790

**Comment by takuki** [comment]
This issue was merged into #790 by @sebastiankb in a [comment](https://github.com/w3c/wot-thing-description/issues/790#issuecomment-515336759).
