### ISSUE TITLE
Question: difference between operation types writeallproperties vs. writemultipleproperties

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#799]
The concept behind `writeallproperties` and `writemultipleproperties` is very similar. A set of properties is send at once.

I wonder whether these 2 operation types have any difference. Does `writeallproperties` *need* to check in any form whether *all* properties are provided?

**Comment by sebastiankb** [comment]
the definitions of these operations can be found [here](https://www.w3.org/TR/wot-architecture/#table-operation-types).

>I wonder whether these 2 operation types have any difference. Does writeallproperties need to check in any form whether all properties are provided?

This feature will be offered by the producer. As consumer I would expert to get all defined property values that are defined within the `properties` field (also see [here ](https://www.w3.org/TR/wot-thing-description/#td-forms-readall-example) for an example). 

In the case of `writemultipleproperties`  the consumer has to provide a selection of properties'.

**Comment by egekorkan** [comment]
> In the case of writemultipleproperties the consumer has to provide a selection of properties'.

However, for `writeallproperties` the consumer still has to provide this selection and this selection SHOULD(?) match all the properties. So should the producer deny `writeallproperties` if all properties are not present in the request of the consumer?

**Comment by takuki** [comment]
> In the case of _writemultipleproperties_ the consumer has to provide a selection of properties.

In my opinion, _writeallproperties_ and _writemultipleproperties_ are different in the following respect.

In _writemultipleproperties_ , only specified properties get changed.

On the other hand, in _writeallproperties_, non-specified properties get their existing values (if any) removed.

**Comment by egekorkan** [comment]
> On the other hand, in writeallproperties, non-specified properties get their existing values (if any) removed.

That means that a TD SHOULND'T have `writeallproperties` and `writemultipleproperties` in the same form?

**Comment by danielpeintner** [comment]
> On the other hand, in writeallproperties, non-specified properties get their existing values (if any) removed.

From the implementation point of view I see this behavior a bit problematic.

Moreover, I am not sure whether this matches the expectation of users. If one property gets forgotten it is suddenly unset.

**Comment by takuki** [comment]
In TD telecon, there were several suggestions.

- _writeallproperties_ requires all fields are specified in payload, otherwise it will get an error.
- _writeallproperties_ may be redundant when also having _writemultipleproperties_ in the same form.

The spec needs to be clear on those points.

**Comment by sebastiankb** [comment]
PR #826 solves this issue. This I close this issue.
