### ISSUE TITLE
Default @context with  http, https, or both?

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#80]
I noticed some that the latest editors draft uses https as default URI context (`https://w3c.github.io/wot/w3c-wot-td-context.jsonld`). The first PWD used both, http (`http://w3c.github.io/wot/w3c-wot-td-context.jsonld`) and https.

I wonder whether we need to agree on one or allow both variants?
I assume _one_ is prefered which allows easy comparison.

Thanks for the clarification.

**Comment by sebastiankb** [comment]
In sake of security in IoT https is prefered. I updated the TD spec. with only https context in the examples.
