### ISSUE TITLE
extend op options with observeallproperties and observemultipleproperties 

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#800]
for multiple property processing we supporting `readallproperties`, `writeallproperties`, `readmultipleproperties`, and `writemultipleproperties`. 

It would be good if we also would support  `observeallproperties` and `observemultipleproperties` for multiple observable use cases.

**Comment by egekorkan** [comment]
While this is still under discussion, it would be good to think of the issue #848

**Comment by sebastiankb** [comment]
since `readmultipleproperties` is under discussion I would suggest that we only go for  `observeallproperties` for TD 1.1

**Comment by sebastiankb** [comment]
From today's TD call:
- in general this feature makes sense
- there should be also a  `unobserveallproperties`
- however, we should evaluate the impact of unobserve a single property
-  @sebastiankb will prepare PR and we will do a discussion on this in one next TD meeting

**Comment by sebastiankb** [comment]
Issue solved by PR that is already merged in last December
