### ISSUE TITLE
Rename Thing Template to Thing Description Template / TD Template

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#801]
Currently, in [Section C](https://www.w3.org/TR/wot-thing-description/#thing-templates) we use the name `Thing Template` that is a subset of the Thing Description model. For me it would make more sense to call it `Thing Description Template`, or short `TD Template`. This would give a more clear context what the template is about. 

Are there some opinions on that? Or, is there anything against including the word `Description` before PR submit?

**Comment by mlagally** [comment]
I don't think this change is really necessary, since the term has been introduced and used almost a year ago.
There are cases where a Thing Template may be used for other purposes, so an instantiation would not be a TD.

**Comment by takuki** [comment]
@mlagally , note that the draft WoT charter uses "Thing Description Templates" already.

**Comment by sebastiankb** [comment]
@mlagally 
> I don't think this change is really necessary, since the term has been introduced almost a year ago and and has been used since then.

The idea is quite old and always the term `Thing Description Template` was used from the beginning. E.g., see this presentation [here](https://www.w3.org/2018/03/wot-f2f/slides/2018-03-26-W3C-WoT-F2F-Prague-iotschema-v2.pdf).

> There are cases where a Thing Template may be used for other purposes, so an instantiation would not be a TD.

Is this the case, why is this defined in the Thing Description document?

**Comment by sebastiankb** [comment]
PR was merged. Close this issue.
