### ISSUE TITLE
server-data-schema and server-data-schema-extras are contradictory (for a first time reader)

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#807]
The mentioned assertions are:
[server-data-schema](https://www.w3.org/TR/wot-thing-description#server-data-schema) :  A WoT Thing Description MUST accurately describe the data returned and accepted by each interaction. 
[server-data-schema-extras](https://www.w3.org/TR/wot-thing-description#server-data-schema-extras) :  A Thing MAY return additional data from an interaction even when such data is not described in the data schemas given in its WoT Thing Description. 

A reader may not realize that this actually applies **only** for ObjectSchema or for ArraySchema (but only if items is an Array of DataSchema). I think that this should be made clear since without this background knowledge, we have contradicting assertions. Also, in case the TD has `additionalProperties:false` for the case of ObjectSchema, the Thing MAY NOT return additional data. This term is not in the spec so this comment may be invalid anyways.

**Comment by hrennau** [comment]
An interesting point - it should be clarified what "additional data" exactly means. Doubtless - additional object members. How about an array which has more items than the data schema allows - is this "additional data" that a Thing MAY return? I suppose not, but I'm not sure! And then, if a data schema describes a scalar type - say, string - would an array with items of that type be conformant? Most probably not. Finally, I agree that the spec should address the situation that a data schema uses additionalProperties: false.

**Comment by egekorkan** [comment]
Regarding your comment on arrays, it is a similar problem. The JSON Schema spec (https://json-schema.org/understanding-json-schema/reference/array.html#list-validation this is not exactly the spec :) ) actually defines `additionalItems` when `items` is **not** a single schema. So if we have the following schema:
```
"items":[{"type":"integer"},{"type":"string"}],
 "additionalItems":true
```
we can accept all of the below since  `additionalItems` is true. This would be still the case in the absence of  `additionalItems` since it defaults to true.
```
[1,"mama"]
[2,"mia",3]
[1,"abc",[1,2,3,4]]
```

**Comment by hrennau** [comment]
Interesting, I was not aware of that! What I thought of was the question if Things were licensed to violate "maxItems", on the grounds of being allowed to "return additional data". I suppose this is not intended, and I agree with you that the spec should be absolutely clear about what is allowed and what not.

How about this refinement of the spec: 
"A Thing MAY return additional data from an interaction even when such data is not described in the data schemas given in its WoT Thing Description, but not if the items violate a constraint of the data schemas.
NOTE. Data schema constraints which a message sent by a Thing must not violate are "additionalItems: false" and "additionalProperties: false". A further case of additional data not allowed is the use of an array where the data schema prescribes a single item.

**Comment by egekorkan** [comment]
We would just have problem that `additionalItems` and `additionalProperties` are not defined in the TD Data Schema vocabulary. We do say that Data Schemas can be extended with other validation keywords however.

**Comment by hrennau** [comment]
Yes, a somewhat grey area, I think. The following text from 5.3.2 Data Schema Vocabulary Definitions:

"It is noted that data schema definitions within Thing Description instances are not limited to this defined subset and may use additional terms found in JSON Schema using a TD Context Extension for the additional terms as described in § 7. TD Context Extensions, otherwise these terms are semantically ignored by TD Processors"

seems to be saying that "additional terms found in JSON Schema" cannot only be used, but are as binding as the Data Schema vocabulary, otherwise the meaning of *not* being semantically ignored would be undefined.

But that is interpretation only, not facts. It would be good if the spec were clearer about this point in 5.3.2.

**Comment by sebastiankb** [comment]
many thanks for all the feedbacks. We should definitely take care of that and make some refinements in the specification to avoid confusion.  should be done before PR transition.

**Comment by sebastiankb** [comment]
@ege will provide a PR that includes a new paragraph for clearification
