### ISSUE TITLE
Proposals are referenced by Google and have wrong date

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#808]
Similar to the need to create have an ARCHIVE repo on w3c/wot we need it here. E.g. searching for `simplified thing description w3c` on google returns the following document: https://w3c.github.io/wot-thing-description/proposals/simplified-td/

This document has the date of the official TD

**Comment by egekorkan** [comment]
From the respec documentation, we can set a static publication date for such documents. See https://github.com/w3c/respec/wiki/publishDate

**Comment by danielpeintner** [comment]
Note: in general there are ways to *tell* search engines that certain folders should not be indexed/removed.

e.g., robots.txt file in root with
```
User-agent: *
Disallow: /proposals/
```

**Comment by sebastiankb** [comment]
issue solved by PR #816

**Comment by k-toumura** [comment]
Unfortunately, robot.txt files in subdirectories are not valid.

in [Robots.txt Specifications](https://developers.google.com/search/reference/robots_txt):
> Crawlers don't check for robots.txt files in subdirectories.
