### ISSUE TITLE
Definition of baseUri and href

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#81]
We need a definition about the usage of (relative) href and base uri. E.g., a relative href needs always a baseUri in TD.

**Comment by sebastiankb** [comment]
Explanations about the usage of base is given by the latest TD version

**Comment by zolkis** [comment]
The spec says some `href` may be relative, the examples give full URLs. In order to simplify implementations, could we make the rule that if `baseURL` is defined, then each `href` is relative to that?

**Comment by mkovatsc** [comment]
Well, each relative URI is; each absolute URIs is not. All implementations need proper Reference Resolution (see [RFC3986](https://tools.ietf.org/html/rfc3986) when dealing with URIs.
