### ISSUE TITLE
[question] How to describe observeOnly properties? 

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#810]
In the current specification, we cannot describe if a property is only observable and not readable and writeable. In the case of MQTT, if one publishes a message without a retain flag or if the broker doesn't support retain, only the current subscribers of the topic will get the message, hence they will be observing. A `readproperty` via MQTT would be possible only if the retain flag is settable to true. I think this is a real use case for MQTT Things. Some solutions:
- Saying that this is an event (needs no spec change)
- A new `observeOnly` for properties. This would be quite confusing since `readOnly` or `writeOnly` equal to `false` would mean that it is observable as well. This needs spec change and would be possible only for next version. Even then, it is not a perfect solution since it makes it impossible to have `readable` and `writeable` but not `observable` properties.
- Bringing back `writeable`, `readable`. This would be perfect solution to fix this little thing but would open all the issues of having `writeable` discussed in #209

**Comment by zolkis** [comment]
In that case modeling with an event makes most sense IMHO. One could argue about the difference between observing (changes reported) and events (all occurences reported), but in this case the meaning is to report all changes, which is fine.

`observeOnly` brings in too much complexity vs other protocols, like OCF/CoAP where we can't observe a property if not readable. 

The [observable, readable, writeable] tuple was a pretty good solution IMHO, we changed it for mostly syntactic and tradition-esthetic reasons.

**Comment by egekorkan** [comment]
Closing since it is at protocol bindings
