### ISSUE TITLE
Reasoning is missing why Example 29 design is considered a good practice

### ISSUE THREAD

**Issue by takuki** [w3c/wot-thing-description#813]
Just below [Example 29,](https://w3c.github.io/wot-thing-description/#saref-state-annotation-example) it says:

> In Example 2, the state of the Thing is given by the status affordance itself and possible state changes are given by the toggle affordance. In other words, the state of the physical world object directly provides the Interaction Affordances of the Thing. This design is satisfactory for simple cases like a light switch. In the general case, however, it is considered a good practice to separate the state of the object from the Interaction Affordances as illustrated above with ssn:forProperty. 

It states that it is a good practice to separate the state of the object from the interaction affordances without explaining the reasoning. Without reasoning, the claim does not mean much.

I suggest to add some reasoning for why the WoT WG thinks it is a good practice.

**Comment by hrennau** [comment]
I agree that the text is puzzling! To start with, I do not understand what is meant by "to separate the state of the object from the Interaction Affordances ..." Comparing examples 29 and 2, this is the only difference: the meaning of the state is in one case (example 2) expressed by @type:

"@type": "saref:OnOffState",

in the other case by an extension property:

 "ssn:forProperty": "urn:dev:ops:32473-WoTLamp-1234/state",

Both amount to the mapping of a simple label ("status") to the identification of a physical state, which is expressed by a resource identifier. I wonder why one does "separate the state of the object from the Interaction Affordances", the other not.

**Comment by vcharpenay** [comment]
thanks for the details, @hrennau.

Essentially, the "good practice" I mentioned in that piece of text is to allow the same state (identified by `urn:dev:ops:32473-WoTLamp-1234/state`) to be exposed via different affordances, i.e. with different data schemas. This can happen, e.g. to provide a short and an extended payload for the same physical state (see example below). This could also happen when several devices act as proxies for the same physical property, e.g.  when two temperature devices measure the temperature of the same room.

```
{
   ...
    "id": "urn:dev:ops:32473-WoTLamp-1234",
    "saref:hasState": { "@id": "urn:dev:ops:32473-WoTLamp-1234/state" },
    ...
    "properties": {
        "shortStatus": {
            "ssn:forProperty": "urn:dev:ops:32473-WoTLamp-1234/state",
            "type": "string",
            ...
        },
        "fullStatus": {
          "ssn:forProperty": "urn:dev:ops:32473-WoTLamp-1234/state",
          "type": "object",
          "properties": {
            "statusString": { "type": "string" },
            "statusCode": { "type": "number" },
            "statusDescription": { "type": "string" }
          }
        },
        ...
    },
    ...
}
```

If you think the text and example above are satisfactory, I'll include them in the spec.

**Comment by sebastiankb** [comment]
the group would like to have a PR on this change. @vcharpenay is taking care on it

**Comment by sebastiankb** [comment]
example was updated by the PPR #831. 
Will close this issue.
