### ISSUE TITLE
Update Privacy Risks and Mitigations that reference IDs

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#824]
Regarding the following

"* However, it would be better to mention the risk of "id" (esp. unique
  ID's being mandatory and we made it optional and removed the
  uniqueness) within the section 10. We might want to add one more PR
  for that purpose."

There already is a privacy risk/mitigation section in section 9 (not 10...) regarding ids but it needs to be revised now that id's are optional and are not "unique", so I can discuss a few other mitigations (like filtering out id's when they are not needed, and using "local" ids that are only valid in a given scope but not globally, and using randomly-generated distributed ids, etc.).

Update: PR available: https://github.com/w3c/wot-thing-description/pull/825

**Comment by sebastiankb** [comment]
PR was merged. Issue can be closed
