### ISSUE TITLE
Add "multipleOf" term to NumberSchema and IntegerSchema

### ISSUE THREAD

**Issue by ToruKawaguchi** [w3c/wot-thing-description#841]
It is ideal if we could indicate the resolution of number properties, such as "targetTemperature" of HVAC being specified in 0.5 degrees Celsius step.
JSON Schema already has "multipleOf" keyword for numeric types, so it is desirable to incorporate it to NumberSchema and IntegerSchema in future TD version.

**Comment by egekorkan** [comment]
The current TD spec allows addition of such extra words that would be parsed by a JSON Schema library. Could you provide example implementation TDs that make use of this?

**Comment by ToruKawaguchi** [comment]
Part of such TD looks like this: 
```
{
  ...
  "properties": {
    "targetTemperature": {
      "type": "number", 
      "minimum": 16, 
      "maximum": 30, 
      "multipleOf": 0.5
    }
  }
  ...
}
```

**Comment by takuki** [comment]
In 2019-11-08 TD telecon, it was suggested to support this in the next version of TD spec.

**Comment by ToruKawaguchi** [comment]
@takuki Thanks a lot!

**Comment by sebastiankb** [comment]
PR is merged

**Comment by egekorkan** [comment]
In the call of 12.05.2021, we have decided to close this issue
