### ISSUE TITLE
Clarifying default bindings for all op values

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#843]
The spec is quite clear on how the HTTP binding would work for the `op` values `readproperty`, `writeproperty` and `invokeaction`. There is the following sentence in the TD spec, just above the HTTP default binding:

> For the sake of conciseness, the Protocol Binding based on HTTP defines Default Values **for each operation** type, which also aims at convergence of the methods expected by Things (e.g., GET to read, PUT to write)

However, we don't have the default Binding for each `op` value. Notably the following ones are missing:
- [ ]  observeproperty
- [ ]  unobserveproperty
- [ ]  subscribeevent
- [ ]  unsubscribeevent
- [ ]  readallproperties
- [ ]  writeallproperties
- [ ]  readmultipleproperties
- [ ]  writemultipleproperties

I think the last 4 needs special discussion and that is why I have opened the issue #844

**Comment by sebastiankb** [comment]
a simple solution for this version would be to change the sentence

>  For the sake of conciseness, the Protocol Binding based on HTTP defines Default Values for each operation type, which also aims at convergence of the methods expected by Things (e.g., GET to read, PUT to write).

to 

 For the sake of conciseness, the Protocol Binding based on HTTP defines Default Values for readproperty, writeproperty and invokeaction operation types, which also aims at convergence of the methods expected by Things (e.g., GET to read, PUT to write).

**Comment by sebastiankb** [comment]
I will provide a PR. We can discuss on this editorial change when the PR is available and lets decide if we apply this change.

**Comment by egekorkan** [comment]
Fixed with #853 but needs review

**Comment by sebastiankb** [comment]
PR is merged we can close this issue
