### ISSUE TITLE
[question] Protocol bindings for read/writeXproperties

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#844]
As a continuation of #843 , I think that read/writeXproperties are not very clear and I have the following questions:
- I have a TD with multiple properties that all use HTTP GET for `readproperty` and HTTP PUT for `writeproperty`. Without explicit bindings, should the Consumer use HTTP GET for `readallproperties` and `readmultipleproperties` and HTTP PUT for `writeallproperties` and `writemultipleproperties`? I think this is already the case in 90% of the use-cases and the answer is YES.
- I have a TD with multiple properties that all use HTTP GET for `readproperty` but some use HTTP PUT for `writeproperty` and some HTTP POST. Without explicit bindings, should the Consumer use HTTP GET for `readallproperties` and `readmultipleproperties`. What should the consumer do for `writeallproperties` and `writemultipleproperties`? I think this is somewhat likely, especially for already existing IoT devices.
- Similar to the previous but with different protocols for each property. This is quite unlikely but the spec allows it.

I can think that if the binding information is explicit, there shouldn't be any problem. However, in the case of default assumptions, there could be uncertainties between what the Consumer expects and what the Exposed Thing thinks it is providing.

**Comment by egekorkan** [comment]
An example TD where this unclear is [this](https://github.com/w3c/wot/blob/master/plugfest/2019-tpac-fukuoka/TDs/Fujitsu/local/Fujitsu-AgriDevice.jsonld#L19) from Fujitsu

**Comment by sebastiankb** [comment]
we simple forgot this in section https://www.w3.org/TR/wot-thing-description/#http-binding-assertions 

From my view there should be no issue to mentions readallpropeties and writeallproperties in the table in that section for PR.

**Comment by sebastiankb** [comment]
I will provide a PR and where we can clarify if we can apply the change in the http default table.

**Comment by egekorkan** [comment]
Fixed with #853 but needs review

**Comment by sebastiankb** [comment]
PR is merged we can close this issue
