### ISSUE TITLE
Clarify read/writeXproperties in case readOnly or writeOnly properties

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#845]
When a TD has 3 `"readOnly": true` and 2 `"writeOnly":true` properties, what happens for read/writeXproperties in the following cases:
- Consumer executes the `readallproperties` operation. Does the consumer get non readable properties? (I guess no)
- Consumer executes the `readmultipleproperties` operation with names of non readable properties. Does the Consumer get only the readable properties or an error if possible?
- Consumer executes the `writeallproperties` or `writemultipleproperties`  operation with names and values of non writeable properties. Would only the writeable properties will be actually writen to in the Exposed Thing? 

I think that these cases should be made clear somehow.

**Comment by egekorkan** [comment]
@mlagally this issue is present also in WoT Architecture, Table 1

**Comment by sebastiankb** [comment]
recommend to address this in the next charter. Maybe also a topic for "complex interaction" discussion.

**Comment by mlagally** [comment]
The "writeOnly" properties cause a lot of problems, I suggest we revisit them. See also the discussion in https://github.com/w3c/wot-architecture/issues/412

**Comment by sebastiankb** [comment]
PR is merged we can close this issue
