### ISSUE TITLE
Reference to semantic processing

### ISSUE THREAD

**Issue by takuki** [w3c/wot-thing-description#846]
In section 5.3.2 Data Schema Vocabulary Definitions. it says:

> for details about semantic processing, please refer to the documentation under the namespace IRIs, e.g., https://www.w3.org/2019/wot/td.

Now that appendix section JSON-LD Context Usage describes context files and ontologies, the above sentence also should point to the appendix section D.

**Comment by sebastiankb** [comment]
@takuki will provide a PR for this issue

**Comment by sebastiankb** [comment]
PR is merged, we can close this issue
