### ISSUE TITLE
[Editorial] Implementation report uses non-static links and missing contributor

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#851]
The [CR version of TD](https://www.w3.org/TR/2019/CR-wot-thing-description-20191106/) (with a static link) still references to the implementation report with a non-static link, i.e. https://w3c.github.io/wot-thing-description/testing/report.html

I am guessing that it is meant to be like since the implementation report can be updated until PR version but it is hardcoded [here](https://github.com/w3c/wot-thing-description/blob/master/index.template.html#L13).

Also, the name of Victor Charpeany, who is an editor in the TD document is not listed in the implementation report as a contributor.

**Comment by egekorkan** [comment]
I can add Victor as contributor but I don't have control over how the static version of the report is generated during the publication process. So someone has to generate a static version of the report that we can link in the TD spec. Any thoughts @ashimura ?

**Comment by sebastiankb** [comment]
I think we should freeze the report for PR transition  and provide a static link.
@kaz what is the best practice here?
SSN seems to use also github for it https://www.w3.org/TR/vocab-ssn/

**Comment by takuki** [comment]
In 2/28 TD telecon, Kaz suggested we can create separate sub-folder for new implementation report with new URI.

**Comment by takuki** [comment]
Ege was asked to create a separate issue to discuss who we should credit in the implementation report.
