### ISSUE TITLE
Figures need to remove at-risk items for PR

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#857]
See issue 1 for https://github.com/w3c/wot-thing-description/pull/856.
Basically, PNG files were checked in for the figures that include at-risk items such as the CertSecurityScheme.   The auto-generated figures correctly omit these but the current PNG images still include them.  Unfortunately source files for the manually edited figures (eg SVG files) do not seem to have been checked in so I can't edit them...

**Comment by vcharpenay** [comment]
sources are in a .pptx file: [`/images/uml-overview.pptx`](https://github.com/w3c/wot-thing-description/blob/master/images/uml-overview.pptx). I am not sure why I put it there in the first place but it seems reasonable now to move it to `/visualization` for future work.

**Comment by sebastiankb** [comment]
@mmccool I think, we can close this issue since we merged this PR here https://github.com/w3c/wot-thing-description/commit/67d4d42c92d1ba27d23ba642f7226995158ad786

**Comment by sebastiankb** [comment]
close this issue since PR above was merged
