### ISSUE TITLE
Update ontology files on github.io and w3.org

### ISSUE THREAD

**Issue by vcharpenay** [w3c/wot-thing-description#868]
After PR #744 was merged, the Turtle and HTML files in [`/ontology`](https://github.com/w3c/wot-thing-description/blob/master/ontology/) should have been deployed on github.io. It is not the case, though. If I go e.g. to https://w3c.github.io/wot-thing-description/ontology/td.html, I still get the old version. @ashimura, do you have an explanation, maybe? Does the commit have to be tagged or branched?

Moreover, I thought the w3.org server was configured to redirect to github.io for the `2019/wot` ontology namespaces. After I checked, it seems it is not the case either. It means that all ontology files must be copied there as well*.

(*) note that after merging the PR, `hyperm.ttl` and `hyperm-html` were renamed to `hctl.ttl` and `hctl.html`, respectively. The original prefix was a source of confusion.

**Comment by ashimura** [comment]
I think there are two questions here:

1. synchronization between github.com and gitbub.io

2. changing the filename on the GitHub side for hypermedia namespace from hypermedia.ttl and hyperm.html to hctl.ttl and hctl.html

As for #1 above, I think we need to wait for a while, and it seems it's already updated now.

As for #2 above, we made a decision based on the discussion for [https://github.com/w3c/wot-thing-description/issues/432#issuecomment-493326214](Issue 432) and I'm still not sure if we really need to change the filenames. If we need to do so, I can change the redirection setting but let's discuss this during the main call today (Dec-11).

**Comment by vcharpenay** [comment]
> As for 1 above, I think we need to wait for a while, and it seems it's already updated now.

the files still differ. The file [`td.html` on w3c.github.io](https://w3c.github.io/wot-thing-description/ontology/td.html) should have the same content as [`td.html` in branch `master`](https://github.com/w3c/wot-thing-description/blob/master/ontology/td.html).

> As for 2 above, we made a decision based on the discussion for Isue 432 and I'm still not sure if we really need to change the filenames.

I understand. If need be, I will revert that change. My hope was that redirection keeps working even after this renaming, thanks to a symbolic link I added from the old file. The problem I have is at a different level, though: when I request one of the WoT namespace URIs, I don't get a 30X response but a plain 200. For some reason, I thought the action that followed #432 had been cancelled because of that response code. If redirection still works as specified in that issue, we can end the discussion here (regarding that item).

**Comment by mmccool** [comment]
Given that we are about to do a PR transition, and my understanding is that this does not change the text of the document itself, we will defer this and merge it only if necessary during the PR publication process.

**Comment by ashimura** [comment]
BTW, @vcharpenay , it seems the symbolic link from [hyperm.html](https://github.com/w3c/wot-thing-description/blob/master/ontology/hyperm.html) to ontology/hctl.html is broken.

Probably it should be simply hctl.html (instead of ontology/hctl.html). What do you think?

**Comment by vcharpenay** [comment]
Yes! Thanks @ashimura. See c84fcdf155dfb7fa21ecfea264bd8b8ed81c77f1.

**Comment by ashimura** [comment]
Thanks, @vcharpenay !

**Comment by ashimura** [comment]
Regarding point 1 from [my comment above](https://github.com/w3c/wot-thing-description/issues/868#issuecomment-564533449), I've downloaded td.html from https://w3c.github.io/wot-thing-description/ontology/td.html and https://www.w3.org/2019/wot/td using curl, and there was no difference with the td.html file within the wot-thing-description/ontology directory on my PC.

I used the following command:
* curl -H 'Accept: text/html' https://w3c.github.io/wot-thing-description/ontology/td.html > td1.html
* curl -H 'Accept: text/html' https://www.w3.org/2019/wot/td > td2.html

So I'm wondering what you meant by "the files still differ"...

**Comment by vcharpenay** [comment]
The comparison I made was between the following files:
 - https://raw.githubusercontent.com/w3c/wot-thing-description/master/ontology/td.html
 - https://w3c.github.io/wot-thing-description/ontology/td.html

However, it turns out all changes have been finally propagated from github.com to github.io (which was not the case 5h ago from my location -- maybe CDN servers have different refresh periods depending on the user agent's origin). I'll close the issue. At least, it helped fix the symlink error. Thanks!
