### ISSUE TITLE
Automate running TD rendering script

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#883]
Changes to the TD document require to run 

`npm run render`
or
`./render.sh`

locally to get the generated `index.html`.

I wonder whether it makes sense to automate this process based on each commit.
Do we want to investigate how to do that or are there any reasons why we did not do that in the first place?

**Comment by egekorkan** [comment]
Also as you mentioned, `npm run render` does not work for windows

**Comment by takuki** [comment]
I use [cygwin](https://www.cygwin.com/) to run `npm run render` on Windows, and it runs fine.

**Comment by takuki** [comment]
During March 6th TD telecon, Daniel mentioned he can look into the feasibility. 
However, the participants noted this is not a pressing issue. See minutes [here](https://www.w3.org/2020/03/06-wot-td-minutes.html).

**Comment by sebastiankb** [comment]
what is the status here?

**Comment by danielpeintner** [comment]
I can try to setup a GitHub action as mentioned [here](https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs). Maybe we do that after FPWD.

I see 2 issue:
1. We need to test with the official repo and can not easily play around without (I will look into whether it can be tested with a fork too)
2. We need to add credentials since after successfully rendering we need to push the update to the repo (see [here](https://github.com/marketplace/actions/update-files-on-github))

@ashimura I wonder whether there are other W3C repos doing something similar?

**Comment by egekorkan** [comment]
It would good to know what kind of GitHub payment plan W3C has since our builds will consume minutes that is shared by the entire W3C organization in GitHub. See https://github.com/pricing

**Comment by sebastiankb** [comment]
is this something what we can simple do as [GitHub Actions](https://github.com/w3c/wot-thing-description/actions/new)?

**Comment by danielpeintner** [comment]
I think both can work, Travis and GitHub actions.

I noticed that the render script causes some _noise_ after each run (e.g., always updating SVG images etc). Not sure what we could do about that. If I work on a PR without changing SVG details I simply don't commit those changes. A script can not do so but that might be a non-issue...

**Comment by danielpeintner** [comment]
@JKRhb I recall you mentioned that you want to work on automating the render process. Is this correct? I do not find any issue / mentioning anywhere. Thanks for any feedback!

**Comment by JKRhb** [comment]
> @JKRhb I recall you mentioned that you want to work on automating the render process. Is this correct? I do not find any issue / mentioning anywhere. Thanks for any feedback!

I think we discussed this in the last TD call, but arrived at the conclusion that we wanted to use a pre-commit hook instead? I think @relu91 wanted to create a PR for that.

**Comment by sebastiankb** [comment]
I propose to close this issue since for TD2.0 we should re-design the spec generation

**Comment by sebastiankb** [comment]
from today's TD call, decided to close this issue
