### ISSUE TITLE
[question][behavior][testing] Should writing to an observable property trigger new values being pushed

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#888]
From the Consumer perspective, if the Consumer writes to a property while also observing it, should it definitely get a notification of the value it wrote? For a Thing implemented by node-wot, it is the case but can this be a guaranteed behavior? 
This is an interesting case for testing since at the moment we cannot test event affordances of a Thing automatically since the Consumer does not know how to trigger them. However, the observability of a writable property can be tested if the previous question is valid. 
There were short discussions on whether writing and then reading should return the written value and it was decided that it cannot be guaranteed since a process can change the property value in the meantime. However, I think that this question is different.

P.S. This issue can be moved to wot-testing as well.

**Comment by takuki** [comment]
During April 3 TD teleconference (see minutes [here](https://www.w3.org/2020/04/03-wot-td-minutes.html)) the following arguments were made.

- There should be a notification for every update including the update made by the write operation.
- CoAP creates notification for every update. The behavior may depend on protocols. 
- TD spec could clarify this in Section 8 (Behavioral Assertions).
  - Looser approach works better if we decide to make clarification. In other words, we should not make too strict assumptions.

**Comment by egekorkan** [comment]
Above the title at https://w3c.github.io/wot-thing-description/#sec-op-data-schema-mapping and below the table, we will make this clear and say that the property change can come later or not at all although that is an unusual behavior.

**Comment by sebastiankb** [comment]
from today's TD call:
- there is no guarantee that new values are pushed
- the TD spec should provide information about this situation
- @egekorkan will provide a PR
