### ISSUE TITLE
Evaluate AsyncAPI

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#893]
Similar to OpenAPI, there is an initiative for asynchronous APIs called [AsyncAPI](https://www.asyncapi.com/). Their specification can help us regarding the new EventAffordance related topics. They also have examples for oAuth2, linking data schemas which are JSON Schemas.
I think that we had evaluated Open API in the beginning and used their ideas for the security schemes and this could be also helpful.

**Comment by egekorkan** [comment]
An early version of AsyncAPI generation is available in the TD Playground via this PR https://github.com/thingweb/thingweb-playground/pull/161 and it is deployed. (Also on [npm](https://www.npmjs.com/package/@thing-description-playground/td_to_asyncapi)). Here are our findings:

- We are doing only MQTT at the moment since there wasn't enough time to test other protocols.
- The AsyncAPI specification seems to be focused more on broker-based protocols.
- There is no granular security like in TD
- We need to explore how WS based TDs look like so that we can think of how an AsyncAPI document will look like.
- They talk about HTTP streaming and other event streaming protocols. We have not explored such protocols (like Kafka) in Plugfests yet.

**Comment by egekorkan** [comment]
Async API has published a nice tutorial on describing a websocket API: https://www.asyncapi.com/blog/websocket-part2

They are also protocol agnostic when it comes to many aspects so definitely lots of things to learn for  our eventing issues

**Comment by sebastiankb** [comment]
from today's TD call:
- decided to close since it is not directly relevant for the TD
- however, should be considered in the binding TF 
- maybe also by the Profile discussion (SSE and WebHooks) @mlagally
