### ISSUE TITLE
Semantic information in TDTs

### ISSUE THREAD

**Issue by kolotu** [w3c/wot-thing-description#898]
If you consider a TDT to describe a class of Thing Descriptions, you probably want to allow to reuse one TDT for multiple TDs that are very similar, but do not necessarily share all properties defined in the TDT.
Therefore it might be practical to define some semantic vocabulary for the TDT to describe whether a property is i.e. mandatory in every TD instance, or optional.

In Eclipse Vorto there is vocabulary that covers that adds semantic information to the defined properties:
- mandatory
- optional 
- extension (the property extends a supertype with more metadata)
- breakable (calling the operation can lead to a fault status)
- multiple (this property can also be a list)

See below for a complete figure showing the Vorto vocabulary and see [here](https://github.com/eclipse/vorto/blob/development/docs/vortolang-1.0.md) for further information about vortolang
![image](https://user-images.githubusercontent.com/56577255/80707810-e2300680-8aea-11ea-8152-0e4ed2df7619.png)

**Comment by sebastiankb** [comment]
Many thanks for this input. We should evaluate the semantic equivalence to the features

-     mandatory / optional   
-     extension (the property extends a supertype with more metadata)
-     breakable (calling the operation can lead to a fault status)
-     multiple (this property can also be a list)

Maybe, mandatory / optional  can be managed via Shape? 

@vcharpenay can you evaluate those points?

**Comment by vcharpenay** [comment]
@kolotu, can you elaborate on the meaning of `breakable`? It seems to me that it's not specific to class definitions (TDTs) but more something device descriptions (TD documents) could include.

**Comment by vcharpenay** [comment]
From the point of view of RDF, the TD model is simply a [SHACL](https://www.w3.org/TR/shacl/) shape, that is, a schema over an RDF graph (see [`td-validation.ttl`](https://github.com/w3c/wot-thing-description/blob/master/validation/td-validation.ttl)). SHACL is a quite versatile schema language, so it is always possible to create TDTs as SHACL shapes that are more restrictive than the generic one.

The example below gives a shape that requires a certain TD to have a `temperature` property:

```json
{
  "@context": {
    "@vocab": "http://www.w3.org/ns/shacl#",
    "td": "https://www.w3.org/2019/wot/td#"
  },
  "@id": "urn:ex:TemperatureThingTemplate",
  "@type": "NodeShape",
  "property": {
    "path": "td:hasPropertyAffordance",
    "minCount": 1,
    "maxCount": 1,
    "node": {
      "@type": "NodeShape",
      "property": {
        "path": "td:name",
        "hasValue": "temperature"
      }
    }
  }
}
```

You can see that it uses `minCount` and `maxCount` which one can use to emulate `optional` and `multiple`.

**Comment by vcharpenay** [comment]
It is also possible to emulate `extension` by stating that a TDT is the conjunction of some shape **and** its parent. Here is another example, where the above shape is "extended" to restrict the temperature value to the interval [-40,40].

```json
{
  "@context": {
    "@vocab": "http://www.w3.org/ns/shacl#",
    "jsonschema": "https://www.w3.org/2019/wot/json-schema#"
  },
  "@id": "urn:ex:RestrictedTemperatureAffordance",
  "and": [
    "urn:ex:TemperatureAffordance",
    {
      "property": {
        "path": "jsonschema:minimum",
        "hasValue": -40
      },
      "property": {
        "path": "jsonschema:maximum",
        "hasValue": 40
      }
    }
  ]
}
```

In fact, SHACL defines [many more constraints](https://www.w3.org/TR/shacl/#core-components) than just this 'and' restriction. It roughly has the same expressiveness as JSON schema.

**Comment by vcharpenay** [comment]
You can see that SHACL shape definitions  are a bit verbose. It would of course be better to simply define TDs as if they were templates and add a few keywords. This is the approach of schema.org to define [`ProductModel`s](https://schema.org/ProductModel) as if they were [`Product`s](https://schema.org/Product).

But I think it would be good to at least provide some equivalence with SHACL to have a clear semantics for each keyword we add to TDTs.

**Comment by kolotu** [comment]
@vcharpenay `breakable` describes that the invocation of the operation could lead to a fault state - similar to the `throws Exception` method signature in Java.
Breakable does not provide further details about the potential fault state, as that is more device-specific.

**Comment by sebastiankb** [comment]
just for information: Thing Description Template (TDT) will be called as Thing Model in the future

**Comment by egekorkan** [comment]
Given that Thing Models are properly implemented, closing
