### ISSUE TITLE
[TF-TD] href in DataSchema

### ISSUE THREAD

**Issue by mariapoveda** [w3c/wot-thing-description#9]
Is there a reason to keep the same attribute for indicating the Link URI and the Data Schema possible XML schema? I think there  are two different meanings (semantics) being mixed in one attribute. I would rename the one in DataSchema maybe "schemaURI"?

**Comment by sebastiankb** [comment]
The semantics should be the same for href: href is just a common used term to make a pointer by a URI. 
But you are right that we need a more detail discussion about this, especially about the usage. In the past we used / embed only JSON Schema definitions and href is never used for pointing another schema language. We should discuss this in a breakout session in Düsseldorf.

**Comment by sebastiankb** [comment]
href is not considered anymore in the latest version of TD. I will close this issue.
