### ISSUE TITLE
Thing Model of an SDF/OneDM Example

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#903]
This is a first start to design a TDT of an OneDM Example that can be found [here](https://github.com/mjkoster/ODM-Examples/blob/master/test-definitions/switch-enum-type.sdf.json).

```json
{
    "@context": "https://www.w3.org/2019/wot/td/v1",
    "@type": "ThingTemplate",
    "title": "Example file for ODM Simple JSON Definition Format",
    "new:version": "20190424",
    "new:copyright": "Copyright 2019 Example Corp.\n        All rights reserved.",
    "new:license": "http://example.com/license",
    "id": "http://example.com/capability/odm",
    "actions": {
        "On": {"description": "Action to turn the switch on"},
        "Off": {"description": "Action to turn the switch off"}
    },
    "properties": {
        "State": {
            "description": "The state of the switch, whether on or off",
            "type": "string",
            "oneOf": [
                {
                    "type": "string",
                    "const": "on",
                    "description": "The on state"
                },
                {
                    "type": "string",
                    "const": "off",
                    "description": "The off state"
                }
            ]
        }
    }
}
```

Note that vocabularies that have the **new:** prefix are not yet in the TD namespace and maybe can be considered to be new candidates for the new TD version. I know we already have the `version` term, but it is intended for TD instances. That needs discussion if we maybe introduce the sub-term `template` in the existing TD version container to have `"version":{"template": "20190424"}`.

What is definitely missing in TD / TDT so far is the XPointer feature to point to some existing definitions like in the OneDM example (e.g., StateData). But also this is already discussed and it is expected to be supported soon in TD / TDT (see issue #604 and #307). 

Clarification is also needed about the [odmObject](https://github.com/one-data-model/language/blob/master/sdf.md#odmobject) feature which currently cannot be expressed in TDT but in SHACL (also see #898).

**Comment by egekorkan** [comment]
Given that license is a URI anyways, in the current specification it can be described with links vocabulary. An example below:
```jsonc
...
"links": [{
    "rel": "license",
    "href": "http://example.com/license",
    "type": "text/html"
}]
...
```

Same can be done for copyright with the `"rel":"copyright"` if the copyright is available somewhere else. If it needs to be embedded into the TD, we would need a new keyword. These Link Relation types are already standardized at IANA (https://www.iana.org/assignments/link-relations/link-relations.xhtml).

Regarding version, I would support the addition of different keys in the version object. `instance` that we already have would denote the version of a concrete TD instance and there could be hardware, firmware etc. However, having a TD that has version key but not the instance key inside it would make it invalid and be a breaking change.

**Comment by danielpeintner** [comment]
Please find an[ initial comparison](https://danielpeintner.github.io/wot-pages/sdf/) between SDF and TD (slightly different to the example given by @sebastiankb )

**Comment by takuki** [comment]
> This is a first start to design a TDT of an OneDM Example that can be found [here](https://github.com/mjkoster/ODM-Examples/blob/master/test-definitions/switch-enum-type.sdf.json).

@sebastiankb , the link to OneDM example in the above appears somehow broken.

**Comment by danielpeintner** [comment]
> > This is a first start to design a TDT of an OneDM Example that can be found [here](https://github.com/mjkoster/ODM-Examples/blob/master/test-definitions/switch-enum-type.sdf.json).
> 
> @sebastiankb , the link to OneDM example in the above appears somehow broken.

I think the file has been moved (or removed) but I did copy it to left column in [SDF example](https://danielpeintner.github.io/wot-pages/sdf/).

It was similar to the example [here](https://github.com/mjkoster/ODM-Examples/blob/master/sdf/sdf.md#example-definition) but not 100% the same.

**Comment by sebastiankb** [comment]
It seems that the files have been moved to another folder. I think this is the new location of the example [here](https://github.com/mjkoster/ODM-Examples/blob/master/examples/switch-enum-type.sdf.json).

@mjkoster can you confirm this

**Comment by mjkoster** [comment]
Yes, I'm sorry about that. I refactored the files in my repo to prepare a set of consistent examples for OneDM contribution. You have the right location.

**Comment by mjkoster** [comment]
here are some more
https://github.com/mjkoster/ODM-Examples/tree/master/examples

**Comment by sebastiankb** [comment]
after a renewed consideration the question arises whether such information like license and copyright should be declared again in a TD/TDT instance, since this information is already provided at the origin of the OneDM SDF definition. Assuming we will also have a OneDM SDF representation in RDF hosted by iotschema.org, we can integrate OneDM definitions using the @type like here: 

```json
{
    "@context": [
        "https://www.w3.org/2019/wot/td/v1",
        {"iot": "http://iotschema.org/capability/odm"}
    ],
    "title": "Switch based on oneDM /iotschema.org definition",
    "@type": [
        "ThingTemplate",
        "iot:odmSwitch"
    ],
    "actions": {
        "On": {"description": "Action to turn the switch on"},
        "Off": {"description": "Action to turn the switch off"}
    },
    "properties": {
        "State": {
            "description": "The state of the switch, whether on or off",
            "type": "string",
            "oneOf": [
                {
                    "type": "string",
                    "const": "on",
                    "description": "The on state"
                },
                {
                    "type": "string",
                    "const": "off",
                    "description": "The off state"
                }
            ]
        }
    }
}
```

**Comment by sebastiankb** [comment]
The definition 
```json
"oneOf": [
                {
                    "type": "string",
                    "const": "on",
                    "description": "The on state"
                },
                {
                    "type": "string",
                    "const": "off",
                    "description": "The off state"
                }
            ]
```

can be also replaced by 
```
"enum" :["on", "off"]
```

**Comment by mlagally** [comment]
This is a follow-up of a WoT-T2TRG conversation:
If we look at the descriptions in the example the semantics of the "on" / "off" states are currently expressed in the "description", which is a human readable representation. 
If we imagine a SDF definition of a switch with constants in a different language (e.g. German: "an", "aus") we need a human to do the mapping. It would be nice to have a way for expressing that the "on" and "an" operation have the same behavior.

**Comment by danielpeintner** [comment]
> It would be nice to have a way for expressing that the "on" and "an" operation have the same behavior.

I believe we can already do so. We have the type [MultiLanguage](https://w3c.github.io/wot-thing-description/#multilanguage) that is used by titles and descriptions.

```
{
  "type": "string",
  "oneOf": [
    {
      "descriptions": {
        "en": "switch on",
        "de": "schalter an"
      },
      "type": "string",
      "const": "on"
    },
    {
      "descriptions": {
        "en": "switch off",
        "de": "schalter aus"
      },
      "type": "string",
      "const": "off"
    }
  ]
}
```

Having said that, the value that is used is still `"on"`. @mlagally  Did you mean to change also `on` to `an`?  One can do so by extending the `oneOf` construct but I don't think this is what is usually done...

**Comment by sebastiankb** [comment]
From today's TD call:
- we will create some examples from Zigbee
- proposal is to have a SDF example (on/off, light control, etc.) which is generated to TM and TD
- @mjkoster will provide this example

**Comment by JKRhb** [comment]
I am currently working on a converter between WoT and SDF written in Python (see [this repository](https://github.com/JKRhb/sdf-wot-converter-py)). So far, I have been able to cover most of the SDF specification for transforming SDF models into WoT Thing Models. You can try it out either on the command line or using https://sdf-wot-converter.herokuapp.com/. I also set up a [repository](https://github.com/JKRhb/onedm-playground-wot-tm) that gets automatically updated with converted models from the [oneDm playground](https://github.com/one-data-model/playground). I would be glad if you could take a look at it and try it out for yourselves :) Any kind of feedback is highly appreciated!

Following in part the comparison by @danielpeintner, the first example from the SDF draft

```json
{
  "info": {
    "title": "Example file for OneDM Semantic Definition Format",
    "version": "2019-04-24",
    "copyright": "Copyright 2019 Example Corp. All rights reserved.",
    "license": "https://example.com/license"
  },
  "namespace": {
    "cap": "https://example.com/capability/cap"
  },
  "defaultNamespace": "cap",
  "sdfObject": {
    "Switch": {
      "sdfProperty": {
        "value": {
          "description": "The state of the switch; false for off and true for on.",
          "type": "boolean"
        }
      },
      "sdfAction": {
        "on": {
          "description": "Turn the switch on; equivalent to setting value to true."
        },
        "off": {
          "description": "Turn the switch off; equivalent to setting value to false."
        },
        "toggle": {
          "description": "Toggle the switch; equivalent to setting value to its complement."
        }
      }
    }
  }
}
```

is currently translated by my converter to this TM:

```json
{
  "@context": [
    "http://www.w3.org/ns/td",
    {
      "cap": "https://example.com/capability/cap",
      "sdf": "https://example.com/sdf"
    }
  ],
  "@type": "tm:ThingModel",
  "title": "Example file for OneDM Semantic Definition Format",
  "description": "Copyright 2019 Example Corp. All rights reserved.",
  "links": [
    {
      "href": "https://example.com/license",
      "rel": "license"
    }
  ],
  "version": {
    "model": "2019-04-24"
  },
  "sdf:defaultNamespace": "cap",
  "actions": {
    "Switch_on": {
      "sdf:jsonPointer": "#/sdfObject/Switch/sdfAction/on",
      "description": "Turn the switch on; equivalent to setting value to true."
    },
    "Switch_off": {
      "sdf:jsonPointer": "#/sdfObject/Switch/sdfAction/off",
      "description": "Turn the switch off; equivalent to setting value to false."
    },
    "Switch_toggle": {
      "sdf:jsonPointer": "#/sdfObject/Switch/sdfAction/toggle",
      "description": "Toggle the switch; equivalent to setting value to its complement."
    }
  },
  "properties": {
    "Switch_value": {
      "sdf:jsonPointer": "#/sdfObject/Switch/sdfProperty/value",
      "description": "The state of the switch; false for off and true for on.",
      "type": "boolean"
    }
  }
}
```

The name of nested definitions like `sdfObject` or `sdfThing` is used as a prefix while the original location of the affordance is included as a `sdf:jsonPointer` field. Like fields for which no WoT equivalent exists (like `$comment`) its name is prefixed with `sdf:`.

Regarding the WoT -> SDF direction there are still a couple of blank spots that probably need a bit more discussion (like `forms`, `links`, and `securityDefinitions`). Roundtripping from SDF to WoT TM and back again is mostly already possible, however.

**Comment by relu91** [comment]
_Disclaimer I don't really know SDF_

What feels odd to me is the strategy used to map affordance names. I would map each object in one TM (cause we can't express sub Thing Models in one file) and use the `sdf:Object` properties as titles of those TMs. I would like to see something like this:
```js
{
  "@context": [
    "http://www.w3.org/ns/td",
    {
      "cap": "https://example.com/capability/cap",
      "sdf": "https://example.com/sdf"
    }
  ],
  "@type": "tm:ThingModel",
  "title": "Switch",
  "description": "Example file for OneDM Semantic Definition Format", // notice I removed the copyright notice. I think the sdf:title fits better here
  "links": [
    {
      "href": "https://example.com/license",
      "rel": "license"
    }
  ],
  "version": {
    "model": "2019-04-24"
  },
  "sdf:defaultNamespace": "cap",
  "actions": {
    "on": {
      "sdf:jsonPointer": "#/sdfObject/Switch/sdfAction/on",
      "description": "Turn the switch on; equivalent to setting value to true."
    },
    "off": {
      "sdf:jsonPointer": "#/sdfObject/Switch/sdfAction/off",
      "description": "Turn the switch off; equivalent to setting value to false."
    },
    "toggle": {
      "sdf:jsonPointer": "#/sdfObject/Switch/sdfAction/toggle",
      "description": "Toggle the switch; equivalent to setting value to its complement."
    }
  },
  "properties": {
    "value": {
      "sdf:jsonPointer": "#/sdfObject/Switch/sdfProperty/value",
      "description": "The state of the switch; false for off and true for on.",
      "type": "boolean"
    }
  }
}

```

**Comment by JKRhb** [comment]
> What feels odd to me is the strategy used to map affordance names.

You are right, this is something that definitely requires a bit more discussion. While mapping individual objects to their own TMs is certainly a cleaner approach, the question arises how to deal with SDF models that have multiple levels of nesting. For example, you can define an SDF model like the following:

```json
{
  "info": {
    "title": "SDF example with nesting",
    "version": "2019-04-24",
    "copyright": "Copyright 2019 Example Corp. All rights reserved.",
    "license": "https://example.com/license"
  },
  "sdfProperty": {
    "status": {
      "type": "boolean"
    }
  },
  "sdfObject": {
    "ExampleObject": {
      "sdfProperty": {
        "status": {
          "type": "boolean"
        }
      }
    }
  },
  "sdfThing": {
    "ExampleThing": {
      "sdfObject": {
        "NestedObject": {
          "sdfProperty": {
            "status": {
              "type": "boolean"
            }
          }
        }
      },
      "sdfThing": {
        "NestedThing": {
          "sdfObject": {
            "NestedObject": {
              "sdfProperty": {
                "status": {
                  "type": "boolean"
                }
              }
            }
          }
        }
      }
    }
  }
}
```

In this case, you have both a property at the top level and properties in `sdfObject`s that are included in `sdfThing`s (which allow for any depth of nesting). I guess you could map every object to its own file and then include `subThing` links in the "main" TM (and probably nested sub-TMs?). This would make conversion between SDF and WoT not as straightforward, however, as well as conversion from TMs to TDs.

I guess the most elegant solution would be to allow for nested definitions in TMs/TDs themselves (like the components mentioned by @mmccool in #1177).

**Comment by JKRhb** [comment]
Update: I recently published a major new version of my [SDF WoT converter](https://github.com/JKRhb/sdf-wot-converter-py), which now follows the linking approach discussed in issues like #1177 and https://github.com/w3c/wot-thing-description/issues/1407. 
As SDF now also supports affordances at the `sdfThing` level (in its latest Editor's draft), mapping between SDF models and TMs/TDs is now relatively straightforward, as you can convert every `sdfThing` to a TM/TD with links to submodels/subthings. The converter also supports SDF ⇿ TD conversion via a new concept called [mapping files](https://datatracker.ietf.org/doc/html/draft-bormann-asdf-sdf-mapping-00.txt), where all definitions not mappable to an SDF model are included via JSON pointers. You can try out the converter and most of its functionality in the current version of the web interface (https://sdf-wot-converter.herokuapp.com/).

I would be very grateful for any feedback :)

**Comment by egekorkan** [comment]
I have given the converter a try. It seems to work well for the TM <-> SDF but other combinations do not?

**Comment by egekorkan** [comment]
By the way, can we close this issue? Given that the examples are available at the convertor by @JKRhb
