### ISSUE TITLE
Introduction is missing security component

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#904]
The introduction of the document says:
> A TD instance has four main components: textual metadata about the Thing itself, a set of Interaction Affordances that indicate how the Thing can be used, schemas for the data exchanged with the Thing for machine-understandability, and, finally, Web links to express any formal or informal relation to other Things or documents on the Web. 

However, security related information is another important block of the TD and I think it would be good to include it here.

**Comment by takuki** [comment]
This is a simple fix. TD TF can work on it after the rendering script works again.

**Comment by sebastiankb** [comment]
agree, this is editorial
