### ISSUE TITLE
Missing triple resolution in JSON-LD playground for properties forms

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#905]
There seems some not expected behavior when we want to see the triples of the forms of a property. Please see the following example in the JSON-LD playground and check the N-Quads tab: [example](https://json-ld.org/playground/#startTab=tab-nquads&json-ld=%7B%22%40context%22%3A%5B%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Ftd%2Fv1%22%5D%2C%22id%22%3A%22urn%3Adev%3Aops%3A32473-WoTLamp-1234%22%2C%22title%22%3A%22MyLampThing%22%2C%22securityDefinitions%22%3A%7B%22basic_sc%22%3A%7B%22scheme%22%3A%22basic%22%2C%22in%22%3A%22header%22%7D%7D%2C%22security%22%3A%5B%22basic_sc%22%5D%2C%22properties%22%3A%7B%22status%22%3A%7B%22type%22%3A%22string%22%2C%22forms%22%3A%5B%7B%22href%22%3A%22https%3A%2F%2Fmylamp.example.com%2Fstatus%22%2C%22htv%3Amethod%22%3A%22GET%22%7D%5D%7D%7D%7D&frame=%7B%7D&context=%7B%7D).

The triples for the forms are missing such as "htv:method". However, when I change the definition in the context such as [here](https://json-ld.org/playground/#startTab=tab-nquads&json-ld=%7B%22%40context%22%3A%5B%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Ftd%2Fv1%22%2C%7B%7D%5D%2C%22id%22%3A%22urn%3Adev%3Aops%3A32473-WoTLamp-1234%22%2C%22title%22%3A%22MyLampThing%22%2C%22securityDefinitions%22%3A%7B%22basic_sc%22%3A%7B%22scheme%22%3A%22basic%22%2C%22in%22%3A%22header%22%7D%7D%2C%22security%22%3A%5B%22basic_sc%22%5D%2C%22properties%22%3A%7B%22status%22%3A%7B%22type%22%3A%22string%22%2C%22forms%22%3A%5B%7B%22href%22%3A%22https%3A%2F%2Fmylamp.example.com%2Fstatus%22%2C%22htv%3Amethod%22%3A%22GET%22%7D%5D%7D%7D%7D&frame=%7B%7D&context=%7B%7D) the triples appears as expected. 

Any ideas?

**Comment by pchampin** [comment]
It seems to be a jsonld.js problem. @gkellogg's [Ruby implementation](http://rdf.greggkellogg.net/distiller?command=serialize&format=jsonld&output_format=nquads) gives the expected result. @dlongley @dlehn any idea?

**Comment by dlongley** [comment]
@davidlehn -- seems related to: https://github.com/digitalbazaar/jsonld.js/issues/394

**Comment by gkellogg** [comment]
@dlongley @davidlehn, this is up for discussion on an upcoming joint meeting at TPAC between WoT and JSON-LD working groups, can we either resolve this or update the status?

**Comment by vcharpenay** [comment]
looking again at the example on the playground, it seems the problem has changed: statements about the form are now present but IRIs are not correctly resolved.

Expected:
```
<urn:dev:ops:32473-WoTLamp-1234> <http://purl.org/dc/terms/title> "MyLampThing" .
<urn:dev:ops:32473-WoTLamp-1234> <https://www.w3.org/2019/wot/td#hasPropertyAffordance> _:b0 .
_:b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://www.w3.org/2019/wot/json-schema#StringSchema> .
_:b0 <https://www.w3.org/2019/wot/json-schema#propertyName> "status" .
_:b0 <https://www.w3.org/2019/wot/td#hasForm> _:b1 .
_:b1 <http://www.w3.org/2011/http#method> "GET" .
_:b1 <https://www.w3.org/2019/wot/hypermedia#hasTarget> <https://mylamp.example.com/status> .
```

Actual (obtained when including an empty context `{}`, as pointed out by @sebastiankb):
```
<urn:dev:ops:32473-WoTLamp-1234> <http://purl.org/dc/terms/title> "MyLampThing" .
<urn:dev:ops:32473-WoTLamp-1234> <https://www.w3.org/2019/wot/td#hasPropertyAffordance> _:b0 .
_:b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://www.w3.org/2019/wot/json-schema#StringSchema> .
_:b0 <https://www.w3.org/2019/wot/json-schema#forms> _:b1 .
_:b0 <https://www.w3.org/2019/wot/json-schema#propertyName> "status" .
_:b1 <http://www.w3.org/2011/http#method> "GET" .
_:b1 <https://www.w3.org/2019/wot/json-schema#href> "https://mylamp.example.com/status" .
```

**Comment by davidlehn** [comment]
The fix from https://github.com/digitalbazaar/jsonld.js/issues/394 to handle empty scoped contexts is now live on the playground.  I'm not sure how to check if the use case here was addressed by that fix.  It does look like at least both examples produce the same output.  Are the example links out of date?  That "security" property value is expanding with the playground URL prefix.

@vcharpenay: The playground and jsonld.js code hadn't changed in quite a long time, so the behavior wouldn't have changed recently.  However, the remote context might have changed causing different output.

**Comment by vcharpenay** [comment]
The problem has indeed been fixed on the playground. Thanks!
