### ISSUE TITLE
Refer to developer documentation from a TD

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#918]
The TD should contain a field to refer to developer documentation.

**Comment by mlagally** [comment]
I filed https://github.com/w3c/wot-thing-description/issues/918 to make sure the TD TF is aware.

**Comment by mlagally** [comment]
I like this approach, it would be nice to have it in an example.
@sebastiankb:
we should define this "documentation" relationship type in the 1.1 spec.

**Comment by sebastiankb** [comment]
I started to work on the topic about relation types and created a PR for the TD spec #1034. I would be happy to receive some feedback.

**Comment by sebastiankb** [comment]
issue is addressed in the latest draft
