### ISSUE TITLE
Warning by W3C validator

### ISSUE THREAD

**Issue by shujikamitsuna** [w3c/wot-thing-description#919]
Dear Sir and Madam

This is Shuji Kamitsuna@Japan.
Thank you for the great recommendation!

The W3C validator reports the following warning in the latest published version of the Thing Description.

https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.w3.org%2FTR%2F2020%2FREC-wot-thing-description-20200409%2F

Best Regards,

**Comment by sebastiankb** [comment]
thanks for the hint.

@knimura please can you check this.

**Comment by egekorkan** [comment]
This issue has been addressed a while ago, closing.

Also, we do new checks for the new publication
