### ISSUE TITLE
Editorial issues for consolidated TD REC updates - Errata items

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#920]
see the following items

- [x] PR https://github.com/w3c/wot-thing-description/pull/914
- [ ] Issue https://github.com/w3c/wot-thing-description/issues/919
- [ ] Issue https://github.com/w3c/wot-thing-description/issues/915
- [ ] Issue https://github.com/w3c/wot-thing-description/issues/925
- [ ] Issue #942

**Comment by takuki** [comment]
I think Issue #925 should also be included.

**Comment by ashimura** [comment]
During the TD call on 5 Aug 2020, we identified issue #942 should be also included here.

**Comment by egekorkan** [comment]
All the issues linked here are addressed, closing.
