### ISSUE TITLE
streams and compound values - Issue 281 from w3c/wot

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#934]
Coming from https://github.com/w3c/wot/issues/281

There were also discussions with W3C MEIG on how to describe streams so this issue seems to be still relevant

**Comment by sebastiankb** [comment]
I think, this origin issue is outdated. Server-Sent Events can be signalized by the `subprotocol` and the plans for compound values is also addressed in this issue #307 and most likely introduced in TD 1.1
