### ISSUE TITLE
Add a class field to the TD - Issue 268 from w3c/wot

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#935]
Coming from https://github.com/w3c/wot/issues/268

There was also a similar discussion somewhere but couldn't find it

**Comment by sebastiankb** [comment]
Sounds like a topic that is covered by Thing Description Templates, right?

**Comment by sebastiankb** [comment]
based on today's TD call there was the hint that this topic may also relevant for scripting API and semantic annotations. There seems a relevant issue here: https://github.com/w3c/wot-scripting-api/issues/204

**Comment by relu91** [comment]
> Sounds like a topic that is covered by Thing Description Templates, right?

As I see it, yes. Moreover, since the TD is a JSON-LD document we have also "@type" and SHACL to possibly implement the same semantic of a `class` field. I propose closing this in favor of the discussion about TDTs.
