### ISSUE TITLE
Example 35 is incorrect or has inconsistency

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#942]
The Example 35 of the spec has the following TD:
```json
{
    "@context": "https://www.w3.org/2019/wot/td/v1",
    "id": "urn:dev:ops:32473-Thing-1234",
    "title": "WebhookThing",
    "description": "Webhook-based Event with subscription and unsubscribe form.",
    "securityDefinitions": {"nosec_sc": {"scheme": "nosec"}},
    "security": ["nosec_sc"],
    "events": {
        "temperature": {
            "description": "Provides periodic temperature value updates.",
            "subscription": {
                "type": "object",
                "properties": {
                    "callbackURL": {
                        "type": "string",
                        "format": "uri",
                        "description": "Callback URL provided by subscriber for Webhook notifications.",
                        "writeOnly": true
                    },
                    "subscriptionID": {
                        "type": "string",
                        "description": "Unique subscription ID for cancellation provided by WebhookThing.",
                        "readOnly": true
                    }
                }
            },
            "data": {
                "type": "number",
                "description": "Latest temperature value that is sent to the callback URL."
            },
            "cancellation": {
                "type": "object",
                "properties": {
                    "subscriptionID": {
                        "type": "integer",
                        "description": "Required subscription ID to cancel subscription.",
                        "writeOnly": true
                    }
                }
            },
            "uriVariables": {
                "subscriptionID": { "type": "string" }
            },
            "forms": [
                {
                    "op": "subscribeevent",
                    "href": "http://192.168.0.124:8080/events/temp/subscribe",
                    "contentType": "application/json",
                    "htv:methodName": "POST"
                },
                {
                    "op": "unsubscribeevent",
                    "href": "http://192.168.0.124:8080/events/temp/{subscriptionID}",
                    "htv:methodName": "DELETE"
                }
            ]
        }
    }
}
```

For the unsubscription, the corresponding form seems to use `uriVariables` via `"href": "http://192.168.0.124:8080/events/temp/{subscriptionID}",`. There is also the corresponding `uriVariables` object. However, there is also the cancellation object. Does it really mean that I should send the subscriptionID in the payload and in the body of the message? I am guessing that the cancellation object needs to be removed.

P.S. I think there is a related issue to this in TD but I couldn't find it. Here is one from Scripting API: https://github.com/w3c/wot-scripting-api/issues/208

**Comment by sebastiankb** [comment]
good point. 

In general, this example causes a lot of discussion (also see #812). For TD 1.1 we should definitely rework on that and make them very clear. An example from the plugfest would be good.

**Comment by sebastiankb** [comment]
in today's TD cal we chould at least fix the uriVariable issue. The errata document can cover this. #920

**Comment by sebastiankb** [comment]
I just read the related text to the example and it says:

> This can be further automated by using a TD Context Extension to include proper semantic annotations. Alternatively, one can imagine unsubscribing using the cancellation member similarly to subscription and combine this with a unsubscribeevent form that describes a POST request with payload to unsubscribe. 

That means this is an alternative solution to the `uriVariable`. I think this is confusing and I would propose to have two examples to show the alternative.

**Comment by egekorkan** [comment]
Call of 02.03: Done already, closing.
