### ISSUE TITLE
New term 'serialNumber'?

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#946]
coming from https://github.com/w3c/wot-thing-description/issues/941

From today's TD call: 
- We have to be careful to introduce such a term since it has privacy implication (similar with the id field)
- maybe we can also use the link approach for it. Have to be evaluated. 
- manufacture needs maybe to be defined

**Comment by benfrancis** [comment]
Could an existing ontology be reused for this kind of metadata?

E.g.
- https://schema.org/serialNumber
- https://schema.org/manufacturer

```
{
  "@context": [
        "https://www.w3.org/2019/wot/td/v1",
        { "s": "http://schema.org" }
    ],
    "id": "urn:dev:ops:32473-WoTLamp-1234",
    "s:serialNumber": "4CE0460D0G",
    "s:manufacturer": "Acme",
    "title": "MyLampThing",
    "securityDefinitions": {
        "basic_sc": {"scheme": "basic", "in":"header"}
    },
    "security": ["basic_sc"],
    "properties": {
        "status" : {
            "type": "string",
            "forms": [{"href": "https://mylamp.example.com/status"}]
        }
    },
    "actions": {
        "toggle" : {
            "forms": [{"href": "https://mylamp.example.com/toggle"}]
        }
    },
    "events":{
        "overheating":{
            "data": {"type": "string"},
            "forms": [{
                "href": "https://mylamp.example.com/oh",
                "subprotocol": "longpoll"
            }]
        }
    }
}
```

**Comment by sebastiankb** [comment]
I think we should include the schema.org example in Section https://w3c.github.io/wot-thing-description/#semantic-annotations-example-version-units  and make the title more generic like `Additional Basic Metadata`
