### ISSUE TITLE
New terms hardwareRevision and softwareRevision?

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#947]
coming from https://github.com/w3c/wot-thing-description/issues/941

From today's TD call: 

- both terms can be embedded in the VersionInfo container
- however, we should also check if there are some privacy and security issue like tracking risk
- we must define them as optional

**Comment by benfrancis** [comment]
As with https://github.com/w3c/wot-thing-description/issues/946#issuecomment-672915816

- https://schema.org/model
- https://schema.org/softwareVersion

```
{
  "@context": [
        "https://www.w3.org/2019/wot/td/v1",
        { "s": "http://schema.org" }
    ],
    "id": "urn:dev:ops:32473-WoTLamp-1234",
    "s:model": "Super Widget 2.0",
    "s:softwareVersion": "v4.2",
    "title": "MyLampThing",
    ...
}
```

**Comment by sebastiankb** [comment]
also see comment here https://github.com/w3c/wot-thing-description/issues/946#issuecomment-957776392
