### ISSUE TITLE
[Minor] description of observable should mention unobserveproperty (besides observeproperty)

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#950]
The description of [observable](https://w3c.github.io/wot-thing-description/#propertyaffordance) reads as follows.

"A hint that indicates whether Servients hosting the Thing and Intermediaries should provide a Protocol Binding that supports the observeproperty operation for this Property."

I think it should also mention  `unobserveproperty`

**Comment by takuki** [comment]
In TD TF call on Sept 2, the group finds this as a clarification that should be addressed in TD v1.1.
