### ISSUE TITLE
Unsubscribing and unobserving are not in default values

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#957]
The default values section do not say that `unsubscribeevent` is a default value in the `op` of an Event Affordance but `subscribeevent` is. If the defaults are filled, this results in a TD that cannot be used by a Scripting API implementation since when the `op` value is existing, its contents cannot be changed and there is no form to unsubscribe from the event.

We can also look at it from another perspective and add an assertion saying that if there is a form in the forms array with `subscribeevent` there should be a form (or the same form) with the `op` value of `unsubscribeevent`. We can say the same for observable properties, i.e. if there is `op` value of `observeproperty`, there should be also `unobserveproperty` somewhere.

**Warning:** Even though it is a small change, it is a breaking change from my point of view.

**Comment by danielpeintner** [comment]
Nice finding!

> We can also look at it from another perspective and add an assertion saying that if there is a form in the forms array with `subscribeevent` there should be a form (or the same form) with the `op` value of `unsubscribeevent`. We can say the same for observable properties, i.e. if there is `op` value of `observeproperty`, there should be also `unobserveproperty` somewhere.

I think the same applies vice-versa also meaning that if  `unsubscribeevent` is present there should be `subscribeevent` also.

> **Warning:** Even though it is a small change, it is a breaking change from my point of view

Personally I do not see it as _dangerous_ and I assume we can add an explanation saying that if _one_ is present the counterpart is present also...

**Comment by zolkis** [comment]
I think it's more like a "fixing" change than a "breaking" change.

A script could rightfully assume that if it can subscribe to something, it can also unsubscribe from it. This should be regarded as _one_ functionality with two aspects.

**Comment by takuki** [comment]
> Another question is what to do with "orphan subscriptions", e.g. a subscription record at the server that contains an address that is offline ATM or has the address changed. I guess this is impl optimization since it's protocol-dependent.

If a protocol supports heartbeat to detect connection loss, that protocol may be able to consider the subscription dead, and no explicit unsubscription may be necessary. But I agree it is a good practice to have both subscription and unsubscription at the same time.

**Comment by sebastiankb** [comment]
Regarding @takuki comment, I wonder about the scenarios like streaming data via websocket and clients can simply listen to the stream. No explicit unsubscription interaction is required to stop the listing process (the client simple stop the listening).

**Comment by egekorkan** [comment]
Same with longpoll :)

**Comment by sebastiankb** [comment]
From today's TD call:
- for each operation that is possible with a property, action or event there should be a form entry about this operation
- e.g., if there is a subscribeevent / observeproperty there should be also an unsubscribeevent / unobserveproperty 
- this is less a 'default value' topic, its more about a requirement statement
- this requirement should be provided as text in the TD spec (@relu91 and @danielpeintner will provide a proposal)

**Comment by sebastiankb** [comment]
PR is merged

**Comment by egekorkan** [comment]
In the call of 12.05, we have decided to close this issue
