### ISSUE TITLE
[multiLang] Should titles and descriptions be present in the TD after language negotation

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#959]
Coming from https://github.com/eclipse/thingweb.node-wot/issues/320

When content negotiation happens about the language of a TD document, the TD producer can deliver a TD where all the `title` and `description` elements are of the desired language. In this case, should the `titles` and `descriptions` elements stay in the TD or should they be removed or it is up to the implementation?

Since this is something specific to TDs, we can be more assertive on how something MUST be done.

Examples:
There is a TD that has the following:
```json
    "@context": [
        "https://www.w3.org/2019/wot/td/v1"
    ],
    title: "counter",
    titles: {
        "en": "counter",
        "de": "zähler",
        "it": "Contatore"
    }
```
When the language negotation happens to select `de`, should the result be the following:
```json
    "@context": [
        "https://www.w3.org/2019/wot/td/v1",
        { "@language" : "de" }
    ],
    title: "zähler",
    titles: {
        "en": "counter",
        "de": "zähler",
        "it": "Contatore"
    }
```
or should it be the following (without `titles`)
```json
    "@context": [
        "https://www.w3.org/2019/wot/td/v1",
        { "@language" : "de" }
    ],
    title: "zähler"
```

**Comment by danielpeintner** [comment]
As discussed in the original [issue](https://github.com/eclipse/thingweb.node-wot/issues/320#issuecomment-691041881) I think it is best to have the freedom to choose due to
* some use cases need more compact representations
* others are more in favor of still providing other languages

Having said that, _freedom_ often leads to expectations that are not met by one or the other implementation :-(

**Comment by gatemezing** [comment]
+1 for the first option.
What about the option with titles but removing the already selected language in the `titles` ?

**Comment by egekorkan** [comment]
@gatemezing there is also a related issue https://github.com/w3c/wot-thing-description/issues/985 
What you are saying is desired but I am not sure if the current spec version allows it.

**Comment by sebastiankb** [comment]
I'm agree with @danielpeintner comment. This should be flexible depending of the use case. `@language` just points out what is the default language of `title` and `description`. `titles` and `descriptions` can be still used to show that different languages are supported and which, e.g., can be used to switch the language of an IoT dashboard on the fly.
