### ISSUE TITLE
How to model multiple InteractionAffordances of the same nature

### ISSUE THREAD

**Issue by fennibay** [w3c/wot-thing-description#963]
In some use cases, we have things providing an array of similar functions (such as a light array having multiple lamps) which are ideally exposed as InteractionAffordances of about the same content, i.e. same semantics and data schema, slightly different protocol bindings.
 
If we take properties as an example, with today’s means we can model this as follows, which I consider somewhat ugly, especially when the number of functions and their properties grow.
 
```
    "properties": {
        "brightness1": {
            "@type": "xy:brightness",
            "type": "number",
            // ...,
        },
        "brightness2": {
            "@type": "xy:brightness",
            "type": "number",
            // ...,
        },
        "temperature1": {
            "@type": "xy:temp",
            // ...
        },
        "temperature2": {
            "@type": "xy:temp",
            // ...
        }
    }
 ```

Solution alternatives:
1. Model this as multiple things, and an overarching thing linking them together. This would violate the logical thing – physical thing mapping a bit. But would work actually. This can be further extended by having top-level thing's operations (read/write multiple/all properties) access the underlying things protocol bindings directly
2. Introduce a possibility to have an array of InteractionAffordances under an object:
 
```
    "properties": {
        "brightness": [
            {
                "@type": "xy:brightness",
                "type": "number"
                // ...,
            },
            {
                "@type": "xy:brightness",
                "type": "number"
                // ...,
            }
        ],
        "temperature": [
            {
                "@type": "xy:temp"
                // ...
            },
            {
                "@type": "xy:temp",
                // ...
            }
        ]
    }
```

Which way should we go? Is there maybe a better way?

cc @sebastiankb

**Comment by egekorkan** [comment]
I think this (without the array version) would be a valid use case for `readmultipleproperties`, for which there wasn't one until now. However, your concern seems to be on how the TD is modeled, which doesn't change by having the `readmultipleproperties` operation.

Having an array is quite undesirable at this stage since it would make Consumer implementations more difficult due to more flexibility. Also, how would we differentiate between different temperatures? It would probably be by their index in the array, which would mean getting the property (not reading) by something like `myTD.properties.temperature[0]`. It would make a Scripting API implementation code _ugly_ since we need to have code like `myThing.readProperty(temperature[0])`

**Comment by danielpeintner** [comment]
**Note 1**  I think the initial example with having types for each interaction like `"@type": "xy:brightness"` make sense and also match "how" the Scripting API core can be extended (see  `https://github.com/w3c/wot-scripting-api/issues/204):
* read all properties with given `@type` or combination of types (e.g., lamps in a given room etc)
* switch off all lamps etc
* ...

**Note 2** One can already now model composed properties like the following (not sure though whether this is desired in this case)

```
	"properties": {
		"lights": {
			"type": "object",
			"properties": {
				"brightness1": {
					"type": "number"
				},
				"brightness2": {
					"type": "number"
				}
			}
		}
	}
```

Doing so would also allow setting a certain brightness only. 
Having said that, I would rather go for a dedicated action for reading writing values a la
`invokeAction("setBrightness", { "lights": ["brightness1", "brightness2"], "value": 12});`
_As said, I am not sure whether composed types make sense at all in this case!_

**Comment by fennibay** [comment]
Thanks for the quick replies.

@egekorkan the second alternative (arrays of InteractionAffordances) would definitely make consumer interface more complex, you're right. And I imagined an array indexing scheme, as well.

Regarding `readmultipleproperties`, when I think further, I don't see how it's relevant. This operation can be defined on a Thing and not on an InteractionAffordance, e.g if I wanted to read brightness and temperature at the same time. My issue is rather modeling multiple brightness properties in a single property, and not model them as multiple properties and access with a single `readmultipleproperties` operation.

@danielpeintner I understand that in this example you don't really have composed properties, but just a property with a complex data schema comprising multiple brightness properties. I don't really have the granularity to access a single brightness here. Or do I miss something?

After discussions, I favor the first alternative more, where the top-level thing is referring to subordinate things via `links`. **Optionally** I could introduce properties in the top-level thing, which compose the subordinate things' according properties, as follows:

![composite_thing drawio](https://user-images.githubusercontent.com/30393701/93323736-4858c400-f815-11ea-9a47-daeadb9c9380.png)

But here it's not clear to me how to fill in the `forms` of the top-level property. Can I have multiple forms with `op: "readproperty"` under a property?

**Comment by egekorkan** [comment]
_I_ think in general it is a bad idea to split a physical Thing into multiple TDs. Having a simple but an _ugly_ TD with multiple properties is much more understandable for machines and humans if we talking about 1-5 similar properties. If you have actually a Thing that has 100 similar property names, we should of course try think of an elaborate approach.

> Can I have multiple forms with op: "readproperty" under a property?

Yes you can :) The consumer needs to know which one to pick though

**Comment by relu91** [comment]
> After discussions, I favor the first alternative more, where the top-level thing is referring to subordinate things via links. Optionally I could introduce properties in the top-level thing, which compose the subordinate things' according properties, as follows:

I actually don't mind splitting a physical thing into different *subthings* if it is composed of logical different physical components (i.e. different lights).  We used the same approach in our projects and it worked quite well. Furthermore, I think this is the only reasonable approach if you cannot modify the API of the described device. The options seems a bit "hacky". 

>I think in general it is a bad idea to split a physical Thing into multiple TDs. Having a simple but an ugly TD with multiple properties is much more understandable for machines and humans if we talking about 1-5 similar properties.

I am on the opposite, I prefer small linked documents that one big document with 5 similar properties. 

Another topic is how we can improve the compositional mechanism that we have right now (i.e. using only links). There is an open issue for that https://github.com/w3c/wot-thing-description/issues/958.

**Comment by fennibay** [comment]
> Doing so would also allow setting a certain brightness only.

@danielpeintner  sorry I noticed this point later. How would this work exactly?

>> Can I have multiple forms with op: "readproperty" under a property?

> Yes you can :) The consumer needs to know which one to pick though

@egekorkan :-) in my case, it has to use simply all of them, e.g. when doing readproperty on the top-level brightness property it will filter all forms with `op: "readproperty"`, execute them in order and put the results to the number array defined in the logical schema. Is that correct?

> I think in general it is a bad idea to split a physical Thing into multiple TDs.

> I actually don't mind splitting a physical thing into different subthings if it is composed of logical different physical components (i.e. different lights).

@relu91 @egekorkan I guess this will remain a reference left to the Thing modeler (TD author). I agree that when the thing can be divided into logical subunits, multiple TDs start to make more sense.

**Comment by egekorkan** [comment]
> @egekorkan :-) in my case, it has to use simply all of them, e.g. when doing readproperty on the top-level brightness property it will filter all forms with op: "readproperty", execute them in order and put the results to the number array defined in the logical schema. Is that correct?

So the logic is to pick **one** form that the needed `op` present in. Executing multiple forms is something we have not considered so far but it would be interesting but complicated to structure algorithmically.

**Comment by sebastiankb** [comment]
Together with @vcharpenay we discussed @fennibay second solution, however, in the context of Thing Model, where we can include properties from a ThingModel A and ThingModel B which have the identical name.  

In general, there will be different kind of ways how this can be implemented. I think, splitting up in muliple sub-TDs is one of the solutions. 

I'm thinking out loud: how about introducing a new `op` value something like `readAllLinkedPropertiesByName`.  The API takes a property name and retrieve all linked TDs that have identical property name and returns the composed result.

**Comment by danielpeintner** [comment]
> > Doing so would also allow setting a certain brightness only.
> 
> @danielpeintner sorry I noticed this point later. How would this work exactly?

I think there is nothing that prevents you to call/set a single brightness value

`invokeAction("setBrightness", { "lights": ["brightness1"], "value": 12});`

**Comment by fennibay** [comment]
> I think there is nothing that prevents you to call/set a single brightness value

Ok, I had a more strict interpretation of data schema. But I understand, especially if the fields are specified as optional, it's completely legal of course. It would be applicable to properties, as well.

> So the logic is to pick one form that the needed op present in. Executing multiple forms is something we have not considered so far but it would be interesting but complicated to structure algorithmically.

Yeah, it can get really complicated to assemble a top-level property's data schema from multiple protocol read accesses, and vice-versa to disassemble for a write.

> I'm thinking out loud: how about introducing a new op value something like readAllLinkedPropertiesByName. The API takes a property name and retrieve all linked TDs that have identical property name and returns the composed result.

I believe this would complicate things unnecessarily. Especially InteractionAffordance names are currently local to the Thing scope, and are just simple strings, not namespace-able. This would make them exposed to a broader scope. I think the current options are adequate:
1. If the Thing is really tightly coupled with its sub-things, it should probably also offer APIs for accessing the sub-thing properties in one go. This would also perform better.
1. Or if the sub-things are relatively independent, they will just be referred from the top-level Thing via links.

I think we can close this issue. Would it be worth to summarize the discussion in some document?
