### ISSUE TITLE
Review resurrected Cert, Public, and PoP SecuritySchemes

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-thing-description#965]
PR https://github.com/w3c/wot-thing-description/pull/951, which fixed the rendering script and which has been merged, has had the (unintended?) side effect of resurrecting three old security schemes, Cert, Public, and PoP.   These are however currently marked as at-risk and it's not clear we want to include them since they will involve extra testing.   We should discuss whether we should remove these.

**Comment by vcharpenay** [comment]
if you'd like to remove them from `index.html` in the mean time, comment out the corresponding Node Shapes in `td-validation.ttl` (Cert: [l. 862-868](https://github.com/w3c/wot-thing-description/blob/master/validation/td-validation.ttl#L862), Public: [l. 880-886](https://github.com/w3c/wot-thing-description/blob/master/validation/td-validation.ttl#L880), PoP: [l. 888-898](https://github.com/w3c/wot-thing-description/blob/master/validation/td-validation.ttl#L888)).

**Comment by mmccool** [comment]
Reviewed in security call 2020.09.21.  Decision: we'll comment them out for now, although we will continue to discuss.  PoP in particular would be good to have but we have to check if enough people are using them and whether we can generate two implementations for testing or not.   They could always be supported by an extension if necessary, so...

To do the PR: @mmccool

**Comment by mmccool** [comment]
These have been commented out again in the current draft, and they do not seem to be needed, so this issue can be closed.   Note: Cert and Public can probably stay gone since they are covered by things like PSK (both are special cases of PSK, actually; one of the ciphersuites for TLS-PSK uses public keys, for instance).  However PoP might get resurrected in TD 2.0 if PoP tokens become more common.  They still seem to be in play but are not yet widely adopted.  Some discussion here: https://leastprivilege.com/2020/01/15/oauth-2-0-the-long-road-to-proof-of-possession-access-tokens/
