### ISSUE TITLE
[JSON-LD] Compacting property affordance for json-schema compatibility does not support the `type` property

### ISSUE THREAD

**Issue by RoboPhred** [w3c/wot-thing-description#967]
I have the following non-compacted JSONLD being generated by my library
```json
{
  "@id": "zwave-master::31-0",
  "@types": ["MultiLevelSwitch"],
  "http://purl.org/dc/terms/title": "Living Room Fan",
  "http://purl.org/dc/terms/description": "In-Wall Smart Fan Control",
  "https://www.w3.org/2019/wot/td#hasPropertyAffordance": [
    {
      "@context": {
        "@vocab": "https://www.w3.org/2019/wot/json-schema#"
      },
      "@index": "zwave-master::multilevel-switch",
      "http://purl.org/dc/terms/title": "Level",
      "type": "number",
      "minimum": 0,
      "maximum": 99,
      "readOnly": false
    }
  ]
}
```

I am trying to compact it, so that the property becomes json-schema validation compatible.  In practice, this results in only `minimum` and `maximum` being recognized.  Both `readOnly`, and critically `type` do not find their alias in the schema and appear as `jsonschema:readOnly` and `jsonschema:type` respectively.

Here is the output I get when I run jsonld-cli against it:
`jsonld compact -c https://www.w3.org/2019/wot/td/v1# test.json`
```json
{
  "@context": "https://www.w3.org/2019/wot/td/v1#",
  "id": "zwave-master::31-0",
  "description": "In-Wall Smart Fan Control",
  "title": "Living Room Fan",
  "properties": {
    "zwave-master::multilevel-switch": {
      "title": "Level",
      "maximum": 99,
      "minimum": 0,
      "jsonschema:readOnly": false,
      "jsonschema:type": "number"
    }
  }
}
```

The compactor prefixed type as `jsonschema:type`, but was apparently unable to resolve it to the compacted `type` key I would have expected.  Because of this, the resulting compacted form cannot be fed to a json-schema validator as the type key is not present in a way that a json-schema validator will understand.

I feel like I am missing some json-ld construct like a `@type` or `@types` annotation, but using either of those simply leaves the property as-is without transforming it, still leaving me without a `type` key.

How can I form my json-ld so that it produces valid json-schema when compacted?

Possibly related issues:
#894
#889

**Comment by RoboPhred** [comment]
I have hacked around with a few different methods, and made some small progress.

Firstly, despite the wot documentation, `type` comes from `http://www.w3.org/1999/02/22-rdf-syntax-ns#`, and not from json-schema as I thought.  Still, this isnt enough to fix the issue, as:

```json
{
  "@id": "zwave-master::31-0",
  "@types": ["MultiLevelSwitch"],
  "http://purl.org/dc/terms/title": "Living Room Fan",
  "http://purl.org/dc/terms/description": "In-Wall Smart Fan Control",
  "https://www.w3.org/2019/wot/td#hasPropertyAffordance": [
    {
      "@context": {
        "@vocab": "https://www.w3.org/2019/wot/json-schema#"
      },
      "@index": "zwave-master::multilevel-switch",
      "http://purl.org/dc/terms/title": "Level",
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#type": "number",
      "minimum": 0,
      "maximum": 99,
      "readOnly": false
    }
  ]
}
```
just gives the type key as `rdf:type`; still impossible for a json schema validator to parse.

Then, I tried taking the proper compacted form, and expanding it instead.  Suprisingly, re-compacting this expanded form worked!  So that means something in the particulars of the syntax is causing the issue, not the keys or namespaces being used.

By trail and error, I minimized the expanded form to make this functional example:

{
  "@id": "zwave-master::31-0",
  "@types": ["MultiLevelSwitch"],
  "http://purl.org/dc/terms/title": "Living Room Fan",
  "http://purl.org/dc/terms/description": "In-Wall Smart Fan Control",
  "https://www.w3.org/2019/wot/td#hasPropertyAffordance": [
    {
      "@context": {
        "@vocab": "https://www.w3.org/2019/wot/json-schema#"
      },
      "@index": "zwave-master::multilevel-switch",
      "http://purl.org/dc/terms/title": "Level",
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#type": {
        "@id": "https://www.w3.org/2019/wot/json-schema#NumberSchema"
      },
      "minimum": 0,
      "maximum": 99,
      "readOnly": false
    }
  ]
}
```

This works!  `type` is specified correctly in the output!

The thing that fixes it is apparently to specify type like this:
```
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#type": {
        "@id": "https://www.w3.org/2019/wot/json-schema#NumberSchema"
      },
```

Why is this needed?  The context already defines `type` as 
```
"type": {
          "@id": "rdf:type",
          "@type": "@vocab"
        },
```
So json-ld should know that the value is an ID checked against https://www.w3.org/2019/wot/json-schema#.  However, the following do not work:

```
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#type": {
        "@id": "number"
      },
```
This uses the proper `type` key but uses a bogus `https://json-ld.org/playground/number` value in the playground.

```
"http://www.w3.org/1999/02/22-rdf-syntax-ns#type": "https://www.w3.org/2019/wot/json-schema#NumberSchema",
```
This likewise fails to resolve the key, and results in `"rdf:type": ""http://www.w3.org/1999/02/22-rdf-syntax-ns#type": "https://www.w3.org/2019/wot/json-schema#NumberSchema"`


I think I have enough information now to hack around the problem, but this behavior does not seem right...  Can anyone shine some information on why the type property needs such an exacting format to compact and why it ignores the schema vocab aliases entirely?

**Comment by BigBlueHat** [comment]
This seems to be happening because `number` and `NumberSchema` amount to synonyms in the context file, and the processor is "going until it runs out" and ultimately returning the last identifier it finds--in this case `NumberSchema` (and not it's alias "number").

Here's a minimal version of what's described here (and a [playground link](https://tinyurl.com/y5jo6c8u) to test):
```json
{
    "@context": {
        "@version": 1.1,
        "@vocab": "https://www.w3.org/2019/wot/json-schema#",
        "id": { "@id": "@id" },
        "type": { "@id": "@type" },
        "number": "NumberSchema"
    },
  "type": "number"
}
```
which compacts to...
```json
{
  "@type": "https://www.w3.org/2019/wot/json-schema#NumberSchema"
}
```

If you remove the `"number": "NumberSchema"` "alias", then this will fallback to the "catch all" `@vocab` definition.

One solution (depending on what you're wanting throughout the processing process) would be to define the `number` term this way (using the example context above):
```json
{
    "@context": {
      "@version": 1.1,
      "@vocab": "https://www.w3.org/2019/wot/json-schema#",
      "id": { "@id": "@id" },
      "type": { "@id": "@type" },
      "number": {
        "@id": "number",
        "@type": "NumberSchema"
      }
    },
  "number": 5
}
```
which results in an expanded output of...
```json
[
  {
    "https://www.w3.org/2019/wot/json-schema#number": [
      {
        "@type": "https://www.w3.org/2019/wot/json-schema#NumberSchema",
        "@value": 5
      }
    ]
  }
]
```
and a compacted version (using the same embedded context--[here's the playground link](https://tinyurl.com/y44kxtpm)):
```json
{
  "@context": {
    "@version": 1.1,
    "@vocab": "https://www.w3.org/2019/wot/json-schema#",
    "id": {
      "@id": "@id"
    },
    "type": {
      "@id": "@type"
    },
    "number": {
      "@id": "number",
      "@type": "NumberSchema"
    }
  },
  "number": 5
}
```
which results in the round tripping result you want (from what I understand).

If that indeed matches what you're attempting, then defining your "*Schema" terms this way, should fix the problem:
```json
{
    "number": {
      "@id": "number",
      "@type": "NumberSchema"
    }
}
```

Hope that helps!
🎩

**Comment by pchampin** [comment]
To illustrate the last point in my comment above, I coined [an example] where a unique property is compacted in various ways, depending on its values. As you can see, the "compacting context" has several term definitions with the same `@id`, but different "constraints" on `@type` or `@language`...

Hope this clarifies why your term definition `"type": {"@id": "rdf:type", "@type": "@vocab"}` is not applied during conversion.

[an example]:https://json-ld.org/playground/#startTab=tab-compacted&json-ld=%5B%7B%22http%3A%2F%2Fexample.org%2Fns%2Fproperty%22%3A%5B%7B%22%40id%22%3A%22http%3A%2F%2Fexample.org%2Fns%2Ffoo%22%7D%2C%7B%22%40id%22%3A%22http%3A%2F%2Fexample.org%2Fns%2Fbar%22%7D%2C%7B%22%40value%22%3A%22cat%22%2C%22%40language%22%3A%22en%22%7D%2C%7B%22%40value%22%3A%22chat%22%2C%22%40language%22%3A%22fr%22%7D%2C%7B%22%40value%22%3A%22Katze%22%2C%22%40language%22%3A%22de%22%7D%2C%7B%22%40value%22%3A%22%E3%81%8A%E3%81%97%E3%82%83%E3%81%B9%E3%82%8A%22%2C%22%40language%22%3A%22jp%22%7D%5D%7D%5D&context=%7B%22%40context%22%3A%7B%22ex%22%3A%22http%3A%2F%2Fexample.org%2Fns%2F%22%2C%22p_vocab%22%3A%7B%22%40id%22%3A%22ex%3Aproperty%22%2C%22%40type%22%3A%22%40vocab%22%7D%2C%22p_id%22%3A%7B%22%40id%22%3A%22ex%3Aproperty%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22p_fr%22%3A%7B%22%40id%22%3A%22ex%3Aproperty%22%2C%22%40language%22%3A%22fr%22%7D%2C%22p_en%22%3A%7B%22%40id%22%3A%22ex%3Aproperty%22%2C%22%40language%22%3A%22en%22%7D%2C%22foo%22%3A%22ex%3Afoo%22%7D%7D

**Comment by RoboPhred** [comment]
Thanks.  I am learning that @vocab is not enough to allow me to convert json-schema into json-ld.  I was able to find additional information, including a context that claims to do the conversion.  I am now working on the problem through that angle, and documenting the new problems arising from this over at #988.

Thanks for your help everyone!
