### ISSUE TITLE
No examples for observeproperty and unobserveproperty

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#969]
There are no examples in the specification that showcase a form with the `op` values of `observeproperty` and/or `unobserveproperty`.

**Comment by danielpeintner** [comment]
I think it is good to have many examples. Having said that, I think they are not normative in the spec and make the document itself more verbose. Hence I wonder whether it makes sense to craft a place where we can put more (sophisticated) samples and point to it... maybe in the test folders?

**Comment by sebastiankb** [comment]
This protocol-related part is perhaps of more relevance for the binding document. Why not give a few examples there?

**Comment by sebastiankb** [comment]
Propose to move this issue to binding repo and close it here
