### ISSUE TITLE
JSON-LD 1.0 will be republished as superseded version

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-thing-description#970]
Seems no impact for TD since it rely on JSON-LD 1.1. We will discuss this with the JSON-LD Maintenance WG.

**Comment by iherman** [comment]
This is under way at the AC, see:

https://www.w3.org/2002/09/wbs/33280/jsonld10-sup/

The deadline for vote is 21st of October; unless there is an objection the superseded version should be published end of October or early November (depending of the availability of the webmaster during the TPAC weeks).

I propose this issue could be closed.
