### ISSUE TITLE
How flexible is TD Template instantiation?

### ISSUE THREAD

**Issue by devonsparks** [w3c/wot-thing-description#971]
Hi all,

Question about TD instantiation wrt TD Templates: 

I've been modeling "classes" of Things that all share a common interface contract (properties, actions, events) using TD Templates. I have a separate collection of instance data that has specific IDs, titles, descriptions and property values/URIs that conform to that interface. Now I'd like to put the two together, effectively "instantiating" the Templates by filling in the missing slots with instance data. For properties and actions, `uriVariables` seem like a good fit. But what if I wanted to pass, say, `id`, `title`, or `description` fields to the Thing Template as part of the instantiation process? Are there any existing rules around or support for this kind of Template composition or do I have to write my own "compositor" for this use case?

I think my question might be related to #962 but didn't want to dilute that thread in case it's a separate topic.

Thanks!

**Comment by egekorkan** [comment]
Here is a more relevant issue :blush: 
https://github.com/w3c/wot-thing-description/issues/897

**Comment by devonsparks** [comment]
Ah, #897 is exactly what I was looking for - thanks @egekorkan! Will continue the conversation there...
