### ISSUE TITLE
Render script related issues

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#973]
While working on https://github.com/w3c/wot-thing-description/pull/960 I noticed some issues...

<strike>1. Someone needs to to run render script and check-in all changes (which does not seem to be the case right now)
  - index.html misses a lot of changes
  - other files as well
  - e.g., ontology/jsonschema.html has been changed but is not checked in et cetera.</strike>
  - e.g., not sure about SVG files and whetehr they change always 

2. There are some bugs like in https://w3c.github.io/wot-thing-description/#x5-4-default-value-definitions
 - There is twice "5.4"

<strike>3. if we work on *new* PRs it looks that a given PR brings lots of new stuff but that is not the case... </strike>

Edit: some parts are done, see strikes

**Comment by sebastiankb** [comment]
@danielpeintner what is the status here? Can we close?

**Comment by danielpeintner** [comment]
Yes, the issues are all gone by now. Thanks!
