### ISSUE TITLE
Definition of contentEncoding should be of type xsd:string

### ISSUE THREAD

**Issue by takuki** [w3c/wot-thing-description#980]
Both in context/json-schema-context.jsonld and context/td-context-1.1.jsonld

    "contentEncoding": {
      "@id": "jsonschema:contentEncoding",
      "@type": "xsd:unsignedInt"
    },

It should be xsd:string.

**Comment by sebastiankb** [comment]
From today's TD call:
- we should fix this 
- @sebastiankb can provide a PR

**Comment by sebastiankb** [comment]
the issue was solved by the merged PR
