### ISSUE TITLE
"MultiLanguage Map" is used without definition

### ISSUE THREAD

**Issue by takuki** [w3c/wot-thing-description#983]
There used to be a section [MultiLanguage](https://www.w3.org/TR/2020/REC-wot-thing-description-20200409/#multilanguage) in TD 1.0.

There still are more than a couple of places using the term, but the section is missing in the current draft.
See section 5.3.1.1 Thing and 6.3.2 Human-Readable Metadata.

**Comment by danielpeintner** [comment]
It seems `MultiLanguage` needs to be added to https://github.com/w3c/wot-thing-description/blob/master/validation/td-validation.ttl

I browsed through the history of the file `td-validation.ttl` and I did not find it. It seems it has never been there?
@vcharpenay do you know?

**Comment by sebastiankb** [comment]
is this issue still relevant? The MultiLanguage section is available [here](https://www.w3.org/TR/wot-thing-description11/#multilanguage)
