### ISSUE TITLE
Review - Thing Description 1.1 version

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-thing-description#987]
Besides some obvious typos (see PR https://github.com/w3c/wot-thing-description/pull/986) please find below some more comments/questions...

### 4. Namespaces

section speaks that "associated JSON-LD context file is versioned such that every version has its own URI (v1, v1.1, v2, ...) "

Doesn't that mean we should have

... this specification is identified by the following IRI: 
`https://www.w3.org/2019/wot/td/v1.1`

Instead we use everywhere 
`https://www.w3.org/2019/wot/td/v1`

### 5.3.2.4 NumberSchema
and
### 5.3.2.5 IntegerSchema

both have the statement for multipleOf
"Only applicable for associated number or integer types"
I think this is not necessary since we are in a given type number or integer context already.

Moreover in NumberSchema I think the following statement is wrong
"The result of division of the numeric instance on the multipleOf value should be integer"
There is no need for being of type integer. It can be number also right?

### 6.2 Omitting Default Values

Some minor consistency issues in Example 3
* some terms are like this
`"security": "basic_sc",`
while others contains spaces after :
`"readOnly" : false`
`"writeOnly" : false`

Same applies to many more example 6, 7, 8, 9, ...
Maybe an overall _pretty-print_ should be done..

### 6.3.2 Human-Readable Metadata

"default language is defined by a value assigned to @language in the @context, and this, along with a script subtag if necessary, can be used to determine a base text direction"

I am not sure what _script subtag_ refers to. The same text is present twice in the document.
Do we have an example?

### 7.1 Semantic Annotations

"Next subsections shows" --> "Next subsections show" ?

### 7.1.3 Example III: Geolocation Annotations

"and can be relyed on different" --> "and can be relied on different" ?

**Comment by sebastiankb** [comment]
>Doesn't that mean we should have ... this specification is identified by the following IRI:
> https://www.w3.org/2019/wot/td/v1.1

Good point. Alternative would be, that we go back to the https://www.w3.org/ns/td namespace which we used during the draft phase of TD 1.0

**Comment by sebastiankb** [comment]
>both have the statement for multipleOf
>"Only applicable for associated number or integer types"
>I think this is not necessary since we are in a given type number or integer context already.

This text is coming from the ontology definition which has not specific context at that point:
https://w3c.github.io/wot-thing-description/ontology/jsonschema.html#multipleof

**Comment by sebastiankb** [comment]
>The result of division of the numeric instance on the multipleOf value should be integer

good point, I will remove this sentence

**Comment by sebastiankb** [comment]
>I am not sure what script subtag refers to. The same text is present twice in the document.
>Do we have an example?

@mmccool can you comment this?

**Comment by sebastiankb** [comment]
@danielpeintner many thanks for your review. The update can be found in PR #989

**Comment by sebastiankb** [comment]
can be closed since FPWD is released
