### ISSUE TITLE
[json-schema][json-ld] Json Schema RDF context fails to round trip

### ISSUE THREAD

**Issue by RoboPhred** [w3c/wot-thing-description#988]
The Json Schema RDF gives a [json-ld context](https://www.w3.org/2019/wot/json-schema#interpreting-json-schema-as-json-ld-1-1) that it claims can be used to turn json-schema into a json-ld fragment.  However, it fails to handle the "properties" key when going through a round trip from json-schema to json-ld expanded and back:

My test schema is an object with two properties:
```
  "type": "object",
  "properties": {
    "foo": {"type": "integer"},
    "bar": {"type": "string", "maxLength": 2}
  }
```

The playground for turning json-schema into json-ld expanded is [here](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%7B%22%40version%22%3A1.1%2C%22xsd%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%22%2C%22%40vocab%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23%22%2C%22id%22%3A%7B%22%40id%22%3A%22%40id%22%7D%2C%22type%22%3A%7B%22%40id%22%3A%22%40type%22%7D%2C%22object%22%3A%22ObjectSchema%22%2C%22array%22%3A%22ArraySchema%22%2C%22boolean%22%3A%22BooleanSchema%22%2C%22string%22%3A%22StringSchema%22%2C%22number%22%3A%22NumberSchema%22%2C%22integer%22%3A%22IntegerSchema%22%2C%22null%22%3A%22NullSchema%22%2C%22properties%22%3A%7B%22%40type%22%3A%22%40vocab%22%2C%22%40container%22%3A%22%40index%22%2C%22%40index%22%3A%22propertyName%22%7D%2C%22items%22%3A%7B%22%40type%22%3A%22%40vocab%22%7D%2C%22oneOf%22%3A%7B%22%40type%22%3A%22%40vocab%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22allOf%22%3A%7B%22%40type%22%3A%22%40vocab%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22anyOf%22%3A%7B%22%40type%22%3A%22%40vocab%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22minItems%22%3A%7B%22%40type%22%3A%22xsd%3Adecimal%22%7D%2C%22maxItems%22%3A%7B%22%40type%22%3A%22xsd%3Adecimal%22%7D%2C%22minimum%22%3A%7B%22%40type%22%3A%22xsd%3Adecimal%22%7D%2C%22maximum%22%3A%7B%22%40type%22%3A%22xsd%3Adecimal%22%7D%2C%22enum%22%3A%7B%22%40container%22%3A%22%40set%22%2C%22%40type%22%3A%22%40json%22%7D%2C%22writeOnly%22%3A%7B%22%40type%22%3A%22xsd%3Aboolean%22%7D%2C%22readOnly%22%3A%7B%22%40type%22%3A%22xsd%3Aboolean%22%7D%2C%22format%22%3A%7B%22%40type%22%3A%22xsd%3Astring%22%7D%2C%22required%22%3A%7B%22%40type%22%3A%22xsd%3Astring%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22title%22%3A%7B%22%40type%22%3A%22xsd%3Astring%22%7D%2C%22description%22%3A%7B%22%40type%22%3A%22xsd%3Astring%22%7D%7D%2C%22type%22%3A%22object%22%2C%22properties%22%3A%7B%22foo%22%3A%7B%22type%22%3A%22integer%22%7D%2C%22bar%22%3A%7B%22type%22%3A%22string%22%2C%22maxLength%22%3A2%7D%7D%7D)

The playground re-compacting it is [here](https://json-ld.org/playground/#startTab=tab-compacted&json-ld=%5B%7B%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23properties%22%3A%5B%7B%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23maxLength%22%3A%5B%7B%22%40value%22%3A2%7D%5D%2C%22%40type%22%3A%5B%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23StringSchema%22%5D%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23propertyName%22%3A%5B%7B%22%40value%22%3A%22bar%22%7D%5D%7D%2C%7B%22%40type%22%3A%5B%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23IntegerSchema%22%5D%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23propertyName%22%3A%5B%7B%22%40value%22%3A%22foo%22%7D%5D%7D%5D%2C%22%40type%22%3A%5B%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23ObjectSchema%22%5D%7D%5D&context=%7B%22%40context%22%3A%7B%22%40version%22%3A1.1%2C%22xsd%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%22%2C%22%40vocab%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23%22%2C%22id%22%3A%7B%22%40id%22%3A%22%40id%22%7D%2C%22type%22%3A%7B%22%40id%22%3A%22%40type%22%7D%2C%22object%22%3A%22ObjectSchema%22%2C%22array%22%3A%22ArraySchema%22%2C%22boolean%22%3A%22BooleanSchema%22%2C%22string%22%3A%22StringSchema%22%2C%22number%22%3A%22NumberSchema%22%2C%22integer%22%3A%22IntegerSchema%22%2C%22null%22%3A%22NullSchema%22%2C%22properties%22%3A%7B%22%40type%22%3A%22%40vocab%22%2C%22%40container%22%3A%22%40index%22%2C%22%40index%22%3A%22propertyName%22%7D%2C%22items%22%3A%7B%22%40type%22%3A%22%40vocab%22%7D%2C%22oneOf%22%3A%7B%22%40type%22%3A%22%40vocab%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22allOf%22%3A%7B%22%40type%22%3A%22%40vocab%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22anyOf%22%3A%7B%22%40type%22%3A%22%40vocab%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22minItems%22%3A%7B%22%40type%22%3A%22xsd%3Adecimal%22%7D%2C%22maxItems%22%3A%7B%22%40type%22%3A%22xsd%3Adecimal%22%7D%2C%22minimum%22%3A%7B%22%40type%22%3A%22xsd%3Adecimal%22%7D%2C%22maximum%22%3A%7B%22%40type%22%3A%22xsd%3Adecimal%22%7D%2C%22enum%22%3A%7B%22%40container%22%3A%22%40set%22%2C%22%40type%22%3A%22%40json%22%7D%2C%22writeOnly%22%3A%7B%22%40type%22%3A%22xsd%3Aboolean%22%7D%2C%22readOnly%22%3A%7B%22%40type%22%3A%22xsd%3Aboolean%22%7D%2C%22format%22%3A%7B%22%40type%22%3A%22xsd%3Astring%22%7D%2C%22required%22%3A%7B%22%40type%22%3A%22xsd%3Astring%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22title%22%3A%7B%22%40type%22%3A%22xsd%3Astring%22%7D%2C%22description%22%3A%7B%22%40type%22%3A%22xsd%3Astring%22%7D%7D%7D).

In the second playground, I expected the compacted form to equal my original object (not including the context).  However, it fails to handle the properties key, and instead leaves the properties key in its full IRI of "https://www.w3.org/2019/wot/json-schema#properties".

Of special note here, the use of a propertyName IRI seems to be incompatible with the core Thing Definition context, which does not specify an index:

JSON Schema RDF property definition:
```
"properties": {
  "@type": "@vocab",
  "@container": "@index",
  "@index": "propertyName"
},
```

Thing Definition `td:hasInputSchema` properties definition:
```
"properties": {
 "@id": "jsonschema:properties",
 "@type": "@id",
 "@container": "@index"
},
```

If I remove the existing RDF property definition and replace it with the Thing Definition version, then everything works as expected and I get my original object back.

Here is a round trip with this replacement, showing the properties object properly populated.
[Expansion](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%7B%22%40version%22%3A1.1%2C%22xsd%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%22%2C%22%40vocab%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23%22%2C%22id%22%3A%7B%22%40id%22%3A%22%40id%22%7D%2C%22type%22%3A%7B%22%40id%22%3A%22%40type%22%7D%2C%22object%22%3A%22ObjectSchema%22%2C%22array%22%3A%22ArraySchema%22%2C%22boolean%22%3A%22BooleanSchema%22%2C%22string%22%3A%22StringSchema%22%2C%22number%22%3A%22NumberSchema%22%2C%22integer%22%3A%22IntegerSchema%22%2C%22null%22%3A%22NullSchema%22%2C%22properties%22%3A%7B%22%40id%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23properties%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40index%22%7D%2C%22items%22%3A%7B%22%40type%22%3A%22%40vocab%22%7D%2C%22oneOf%22%3A%7B%22%40type%22%3A%22%40vocab%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22allOf%22%3A%7B%22%40type%22%3A%22%40vocab%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22anyOf%22%3A%7B%22%40type%22%3A%22%40vocab%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22minItems%22%3A%7B%22%40type%22%3A%22xsd%3Adecimal%22%7D%2C%22maxItems%22%3A%7B%22%40type%22%3A%22xsd%3Adecimal%22%7D%2C%22minimum%22%3A%7B%22%40type%22%3A%22xsd%3Adecimal%22%7D%2C%22maximum%22%3A%7B%22%40type%22%3A%22xsd%3Adecimal%22%7D%2C%22enum%22%3A%7B%22%40container%22%3A%22%40set%22%2C%22%40type%22%3A%22%40json%22%7D%2C%22writeOnly%22%3A%7B%22%40type%22%3A%22xsd%3Aboolean%22%7D%2C%22readOnly%22%3A%7B%22%40type%22%3A%22xsd%3Aboolean%22%7D%2C%22format%22%3A%7B%22%40type%22%3A%22xsd%3Astring%22%7D%2C%22required%22%3A%7B%22%40type%22%3A%22xsd%3Astring%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22title%22%3A%7B%22%40type%22%3A%22xsd%3Astring%22%7D%2C%22description%22%3A%7B%22%40type%22%3A%22xsd%3Astring%22%7D%7D%2C%22type%22%3A%22object%22%2C%22properties%22%3A%7B%22foo%22%3A%7B%22type%22%3A%22integer%22%7D%2C%22bar%22%3A%7B%22type%22%3A%22string%22%2C%22maxLength%22%3A2%7D%7D%7D)

[Compaction](https://json-ld.org/playground/#startTab=tab-compacted&json-ld=%5B%7B%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23properties%22%3A%5B%7B%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23maxLength%22%3A%5B%7B%22%40value%22%3A2%7D%5D%2C%22%40type%22%3A%5B%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23StringSchema%22%5D%2C%22%40index%22%3A%22bar%22%7D%2C%7B%22%40type%22%3A%5B%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23IntegerSchema%22%5D%2C%22%40index%22%3A%22foo%22%7D%5D%2C%22%40type%22%3A%5B%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23ObjectSchema%22%5D%7D%5D&context=%7B%22%40version%22%3A1.1%2C%22xsd%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%22%2C%22%40vocab%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23%22%2C%22id%22%3A%7B%22%40id%22%3A%22%40id%22%7D%2C%22type%22%3A%7B%22%40id%22%3A%22%40type%22%7D%2C%22object%22%3A%22ObjectSchema%22%2C%22array%22%3A%22ArraySchema%22%2C%22boolean%22%3A%22BooleanSchema%22%2C%22string%22%3A%22StringSchema%22%2C%22number%22%3A%22NumberSchema%22%2C%22integer%22%3A%22IntegerSchema%22%2C%22null%22%3A%22NullSchema%22%2C%22properties%22%3A%7B%22%40id%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23properties%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40index%22%7D%2C%22items%22%3A%7B%22%40type%22%3A%22%40vocab%22%7D%2C%22oneOf%22%3A%7B%22%40type%22%3A%22%40vocab%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22allOf%22%3A%7B%22%40type%22%3A%22%40vocab%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22anyOf%22%3A%7B%22%40type%22%3A%22%40vocab%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22minItems%22%3A%7B%22%40type%22%3A%22xsd%3Adecimal%22%7D%2C%22maxItems%22%3A%7B%22%40type%22%3A%22xsd%3Adecimal%22%7D%2C%22minimum%22%3A%7B%22%40type%22%3A%22xsd%3Adecimal%22%7D%2C%22maximum%22%3A%7B%22%40type%22%3A%22xsd%3Adecimal%22%7D%2C%22enum%22%3A%7B%22%40container%22%3A%22%40set%22%2C%22%40type%22%3A%22%40json%22%7D%2C%22writeOnly%22%3A%7B%22%40type%22%3A%22xsd%3Aboolean%22%7D%2C%22readOnly%22%3A%7B%22%40type%22%3A%22xsd%3Aboolean%22%7D%2C%22format%22%3A%7B%22%40type%22%3A%22xsd%3Astring%22%7D%2C%22required%22%3A%7B%22%40type%22%3A%22xsd%3Astring%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22title%22%3A%7B%22%40type%22%3A%22xsd%3Astring%22%7D%2C%22description%22%3A%7B%22%40type%22%3A%22xsd%3Astring%22%7D%7D)

Based on this, it seems we have the following issues:
- Either the Thing Definition context needs to be updated to index on `propertyName`, or `propertyName` should be removed from the JSON Schema RDF
- json-ld.js seems to fail to alias a container when the container context has `@index` mapped to an alias.  I will try to get a simplified example of this one.

Background: I have an API that accepts (non json-ld) json-schema.  The library uses expanded form json-ld to build up the thing definition, and only compacts it before sending it out.  Because of this, I need to convert plain json-schema into expanded json-ld when building out the TD.

**Comment by RoboPhred** [comment]
Some more experimenting seems to reveal that this is the result of the `"@type": "@vocab"` line.  If I change it to '"@type": "@id"`, the property generates correctly for both @index and propertyName variants.


Given the expanded form:
```
[
  {
    "https://www.w3.org/2019/wot/json-schema#properties": [
      {
        "https://www.w3.org/2019/wot/json-schema#propertyName": [
          {
            "@value": "bar"
          }
        ]
      }
    ]
  }
]
```

The following example fails
[Playground link](https://json-ld.org/playground/#startTab=tab-compacted&json-ld=%5B%7B%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23properties%22%3A%5B%7B%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23propertyName%22%3A%5B%7B%22%40value%22%3A%22bar%22%7D%5D%7D%5D%7D%5D&context=%7B%22%40version%22%3A1.1%2C%22xsd%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%22%2C%22%40vocab%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23%22%2C%22id%22%3A%7B%22%40id%22%3A%22%40id%22%7D%2C%22properties%22%3A%7B%22%40type%22%3A%22%40vocab%22%2C%22%40container%22%3A%22%40index%22%2C%22%40index%22%3A%22propertyName%22%7D%7D)
```
{
  "@context": {
    "@version": 1.1,
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "@vocab": "https://www.w3.org/2019/wot/json-schema#",
    "id": {
      "@id": "@id"
    },
    "properties": {
      "@type": "@vocab",
      "@container": "@index",
      "@index": "propertyName"
    }
  },
  "https://www.w3.org/2019/wot/json-schema#properties": {
    "propertyName": "bar"
  }
}
```



The following has @type changed to @id, which properly generates the `property` key:
[Playground](https://json-ld.org/playground/#startTab=tab-compacted&json-ld=%5B%7B%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23properties%22%3A%5B%7B%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23propertyName%22%3A%5B%7B%22%40value%22%3A%22bar%22%7D%5D%7D%5D%7D%5D&context=%7B%22%40version%22%3A1.1%2C%22xsd%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%22%2C%22%40vocab%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23%22%2C%22id%22%3A%7B%22%40id%22%3A%22%40id%22%7D%2C%22properties%22%3A%7B%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40index%22%2C%22%40index%22%3A%22propertyName%22%7D%7D)
```
{
  "@context": {
    "@version": 1.1,
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "@vocab": "https://www.w3.org/2019/wot/json-schema#",
    "id": {
      "@id": "@id"
    },
    "properties": {
      "@type": "@id",
      "@container": "@index",
      "@index": "propertyName"
    }
  },
  "properties": {
    "bar": {}
  }
}
```

**Comment by vcharpenay** [comment]
thanks for digging in! I've made changes to the TD context, see a37f0609bb0d943545f69404e9196408f257aab1. `propertyName` is important, it was missing in the TD context. To fix your issue, I just removed `@type: @vocab`, which is superfluous anyway (in both TD and JSON Schema documents).

Please try and comment if your problem persists.

**Comment by RoboPhred** [comment]
After the changes, I am now getting json-ld errors when trying to compact my expanded form:

The error is: `jsonld.SyntaxError: Absolute IRI "jsonschema:propertyName" confused with prefix "jsonschema".`

[Playground link](https://json-ld.org/playground/#startTab=tab-compacted&json-ld=%7B%22%40id%22%3A%22zwave-master%3A%3A22-0%22%2C%22%40types%22%3A%5B%22MultiLevelSwitch%22%5D%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Ftitle%22%3A%22Inovelli%20Test%22%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Fdescription%22%3A%22Red%20Series%20Dimmer%22%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Ftd%23hasEventAffordance%22%3A%5B%7B%22%40index%22%3A%22zwave-master%3A%3Acentral-scene-triggered%22%2C%22%40type%22%3A%5B%22CentralScene%22%5D%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Ftitle%22%3A%22Central%20Scene%20Triggered%22%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Fdescription%22%3A%22Raised%20when%20this%20device%20triggers%20a%20scene.%22%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Ftd%23hasNotificationSchema%22%3A%7B%22%40context%22%3A%7B%22td%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Ftd%23%22%2C%22jsonschema%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23%22%2C%22wotsec%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fsecurity%23%22%2C%22hctl%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fhypermedia%23%22%2C%22dct%22%3A%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%22%2C%22schema%22%3A%22http%3A%2F%2Fschema.org%2F%22%2C%22rdf%22%3A%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%22%2C%22%40vocab%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23%22%2C%22DataSchema%22%3A%7B%22%40id%22%3A%22jsonschema%3ADataSchema%22%7D%2C%22readOnly%22%3A%7B%22%40id%22%3A%22jsonschema%3AreadOnly%22%2C%22%40type%22%3A%22xsd%3Aboolean%22%7D%2C%22writeOnly%22%3A%7B%22%40id%22%3A%22jsonschema%3AwriteOnly%22%2C%22%40type%22%3A%22xsd%3Aboolean%22%7D%2C%22maximum%22%3A%7B%22%40id%22%3A%22jsonschema%3Amaximum%22%7D%2C%22minimum%22%3A%7B%22%40id%22%3A%22jsonschema%3Aminimum%22%7D%2C%22maxItems%22%3A%7B%22%40id%22%3A%22jsonschema%3AmaxItems%22%2C%22%40type%22%3A%22xsd%3AunsignedInt%22%7D%2C%22minItems%22%3A%7B%22%40id%22%3A%22jsonschema%3AminItems%22%2C%22%40type%22%3A%22xsd%3AunsignedInt%22%7D%2C%22contentEncoding%22%3A%7B%22%40id%22%3A%22jsonschema%3AcontentEncoding%22%2C%22%40type%22%3A%22xsd%3AunsignedInt%22%7D%2C%22minLength%22%3A%7B%22%40id%22%3A%22jsonschema%3AminLength%22%2C%22%40type%22%3A%22xsd%3AunsignedInt%22%7D%2C%22maxLength%22%3A%7B%22%40id%22%3A%22jsonschema%3AmaxLength%22%2C%22%40type%22%3A%22xsd%3AunsignedInt%22%7D%2C%22contentMediaType%22%3A%7B%22%40id%22%3A%22jsonschema%3AcontentMediaType%22%2C%22%40type%22%3A%22xsd%3Astring%22%7D%2C%22items%22%3A%7B%22%40id%22%3A%22jsonschema%3Aitems%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22required%22%3A%7B%22%40id%22%3A%22jsonschema%3Arequired%22%2C%22%40type%22%3A%22xsd%3Astring%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22enum%22%3A%7B%22%40id%22%3A%22jsonschema%3Aenum%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22const%22%3A%7B%22%40id%22%3A%22jsonschema%3Aconst%22%7D%2C%22multipleOf%22%3A%7B%22%40id%22%3A%22jsonschema%3AmultipleOf%22%7D%2C%22format%22%3A%7B%22%40id%22%3A%22jsonschema%3Aformat%22%7D%2C%22oneOf%22%3A%7B%22%40id%22%3A%22jsonschema%3AoneOf%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22allOf%22%3A%7B%22%40id%22%3A%22jsonschema%3AallOf%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22anyOf%22%3A%7B%22%40id%22%3A%22jsonschema%3AanyOf%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22type%22%3A%7B%22%40id%22%3A%22rdf%3Atype%22%2C%22%40type%22%3A%22%40vocab%22%7D%2C%22title%22%3A%7B%22%40id%22%3A%22dct%3Atitle%22%7D%2C%22titles%22%3A%7B%22%40id%22%3A%22dct%3Atitle%22%2C%22%40container%22%3A%22%40language%22%7D%2C%22description%22%3A%7B%22%40id%22%3A%22dct%3Adescription%22%7D%2C%22descriptions%22%3A%7B%22%40id%22%3A%22dct%3Adescription%22%2C%22%40container%22%3A%22%40language%22%7D%2C%22object%22%3A%22jsonschema%3AObjectSchema%22%2C%22array%22%3A%22jsonschema%3AArraySchema%22%2C%22boolean%22%3A%22jsonschema%3ABooleanSchema%22%2C%22string%22%3A%22jsonschema%3AStringSchema%22%2C%22number%22%3A%22jsonschema%3ANumberSchema%22%2C%22integer%22%3A%22jsonschema%3AIntegerSchema%22%2C%22null%22%3A%22jsonschema%3ANullSchema%22%2C%22properties%22%3A%7B%22%40id%22%3A%22jsonschema%3Aproperties%22%2C%22%40container%22%3A%22%40index%22%2C%22%40index%22%3A%22jsonschema%3ApropertyName%22%7D%2C%22unit%22%3A%7B%22%40id%22%3A%22schema%3AunitCode%22%2C%22%40type%22%3A%22%40vocab%22%7D%7D%2C%22type%22%3A%22object%22%2C%22properties%22%3A%7B%22scene%22%3A%7B%22type%22%3A%22number%22%7D%2C%22key%22%3A%7B%22type%22%3A%22number%22%7D%2C%22keyName%22%3A%7B%22type%22%3A%22string%22%7D%7D%7D%7D%5D%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Ftd%23hasPropertyAffordance%22%3A%5B%7B%22%40index%22%3A%22zwave-master%3A%3Amultilevel-switch%22%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Ftitle%22%3A%22Level%22%2C%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%22%3A%7B%22%40id%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23NumberSchema%22%7D%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23minimum%22%3A0%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23maximum%22%3A99%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23readOnly%22%3Afalse%7D%5D%7D&context=%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Ftd%2Fv1%23%22)

The expanded form I am using uses full IRIs for most terms, but falls back into using the json schema to json-ld context mapping for events

**Comment by pchampin** [comment]
I think this is a problem either with the implementation of with the algorithm in the spec. I submitted an issue (see above). A quick fix consist in not using compact IRIs as values for `@index` in your context. Either use the absolute IRI, or add a term definition `"propertyName": "jsonschema:propertyName"` and use `"@index": "propertyName"`.
