### ISSUE TITLE
[question] Meaning of htv:headers in forms

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#991]
It might be more appropriate to open this issue in the binding templates but since the HTTP binding is partially specified in the TD specification and generally there is more discussion here I am putting it here for now.

When there is htv:headers in a form like the following:
```jsonc
"htv:headers":
  [
    {
      "htv:fieldName": "Date",
      "htv:fieldValue": // Doesn't make sense for date I think?
    }
]
```
Does this mean that the Consumer should send the Date in the header of the request or does it mean that the Thing will send the Date in the response since Date is a header field applicable to both request and response. This might not be the best example but this seemed a bit ambiguous to me, thus a question.

**Comment by sebastiankb** [comment]
It depends on if the `response` term is used in the `forms`. If `htv:headers` used at `forms` level I would expect that those information have to be provided by the consumer. The Thing may response also with that header field. 

If the header is defined within the response container, only the Thing will provide this information.

**Comment by egekorkan** [comment]
I sort of agree but we have for example `contentType` in the forms level that indicates the content type delivered by the Thing and also what the Consumer should use for sending a request (like for an `invokeaction`). So if it is put in the `response` container, it is all clear, if not, it is not necessarily in the request.

**Comment by sebastiankb** [comment]
For the contentType we have some detail guideline provided in the TD spec:

>The optional response name-value pair can be used to provide metadata for the expected response message. With the core vocabulary, it only includes content type information, but TD Context Extensions could be applied. If no response name-value pair is provided, it MUST be assumed that the content type of the response is equal to the content type assigned to the Form instance. Note that contentType within an ExpectedResponse Class does not have a Default Value. For instance, if the value of the content type of the form is application/xml the assumed value of the content type of the response will be also application/xml.

>In some use cases, input and output data might be represented in a different form, for instance an Action that accepts JSON, but returns an image. In such a case, the optional response name-value pair can describe the content type of the expected response. If the content type of the expected response differs from the content type of the form, the Form instance MUST include a name-value pair with the name response. For instance, an ActionAffordance could only accept application/json for its input data, while it will respond with an image/jpeg content type for its output data. In that case the content types differ and the response name-value pair has to be used to provide response content type (image/jpeg) information to the Consumer.

**Comment by egekorkan** [comment]
Thus, something similar should be explained for the headers?

**Comment by sebastiankb** [comment]
This cannot generalized since this is protocol specific. I'm agree the best place is the binding template spec for it.

**Comment by sebastiankb** [comment]
From today's TD call:
- there needs a clarification how the header information should be used 
- especially in relation with the `response` field
- this should be explained in the binding document 
- @egekorkan will share some concrete use case
